namespace SB.Domain;
public static class AbsencesCdoModelSample
{
    public static readonly AbsencesCdoModel Sample =
        new(
            new AbsencesCdoModelAbsence[]
            {
                new AbsencesCdoModelAbsence(
                    1,
                    "Валентина Найденова Кръстева",
                    false,
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 4.5M),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(2, 0),
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(3, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0)
                    ),
                new AbsencesCdoModelAbsence(
                    2,
                    "Венцислав Петров Геров",
                    false,
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(2, 0),
                    new AbsencesItemByTypes(0, 1.5M),
                    new AbsencesItemByTypes(2, 0),
                    new AbsencesItemByTypes(0, 2.5M),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(4, 0),
                    new AbsencesItemByTypes(4, 0),
                    new AbsencesItemByTypes(0, 0)
                    ),
                new AbsencesCdoModelAbsence(
                    3,
                    "Георги Молов Кръстев",
                    false,
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(2, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 1),
                    new AbsencesItemByTypes(2, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(2, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0)
                    ),
                new AbsencesCdoModelAbsence(
                    4,
                    "Гергана Найденова Кръстева",
                    false,
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(5, 3),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(0, 0.5M),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(4, 0),
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(2, 0),
                    new AbsencesItemByTypes(4, 0),
                    new AbsencesItemByTypes(0, 0)
                    ),
                new AbsencesCdoModelAbsence(
                    5,
                    "Гергана Жекова Минева",
                    false,
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 4.5M),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0)
                    ),
                new AbsencesCdoModelAbsence(
                    6,
                    "Глория Бончева Вътова",
                    false,
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(2, 0),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 4.5M),
                    new AbsencesItemByTypes(2, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(4, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 3)
                    ),
                new AbsencesCdoModelAbsence(
                    7,
                    "Даниел Петров Монов",
                    false,
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 4.5M),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0)
                    ),
                new AbsencesCdoModelAbsence(
                    8,
                    "Желязко Ганчев Нецов",
                    false,
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 4.5M),
                    new AbsencesItemByTypes(2, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0)
                    ),
                new AbsencesCdoModelAbsence(
                    9,
                    "Здравко Невенов Иванов",
                    false,
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(4, 0),
                    new AbsencesItemByTypes(0, 4.5M),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0)
                    ),
                new AbsencesCdoModelAbsence(
                    10,
                    "Златка Найденова Кръстева",
                    false,
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(5, 3),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 4.5M),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0)
                    ),
                new AbsencesCdoModelAbsence(
                    11,
                    "Михаела Томова Бинева",
                    false,
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(5, 0),
                    new AbsencesItemByTypes(0, 2),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 4.5M),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(4, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0),
                    new AbsencesItemByTypes(0, 0)
                    ),
            }
        );
}
