#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

# Install the necessary locale packages
RUN apt-get update && \
    apt-get install -y locales wget libgdiplus && \
    locale-gen bg_BG.UTF-8

# Set the locale environment variables
ENV LANG=bg_BG.UTF-8 \
    LANGUAGE=bg_BG:en \
    LC_ALL=bg_BG.UTF-8

RUN wget -P /app https://github.com/rdvojmoc/DinkToPdf/raw/master/v0.12.4/64%20bit/libwkhtmltox.dll

RUN wget -P /app https://github.com/rdvojmoc/DinkToPdf/raw/master/v0.12.4/64%20bit/libwkhtmltox.dylib

RUN wget -P /app https://github.com/rdvojmoc/DinkToPdf/raw/master/v0.12.4/64%20bit/libwkhtmltox.so

USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY . .
COPY RegStamps.Web/appsettings.test.json RegStamps.Web/appsettings.json
RUN dotnet restore "./RegStamps.Web/./RegStamps.Web.csproj"
WORKDIR "/src/RegStamps.Web"
RUN dotnet build "./RegStamps.Web.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./RegStamps.Web.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RegStamps.Web.dll"]