// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.ASPDataAccess
{
    public partial class PomptTempDatum
    {
        public int PersonId { get; set; }
        public string PersonalId { get; set; }
        public int PersonalIdType { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public short Year { get; set; }
        public short Month { get; set; }
        public decimal? MonthlyAbsencesForValidReason { get; set; }
        public decimal? MonthlyAbsencesForUnvalidReason { get; set; }
        public int? InstitutionCode { get; set; }
        public int? BasicClass { get; set; }
        public DateTime? EnrollmentDate { get; set; }
        public DateTime? DischargeDate { get; set; }
        public int? EduFormId { get; set; }
        public DateTime TimeStamp { get; set; }
    }
}