import { SysRoleEnum } from 'src/shared/enums/role.enum';
import { SysSchemaEnum } from 'src/shared/enums/schemas.enum';
import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddRolesToTables1660029439805 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            INSERT INTO reporting.SchemaRoleAccess(SchemaName, AllowedSysRole)
            VALUES
            ('${SysSchemaEnum.PHONES}', ${SysRoleEnum.MON_ADMIN}),
            ('${SysSchemaEnum.PHONES}', ${SysRoleEnum.CIOO}),
            ('${SysSchemaEnum.PHONES}', ${SysRoleEnum.MON_EXPERT}),
            ('${SysSchemaEnum.PHONES}', ${SysRoleEnum.MON_OBGUM}),
            ('${SysSchemaEnum.PHONES}', ${SysRoleEnum.MON_CHRAO}),
            ('${SysSchemaEnum.PHONES}', ${SysRoleEnum.MON_OBGUM_FINANCES}),
            ('${SysSchemaEnum.R_COUNCILS}', ${SysRoleEnum.MON_ADMIN}),
            ('${SysSchemaEnum.R_COUNCILS}', ${SysRoleEnum.CIOO}),
            ('${SysSchemaEnum.R_COUNCILS}', ${SysRoleEnum.MON_EXPERT}),
            ('${SysSchemaEnum.R_COUNCILS}', ${SysRoleEnum.MON_OBGUM}),
            ('${SysSchemaEnum.R_COUNCILS}', ${SysRoleEnum.MON_CHRAO}),
            ('${SysSchemaEnum.R_COUNCILS}', ${SysRoleEnum.MON_OBGUM_FINANCES}),
            ('${SysSchemaEnum.R_HOSTELS}', ${SysRoleEnum.MON_ADMIN}),
            ('${SysSchemaEnum.R_HOSTELS}', ${SysRoleEnum.CIOO}),
            ('${SysSchemaEnum.R_HOSTELS}', ${SysRoleEnum.MON_EXPERT}),
            ('${SysSchemaEnum.R_HOSTELS}', ${SysRoleEnum.MON_OBGUM}),
            ('${SysSchemaEnum.R_HOSTELS}', ${SysRoleEnum.MON_CHRAO}),
            ('${SysSchemaEnum.R_HOSTELS}', ${SysRoleEnum.MON_OBGUM_FINANCES}),
            ('${SysSchemaEnum.R_IMMIGRANTS_DOB_HOURS}', ${SysRoleEnum.MON_ADMIN}),
            ('${SysSchemaEnum.R_IMMIGRANTS_DOB_HOURS}', ${SysRoleEnum.CIOO}),
            ('${SysSchemaEnum.R_IMMIGRANTS_DOB_HOURS}', ${SysRoleEnum.MON_EXPERT}),
            ('${SysSchemaEnum.R_IMMIGRANTS_DOB_HOURS}', ${SysRoleEnum.MON_OBGUM}),
            ('${SysSchemaEnum.R_IMMIGRANTS_DOB_HOURS}', ${SysRoleEnum.MON_CHRAO}),
            ('${SysSchemaEnum.R_IMMIGRANTS_DOB_HOURS}', ${SysRoleEnum.MON_OBGUM_FINANCES}),
            ('${SysSchemaEnum.R_IMMIGRANTS_DOB_HOURS}', ${SysRoleEnum.RUO}),
            ('${SysSchemaEnum.R_IMMIGRANTS_DOB_HOURS}', ${SysRoleEnum.RUO_EXPERT}),
            ('${SysSchemaEnum.REFUGEE_INSTITUTIONS}', ${SysRoleEnum.MON_ADMIN}),
            ('${SysSchemaEnum.REFUGEE_INSTITUTIONS}', ${SysRoleEnum.CIOO}),
            ('${SysSchemaEnum.REFUGEE_INSTITUTIONS}', ${SysRoleEnum.MON_EXPERT}),
            ('${SysSchemaEnum.REFUGEE_INSTITUTIONS}', ${SysRoleEnum.MON_OBGUM}),
            ('${SysSchemaEnum.REFUGEE_INSTITUTIONS}', ${SysRoleEnum.MON_CHRAO}),
            ('${SysSchemaEnum.REFUGEE_INSTITUTIONS}', ${SysRoleEnum.MON_OBGUM_FINANCES}),
            ('${SysSchemaEnum.REFUGEE_INSTITUTIONS}', ${SysRoleEnum.RUO}),
            ('${SysSchemaEnum.REFUGEE_INSTITUTIONS}', ${SysRoleEnum.RUO_EXPERT}),
            ('${SysSchemaEnum.REFUGEE_RECEIVED_REQUESTS}', ${SysRoleEnum.MON_ADMIN}),
            ('${SysSchemaEnum.REFUGEE_RECEIVED_REQUESTS}', ${SysRoleEnum.CIOO}),
            ('${SysSchemaEnum.REFUGEE_RECEIVED_REQUESTS}', ${SysRoleEnum.MON_EXPERT}),
            ('${SysSchemaEnum.REFUGEE_RECEIVED_REQUESTS}', ${SysRoleEnum.MON_OBGUM}),
            ('${SysSchemaEnum.REFUGEE_RECEIVED_REQUESTS}', ${SysRoleEnum.MON_CHRAO}),
            ('${SysSchemaEnum.REFUGEE_RECEIVED_REQUESTS}', ${SysRoleEnum.MON_OBGUM_FINANCES}),
            ('${SysSchemaEnum.REFUGEE_RECEIVED_REQUESTS}', ${SysRoleEnum.RUO}),
            ('${SysSchemaEnum.REFUGEE_RECEIVED_REQUESTS}', ${SysRoleEnum.RUO_EXPERT}),
            ('${SysSchemaEnum.REFUGEE_WITHDRAWN_REQUESTS}', ${SysRoleEnum.MON_ADMIN}),
            ('${SysSchemaEnum.REFUGEE_WITHDRAWN_REQUESTS}', ${SysRoleEnum.CIOO}),
            ('${SysSchemaEnum.REFUGEE_WITHDRAWN_REQUESTS}', ${SysRoleEnum.MON_EXPERT}),
            ('${SysSchemaEnum.REFUGEE_WITHDRAWN_REQUESTS}', ${SysRoleEnum.MON_OBGUM}),
            ('${SysSchemaEnum.REFUGEE_WITHDRAWN_REQUESTS}', ${SysRoleEnum.MON_CHRAO}),
            ('${SysSchemaEnum.REFUGEE_WITHDRAWN_REQUESTS}', ${SysRoleEnum.MON_OBGUM_FINANCES}),
            ('${SysSchemaEnum.REFUGEE_WITHDRAWN_REQUESTS}', ${SysRoleEnum.RUO}),
            ('${SysSchemaEnum.REFUGEE_WITHDRAWN_REQUESTS}', ${SysRoleEnum.RUO_EXPERT}),
            ('${SysSchemaEnum.R_INSTITUTIONS}', ${SysRoleEnum.MON_ADMIN}),
            ('${SysSchemaEnum.R_INSTITUTIONS}', ${SysRoleEnum.CIOO}),
            ('${SysSchemaEnum.R_INSTITUTIONS}', ${SysRoleEnum.MON_EXPERT}),
            ('${SysSchemaEnum.R_INSTITUTIONS}', ${SysRoleEnum.MON_OBGUM}),
            ('${SysSchemaEnum.R_INSTITUTIONS}', ${SysRoleEnum.MON_CHRAO}),
            ('${SysSchemaEnum.R_INSTITUTIONS}', ${SysRoleEnum.MON_OBGUM_FINANCES}),
            ('${SysSchemaEnum.R_INSTITUTIONS}', ${SysRoleEnum.NIO}),
            ('${SysSchemaEnum.R_INSTITUTIONS}', ${SysRoleEnum.RUO}),
            ('${SysSchemaEnum.R_INSTITUTIONS}', ${SysRoleEnum.RUO_EXPERT}),
            ('${SysSchemaEnum.R_INSTITUTIONS}', ${SysRoleEnum.MUNICIPALITY}),
            ('${SysSchemaEnum.R_INSTITUTIONS}', ${SysRoleEnum.BUDGETING_INSTITUTION}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.MON_ADMIN}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.CIOO}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.MON_EXPERT}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.MON_OBGUM}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.MON_CHRAO}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.MON_OBGUM_FINANCES}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.NIO}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.RUO}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.RUO_EXPERT}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.MUNICIPALITY}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.INSTITUTION}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.EXTERNAL_INSTITUTIONS_EXPERT}),
            ('${SysSchemaEnum.R_STUDENTS}', ${SysRoleEnum.BUDGETING_INSTITUTION}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.MON_ADMIN}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.CIOO}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.MON_EXPERT}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.MON_OBGUM}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.MON_CHRAO}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.MON_OBGUM_FINANCES}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.NIO}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.RUO}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.RUO_EXPERT}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.MUNICIPALITY}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.INSTITUTION}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.EXTERNAL_INSTITUTIONS_EXPERT}),
            ('${SysSchemaEnum.R_CLASSES}', ${SysRoleEnum.BUDGETING_INSTITUTION}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.MON_ADMIN}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.CIOO}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.MON_EXPERT}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.MON_OBGUM}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.MON_CHRAO}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.MON_OBGUM_FINANCES}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.NIO}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.RUO}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.RUO_EXPERT}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.MUNICIPALITY}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.INSTITUTION}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.EXTERNAL_INSTITUTIONS_EXPERT}),
            ('${SysSchemaEnum.R_PERSONAL}', ${SysRoleEnum.BUDGETING_INSTITUTION}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.MON_ADMIN}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.CIOO}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.MON_EXPERT}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.MON_OBGUM}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.MON_CHRAO}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.MON_OBGUM_FINANCES}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.NIO}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.RUO}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.RUO_EXPERT}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.MUNICIPALITY}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.INSTITUTION}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.EXTERNAL_INSTITUTIONS_EXPERT}),
            ('${SysSchemaEnum.R_FOREIGN_LANGUAGES}', ${SysRoleEnum.BUDGETING_INSTITUTION})
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
