// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Neispuo.Tools.DataAccess;

public partial class AdmissionDocument
{
    public int Id { get; set; }

    public DateTime AdmissionDate { get; set; }

    public string NoteNumber { get; set; }

    public DateTime NoteDate { get; set; }

    public DateTime? DischargeDate { get; set; }

    public int AdmissionReasonTypeId { get; set; }

    public int Status { get; set; }

    public int InstitutionId { get; set; }

    public int? RelocationDocumentId { get; set; }

    public int PersonId { get; set; }

    public int PositionId { get; set; }

    public int CreatedBySysUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public int? ModifiedBySysUserId { get; set; }

    public DateTime? ModifyDate { get; set; }

    public DateTime? ConfirmationDate { get; set; }

    public short SchoolYear { get; set; }

    public bool HasHealthStatusDocument { get; set; }

    public bool HasImmunizationStatusDocument { get; set; }

    public int? CurrentStudentClassId { get; set; }

    public virtual ICollection<AdmissionDocumentDocument> AdmissionDocumentDocuments { get; set; } = new List<AdmissionDocumentDocument>();

    public virtual ICollection<AdmissionPermissionRequest> AdmissionPermissionRequests { get; set; } = new List<AdmissionPermissionRequest>();

    public virtual AdmissionReasonType AdmissionReasonType { get; set; }

    public virtual SysUser CreatedBySysUser { get; set; }

    public virtual StudentClass CurrentStudentClass { get; set; }

    public virtual InstitutionSchoolYear InstitutionSchoolYear { get; set; }

    public virtual SysUser ModifiedBySysUser { get; set; }

    public virtual Person Person { get; set; }

    public virtual RelocationDocument RelocationDocument { get; set; }

    public virtual ICollection<StudentClassHistory> StudentClassHistories { get; set; } = new List<StudentClassHistory>();

    public virtual ICollection<StudentClass> StudentClasses { get; set; } = new List<StudentClass>();
}