// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Neispuo.Tools.DataAccess;

public partial class BaseSchoolType
{
    public int BaseSchoolTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsValid { get; set; }

    public DateTime? ValidFrom { get; set; }

    public DateTime? ValidTo { get; set; }

    public virtual ICollection<InstitutionSchoolYear> InstitutionSchoolYears { get; set; } = new List<InstitutionSchoolYear>();

    public virtual ICollection<Institution> Institutions { get; set; } = new List<Institution>();
}