// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Neispuo.Tools.DataAccess;

public partial class ClassShiftLimit
{
    public int ClassShiftLimitId { get; set; }

    public int InstTypeId { get; set; }

    public int? ClassShiftId { get; set; }
}