// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Neispuo.Tools.DataAccess;

/// <summary>
/// Учебен план
/// </summary>
public partial class Curriculum
{
    /// <summary>
    /// Уникален идентификатор на запи
    /// </summary>
    public int CurriculumId { get; set; }

    /// <summary>
    /// Учебна година
    /// </summary>
    public short SchoolYear { get; set; }

    /// <summary>
    /// Код на институцията
    /// </summary>
    public int InstitutionId { get; set; }

    /// <summary>
    /// Пореден номер на групата по уч
    /// </summary>
    public short? CurriculumGroupNum { get; set; }

    /// <summary>
    /// Учебен предмет
    /// </summary>
    public int? SubjectId { get; set; }

    /// <summary>
    /// Начин на изучаване
    /// </summary>
    public int? SubjectTypeId { get; set; }

    /// <summary>
    /// Брой учебни седмици І срок
    /// </summary>
    public short? WeeksFirstTerm { get; set; }

    /// <summary>
    /// Брой часове седмично І срок
    /// </summary>
    public float? HoursWeeklyFirstTerm { get; set; }

    /// <summary>
    /// Брой учебни седмици ІІ срок
    /// </summary>
    public short? WeeksSecondTerm { get; set; }

    /// <summary>
    /// Брой часове седмично ІІ срок
    /// </summary>
    public float? HoursWeeklySecondTerm { get; set; }

    /// <summary>
    /// Маркер &quot;Учебен предмет (различ
    /// </summary>
    public bool? IsFl { get; set; }

    /// <summary>
    /// Чужд език
    /// </summary>
    public int? FlsubjectId { get; set; }

    /// <summary>
    /// Маркер за индивидуален час
    /// </summary>
    public int? IsIndividualLesson { get; set; }

    /// <summary>
    /// Норма на предмета
    /// </summary>
    public int? NormaS { get; set; }

    /// <summary>
    /// Адрес, на който се провежда об
    /// </summary>
    public int? InstitutionDepartmentId { get; set; }

    /// <summary>
    /// Идентификатор на основния запи
    /// </summary>
    public int? ParentCurriculumId { get; set; }

    /// <summary>
    /// Раздел от учебния план
    /// </summary>
    public int? CurriculumPartId { get; set; }

    /// <summary>
    /// Идентификатор за сортиране
    /// </summary>
    public int? SortOrder { get; set; }

    public int? TmpCurricIdOrig { get; set; }

    public int? TmpClassIdOrig { get; set; }

    public short? TmpSubjectIdOrig { get; set; }

    public int? TmpDepIdOrig { get; set; }

    public int? TmpProfSubjId { get; set; }

    /// <summary>
    /// Дата, от която е валидна стойн
    /// </summary>
    public DateTime? ValidFrom { get; set; }

    /// <summary>
    /// Дата, до която е валидна стойн
    /// </summary>
    public DateTime? ValidTo { get; set; }

    public int? SysUserId { get; set; }

    /// <summary>
    /// Маркер &quot;Предметът се изучава о
    /// </summary>
    public bool? IsWholeClass { get; set; }

    /// <summary>
    /// Маркер &quot;Предметът се изучава о
    /// </summary>
    public bool? IsAllStudents { get; set; }

    public string AzureId { get; set; }

    public string ExternalId { get; set; }

    public bool IsValid { get; set; }

    public bool IsCombined { get; set; }

    public int? TotalTermHours { get; set; }

    public int? StudentsCount { get; set; }

    public int? MainSubjectId { get; set; }

    public bool? IsIndividualCurriculum { get; set; }

    public virtual ICollection<CurriculumClass> CurriculumClasses { get; set; } = new List<CurriculumClass>();

    public virtual CurriculumPart CurriculumPart { get; set; }

    public virtual ICollection<CurriculumStudent> CurriculumStudents { get; set; } = new List<CurriculumStudent>();

    public virtual ICollection<CurriculumTeacher> CurriculumTeachers { get; set; } = new List<CurriculumTeacher>();

    public virtual Fl Flsubject { get; set; }

    public virtual InstitutionDepartment InstitutionDepartment { get; set; }

    public virtual InstitutionSchoolYear InstitutionSchoolYear { get; set; }

    public virtual ICollection<Curriculum> InverseParentCurriculum { get; set; } = new List<Curriculum>();

    public virtual Subject MainSubject { get; set; }

    public virtual Curriculum ParentCurriculum { get; set; }

    public virtual CurrentYear SchoolYearNavigation { get; set; }

    public virtual Subject Subject { get; set; }

    public virtual SubjectType SubjectType { get; set; }

    public virtual SysUser SysUser { get; set; }
}