// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Neispuo.Tools.DataAccess;

public partial class LodAssessmentGrade
{
    public int Id { get; set; }

    public int LodAssessmentId { get; set; }

    public int GradeCategoryId { get; set; }

    public int GradeId { get; set; }

    public int CreatedBySysUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public int? ModifiedBySysUserId { get; set; }

    public DateTime? ModifyDate { get; set; }

    public decimal? DecimalGrade { get; set; }

    public virtual SysUser CreatedBySysUser { get; set; }

    public virtual GradeNom Grade { get; set; }

    public virtual GradeCategory GradeCategory { get; set; }

    public virtual LodAssessment LodAssessment { get; set; }

    public virtual SysUser ModifiedBySysUser { get; set; }
}