// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Neispuo.Tools.DataAccess;

public partial class Municipality
{
    public int MunicipalityId { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public int? RegionId { get; set; }

    public string Description { get; set; }

    public virtual Region Region { get; set; }

    public virtual ICollection<Town> Towns { get; set; } = new List<Town>();
}