// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Neispuo.Tools.DataAccess;

public partial class PersonalDevelopmentSupport
{
    public int Id { get; set; }

    public string EarlyEvaluationAndEducationalRiskInfo { get; set; }

    public string AdditionalModulesNeededForNonBulgarianSpeakingInfo { get; set; }

    public string EvaluationConclusionInfo { get; set; }

    public int? SupportPeriodTypeId { get; set; }

    public int? StudentTypeId { get; set; }

    public int PersonId { get; set; }

    public short SchoolYear { get; set; }

    public int CreatedBySysUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public int? ModifiedBySysUserId { get; set; }

    public DateTime? ModifyDate { get; set; }

    public virtual SysUser CreatedBySysUser { get; set; }

    public virtual SysUser ModifiedBySysUser { get; set; }

    public virtual Person Person { get; set; }

    public virtual ICollection<PersonalDevelopmentAdditionalSupportType> PersonalDevelopmentAdditionalSupportTypes { get; set; } = new List<PersonalDevelopmentAdditionalSupportType>();

    public virtual ICollection<PersonalDevelopmentCommonSupportType> PersonalDevelopmentCommonSupportTypes { get; set; } = new List<PersonalDevelopmentCommonSupportType>();

    public virtual ICollection<PersonalDevelopmentDocument> PersonalDevelopmentDocuments { get; set; } = new List<PersonalDevelopmentDocument>();

    public virtual ICollection<PersonalDevelopmentEarlyEvaluationReason> PersonalDevelopmentEarlyEvaluationReasons { get; set; } = new List<PersonalDevelopmentEarlyEvaluationReason>();

    public virtual CurrentYear SchoolYearNavigation { get; set; }

    public virtual StudentType StudentType { get; set; }

    public virtual SupportPeriod SupportPeriodType { get; set; }
}