// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Neispuo.Tools.DataAccess;

public partial class RegisterLeftForAbroad
{
    public int Id { get; set; }

    public int PersonalIdType { get; set; }

    public string PersonalId { get; set; }

    public string FullName { get; set; }

    public DateTime BirthDate { get; set; }

    public int InstitutionId { get; set; }

    public string InstitutionName { get; set; }

    public DateTime EventDate { get; set; }
}