// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Neispuo.Tools.DataAccess;

public partial class SchoolTypeLodAccess
{
    public int Id { get; set; }

    public int DetailedSchoolTypeId { get; set; }

    public bool IsLodAccessAllowed { get; set; }
}