// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Neispuo.Tools.DataAccess;

public partial class Sppooprofession
{
    public int SppooprofessionId { get; set; }

    public int ProfAreaId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string SppooprofessionCode { get; set; }

    public bool? IsValid { get; set; }

    public DateTime? ValidFrom { get; set; }

    public DateTime? ValidTo { get; set; }

    public bool? CanChoose { get; set; }

    public int? ProfGroupMonid { get; set; }

    public string NameEn { get; set; }

    public string NameFr { get; set; }

    public string NameDe { get; set; }

    public virtual ICollection<Diploma> Diplomas { get; set; } = new List<Diploma>();

    public virtual SppooprofArea ProfArea { get; set; }

    public virtual ICollection<Recognition> Recognitions { get; set; } = new List<Recognition>();

    public virtual ICollection<Sppoospeciality> Sppoospecialities { get; set; } = new List<Sppoospeciality>();
}