// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Neispuo.Tools.DataAccess;

public partial class TaskNotification
{
    public int Id { get; set; }

    public int? ScheduledTaskId { get; set; }

    public int? InstitutionId { get; set; }

    public int? NotificationTemplateId { get; set; }

    public int NotifyOffsetMinutes { get; set; }

    public DateTime NotifyTime { get; set; }

    public bool IsSent { get; set; }

    public DateTime? SentTime { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public string Message { get; set; }

    public DateTime? CreateDate { get; set; }

    public virtual NotificationTemplate NotificationTemplate { get; set; }

    public virtual ScheduledTask ScheduledTask { get; set; }
}