// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Neispuo.Tools.DataAccess;

public partial class Template
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Principal { get; set; }

    public int BasicDocumentId { get; set; }

    public int? InstitutionId { get; set; }

    public int CreatedBySysUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public int? ModifiedBySysUserId { get; set; }

    public DateTime? ModifyDate { get; set; }

    public long? TmpDocTemplateId { get; set; }

    public string Contents { get; set; }

    public string SubjectContents { get; set; }

    public string Deputy { get; set; }

    public short SchoolYear { get; set; }

    public string CommissionOrderNumber { get; set; }

    public DateTime? CommissionOrderData { get; set; }

    public int? BasicClassId { get; set; }

    public int? RuoRegId { get; set; }

    public virtual BasicClass BasicClass { get; set; }

    public virtual BasicDocument BasicDocument { get; set; }

    public virtual SysUser CreatedBySysUser { get; set; }

    public virtual ICollection<Diploma> Diplomas { get; set; } = new List<Diploma>();

    public virtual ICollection<GraduationCommissionMember> GraduationCommissionMembers { get; set; } = new List<GraduationCommissionMember>();

    public virtual InstitutionSchoolYear InstitutionSchoolYear { get; set; }

    public virtual SysUser ModifiedBySysUser { get; set; }

    public virtual ICollection<TemplateSubject> TemplateSubjects { get; set; } = new List<TemplateSubject>();
}