FROM maven:3.6.3-openjdk-17-slim@sha256:ead687c670f30898fc28e6c7b9dab652360d522b8912ba96eca0f08592a73eec AS build
RUN mkdir /project
COPY . /project
WORKDIR /project
RUN mvn clean package -DskipTests
 
 
FROM eclipse-temurin:17.0.4.1_1-jre-alpine@sha256:e1506ba20f0cb2af6f23e24c7f8855b417f0b085708acd9b85344a884ba77767
RUN apk add openssl
RUN mkdir /opt/app
COPY --from=build /project/target/*.jar /opt/app/java-application.jar
WORKDIR /opt/app
COPY --from=build /project/test/* /opt/app/
RUN echo -n | openssl s_client -connect test-usermng-server.mon.bg:443 | openssl x509 > cert.pem && \
    openssl x509 -in cert.pem -text -out cert.crt && \
    keytool -import -file cert.crt -alias mon.bg -trustcacerts -keystore /opt/java/openjdk/lib/security/cacerts  -storepass changeit -noprompt
CMD "java" "-jar" "/opt/app/java-application.jar"