export enum WorkflowType {
    CHOOSE = <any>'',
    SCHOOL_CREATE = <any>1,
    SCHOOL_UPDATE = <any>2,
    SCHOOL_DELETE = <any>3,
    CLASS_CREATE = <any>4,
    CLASS_UPDATE = <any>5,
    CLASS_DELETE = <any>6,
    USER_CREATE = <any>7,
    USER_UPDATE = <any>8,
    USER_DELETE = <any>9,
    ENROLLMENT_CREATE = <any>10,
    ENROLLMENT_CLASS_CREATE = <any>11,
    ENROLLMENT_SCHOOL_CREATE = <any>12,
    ENROLLMENT_DELETE = <any>13,
    ENROLLMENT_CLASS_DELETE = <any>14,
    ENROLLMENT_SCHOOL_DELETE = <any>15,
}
