FROM node:14.17.4-alpine3.14 as build
COPY ./ /survey/
WORKDIR /survey/
RUN npm install
ARG BUILD_ENV=production
RUN npm run build -- --configuration $BUILD_ENV
FROM nginx:latest
COPY --from=build  /survey/nginx.conf /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build  /survey/dist/survey/ /usr/share/nginx/html
RUN rm -rf /survey
EXPOSE 80
