// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class ClassTypeLimit
    {
        public int ClassTypeLimitId { get; set; }
        public int ClassTypeId { get; set; }
        public int DetailedSchoolTypeId { get; set; }
        public int InstType { get; set; }
        public int ClassKind { get; set; }
        public int BasicClassId { get; set; }
    }
}