// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class CommonPersonalDevelopmentSupportAttachment
    {
        public int Id { get; set; }
        public int CommonPersonalDevelopmentSupportId { get; set; }
        public int DocumentId { get; set; }
        public int CreatedBySysUserId { get; set; }
        public DateTime CreateDate { get; set; }
        public int? ModifiedBySysUserId { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? OldId { get; set; }

        public virtual CommonPersonalDevelopmentSupport CommonPersonalDevelopmentSupport { get; set; }
        public virtual SysUser CreatedBySysUser { get; set; }
        public virtual Document Document { get; set; }
        public virtual SysUser ModifiedBySysUser { get; set; }
    }
}