// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class CurriculumPart
    {
        public CurriculumPart()
        {
            Curricula = new HashSet<Curriculum>();
            LodAssessments = new HashSet<LodAssessment>();
            RelocationDocumentCurrentTermGrades = new HashSet<RelocationDocumentCurrentTermGrade>();
            StudentEvaluations = new HashSet<StudentEvaluation>();
        }

        public int CurriculumPartId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? IsValid { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }

        public virtual ICollection<Curriculum> Curricula { get; set; }
        public virtual ICollection<LodAssessment> LodAssessments { get; set; }
        public virtual ICollection<RelocationDocumentCurrentTermGrade> RelocationDocumentCurrentTermGrades { get; set; }
        public virtual ICollection<StudentEvaluation> StudentEvaluations { get; set; }
    }
}