// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class DirCurrentDatum
    {
        public int InstitutionId { get; set; }
        public string InstitutionName { get; set; }
        public int PersonId { get; set; }
        public string PersonalId { get; set; }
        public string NamesDir { get; set; }
        public string PhoneNumber { get; set; }
    }
}