// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class DischargeReasonType
    {
        public DischargeReasonType()
        {
            DischargeDocuments = new HashSet<DischargeDocument>();
            RelocationDocuments = new HashSet<RelocationDocument>();
            StudentClassHistories = new HashSet<StudentClassHistory>();
            StudentClasses = new HashSet<StudentClass>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsValid { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public bool IsForDischarge { get; set; }
        public bool IsForRelocation { get; set; }
        public bool IsForInternalEnrollment { get; set; }

        public virtual ICollection<DischargeDocument> DischargeDocuments { get; set; }
        public virtual ICollection<RelocationDocument> RelocationDocuments { get; set; }
        public virtual ICollection<StudentClassHistory> StudentClassHistories { get; set; }
        public virtual ICollection<StudentClass> StudentClasses { get; set; }
    }
}