// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class DocManagementApplication
    {
        public DocManagementApplication()
        {
            DocManagementApplicationAttachments = new HashSet<DocManagementApplicationAttachment>();
            DocManagementApplicationItems = new HashSet<DocManagementApplicationItem>();
            DocManagementApplicationStatuses = new HashSet<DocManagementApplicationStatus>();
            InverseParent = new HashSet<DocManagementApplication>();
        }

        public int Id { get; set; }
        public int? ParentId { get; set; }
        public int CampaignId { get; set; }
        public int InstitutionId { get; set; }
        public short SchoolYear { get; set; }
        public string Status { get; set; }
        public int CreatedBySysUserId { get; set; }
        public DateTime CreateDate { get; set; }
        public int? ModifiedBySysUserId { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string DeliveryNotes { get; set; }
        public int? RequestedInstitutionId { get; set; }
        public bool IsExchangeRequest { get; set; }

        public virtual DocManagementCampaign Campaign { get; set; }
        public virtual SysUser CreatedBySysUser { get; set; }
        public virtual InstitutionSchoolYear InstitutionSchoolYear { get; set; }
        public virtual InstitutionSchoolYear InstitutionSchoolYearNavigation { get; set; }
        public virtual SysUser ModifiedBySysUser { get; set; }
        public virtual DocManagementApplication Parent { get; set; }
        public virtual CurrentYear SchoolYearNavigation { get; set; }
        public virtual ICollection<DocManagementApplicationAttachment> DocManagementApplicationAttachments { get; set; }
        public virtual ICollection<DocManagementApplicationItem> DocManagementApplicationItems { get; set; }
        public virtual ICollection<DocManagementApplicationStatus> DocManagementApplicationStatuses { get; set; }
        public virtual ICollection<DocManagementApplication> InverseParent { get; set; }
    }
}