// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class DocManagementApplicationAttachment
    {
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public int DocumentId { get; set; }

        public virtual DocManagementApplication Application { get; set; }
        public virtual Document Document { get; set; }
    }
}