// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class Document
    {
        public Document()
        {
            AdditionalPersonalDevelopmentSupportAttachments = new HashSet<AdditionalPersonalDevelopmentSupportAttachment>();
            AdditionalPersonalDevelopmentSupportItemAttachments = new HashSet<AdditionalPersonalDevelopmentSupportItemAttachment>();
            AdmissionDocumentDocuments = new HashSet<AdmissionDocumentDocument>();
            AdmissionPermissionRequestAttachments = new HashSet<AdmissionPermissionRequestAttachment>();
            ApplicationDocuments = new HashSet<ApplicationDocument>();
            AwardDocuments = new HashSet<AwardDocument>();
            CommonPersonalDevelopmentSupportAttachments = new HashSet<CommonPersonalDevelopmentSupportAttachment>();
            DischargeDocumentDocuments = new HashSet<DischargeDocumentDocument>();
            DocManagementApplicationAttachments = new HashSet<DocManagementApplicationAttachment>();
            DocManagementCampaignAttachments = new HashSet<DocManagementCampaignAttachment>();
            EqualizationAttachments = new HashSet<EqualizationAttachment>();
            InternationalMobilityDocuments = new HashSet<InternationalMobilityDocument>();
            Lodfinalizations = new HashSet<Lodfinalization>();
            NoteDocuments = new HashSet<NoteDocument>();
            OresAttachments = new HashSet<OresAttachment>();
            OtherDocumentDocuments = new HashSet<OtherDocumentDocument>();
            PersonalDevelopmentDocuments = new HashSet<PersonalDevelopmentDocument>();
            PersonalEarlyAssessmentAttachments = new HashSet<PersonalEarlyAssessmentAttachment>();
            ReassessmentDocuments = new HashSet<ReassessmentDocument>();
            RecognitionDocuments = new HashSet<RecognitionDocument>();
            RelocationDocumentDocuments = new HashSet<RelocationDocumentDocument>();
            ResourceSupportDocuments = new HashSet<ResourceSupportDocument>();
            SanctionDocuments = new HashSet<SanctionDocument>();
            ScholarshipStudentDocuments = new HashSet<ScholarshipStudentDocument>();
            SpecialNeedsYearAttachments = new HashSet<SpecialNeedsYearAttachment>();
            ValidationDocuments = new HashSet<ValidationDocument>();
        }

        public int Id { get; set; }
        public Guid Rowguid { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public int? BlobId { get; set; }
        public int CreatedBySysUserId { get; set; }
        public DateTime CreateDate { get; set; }
        public int? ModifiedBySysUserId { get; set; }
        public DateTime? ModifyDate { get; set; }

        public virtual SysUser CreatedBySysUser { get; set; }
        public virtual SysUser ModifiedBySysUser { get; set; }
        public virtual ICollection<AdditionalPersonalDevelopmentSupportAttachment> AdditionalPersonalDevelopmentSupportAttachments { get; set; }
        public virtual ICollection<AdditionalPersonalDevelopmentSupportItemAttachment> AdditionalPersonalDevelopmentSupportItemAttachments { get; set; }
        public virtual ICollection<AdmissionDocumentDocument> AdmissionDocumentDocuments { get; set; }
        public virtual ICollection<AdmissionPermissionRequestAttachment> AdmissionPermissionRequestAttachments { get; set; }
        public virtual ICollection<ApplicationDocument> ApplicationDocuments { get; set; }
        public virtual ICollection<AwardDocument> AwardDocuments { get; set; }
        public virtual ICollection<CommonPersonalDevelopmentSupportAttachment> CommonPersonalDevelopmentSupportAttachments { get; set; }
        public virtual ICollection<DischargeDocumentDocument> DischargeDocumentDocuments { get; set; }
        public virtual ICollection<DocManagementApplicationAttachment> DocManagementApplicationAttachments { get; set; }
        public virtual ICollection<DocManagementCampaignAttachment> DocManagementCampaignAttachments { get; set; }
        public virtual ICollection<EqualizationAttachment> EqualizationAttachments { get; set; }
        public virtual ICollection<InternationalMobilityDocument> InternationalMobilityDocuments { get; set; }
        public virtual ICollection<Lodfinalization> Lodfinalizations { get; set; }
        public virtual ICollection<NoteDocument> NoteDocuments { get; set; }
        public virtual ICollection<OresAttachment> OresAttachments { get; set; }
        public virtual ICollection<OtherDocumentDocument> OtherDocumentDocuments { get; set; }
        public virtual ICollection<PersonalDevelopmentDocument> PersonalDevelopmentDocuments { get; set; }
        public virtual ICollection<PersonalEarlyAssessmentAttachment> PersonalEarlyAssessmentAttachments { get; set; }
        public virtual ICollection<ReassessmentDocument> ReassessmentDocuments { get; set; }
        public virtual ICollection<RecognitionDocument> RecognitionDocuments { get; set; }
        public virtual ICollection<RelocationDocumentDocument> RelocationDocumentDocuments { get; set; }
        public virtual ICollection<ResourceSupportDocument> ResourceSupportDocuments { get; set; }
        public virtual ICollection<SanctionDocument> SanctionDocuments { get; set; }
        public virtual ICollection<ScholarshipStudentDocument> ScholarshipStudentDocuments { get; set; }
        public virtual ICollection<SpecialNeedsYearAttachment> SpecialNeedsYearAttachments { get; set; }
        public virtual ICollection<ValidationDocument> ValidationDocuments { get; set; }
    }
}