// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    /// <summary>
    /// Актуален статус в образователн
    /// </summary>
    public partial class EducationalState
    {
        /// <summary>
        /// Уникален идентификатор на запи
        /// </summary>
        public int EducationalStateId { get; set; }
        /// <summary>
        /// Връзка човек
        /// </summary>
        public int? PersonId { get; set; }
        /// <summary>
        /// Код на институцията
        /// </summary>
        public int? InstitutionId { get; set; }
        /// <summary>
        /// Позиция в образователната сист
        /// </summary>
        public int? PositionId { get; set; }

        public virtual Institution Institution { get; set; }
        public virtual Person Person { get; set; }
        public virtual Position Position { get; set; }
    }
}