// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class EducationGradeType
    {
        public int EducationGradeTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? IsValid { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public int? SortOrd { get; set; }
    }
}