// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class Fl
    {
        public Fl()
        {
            ClassGroups = new HashSet<ClassGroup>();
            Curricula = new HashSet<Curriculum>();
            DiplomaSubjects = new HashSet<DiplomaSubject>();
            LodAssessments = new HashSet<LodAssessment>();
            TemplateSubjects = new HashSet<TemplateSubject>();
        }

        public int Flid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? IsValid { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public bool? CanChoose { get; set; }

        public virtual ICollection<ClassGroup> ClassGroups { get; set; }
        public virtual ICollection<Curriculum> Curricula { get; set; }
        public virtual ICollection<DiplomaSubject> DiplomaSubjects { get; set; }
        public virtual ICollection<LodAssessment> LodAssessments { get; set; }
        public virtual ICollection<TemplateSubject> TemplateSubjects { get; set; }
    }
}