// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class Grade
    {
        public Grade()
        {
            StudentEvaluationAnnualEvaluationNavigations = new HashSet<StudentEvaluation>();
            StudentEvaluationFirstTermEvaluationNavigations = new HashSet<StudentEvaluation>();
            StudentEvaluationOneYearAgoEvaluationNavigations = new HashSet<StudentEvaluation>();
            StudentEvaluationSecondTermEvaluationNavigations = new HashSet<StudentEvaluation>();
            StudentEvaluationTwoYearsAgoEvaluationNavigations = new HashSet<StudentEvaluation>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsValid { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public bool IsSpecialGrade { get; set; }

        public virtual ICollection<StudentEvaluation> StudentEvaluationAnnualEvaluationNavigations { get; set; }
        public virtual ICollection<StudentEvaluation> StudentEvaluationFirstTermEvaluationNavigations { get; set; }
        public virtual ICollection<StudentEvaluation> StudentEvaluationOneYearAgoEvaluationNavigations { get; set; }
        public virtual ICollection<StudentEvaluation> StudentEvaluationSecondTermEvaluationNavigations { get; set; }
        public virtual ICollection<StudentEvaluation> StudentEvaluationTwoYearsAgoEvaluationNavigations { get; set; }
    }
}