// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class GradeResultSubject
    {
        public short SchoolYear { get; set; }
        public int GradeResultId { get; set; }
        public int CurriculumId { get; set; }
        public int? Session1Grade { get; set; }
        public bool? Session1NoShow { get; set; }
        public int? Session2Grade { get; set; }
        public bool? Session2NoShow { get; set; }
        public int? Session3Grade { get; set; }
        public bool? Session3NoShow { get; set; }

        public virtual Curriculum Curriculum { get; set; }
        public virtual GradeResult GradeResult { get; set; }
    }
}