// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class ModernizationDegree
    {
        public ModernizationDegree()
        {
            AvailableArchitectures = new HashSet<AvailableArchitecture>();
        }

        public int ModernizationDegreeId { get; set; }
        public string Name { get; set; }
        public int? IsSupportiveEnv { get; set; }
        public bool? IsValid { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }

        public virtual ICollection<AvailableArchitecture> AvailableArchitectures { get; set; }
    }
}