// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class OtherInstitution
    {
        public int Id { get; set; }
        public string Reason { get; set; }
        public int InstitutionId { get; set; }
        public int PersonId { get; set; }
        public int CreatedBySysUserId { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public DateTime CreateDate { get; set; }
        public int? ModifiedBySysUserId { get; set; }
        public DateTime? ModifyDate { get; set; }
        public short? SchoolYear { get; set; }

        public virtual SysUser CreatedBySysUser { get; set; }
        public virtual InstitutionSchoolYear InstitutionSchoolYear { get; set; }
        public virtual SysUser ModifiedBySysUser { get; set; }
        public virtual Person Person { get; set; }
    }
}