// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class PersonalDevelopmentCommonSupportType
    {
        public int Id { get; set; }
        public int PersonalDevelopmentSupportId { get; set; }
        public int CommonSupportTypeId { get; set; }
        public string Information { get; set; }

        public virtual CommonSupportType CommonSupportType { get; set; }
        public virtual PersonalDevelopmentSupport PersonalDevelopmentSupport { get; set; }
    }
}