// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class PositionKind
    {
        public PositionKind()
        {
            StaffPositions = new HashSet<StaffPosition>();
        }

        public int PositionKindId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? IsValid { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }

        public virtual ICollection<StaffPosition> StaffPositions { get; set; }
    }
}