// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class SchoolBooksGrade
    {
        public short SchoolYear { get; set; }
        public int GradeId { get; set; }
        public int Category { get; set; }
        public int ClassBookId { get; set; }
        public int PersonId { get; set; }
        public int CurriculumId { get; set; }
        public DateTime Date { get; set; }
        public int Type { get; set; }
        public int Term { get; set; }
        public int? ScheduleLessonId { get; set; }
        public int? TeacherAbsenceId { get; set; }
        public string Comment { get; set; }
        public decimal? DecimalGrade { get; set; }
        public int? SpecialGrade { get; set; }
        public int? QualitativeGrade { get; set; }
        public DateTime CreateDate { get; set; }
        public int CreatedBySysUserId { get; set; }
        public DateTime ModifyDate { get; set; }
        public int ModifiedBySysUserId { get; set; }
        public byte[] Version { get; set; }

        public virtual ClassBook ClassBook { get; set; }
        public virtual SysUser CreatedBySysUser { get; set; }
        public virtual Curriculum Curriculum { get; set; }
        public virtual SysUser ModifiedBySysUser { get; set; }
        public virtual Person Person { get; set; }
    }
}