// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    /// <summary>
    /// СОП - година
    /// </summary>
    public partial class SpecialNeedsYear
    {
        public SpecialNeedsYear()
        {
            SpecialNeeds = new HashSet<SpecialNeed>();
            SpecialNeedsYearAttachments = new HashSet<SpecialNeedsYearAttachment>();
        }

        /// <summary>
        /// Уникален идентификатор на запи
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Уникален идентификатор на запи
        /// </summary>
        public int PersonId { get; set; }
        /// <summary>
        /// Учебна година
        /// </summary>
        public short SchoolYear { get; set; }
        /// <summary>
        /// не се използва
        /// </summary>
        public bool HasSuportiveEnvironment { get; set; }
        /// <summary>
        /// не се използва
        /// </summary>
        public string SupportiveEnvironment { get; set; }
        public int CreatedBySysUserId { get; set; }
        public DateTime CreateDate { get; set; }
        public int? ModifiedBySysUserId { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string ExternalId { get; set; }

        public virtual SysUser CreatedBySysUser { get; set; }
        public virtual SysUser ModifiedBySysUser { get; set; }
        public virtual Person Person { get; set; }
        public virtual CurrentYear SchoolYearNavigation { get; set; }
        public virtual ICollection<SpecialNeed> SpecialNeeds { get; set; }
        public virtual ICollection<SpecialNeedsYearAttachment> SpecialNeedsYearAttachments { get; set; }
    }
}