// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class StudentClassHistory
    {
        public int Id { get; set; }
        public int StudentClassId { get; set; }
        public short SchoolYear { get; set; }
        public int ClassId { get; set; }
        public int PersonId { get; set; }
        public int? StudentSpecialityId { get; set; }
        public int StudentEduFormId { get; set; }
        public int? ClassNumber { get; set; }
        public int Status { get; set; }
        public bool? IsIndividualCurriculum { get; set; }
        public bool? IsHourlyOrganization { get; set; }
        public bool? IsForSubmissionToNra { get; set; }
        public bool IsCurrent { get; set; }
        public int RepeaterId { get; set; }
        public int? CommuterTypeId { get; set; }
        public bool? HasSuportiveEnvironment { get; set; }
        public string SupportiveEnvironment { get; set; }
        public DateTime EnrollmentDate { get; set; }
        public int? AdmissionDocumentId { get; set; }
        public int PositionId { get; set; }
        public int BasicClassId { get; set; }
        public int ClassTypeId { get; set; }
        public int? FromStudentClassId { get; set; }
        public int? DischargeReasonId { get; set; }
        public int? RelocationDocumentId { get; set; }
        public int? DischargeDocumentId { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBySysUserId { get; set; }
        public DateTime CreateDate { get; set; }
        public int? ModifiedBySysUserId { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? OrestypeId { get; set; }
        public bool? IsFtacoutsourced { get; set; }
        public int InstitutionId { get; set; }

        public virtual AdmissionDocument AdmissionDocument { get; set; }
        public virtual BasicClass BasicClass { get; set; }
        public virtual ClassGroup Class { get; set; }
        public virtual ClassType ClassType { get; set; }
        public virtual CommuterType CommuterType { get; set; }
        public virtual SysUser CreatedBySysUser { get; set; }
        public virtual DischargeDocument DischargeDocument { get; set; }
        public virtual DischargeReasonType DischargeReason { get; set; }
        public virtual StudentClass FromStudentClass { get; set; }
        public virtual InstitutionSchoolYear InstitutionSchoolYear { get; set; }
        public virtual SysUser ModifiedBySysUser { get; set; }
        public virtual ORESType Orestype { get; set; }
        public virtual Person Person { get; set; }
        public virtual Position Position { get; set; }
        public virtual RelocationDocument RelocationDocument { get; set; }
        public virtual RepeaterReason Repeater { get; set; }
        public virtual StudentClass StudentClass { get; set; }
        public virtual EduForm StudentEduForm { get; set; }
        public virtual Sppoospeciality StudentSpeciality { get; set; }
    }
}