// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class Town
    {
        public Town()
        {
            ApplicationChildren = new HashSet<ApplicationChild>();
            Applications = new HashSet<Application>();
            InstitutionDepartments = new HashSet<InstitutionDepartment>();
            InstitutionSchoolYears = new HashSet<InstitutionSchoolYear>();
            Institutions = new HashSet<Institution>();
            LocalAreas = new HashSet<LocalArea>();
            PersonBirthPlaceTowns = new HashSet<Person>();
            PersonCurrentTowns = new HashSet<Person>();
            PersonPermanentTowns = new HashSet<Person>();
            Universities = new HashSet<University>();
        }

        public int TownId { get; set; }
        public string Name { get; set; }
        public int Code { get; set; }
        public string Type { get; set; }
        public int Category { get; set; }
        public decimal? Longtitude { get; set; }
        public decimal? Latitude { get; set; }
        public int? MunicipalityId { get; set; }
        public string Description { get; set; }

        public virtual Municipality Municipality { get; set; }
        public virtual ICollection<ApplicationChild> ApplicationChildren { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<InstitutionDepartment> InstitutionDepartments { get; set; }
        public virtual ICollection<InstitutionSchoolYear> InstitutionSchoolYears { get; set; }
        public virtual ICollection<Institution> Institutions { get; set; }
        public virtual ICollection<LocalArea> LocalAreas { get; set; }
        public virtual ICollection<Person> PersonBirthPlaceTowns { get; set; }
        public virtual ICollection<Person> PersonCurrentTowns { get; set; }
        public virtual ICollection<Person> PersonPermanentTowns { get; set; }
        public virtual ICollection<University> Universities { get; set; }
    }
}