// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class VClassStudent
    {
        public int PersonId { get; set; }
        public string FullName { get; set; }
        public string Pin { get; set; }
        public string PinType { get; set; }
        public bool? IsAzureUser { get; set; }
        public string Username { get; set; }
        public string InitialPassword { get; set; }
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int? ClassNumber { get; set; }
        public bool IsCurrent { get; set; }
        public short SchoolYear { get; set; }
        public string ClassName { get; set; }
        public int InstitutionId { get; set; }
        public bool IsLodApproved { get; set; }
        public bool IsLodFinalized { get; set; }
        public int? LodFinalizationId { get; set; }
        public string LodNotFinalizationYears { get; set; }
        public string MainClassName { get; set; }
        public string EduFormName { get; set; }
        public string PositionName { get; set; }
        public int Status { get; set; }
    }
}