// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class VCurriculumStudentDetail
    {
        public int CurriculumStudentId { get; set; }
        public int CurriculumId { get; set; }
        public int PersonId { get; set; }
        public int? StudentClassId { get; set; }
        public bool IsValid { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public int InstitutionId { get; set; }
        public short SchoolYear { get; set; }
        public string SubjectName { get; set; }
        public string SubjectTypeName { get; set; }
        public float HoursWeeklyFirstTerm { get; set; }
        public float HoursWeeklySecondTerm { get; set; }
    }
}