// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class VLodStudentClass
    {
        public int PersonId { get; set; }
        public short SchoolYear { get; set; }
        public string SchoolYearName { get; set; }
        public int InstitutionId { get; set; }
        public string InstitutionName { get; set; }
        public DateTime EnrollmentDate { get; set; }
        public DateTime? DischargeDate { get; set; }
        public string ClassName { get; set; }
        public int BasicClassId { get; set; }
        public string BasciClassName { get; set; }
        public string EduFormName { get; set; }
        public string ClassTypeName { get; set; }
        public string Speciality { get; set; }
        public string Profession { get; set; }
        public string AdmissionDocNoteNumber { get; set; }
        public DateTime? AdmissionDocNoteDate { get; set; }
        public DateTime? AdmissionDocDate { get; set; }
        public string DischargeDocNoteNumber { get; set; }
        public DateTime? DischargeDocNoteDate { get; set; }
        public DateTime? DischargeDocDischargeDate { get; set; }
        public bool IsCurrent { get; set; }
        public int StudentClassId { get; set; }
    }
}