// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MON.DataAccess
{
    public partial class VStudentDiploma
    {
        public int PersonId { get; set; }
        public int? PersonalIdType { get; set; }
        public string PersonalIdTypeName { get; set; }
        public string PersonalId { get; set; }
        public string FullName { get; set; }
        public int StudentClassId { get; set; }
        public int StudentClassInstitutionId { get; set; }
        public string StudentClassInstitutionName { get; set; }
        public string StudentClassInstitutionAbbreviation { get; set; }
        public short StudentClassSchoolYear { get; set; }
        public string StudentClassSchoolYearName { get; set; }
        public bool StudentClassIsCurrent { get; set; }
        public int StudentClassBasicClassId { get; set; }
        public int? DiplomaId { get; set; }
        public int? BasicDocumentId { get; set; }
        public string BasicDocumentName { get; set; }
        public short? DiplomaSchoolYear { get; set; }
        public int? DiplomaInstitutionId { get; set; }
        public string DiplomaInstitutionName { get; set; }
        public int? DiplomaBasicClassId { get; set; }
        public bool? DiplomaIsCancelled { get; set; }
        public bool? DiplomaIsSigned { get; set; }
        public bool? DiplomaIsPublic { get; set; }
        public int? RegionId { get; set; }
    }
}