export enum TransformTypeEnum {
    CLOSE = 1,
    CONVERSION = 2,
    CHANGE_FINANCING_INSTITUTION = 3,
    TEMP_CLOSED = 4,
    OPENING = 5,
    CHANGE = 6,
    UNSUBSCRIBE = 8,
    CLOSED = 9,
    CONTINUING = 10,
    JOIN = 11,
    MERGE = 12,
    DETACH = 13,
    DIVIDE = 14,
    CHANGE_OF_CIRCUMSTANCES = 15,
    CHANGE_INSTITUTION_TYPE = 16,
    CHANGE_ACTIVITY_TYPE = 17,
    NOT_REGISTERED = 99
}
