export const HTML_SANITIZER_CONFIG = {
  ALLOWED_TAGS: [
    'p',
    'b',
    'strong',
    'i',
    'em',
    'u',
    's',
    'strike',
    'font',
    'a',
    'br',
    'span',
    'ul',
    'ol',
    'li',
    'div',
    'blockquote',
    'pre',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6'
  ],
  ALLOWED_ATTR: [
    'style',
    'href',
    'target',
    'color',
    'size',
    'class',
    'id',
    'align',
    'dir',
    'lang',
    'title',
    'alt',
    'name',
    'rel'
  ],
  ALLOW_DATA_ATTR: false,
  RETURN_TRUSTED_TYPE: false,
  ALLOWED_STYLES: [
    'text-decoration',
    'color',
    'background-color',
    'font-weight',
    'font-style',
    'font-size',
    'font-family',
    'line-height',
    'margin',
    'padding',
    'text-indent',
    'text-transform',
    'letter-spacing',
    'word-spacing',
    'white-space',
    'vertical-align',
    'list-style-type',
    'list-style-position'
  ],
  ADD_TAGS: ['a'],
  ADD_ATTR: ['href', 'target', 'rel'],
  KEEP_CONTENT: true
};
