def backendImage
def frontendImage
def backendImageNameTag
def frontendImageNameTag
def backendImageNameLatestTag
def frontendImageNameLatestTag
def tag
def branchName
def buildLatest = true

pipeline {
    agent { node { label 'mon-neispuo-image-builder' } }
    stages {
        stage('Run semantic-release') {
            steps {
                script {
                    branchName = "${env.GIT_BRANCH}".tokenize('/').last()
                    buildName "#${env.BUILD_NUMBER} ${branchName} TBD"
                    def lastCommitMessage = sh (script: "git log -1 | grep '.*\\[skip ci\\].*'", returnStatus: true)
                    if (lastCommitMessage == 0) {
                        env.CI_SKIP = 'true'
                        error "'[ci skip]' found in git commit message. Aborting."
                    }
                    sh('git tag -l | xargs git tag -d')
                    withCredentials([gitUsernamePassword(credentialsId: 'c62adc8e-e941-4c05-86df-e85191f61c19',
                        gitToolName: 'git-tool')]) {
                        sh('git fetch -t')
                            nvm('v16.13.0') {
                                sh "npm=\$(which npm)"
                                sh 'npm install'
                                sh 'npm run release'
                            }
                        }
                }
            }
        }
        stage('Preset environment details details') {
            steps {
                script {
                    branchName = "${env.GIT_BRANCH}".tokenize('/').last()
                    if (branchName == 'staging') {
                        tag = sh(returnStdout: true, script: "git tag --sort version:refname | cat | awk '/next/' | tail -1").trim()
                    } else if (branchName == 'main') {
                        buildLatest = false
                        tag = sh(returnStdout: true, script: "git tag --sort version:refname | cat | awk '!/next/' | tail -1").trim()
                    } else {
                        scmSkip(deleteBuild: true)
                    }
                    backendImageNameTag = "${env.REGISTRY_NAME}/${env.BACKEND_IMAGE_NAME}:${tag}"
                    frontendImageNameTag = "${env.REGISTRY_NAME}/${env.FRONTEND_IMAGE_NAME}:${tag}"
                    if (buildLatest) {
                        backendImageNameLatestTag = "${env.REGISTRY_NAME}/${env.BACKEND_IMAGE_NAME}:latest"
                        frontendImageNameLatestTag = "${env.REGISTRY_NAME}/${env.FRONTEND_IMAGE_NAME}:latest"
                    }
                    // https://plugins.jenkins.io/build-name-setter/
                    buildName "#${env.BUILD_NUMBER} ${branchName} ${tag}"
                }
            }
        }

        stage('Build and tag images') {
            steps {
                    dir ("${env.WORKSPACE}/${env.BACKEND_PROJECT_PATH}") {
                        script {
                            backendImage = docker.build("${backendImageNameTag}", ". --no-cache -f ${env.WORKSPACE}/${env.BACKEND_PROJECT_PATH}/Dockerfile")
                        }
                    }
                    dir ("${env.WORKSPACE}/${env.FRONTEND_PROJECT_PATH}") {
                        script {
                            sh "echo \"@dssbg:registry=https://gitlab.com/api/v4/projects/22328432/packages/npm/\n//gitlab.com/api/v4/projects/22328432/packages/npm/:_authToken=${env.GL_TOKEN}\" > .npmrc"
                            frontendImage = docker.build("${frontendImageNameTag}", ". --no-cache -f ${env.WORKSPACE}/${env.FRONTEND_PROJECT_PATH}/Dockerfile")
                        }
                    }
            }
        }
        stage('Push images to registry') {
            steps {
                script {
                    docker.withRegistry("https://${env.REGISTRY_NAME}", "${env.REGISTRY_CREDENTIALS}") {
                        backendImage.push(tag)
                        frontendImage.push(tag)
                        if (buildLatest) {
                            backendImage.push('latest')
                            frontendImage.push('latest')
                        }
                    }
                }
            }
        }
        stage('Clean up images') {
            steps {
                sh "docker rmi ${backendImageNameTag} -f"
                sh "docker rmi ${frontendImageNameTag} -f"
                script {
                    if (buildLatest) {
                        sh "docker rmi ${backendImageNameLatestTag} -f"
                        sh "docker rmi ${frontendImageNameLatestTag} -f"
                    }
                }

                sh 'docker system prune -f'
            }
        }
    }
}
