// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplomas.Public.DataAccess
{
    public partial class AspSubmittedDataHistory
    {
        public int Id { get; set; }
        public int InstitutionId { get; set; }
        public string PersonalId { get; set; }
        public int PersonalIdType { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public short? EduFormId { get; set; }
        public short? BasicClassId { get; set; }
        public byte Aspstatus { get; set; }
        public short? Year { get; set; }
        public short Month { get; set; }
        public string ExportTypeCode { get; set; }
        public int CreatedBySysUserId { get; set; }
        public DateTime CreateDate { get; set; }

        public virtual SysUser CreatedBySysUser { get; set; }
        public virtual Month MonthNavigation { get; set; }
        public virtual PersonalIdtype PersonalIdTypeNavigation { get; set; }
    }
}