// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplomas.Public.DataAccess
{
    public partial class AuditModule
    {
        public AuditModule()
        {
            ExtAccesses = new HashSet<ExtAccess>();
            Uierrors = new HashSet<Uierror>();
        }

        public int AuditModuleId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ExtAccess> ExtAccesses { get; set; }
        public virtual ICollection<Uierror> Uierrors { get; set; }
    }
}