// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplomas.Public.DataAccess
{
    public partial class BasicDocument
    {
        public BasicDocument()
        {
            BarcodeYears = new HashSet<BarcodeYear>();
            BasicDocumentLimits = new HashSet<BasicDocumentLimit>();
            BasicDocumentParts = new HashSet<BasicDocumentPart>();
            DiplomaAdditionalDocuments = new HashSet<DiplomaAdditionalDocument>();
            Diplomas = new HashSet<Diploma>();
            OtherDocuments = new HashSet<OtherDocument>();
            PrintTemplates = new HashSet<PrintTemplate>();
            Templates = new HashSet<Template>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsMoC { get; set; }
        public bool HasBarcode { get; set; }
        public string Contents { get; set; }
        public int? Pages { get; set; }
        public bool IsValid { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public int? AttachedImagesCountMin { get; set; }
        public int? AttachedImagesCountMax { get; set; }
        public string ReportFormPath { get; set; }
        public bool IsValidation { get; set; }
        public string CodeClassName { get; set; }
        public bool IsAppendix { get; set; }
        public bool HasFactoryNumber { get; set; }
        public bool IsUniqueForStudent { get; set; }
        public bool? HasSubjects { get; set; }
        public bool IsDuplicate { get; set; }
        public string SeriesFormat { get; set; }
        public int? PageOrientation { get; set; }
        public bool IsIncludedInRegister { get; set; }
        public string BasicClasses { get; set; }
        public string Abbreviation { get; set; }
        public bool IsRuoDoc { get; set; }
        public string MainBasicDocuments { get; set; }
        public string DetailedSchoolTypes { get; set; }

        public virtual ICollection<BarcodeYear> BarcodeYears { get; set; }
        public virtual ICollection<BasicDocumentLimit> BasicDocumentLimits { get; set; }
        public virtual ICollection<BasicDocumentPart> BasicDocumentParts { get; set; }
        public virtual ICollection<DiplomaAdditionalDocument> DiplomaAdditionalDocuments { get; set; }
        public virtual ICollection<Diploma> Diplomas { get; set; }
        public virtual ICollection<OtherDocument> OtherDocuments { get; set; }
        public virtual ICollection<PrintTemplate> PrintTemplates { get; set; }
        public virtual ICollection<Template> Templates { get; set; }
    }
}