// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplomas.Public.DataAccess
{
    public partial class InternationalMobility
    {
        public InternationalMobility()
        {
            InternationalMobilityDocuments = new HashSet<InternationalMobilityDocument>();
        }

        public int Id { get; set; }
        public string Project { get; set; }
        public string ReceivingInstitution { get; set; }
        public string MainObjectives { get; set; }
        public int PersonId { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public int CountryId { get; set; }
        public int CreatedBySysUserId { get; set; }
        public DateTime CreateDate { get; set; }
        public int? ModifiedBySysUserId { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? InstitutionId { get; set; }
        public short SchoolYear { get; set; }

        public virtual Country Country { get; set; }
        public virtual SysUser CreatedBySysUser { get; set; }
        public virtual InstitutionSchoolYear InstitutionSchoolYear { get; set; }
        public virtual SysUser ModifiedBySysUser { get; set; }
        public virtual Student Person { get; set; }
        public virtual CurrentYear SchoolYearNavigation { get; set; }
        public virtual ICollection<InternationalMobilityDocument> InternationalMobilityDocuments { get; set; }
    }
}