// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplomas.Public.DataAccess
{
    public partial class LodEvaluationSectionAb
    {
        public int Id { get; set; }
        public short SchoolYear { get; set; }
        public int OrderNum { get; set; }
        public int? SectionAfirstTermGrade { get; set; }
        public int? SectionAsecondTermGrade { get; set; }
        public int? SectionAfinalGrade { get; set; }
        public int? SectionAsession1Grade { get; set; }
        public int? SectionAsession2Grade { get; set; }
        public int? SectionAsession3Grade { get; set; }
        public int? SectionBfirstTermGrade { get; set; }
        public int? SectionBsecondTermGrade { get; set; }
        public int? SectionBfinalGrade { get; set; }
        public int? SectionBsession1Grade { get; set; }
        public int? SectionBsession2Grade { get; set; }
        public int? SectionBsession3Grade { get; set; }
        public int? SectionAhours { get; set; }
        public int? SectionBhours { get; set; }
        public int PersonId { get; set; }
        public int SubjectId { get; set; }
        public int? SubjectTypeId { get; set; }
        public int? StudentClassId { get; set; }
        public int CreatedBySysUserId { get; set; }
        public DateTime CreateDate { get; set; }
        public int? ModifiedBySysUserId { get; set; }
        public DateTime? ModifyDate { get; set; }

        public virtual SysUser CreatedBySysUser { get; set; }
        public virtual SysUser ModifiedBySysUser { get; set; }
        public virtual Person Person { get; set; }
        public virtual CurrentYear SchoolYearNavigation { get; set; }
        public virtual StudentClass StudentClass { get; set; }
        public virtual Subject Subject { get; set; }
    }
}