// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplomas.Public.DataAccess
{
    public partial class ResourceSupportDocument
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int ResourceSupporReportId { get; set; }
        public int DocumentId { get; set; }

        public virtual Document Document { get; set; }
        public virtual ResourceSupportReport ResourceSupporReport { get; set; }
    }
}