// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplomas.Public.DataAccess
{
    public partial class SysUserSysRole
    {
        public int SysUserId { get; set; }
        public int SysRoleId { get; set; }
        public int? InstitutionId { get; set; }
        public int? BudgetingInstitutionId { get; set; }
        public int? MunicipalityId { get; set; }
        public int? RegionId { get; set; }

        public virtual BudgetingInstitution BudgetingInstitution { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual Municipality Municipality { get; set; }
        public virtual Region Region { get; set; }
        public virtual SysRole SysRole { get; set; }
        public virtual SysUser SysUser { get; set; }
    }
}