import packageJson from '../../../package.json';

export class CONSTANTS {
    static ROUTER_PATH_CONTENT_LAYOUT = 'user-management';

    static ROUTER_PATH_HOME = 'home';

    static ROUTER_PATH_TEACHERS = 'teachers';

    static ROUTER_PATH_TEACHERS_UPDATE = 'update';

    static ROUTER_PATH_TEACHER_CLASSES = 'teacher-classes';

    static ROUTER_PATH_ROLES_UPDATE = 'update-roles';

    static ROUTER_PATH_SCHOOL_BOOKS_ACCESS_UPDATE = 'school-books-access';

    static ROUTER_PATH_STUDENTS = 'students';

    static ROUTER_PATH_PARENTS = 'parents';

    static ROUTER_PATH_AUDIT = 'audit';

    static ROUTER_PATH_ROLE_AUDIT = 'role';

    static ROUTER_PATH_LOGIN_AUDIT = 'login';

    static ROUTER_PATH_STUDENTS_UPDATE = 'update';

    static ROUTER_PATH_INSTITUTIONS = 'institutions';

    static ROUTER_PATH_INSTITUTIONS_UPDATE = 'update';

    static ROUTER_PATH_MON = 'mon';

    static ROUTER_PATH_RUO = 'ruo';

    static ROUTER_PATH_MUNICIPALITIES = 'municipalities';

    static ROUTER_PATH_BUDGET_INSTITUTIONS = 'budget-institutions';

    static ROUTER_PATH_OTHER_USERS = 'other-azure-users';

    static ROUTER_PATH_USERS = 'azure-users';

    static ROUTER_PATH_ERRORS = 'errors';

    static ROUTER_PATH_CREATE_USER = 'create-user';

    static ROUTER_PATH_JOBS = 'jobs';

    static ROUTER_PATH_CLASSES = 'azure-classes';

    static ROUTER_PATH_ORGANIZATIONS = 'azure-organizations';

    static ROUTER_PATH_ENROLLMENTS = 'azure-enrollments';

    static ROUTER_PATH_UNAUTHORIZED = 'unauthorized';

    static ROUTER_PATH_LOGIN_LAYOUT = '';

    static ROUTER_PATH_LOGIN = 'login';

    static ROUTER_PATH_SIGN_IN_CALLBACK = 'signin-callback';

    static ROUTER_PATH_SILENT_SIGN_IN_CALLBACK = 'silent-signin-callback';

    static ROUTER_PATH_AZURE_USERS = 'azure-users';

    static ROUTER_PATH_AZURE_USERS_UPDATE = 'update';

    static ROUTER_PATH_AZURE_CLASSES = 'azure-classes';

    static ROUTER_PATH_AZURE_CLASSES_UPDATE = 'update';

    static ROUTER_PATH_AZURE_ENROLLMENT = 'azure-enrollments';

    static ROUTER_PATH_AZURE_ENROLLMENT_UPDATE = 'update';

    static ROUTER_PATH_AZURE_ORGANIZATIONS = 'azure-organizations';

    static ROUTER_PATH_AZURE_ORGANIZATIONST_UPDATE = 'update';

    static ROUTER_PATH_SYNC_HISTORY = 'sync-history';

    static ROUTER_PATH_LINKED_USERS = 'linked-users';

    static USERMENU_MENU_OPTIONS_EXIT = 'USERMENU.MENU.OPTIONS.EXIT';

    static DASHBOARD_MENU_TITLE = 'DASHBOARD.MENU.TITLE';

    static DASHBOARD_MENU_OPTIONS_MAIN_PORTAL = 'DASHBOARD.MENU.OPTIONS.MAIN_PORTAL';

    static SIDEMENU_SECTION_TITLE_USERS_NEISPUO = 'SIDEMENU.SECTION.TITLE.USERS.NEISPUO';

    static SIDEMENU_SECTION_TITLE_USERS_EXTERNAL = 'SIDEMENU.SECTION.TITLE.USERS.EXTERNAL';

    static SIDEMENU_SECTION_TITLE_USERS_SYNCRONIZATION = 'SIDEMENU.SECTION.TITLE.USERS.SYNCRONIZATION';

    static SIDEMENU_SECTION_TITLE_USERS_ADMIN = 'SIDEMENU.SECTION.TITLE.USERS.ADMIN';

    static SIDEMENU_TAB_TITLE_HOME = 'SIDEMENU.TAB.TITLE.HOME';

    static SIDEMENU_TAB_TITLE_TEACHERS = 'SIDEMENU.TAB.TITLE.TEACHERS';

    static SIDEMENU_TAB_TITLE_TEACHER_CLASSES = 'SIDEMENU.TAB.TITLE.TEACHER_CLASSES';

    static SIDEMENU_TAB_TITLE_TEACHERS_UPDATE = 'SIDEMENU.TAB.TITLE.TEACHERS_UPDATE';

    static SIDEMENU_TAB_TITLE_ROLES_UPDATE = 'SIDEMENU.TAB.TITLE.ROLES_UPDATE';

    static SIDEMENU_TAB_SCHOOL_BOOKS_ACCESS_UPDATE = 'SIDEMENU.TAB.TITLE.SCHOOL_BOOKS_ACCESS';

    static SIDEMENU_TAB_TITLE_ROLE_AUDIT = 'SIDEMENU.TAB.TITLE.ROLE_AUDIT';

    static SIDEMENU_TAB_TITLE_LOGIN_AUDIT = 'SIDEMENU.TAB.TITLE.LOGIN_AUDIT';

    static SIDEMENU_TAB_TITLE_STUDENTS = 'SIDEMENU.TAB.TITLE.STUDENTS';

    static SIDEMENU_TAB_TITLE_STUDENTS_UPDATE = 'SIDEMENU.TAB.TITLE.STUDENTS_UPDATE';

    static SIDEMENU_TAB_TITLE_PARENTS = 'SIDEMENU.TAB.TITLE.PARENTS';

    static SIDEMENU_TAB_TITLE_INSTITUTIONS = 'SIDEMENU.TAB.TITLE.INSTITUTIONS';

    static SIDEMENU_TAB_TITLE_INSTITUTIONS_UPDATE = 'SIDEMENU.TAB.TITLE.INSTITUTIONS_UPDATE';

    static SIDEMENU_TAB_TITLE_MON = 'SIDEMENU.TAB.TITLE.MON';

    static SIDEMENU_TAB_TITLE_RUO = 'SIDEMENU.TAB.TITLE.RUO';

    static SIDEMENU_TAB_TITLE_MUNICIPALITIES = 'SIDEMENU.TAB.TITLE.MUNICIPALITIES';

    static SIDEMENU_TAB_TITLE_BUDGET_INSTITUTIONS = 'SIDEMENU.TAB.TITLE.BUDGET_INSTITUTIONS';

    static SIDEMENU_TAB_TITLE_OTHER_USERS = 'SIDEMENU.TAB.TITLE.OTHER_USERS';

    static SIDEMENU_TAB_TITLE_USERS = 'SIDEMENU.TAB.TITLE.USERS';

    static SIDEMENU_TAB_TITLE_CLASSES = 'SIDEMENU.TAB.TITLE.CLASSES';

    static SIDEMENU_TAB_TITLE_ORGANIZATIONS = 'SIDEMENU.TAB.TITLE.ORGANIZATIONS';

    static SIDEMENU_TAB_TITLE_ENROLLMENTS = 'SIDEMENU.TAB.TITLE.ENROLLMENTS';

    static SIDEMENU_TAB_TITLE_JOBS = 'SIDEMENU.TAB.TITLE.JOBS';

    static SIDEMENU_TAB_TITLE_ERRORS = 'SIDEMENU.TAB.TITLE.ERRORS';

    static SIDEMENU_TAB_TITLE_CREATE_USER = 'SIDEMENU.TAB.TITLE.CREATE_USER';

    static SIDEMENU_TAB_TITLE_UNAUTHORIZED = 'SIDEMENU.TAB.TITLE.UNAUTHORIZED';

    static FOOTER_CONTENT_TEXT1 = 'FOOTER.CONTENT.TEXT1';

    static FOOTER_CONTENT_TEXT2 = 'FOOTER.CONTENT.TEXT2';

    static FOOTER_CONTENT_TEXT3 = 'FOOTER.CONTENT.TEXT3';

    static PRIMENG_DYNAMIC_DIALOG_SELECT_SCHOOL_BOOKS_HEADER = 'PRIMENG.DYNAMIC_DIALOG.SELECT_SCHOOL_BOOKS_HEADER';

    static PRIMENG_CONFIRM_DIALOG_HEADER = 'PRIMENG.CONFIRM_DIALOG.HEADER';

    static PRIMENG_CONFIRM_DIALOG_BUTTON_CONFIRM = 'PRIMENG.CONFIRM_DIALOG.BUTTON.CONFIRM';

    static PRIMENG_CONFIRM_DIALOG_BUTTON_DECLINE = 'PRIMENG.CONFIRM_DIALOG.BUTTON.DECLINE';

    static PRIMENG_CONFIRM_DIALOG_SUMMARY_UPDATE_SCHOOL_BOOK_CODE =
        'PRIMENG.CONFIRM_DIALOG.SUMMARY.UPDATE_SCHOOL_BOOK_CODE';

    static PRIMENG_CONFIRM_DIALOG_MESSAGE_UPDATE_SCHOOL_BOOK_CODE =
        'PRIMENG.CONFIRM_DIALOG.MESSAGE.UPDATE_SCHOOL_BOOK_CODE';

    static PRIMENG_CONFIRM_DIALOG_MESSAGE_DELETE_SCHOOL_BOOK_ACCESS =
        'PRIMENG.CONFIRM_DIALOG.MESSAGE.DELETE_SCHOOL_BOOK_ACCESS';

    static PRIMENG_CONFIRM_DIALOG_MESSAGE_DELETE_SELECTED_SCHOOL_BOOK_ACCESSES =
        'PRIMENG.CONFIRM_DIALOG.MESSAGE.DELETE_SELECTED_SCHOOL_BOOK_ACCESSES';

    static PRIMENG_CONFIRM_DIALOG_MESSAGE_ARE_YOU_SURE = 'PRIMENG.CONFIRM_DIALOG.MESSAGE.ARE_YOU_SURE';

    static PRIMENG_TOASTR_SUMMARY_RESTART_WORKFLOW = 'PRIMENG.TOASTR.SUMMARY.RESTART_WORKFLOW';

    static PRIMENG_TOASTR_SUMMARY_GIVE_SCHOOL_BOOK_ACCESS = 'PRIMENG.TOASTR.SUMMARY.GIVE_SCHOOL_BOOK_ACCESS';

    static PRIMENG_TOASTR_SUMMARY_UPDATE_SCHOOL_BOOK_ACCESS = 'PRIMENG.TOASTR.SUMMARY.UPDATE_SCHOOL_BOOK_ACCESS';

    static PRIMENG_TOASTR_SUMMARY_DELETE_SCHOOL_BOOK_ACCESS = 'PRIMENG.TOASTR.SUMMARY.DELETE_SCHOOL_BOOK_ACCESS';

    static PRIMENG_TOASTR_SUMMARY_ERROR = 'PRIMENG.TOASTR.SUMMARY.ERROR';

    static PRIMENG_CONFIG_FILTER_DELAY_MILISECS = 1000;

    static PRIMENG_MULTISELECT_LABEL_PLACEHOLDER = 'PRIMENG.MULTISELECT.LABEL.PLACEHOLDER';

    static PRIMENG_MULTISELECT_LABEL_EMPTY = 'PRIMENG.MULTISELECT.LABEL.EMPTY';

    static PRIMENG_MULTISELECT_LABEL_NO_MORE_SCHOOL_BOOKS = 'PRIMENG.MULTISELECT.LABEL.NO_MORE_SCHOOL_BOOKS';

    static PRIMENG_CALENDAR_PLACEHOLDER = 'PRIMENG.CALENDAR.PLACEHOLDER';

    static PRIMENG_DROPDOWN_PLACEHOLDER = 'PRIMENG.DROPDOWN.PLACEHOLDER';

    static PRIMENG_INPUT_PLACEHOLDER = 'PRIMENG.INPUT.PLACEHOLDER';

    static PRIMENG_INPUT_PLACEHOLDER_START_SEARCH = 'PRIMENG.INPUT.START_SEARCH';

    static PRIMENG_TITLE_GENERATE_CODE = 'PRIMENG.TITLE.GENERATE_CODE';

    static PRIMENG_TITLE_CREATE_USER = 'PRIMENG.TITLE.CREATE_USER';

    static PRIMENG_TITLE_SYNC_USER = 'PRIMENG.TITLE.SYNC_USER';

    static PRIMENG_TITLE_CONVERT_USER = 'PRIMENG.TITLE.CONVERT_USER';

    static PRIMENG_TITLE_REFRESH = 'PRIMENG.TITLE.REFRESH';

    static PRIMENG_TITLE_SEARCH = 'PRIMENG.TITLE.SEARCH';

    static PRIMENG_TITLE_WORKFLOW_RESTART = 'PRIMENG.TITLE.WORKFLOW_RESTART';

    static PRIMENG_TITLE_SAVE = 'PRIMENG.TITLE.SAVE';

    static PRIMENG_TITLE_LOADING = 'PRIMENG.TITLE.LOADING';

    static PRIMENG_TITLE_CANCEL = 'PRIMENG.TITLE.CANCEL';

    static PRIMENG_TITLE_TOGGLE = 'PRIMENG.TITLE.TOGGLE';

    static PRIMENG_TITLE_SYNC_HISTORY = 'PRIMENG.TITLE.SYNC_HISTORY';

    static PRIMENG_TITLE_ADD_STUDENT = 'PRIMENG.TITLE.ADD_STUDENT';

    static PRIMENG_TITLE_ADD_PARENT = 'PRIMENG.TITLE.ADD_PARENT';

    static PRIMENG_TITLE_ROLES_MANAGEMENT = 'PRIMENG.TITLE.ROLES_MANAGEMENT';

    static PRIMENG_TITLE_SCHOOL_BOOKS_ACCESS = 'PRIMENG.TITLE.SCHOOL_BOOKS_ACCESS';

    static PRIMENG_TITLE_IMPERSONATION = 'PRIMENG.TITLE.IMPERSONATION';

    static PRIMENG_TITLE_SCHOOL_BOOKS_ACCESS_REMOVE = 'PRIMENG.TITLE.SCHOOL_BOOKS_ACCESS_REMOVE';

    static PRIMENG_TITLE_GIVE_SCHOOL_BOOKS_ACCESS = 'PRIMENG.TITLE.GIVE_SCHOOL_BOOKS_ACCESS';

    static PRIMENG_TABLE_FIELD_SCHOOL_YEAR = 'PRIMENG.TABLE.FIELD.SCHOOL_YEAR';

    static PRIMENG_TABLE_FIELD_SCHOOL_BOOK = 'PRIMENG.TABLE.FIELD.SCHOOL_BOOK';

    static PRIMENG_TABLE_FIELD_ADMIN_ACCESS = 'PRIMENG.TABLE.FIELD.ADMIN_ACCESS';

    static CONTENT_TOOLBAR_EXPORT_BUTTON_LABEL_ADD = 'CONTENT.TOOLBAR.EXPORT.BUTTON.LABEL.ADD';

    static CONTENT_TOOLBAR_EXPORT_BUTTON_LABEL_REMOVE = 'CONTENT.TOOLBAR.EXPORT.BUTTON.LABEL.REMOVE';

    static CONTENT_TOOLBAR_EXPORT_BUTTON_LABEL_LOADING = 'CONTENT.TOOLBAR.EXPORT.BUTTON.LABEL.LOADING';

    static CONTENT_TOOLBAR_EXPORT_BUTTON_LABEL_NOT_LOADING = 'CONTENT.TOOLBAR.EXPORT.BUTTON.LABEL.NOT_LOADING';

    static SESSION_STORAGE_SCHOOL_BOOK_ACCESS = 'SESSION_STORAGE_SCHOOL_BOOK_ACCESS';

    static SESSION_STORAGE_ROLE_UPDATE_INSTITUTION_ID = 'SESSION_STORAGE_ROLE_UPDATE_INSTITUTION_ID';

    static VERSION_FRONTEND = `${packageJson.name}: ${packageJson.version}`;

    static LANGUAGE_BG = 'bg';

    static YES = 'YES';

    static NO = 'NO';

    static PROFILE_TAB_NEISPUO = 'PROFILE.TAB.NEISPUO';

    static PROFILE_TAB_PROFILE = 'PROFILE.TAB.PROFILE';

    static PROFILE_TAB_SCHOOL_ENROLLMENTS = 'PROFILE.TAB.SCHOOL_ENROLLMENTS';

    static PROFILE_TAB_CLASS_ENROLLMENTS = 'PROFILE.TAB.CLASS_ENROLLMENTS';

    static PRIMENG_NO_DATA_FOUND = 'PRIMENG.NO_DATA_FOUND';

    static PRIMENG_TITLE_RELOAD_ACTIVE_YEAR = 'PRIMENG.TITLE.RELOAD_ACTIVE_YEAR';

    static PRIMENG_ERROR_LOADING_DATA = 'PRIMENG.ERROR.LOADING_DATA';

    static PRIMENG_LABEL_SELECT_YEARS = 'PRIMENG.LABEL.SELECT_YEARS';

    static PRIMENG_LABEL_LOAD_ENROLLMENTS = 'PRIMENG.LABEL.LOAD_ENROLLMENTS';

    static PRIMENG_TAB_SYNC = 'PRIMENG.TAB.SYNC';

    static PRIMENG_TAB_ENROLLMENTS = 'PRIMENG.TAB.ENROLLMENTS';

    static PRIMENG_TITLE_SYS_USER_TABLE = 'PRIMENG.TITLE.SYS_USER_TABLE';

    static PRIMENG_TITLE_AZURE_DATA = 'PRIMENG.TITLE.AZURE_DATA';

    static PRIMENG_TITLE_LOAD_WITH = 'PRIMENG.TITLE.LOAD_WITH';

    static PRIMENG_TITLE_PUBLIC_EDU_NUMBER = 'PRIMENG.TITLE.PUBLIC_EDU_NUMBER';

    static PRIMENG_TITLE_AZURE_ID = 'PRIMENG.TITLE.AZURE_ID';

    static PRIMENG_TITLE_SCHOOL_PROFILE = 'PRIMENG.TITLE.SCHOOL_PROFILE';

    static PRIMENG_TITLE_ADD = 'PRIMENG.TITLE.ADD';

    static PRIMENG_TITLE_REMOVE = 'PRIMENG.TITLE.REMOVE';

    static PRIMENG_TITLE_EMAIL = 'PRIMENG.TITLE.EMAIL';

    static PRIMENG_TITLE_IDENTIFIER = 'PRIMENG.TITLE.IDENTIFIER';
}
