:r "./Insert/logs/AuditModule.sql"

:r "./Insert/Location/Country.sql"
:r "./Insert/Location/Region.sql"
:r "./Insert/Location/Municipality.sql"
:r "./Insert/Location/Town.sql"
:r "./Insert/Location/LocalArea.sql"

:r "./Insert/noms/BaseSchoolType.sql"
:r "./Insert/noms/BudgetingInstitution.sql"
:r "./Insert/noms/DetailedSchoolType.sql"
:r "./Insert/noms/FinancialSchoolType.sql"
:r "./Insert/noms/Gender.sql"
:r "./Insert/noms/PersonalIDType.sql"
:r "./Insert/noms/ExtSystemType.sql"

:r "./Insert/inst_basic/CurrentYear.sql"

:r "./Insert/core/RelativeType.sql"
:r "./Insert/core/SysRole.sql"
:r "./Insert/core/Position.sql"
:r "./Insert/core/tempPerson.sql"
:r "./Insert/core/tempPersonNames.sql"
:r "./Insert/core/Person.sql"
:r "./Insert/core/SysUser.sql"
:r "./Insert/core/Relative.sql"
:r "./Insert/core/RelativeUpdate.sql"

:r "./Insert/core/Institution.sql"
:r "./Insert/core/InstitutionDepartment.sql"
:r "./Insert/core/InstitutionSchoolYear.sql"

:r "./Insert/core/ExtSystem.sql"
:r "./Insert/core/ExtSystemAccess.sql"
:r "./Insert/core/ExtSystemCertificate.sql"
:r "./Insert/core/InstitutionConfData.sql"
:r "./Insert/school_books/ClassBookExtProvider.sql"

:r "./Insert/document/BasicDocument.sql"
:r "./Insert/document/EducationType.sql"
:r "./Insert/document/ITLevel.sql"

:r "./Insert/inst_nom/BasicClass.sql"
:r "./Insert/inst_nom/BasicSubjectType.sql"
:r "./Insert/inst_nom/ClassType.sql"
:r "./Insert/inst_nom/CurriculumPart.sql"
:r "./Insert/inst_nom/CustomVarValue.sql"
:r "./Insert/inst_nom/EduForm.sql"
:r "./Insert/inst_nom/FLLevel.sql"
:r "./Insert/inst_nom/NKPDPosition.sql"
:r "./Insert/inst_nom/SPPOOEducArea.sql"
:r "./Insert/inst_nom/SPPOOProfArea.sql"
:r "./Insert/inst_nom/SPPOOProfession.sql"
:r "./Insert/inst_nom/SPPOOSpeciality.sql"
:r "./Insert/inst_nom/StaffType.sql"
:r "./Insert/inst_nom/Subject.sql"
:r "./Insert/inst_nom/SubjectType.sql"

:r "./Insert/inst_basic/InstitutionDetail.sql"
:r "./Insert/inst_basic/StaffPosition.sql"

:r "./Insert/inst_year/ClassGroup.sql"
:r "./Insert/inst_year/Curriculum.sql"
:r "./Insert/inst_year/CurriculumClass.sql"
:r "./Insert/inst_year/CurriculumTeacher.sql"
:r "./Insert/inst_year/CurriculumStudent.sql"

:r "./Insert/student/CommuterType.sql"
:r "./Insert/student/RepeaterReason.sql"
:r "./Insert/student/Ministry.sql"
:r "./Insert/student/SanctionType.sql"
:r "./Insert/student/tempStudentClass.sql"
:r "./Insert/student/Student.sql"
:r "./Insert/student/StudentClass.sql"

:r "./Insert/document/Diploma.sql"

:r "./Insert/school_books/SupportActivityType.sql"
:r "./Insert/school_books/SupportDifficultyType.sql"
:r "./Insert/school_books/ProtocolExamType.sql"
:r "./Insert/school_books/ProtocolExamSubType.sql"
:r "./Insert/school_books/QualificationDegree.sql"
:r "./Insert/school_books/QualificationExamType.sql"
:r "./Insert/school_books/AbsenceReason.sql"
:r "./Insert/school_books/PerformanceType.sql"
:r "./Insert/school_books/ReplrParticipationType.sql"
:r "./Insert/school_books/TopicPlanPublisher.sql"

:r "./Insert/school_books/SchoolYearSettingsDefault.sql"
:r "./Insert/school_books/SchoolYearSettings.sql"
:r "./Insert/school_books/Shift.sql"

:r "./Insert/school_books/ClassBook.sql"
:r "./Insert/school_books/Schedule.sql"
:r "./Insert/school_books/ScheduleHour.sql"
:r "./Insert/school_books/ScheduleDate.sql"
:r "./Insert/school_books/ScheduleLesson.sql"
:r "./Insert/school_books/Grade.sql"
:r "./Insert/school_books/Absence.sql"
:r "./Insert/school_books/Topic.sql"

:r "./Insert/school_books/HisMedicalNotice.sql"

:r "./Insert/school_books/UpdateScript.sql"
