/* eslint no-undef: "off" */

cube('RAverageGradesPerClass', {
  sql: 'SELECT * FROM R_Average_Grades_Per_Class',
  title: 'Справка за срочен и годишен успех по класове',
  description:
    'Срочни и годишни оценки по класове и предмети (брой ученици, проценти и средни оценки).',
  // preAggregations: {
  //   orderByRegion: {
  //     type: 'rollup',
  //     dimensions: [
  //       RAverageGradesPerClass.RegionID,
  //       RAverageGradesPerClass.SchoolYear,
  //       RAverageGradesPerClass.InstitutionID,
  //     ],
  //     measures: [
  //       RAverageGradesPerClass.countClassBookId,
  //       RAverageGradesPerClass.sumStudentsStudyingSubject,
  //       RAverageGradesPerClass.sumStudentsWithTerm1Grades,
  //       RAverageGradesPerClass.sumStudentsWithTerm2Grades,
  //       RAverageGradesPerClass.sumStudentsWithYearGrades,
  //       RAverageGradesPerClass.avgPercentStudentsWithTerm1Grades,
  //       RAverageGradesPerClass.avgPercentStudentsWithTerm2Grades,
  //       RAverageGradesPerClass.avgPercentStudentsWithYearGrades,
  //       RAverageGradesPerClass.avgAverageTerm1Grade,
  //       RAverageGradesPerClass.avgAverageTerm2Grade,
  //       RAverageGradesPerClass.avgAverageYearGrade,
  //     ],
  //     indexes: {
  //       r_average_grades_per_class_index: {
  //         columns: [
  //           RAverageGradesPerClass.RegionID,
  //           RAverageGradesPerClass.SchoolYear,
  //           RAverageGradesPerClass.InstitutionID,
  //         ],
  //       },
  //     },
  //   },
  // },

  joins: {},

  measures: {
    countClassBookId: {
      type: 'count',
      title: 'Брой класове',
      sql: 'ClassBookId',
      drillMembers: [
        RegionID,
        RegionName,
        MunicipalityName,
        TownName,
        SchoolYear,
        InstitutionID,
        InstitutionName,
        ClassBookId,
        ClassOrGroupName,
        SubjectName,
        SubjectTypeName,
        StudentsStudyingSubject,
        StudentsWithTerm1Grades,
        StudentsWithTerm2Grades,
        StudentsWithYearGrades,
        PercentStudentsWithTerm1Grades,
        PercentStudentsWithTerm2Grades,
        PercentStudentsWithYearGrades,
        AverageTerm1Grade,
        AverageTerm2Grade,
        AverageYearGrade,
      ],
    },
    sumStudentsStudyingSubject: {
      type: 'sum',
      title: 'Общо ученици, изучаващи предмета',
      sql: 'StudentsStudyingSubject',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        SchoolYear,
        ClassBookId,
        ClassOrGroupName,
        SubjectName,
        SubjectTypeName,
        StudentsStudyingSubject,
      ],
    },
    sumStudentsWithTerm1Grades: {
      type: 'sum',
      title: 'Общо ученици с оценки през I срок',
      sql: 'StudentsWithTerm1Grades',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        SchoolYear,
        ClassBookId,
        ClassOrGroupName,
        SubjectName,
        SubjectTypeName,
        StudentsWithTerm1Grades,
        PercentStudentsWithTerm1Grades,
        AverageTerm1Grade,
      ],
    },
    sumStudentsWithTerm2Grades: {
      type: 'sum',
      title: 'Общо ученици с оценки през II срок',
      sql: 'StudentsWithTerm2Grades',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        SchoolYear,
        ClassBookId,
        ClassOrGroupName,
        SubjectName,
        SubjectTypeName,
        StudentsWithTerm2Grades,
        PercentStudentsWithTerm2Grades,
        AverageTerm2Grade,
      ],
    },
    sumStudentsWithYearGrades: {
      type: 'sum',
      title: 'Общо ученици с годишни оценки',
      sql: 'StudentsWithYearGrades',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        SchoolYear,
        ClassBookId,
        ClassOrGroupName,
        SubjectName,
        SubjectTypeName,
        StudentsWithYearGrades,
        PercentStudentsWithYearGrades,
        AverageYearGrade,
      ],
    },
    avgPercentStudentsWithTerm1Grades: {
      type: 'avg',
      title: 'Среден процент ученици с оценки през I срок',
      sql: 'PercentStudentsWithTerm1Grades',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        SchoolYear,
        ClassBookId,
        ClassOrGroupName,
        SubjectName,
        SubjectTypeName,
        PercentStudentsWithTerm1Grades,
      ],
    },
    avgPercentStudentsWithTerm2Grades: {
      type: 'avg',
      title: 'Среден процент ученици с оценки през II срок',
      sql: 'PercentStudentsWithTerm2Grades',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        SchoolYear,
        ClassBookId,
        ClassOrGroupName,
        SubjectName,
        SubjectTypeName,
        PercentStudentsWithTerm2Grades,
      ],
    },
    avgPercentStudentsWithYearGrades: {
      type: 'avg',
      title: 'Среден процент ученици с годишни оценки',
      sql: 'PercentStudentsWithYearGrades',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        SchoolYear,
        ClassBookId,
        ClassOrGroupName,
        SubjectName,
        SubjectTypeName,
        PercentStudentsWithYearGrades,
      ],
    },
    avgAverageTerm1Grade: {
      type: 'avg',
      title: 'Средна оценка през I срок',
      sql: 'AverageTerm1Grade',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        SchoolYear,
        ClassBookId,
        ClassOrGroupName,
        SubjectName,
        SubjectTypeName,
        AverageTerm1Grade,
      ],
    },
    avgAverageTerm2Grade: {
      type: 'avg',
      title: 'Средна оценка през II срок',
      sql: 'AverageTerm2Grade',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        SchoolYear,
        ClassBookId,
        ClassOrGroupName,
        SubjectName,
        SubjectTypeName,
        AverageTerm2Grade,
      ],
    },
    avgAverageYearGrade: {
      type: 'avg',
      title: 'Средна годишна оценка',
      sql: 'AverageYearGrade',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        SchoolYear,
        ClassBookId,
        ClassOrGroupName,
        SubjectName,
        SubjectTypeName,
        AverageYearGrade,
      ],
    },
  },

  dimensions: {
    RegionID: {
      sql: 'RegionID',
      type: 'number',
      title: 'Код на област',
      shown: false,
    },
    RegionName: {
      sql: 'RegionName',
      type: 'string',
      title: 'Област',
    },
    MunicipalityName: {
      sql: 'MunicipalityName',
      type: 'string',
      title: 'Община',
    },
    TownName: {
      sql: 'TownName',
      type: 'string',
      title: 'Населено място',
    },
    SchoolYear: {
      sql: 'SchoolYear',
      type: 'number',
      title: 'Учебна година',
    },
    InstitutionID: {
      sql: 'InstitutionID',
      type: 'number',
      title: 'Код по НЕИСПУО',
    },
    InstitutionName: {
      sql: 'InstitutionName',
      type: 'string',
      title: 'Име на институция',
    },
    ClassBookId: {
      sql: 'ClassBookId',
      type: 'number',
      title: 'Код на клас',
      shown: false,
    },
    ClassOrGroupName: {
      sql: 'ClassOrGroupName',
      type: 'string',
      title: 'Клас/група',
    },
    SubjectName: {
      sql: 'SubjectName',
      type: 'string',
      title: 'Предмет',
    },
    SubjectTypeName: {
      sql: 'SubjectTypeName',
      type: 'string',
      title: 'Тип предмет',
    },
    StudentsStudyingSubject: {
      sql: 'StudentsStudyingSubject',
      type: 'number',
      title: 'Ученици, изучаващи предмета',
    },
    StudentsWithTerm1Grades: {
      sql: 'StudentsWithTerm1Grades',
      type: 'number',
      title: 'Ученици с оценки - I срок',
    },
    StudentsWithTerm2Grades: {
      sql: 'StudentsWithTerm2Grades',
      type: 'number',
      title: 'Ученици с оценки - II срок',
    },
    StudentsWithYearGrades: {
      sql: 'StudentsWithYearGrades',
      type: 'number',
      title: 'Ученици с годишни оценки',
    },
    PercentStudentsWithTerm1Grades: {
      sql: 'PercentStudentsWithTerm1Grades',
      type: 'number',
      title: 'Процент ученици с оценки - I срок',
    },
    PercentStudentsWithTerm2Grades: {
      sql: 'PercentStudentsWithTerm2Grades',
      type: 'number',
      title: 'Процент ученици с оценки - II срок',
    },
    PercentStudentsWithYearGrades: {
      sql: 'PercentStudentsWithYearGrades',
      type: 'number',
      title: 'Процент ученици с годишни оценки',
    },
    AverageTerm1Grade: {
      sql: 'AverageTerm1Grade',
      type: 'number',
      title: 'Средна оценка - I срок',
    },
    AverageTerm2Grade: {
      sql: 'AverageTerm2Grade',
      type: 'number',
      title: 'Средна оценка - II срок',
    },
    AverageYearGrade: {
      sql: 'AverageYearGrade',
      type: 'number',
      title: 'Средна годишна оценка',
    },
  },

  dataSource: 'default',
});


