/* eslint no-undef: "off" */

cube('RRegularAverageAbsencePerStudent', {
  sql: 'SELECT * FROM R_Regular_Average_Absence_Per_Student',
  title: 'Справка за отсъствия по ученик - I-XII клас',
  description:
    'Средни отсъствия по ученици (I–XII клас) с разбивка по видове извинения.',

  // preAggregations: {
  //   orderByRegion: {
  //     type: 'rollup',
  //     dimensions: [
  //       RRegularAverageAbsencePerStudent.RegionID,
  //       RRegularAverageAbsencePerStudent.SchoolYear,
  //       RRegularAverageAbsencePerStudent.InstitutionID,
  //       RRegularAverageAbsencePerStudent.FirstName,
  //       RRegularAverageAbsencePerStudent.LastName,
  //       RRegularAverageAbsencePerStudent.PersonID,
  //     ],
  //     measures: [
  //       RRegularAverageAbsencePerStudent.countPersonID,
  //       RRegularAverageAbsencePerStudent.sumTotalUnexcusedAbsences,
  //       RRegularAverageAbsencePerStudent.sumExcusedByMedicalNoticeAbsence,
  //       RRegularAverageAbsencePerStudent.sumExcusedByHealthReasonAbsence,
  //       RRegularAverageAbsencePerStudent.sumExcusedByFamilyReasonAbsence,
  //       RRegularAverageAbsencePerStudent.sumExcusedByOtherReasonAbsence,
  //       RRegularAverageAbsencePerStudent.sumTotalExcusedAbsences,
  //     ],
  //     indexes: {
  //       r_regular_average_absence_per_student_index: {
  //         columns: [
  //           RRegularAverageAbsencePerStudent.RegionID,
  //           RRegularAverageAbsencePerStudent.SchoolYear,
  //           RRegularAverageAbsencePerStudent.InstitutionID,
  //           RRegularAverageAbsencePerStudent.FirstName,
  //           RRegularAverageAbsencePerStudent.LastName,
  //           RRegularAverageAbsencePerStudent.PersonID,
  //         ],
  //       },
  //     },
  //   },
  // },

  joins: {},

  measures: {
    countPersonID: {
      type: 'count',
      title: 'Брой ученици',
      sql: 'PersonID',
      drillMembers: [
        RegionID,
        RegionName,
        MunicipalityName,
        TownName,
        SchoolYear,
        InstitutionID,
        InstitutionName,
        DetailedSchoolTypeID,
        BudgetingSchoolTypeID,
        FinancialSchoolTypeID,
        PersonID,
        FirstName,
        MiddleName,
        LastName,
        ClassBookId,
        ClassOrGroupName,
        TotalUnexcusedAbsences,
        ExcusedByMedicalNoticeAbsence,
        ExcusedByHealthReasonAbsence,
        ExcusedByFamilyReasonAbsence,
        ExcusedByOtherReasonAbsence,
        TotalExcusedAbsences,
      ],
    },
    sumTotalUnexcusedAbsences: {
      type: 'sum',
      title: 'Общо неизвинени отсъствия',
      sql: 'TotalUnexcusedAbsences',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        PersonID,
        FirstName,
        LastName,
        SchoolYear,
        ClassOrGroupName,
        TotalUnexcusedAbsences,
      ],
    },
    sumExcusedByMedicalNoticeAbsence: {
      type: 'sum',
      title: 'Общо извинени отсъствия - медицинско удостоверение',
      sql: 'ExcusedByMedicalNoticeAbsence',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        PersonID,
        FirstName,
        LastName,
        SchoolYear,
        ClassOrGroupName,
        ExcusedByMedicalNoticeAbsence,
      ],
    },
    sumExcusedByHealthReasonAbsence: {
      type: 'sum',
      title: 'Общо извинени отсъствия - здравни причини',
      sql: 'ExcusedByHealthReasonAbsence',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        PersonID,
        FirstName,
        LastName,
        SchoolYear,
        ClassOrGroupName,
        ExcusedByHealthReasonAbsence,
      ],
    },
    sumExcusedByFamilyReasonAbsence: {
      type: 'sum',
      title: 'Общо извинени отсъствия - семейни причини',
      sql: 'ExcusedByFamilyReasonAbsence',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        PersonID,
        FirstName,
        LastName,
        SchoolYear,
        ClassOrGroupName,
        ExcusedByFamilyReasonAbsence,
      ],
    },
    sumExcusedByOtherReasonAbsence: {
      type: 'sum',
      title: 'Общо извинени отсъствия - други причини',
      sql: 'ExcusedByOtherReasonAbsence',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        PersonID,
        FirstName,
        LastName,
        SchoolYear,
        ClassOrGroupName,
        ExcusedByOtherReasonAbsence,
      ],
    },
    sumTotalExcusedAbsences: {
      type: 'sum',
      title: 'Общо извинени отсъствия',
      sql: 'TotalExcusedAbsences',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        PersonID,
        FirstName,
        LastName,
        SchoolYear,
        ClassOrGroupName,
        TotalExcusedAbsences,
      ],
    },
  },

  dimensions: {
    RegionID: {
      sql: 'RegionID',
      type: 'number',
      title: 'Код на област',
      shown: false,
    },
    RegionName: {
      sql: 'RegionName',
      type: 'string',
      title: 'Област',
    },
    MunicipalityName: {
      sql: 'MunicipalityName',
      type: 'string',
      title: 'Община',
    },
    TownName: {
      sql: 'TownName',
      type: 'string',
      title: 'Населено място',
    },
    SchoolYear: {
      sql: 'SchoolYear',
      type: 'number',
      title: 'Учебна година',
    },
    InstitutionID: {
      sql: 'InstitutionID',
      type: 'number',
      title: 'Код по НЕИСПУО',
    },
    InstitutionName: {
      sql: 'InstitutionName',
      type: 'string',
      title: 'Име на институция',
    },
    DetailedSchoolTypeID: {
      sql: 'DetailedSchoolTypeID',
      type: 'number',
      title: 'Вид по чл. 38 (детайлен)',
      shown: false,
    },
    BudgetingSchoolTypeID: {
      sql: 'BudgetingSchoolTypeID',
      type: 'number',
      title: 'Вид по чл. 35-36 (според собствеността)',
      shown: false,
    },
    FinancialSchoolTypeID: {
      sql: 'FinancialSchoolTypeID',
      type: 'number',
      title: 'Финансиращ орган',
      shown: false,
    },
    PersonID: {
      sql: 'PersonID',
      type: 'number',
      title: 'Идентификатор на ученика',
      shown: false,
    },
    FirstName: {
      sql: 'FirstName',
      type: 'string',
      title: 'Име',
    },
    MiddleName: {
      sql: 'MiddleName',
      type: 'string',
      title: 'Презиме',
    },
    LastName: {
      sql: 'LastName',
      type: 'string',
      title: 'Фамилия',
    },
    ClassBookId: {
      sql: 'ClassBookId',
      type: 'number',
      title: 'Код на клас',
      shown: false,
    },
    ClassOrGroupName: {
      sql: 'ClassOrGroupName',
      type: 'string',
      title: 'Клас/група',
    },
    TotalUnexcusedAbsences: {
      sql: 'TotalUnexcusedAbsences',
      type: 'number',
      title: 'Общо неизвинени отсъствия',
    },
    ExcusedByMedicalNoticeAbsence: {
      sql: 'ExcusedByMedicalNoticeAbsence',
      type: 'number',
      title: 'Извинени отсъствия - медицинско удостоверение',
    },
    ExcusedByHealthReasonAbsence: {
      sql: 'ExcusedByHealthReasonAbsence',
      type: 'number',
      title: 'Извинени отсъствия - здравни причини',
    },
    ExcusedByFamilyReasonAbsence: {
      sql: 'ExcusedByFamilyReasonAbsence',
      type: 'number',
      title: 'Извинени отсъствия - семейни причини',
    },
    ExcusedByOtherReasonAbsence: {
      sql: 'ExcusedByOtherReasonAbsence',
      type: 'number',
      title: 'Извинени отсъствия - други причини',
    },
    TotalExcusedAbsences: {
      sql: 'TotalExcusedAbsences',
      type: 'number',
      title: 'Общо извинени отсъствия',
    },
  },

  dataSource: 'default',
});


