/* eslint no-undef: "off" */

cube('RStudents', {
  sql: 'SELECT * FROM R_Students',
  title: 'Брой ученици по групи / паралелки',
  description:
    'Служи за извършване на справки свързани с данни по Брой ученици по групи / паралелки.',

  // preAggregations: {
  //   orderByRegion: {
  //     type: 'rollup',
  //     dimensions: [
  //       RStudents.RegionID,
  //       RStudents.InstitutionID,
  //       RStudents.InstitutionDepartmentID,
  //       RStudents.MunicipalityID,
  //     ],
  //     measures: [
  //       RStudents.countInstitutionID,
  //       RStudents.sumStudentsCount,
  //       RStudents.sumStudentCSOPCount,
  //       RStudents.sumRepeaterCount,
  //       RStudents.sumCommuterCount,
  //     ],
  //     indexes: {
  //       r_students_index: {
  //         columns: [
  //           RStudents.RegionID,
  //           RStudents.InstitutionID,
  //           RStudents.InstitutionDepartmentID,
  //           RStudents.MunicipalityID,
  //         ],
  //       },
  //     },
  //   },
  // },

  joins: {},

  measures: {
    countInstitutionID: {
      type: 'count',
      title: 'Брой "Институции"',
      drillMembers: [
        InstitutionID,
        InstitutionName,
        InstitutionAbbreviation,
        InstitutionDepartmentName,
        RegionID,
        RegionName,
        MunicipalityID,
        MunicipalityName,
        TownID,
        TownName,
        LAreaName,
        BasicSchoolTypeName,
        DetailedSchoolTypeName,
        FinancialSchoolTypeName,
        BudgetingSchoolTypeID,
        IsInnovative,
        IsCentral,
        IsProtected,
        IsStateFunded,
        HasMunDecisionFor4,
        ParentClassID,
        ClassId,
        RomeClassName,
        ClassName,
        EduFormName,
        SpecialtyName,
        ClassKind,
        ClassType,
        IsCSOP,
        IsCDO,
        IsCombined,
        IsNotPresentForm,
        IsHourlyOrganization,
        StudentsCount,
        StudentCSOPCount,
        RepeaterCount,
        CommuterCount,
      ],
    },
    countClassID: {
      type: 'count',
      title: 'Брой "Паралелки"',
      drillMembers: [
        InstitutionID,
        InstitutionName,
        InstitutionAbbreviation,
        InstitutionDepartmentName,
        RegionID,
        RegionName,
        MunicipalityID,
        MunicipalityName,
        TownID,
        TownName,
        LAreaName,
        BasicSchoolTypeName,
        DetailedSchoolTypeName,
        FinancialSchoolTypeName,
        BudgetingSchoolTypeID,
        IsInnovative,
        IsCentral,
        IsProtected,
        IsStateFunded,
        HasMunDecisionFor4,
        ParentClassID,
        ClassId,
        RomeClassName,
        ClassName,
        EduFormName,
        SpecialtyName,
        ClassKind,
        ClassType,
        IsCSOP,
        IsCDO,
        IsCombined,
        IsNotPresentForm,
        IsHourlyOrganization,
        StudentsCount,
        StudentCSOPCount,
        RepeaterCount,
        CommuterCount,
      ],
    },
    sumStudentsCount: {
      type: 'sum',
      title: 'Сумирай по "Брой ученици"',
      sql: 'StudentsCount',
      drillMembers: [
        InstitutionID,
        InstitutionName,
        InstitutionAbbreviation,
        InstitutionDepartmentName,
        RegionID,
        RegionName,
        MunicipalityID,
        MunicipalityName,
        TownID,
        TownName,
        LAreaName,
        BasicSchoolTypeName,
        DetailedSchoolTypeName,
        FinancialSchoolTypeName,
        BudgetingSchoolTypeID,
        IsInnovative,
        IsCentral,
        IsProtected,
        IsStateFunded,
        HasMunDecisionFor4,
        ParentClassID,
        ClassId,
        RomeClassName,
        ClassName,
        EduFormName,
        SpecialtyName,
        ClassKind,
        ClassType,
        IsCSOP,
        IsCDO,
        IsCombined,
        IsNotPresentForm,
        IsHourlyOrganization,
        StudentsCount,
        StudentCSOPCount,
        RepeaterCount,
        CommuterCount,
      ],
    },
    sumStudentCSOPCount: {
      type: 'sum',
      title: 'Сумирай по "Брой ученици - ЦСОП"',
      sql: 'StudentCSOPCount',
      drillMembers: [
        InstitutionID,
        InstitutionName,
        InstitutionAbbreviation,
        InstitutionDepartmentName,
        RegionID,
        RegionName,
        MunicipalityID,
        MunicipalityName,
        TownID,
        TownName,
        LAreaName,
        BasicSchoolTypeName,
        DetailedSchoolTypeName,
        FinancialSchoolTypeName,
        BudgetingSchoolTypeID,
        IsInnovative,
        IsCentral,
        IsProtected,
        IsStateFunded,
        HasMunDecisionFor4,
        ParentClassID,
        ClassId,
        RomeClassName,
        ClassName,
        EduFormName,
        SpecialtyName,
        ClassKind,
        ClassType,
        IsCSOP,
        IsCDO,
        IsCombined,
        IsNotPresentForm,
        IsHourlyOrganization,
        StudentsCount,
        StudentCSOPCount,
        RepeaterCount,
        CommuterCount,
      ],
    },
    sumRepeaterCount: {
      type: 'sum',
      title: 'Сумирай по "Брой ученици - второгодници"',
      sql: 'RepeaterCount',
      drillMembers: [
        InstitutionID,
        InstitutionName,
        InstitutionAbbreviation,
        InstitutionDepartmentName,
        RegionID,
        RegionName,
        MunicipalityID,
        MunicipalityName,
        TownID,
        TownName,
        LAreaName,
        BasicSchoolTypeName,
        DetailedSchoolTypeName,
        FinancialSchoolTypeName,
        BudgetingSchoolTypeID,
        IsInnovative,
        IsCentral,
        IsProtected,
        IsStateFunded,
        HasMunDecisionFor4,
        ParentClassID,
        ClassId,
        RomeClassName,
        ClassName,
        EduFormName,
        SpecialtyName,
        ClassKind,
        ClassType,
        IsCSOP,
        IsCDO,
        IsCombined,
        IsNotPresentForm,
        IsHourlyOrganization,
        StudentsCount,
        StudentCSOPCount,
        RepeaterCount,
        CommuterCount,
      ],
    },
    sumCommuterCount: {
      type: 'sum',
      title: 'Сумирай по "Брой ученици - пътуващи"',
      sql: 'CommuterCount',
      drillMembers: [
        InstitutionID,
        InstitutionName,
        InstitutionAbbreviation,
        InstitutionDepartmentName,
        RegionID,
        RegionName,
        MunicipalityID,
        MunicipalityName,
        TownID,
        TownName,
        LAreaName,
        BasicSchoolTypeName,
        DetailedSchoolTypeName,
        FinancialSchoolTypeName,
        BudgetingSchoolTypeID,
        IsInnovative,
        IsCentral,
        IsProtected,
        IsStateFunded,
        HasMunDecisionFor4,
        ParentClassID,
        ClassId,
        RomeClassName,
        ClassName,
        EduFormName,
        SpecialtyName,
        ClassKind,
        ClassType,
        IsCSOP,
        IsCDO,
        IsCombined,
        IsNotPresentForm,
        IsHourlyOrganization,
        StudentsCount,
        StudentCSOPCount,
        RepeaterCount,
        CommuterCount,
      ],
    },
  },

  dimensions: {
    InstitutionID: {
      sql: 'InstitutionID',
      type: 'number',
      title: 'Код по НЕИСПУО',
    },
    InstitutionName: {
      sql: 'InstitutionName',
      type: 'string',
      title: 'Име на институция',
    },
    InstitutionAbbreviation: {
      sql: 'InstitutionAbbreviation',
      type: 'string',
      title: 'Кратко наименование на институция',
    },
    InstitutionDepartmentID: {
      sql: 'InstitutionDepartmentID',
      type: 'number',
      title: 'Код филиал',
      shown: false,
    },
    InstitutionDepartmentName: {
      sql: 'InstitutionDepartmentName',
      type: 'string',
      title: 'Филиал',
    },
    RegionID: {
      sql: 'RegionID',
      type: 'number',
      title: 'Код област',
      shown: false,
    },
    RegionName: {
      sql: 'RegionName',
      type: 'string',
      title: 'Област',
    },
    MunicipalityID: {
      sql: 'MunicipalityID',
      type: 'number',
      title: 'Код община',
      shown: false,
    },
    MunicipalityName: {
      sql: 'MunicipalityName',
      type: 'string',
      title: 'Община',
    },
    TownID: {
      sql: 'TownID',
      type: 'number',
      title: 'Код населено място',
      shown: false,
    },
    TownName: {
      sql: 'TownName',
      type: 'string',
      title: 'Населено място',
    },
    LocalAreaID: {
      sql: 'LocalAreaID',
      type: 'number',
      title: 'Код по район',
      shown: false,
    },
    LAreaName: {
      sql: 'LAreaName',
      type: 'string',
      title: 'Район',
    },
    BasicSchoolTypeName: {
      sql: 'BasicSchoolTypeName',
      type: 'string',
      title: 'по чл. 37',
    },
    DetailedSchoolTypeName: {
      sql: 'DetailedSchoolTypeName',
      type: 'string',
      title: 'по чл. 38',
    },
    FinancialSchoolTypeName: {
      sql: 'FinancialSchoolTypeName',
      type: 'string',
      title: 'Финансиране',
    },
    IsInnovative: {
      sql: 'IsInnovative',
      type: 'string',
      title: 'Иновативно',
    },
    IsCentral: {
      sql: 'IsCentral',
      type: 'string',
      title: 'Средищно',
    },
    IsProtected: {
      sql: 'IsProtected',
      type: 'string',
      title: 'Защитено',
    },
    IsStateFunded: {
      sql: 'IsStateFunded',
      type: 'string',
      title: 'С национално значение',
    },
    HasMunDecisionFor4: {
      sql: 'HasMunDecisionFor4',
      type: 'string',
      title: 'Решение за задължително обучение на 4 годишните',
    },
    BudgetingSchoolTypeID: {
      sql: 'BudgetingSchoolTypeID',
      type: 'number',
      title: 'Код финансираща институция',
      shown: false,
    },
    ParentClassID: {
      sql: 'ParentClassID',
      type: 'number',
      title: 'Код на класа',
      shown: false,
    },
    ClassId: {
      sql: 'ClassId',
      type: 'number',
      title: 'Код на група',
      shown: false,
    },
    RomeClassName: {
      sql: 'RomeClassName',
      type: 'string',
      title: 'Випуск',
    },
    ClassName: {
      sql: 'ClassName',
      type: 'string',
      title: 'Паралелка/Група',
    },
    EduFormName: {
      sql: 'EduFormName',
      type: 'string',
      title: 'Форма на обучение',
    },
    ClassKind: {
      sql: 'ClassKind',
      type: 'string',
      title: 'Категория',
    },
    ClassType: {
      sql: 'ClassType',
      type: 'string',
      title: 'Профил/вид на паралелка/група',
    },
    SpecialtyName: {
      sql: 'SpecialtyName',
      type: 'string',
      title: 'Специалност',
    },
    StudentsCount: {
      sql: 'StudentsCount',
      type: 'number',
      title: 'Общ брой ученици',
    },
    StudentCSOPCount: {
      sql: 'StudentCSOPCount',
      type: 'number',
      title: 'Брой ученици, обучаващи се в ЦСОП',
    },
    StudentSOPCount: {
      sql: 'StudentSOPCount',
      type: 'number',
      title: 'Брой ученици със СОП',
    },
    CountMale: {
      sql: 'CountMale',
      type: 'number',
      title: 'Брой момчета',
    },
    CountFemale: {
      sql: 'CountFemale',
      type: 'number',
      title: 'Брой момичета',
    },
    RepeaterCount: {
      sql: 'RepeaterCount',
      type: 'number',
      title: 'Брой ученици - второгодници',
    },
    CommuterCount: {
      sql: 'CommuterCount',
      type: 'number',
      title: 'Брой ученици - пътуващи',
    },
    IsCSOP: {
      sql: 'IsCSOP',
      type: 'string',
      title: 'Паралелка/група за деца със СОП',
    },
    IsCDO: {
      sql: 'IsCDO',
      type: 'string',
      title: 'ЦДО',
    },
    IsCombined: {
      sql: 'IsCombined',
      type: 'string',
      title: 'Слята паралелка',
    },
    IsNotPresentForm: {
      sql: 'IsNotPresentForm',
      type: 'string',
      title: 'СФО',
    },
    IsHourlyOrganization: {
      sql: 'IsHourlyOrganization',
      type: 'string',
      title: 'Брой деца на почасова организация ',
    },
    SchoolYear: {
      sql: 'SchoolYear',
      type: 'number',
      title: 'Учебна година',
      shown: false,
    },
  },

  dataSource: 'default',
});
