/* eslint no-undef: "off" */

cube('RTwentyFivePercentageAbsences', {
  sql: 'SELECT * FROM R_Twenty_Five_Percentage_Absences',
  title: 'Справка за учениците с 25% отсъствия',
  description:
    'Ученици, достигнали или превишили 25% отсъствия по предмети (с проценти по I/II срок и учебна година).',

  // preAggregations: {
  //   orderByRegion: {
  //     type: 'rollup',
  //     dimensions: [
  //       RTwentyFivePercentageAbsences.RegionID,
  //       RTwentyFivePercentageAbsences.SchoolYear,
  //       RTwentyFivePercentageAbsences.InstitutionID,
  //       RTwentyFivePercentageAbsences.PersonID,
  //     ],
  //     measures: [
  //       RTwentyFivePercentageAbsences.countPersonID,
  //       RTwentyFivePercentageAbsences.sumAbsencesTerm1,
  //       RTwentyFivePercentageAbsences.sumAbsencesTerm2,
  //       RTwentyFivePercentageAbsences.sumTotalAbsences,
  //       RTwentyFivePercentageAbsences.avgAbsencePercentTerm1,
  //       RTwentyFivePercentageAbsences.avgAbsencePercentTerm2,
  //       RTwentyFivePercentageAbsences.avgTotalPercentWholeYear,
  //     ],
  //     indexes: {
  //       r_twenty_five_percentage_absences_index: {
  //         columns: [
  //           RTwentyFivePercentageAbsences.RegionID,
  //           RTwentyFivePercentageAbsences.SchoolYear,
  //           RTwentyFivePercentageAbsences.InstitutionID,
  //           RTwentyFivePercentageAbsences.PersonID,
  //         ],
  //       },
  //     },
  //   },
  // },

  joins: {},

  measures: {
    countPersonID: {
      type: 'count',
      title: 'Брой ученици с 25%+ отсъствия',
      sql: 'PersonID',
      drillMembers: [
        RegionID,
        RegionName,
        MunicipalityName,
        TownName,
        InstitutionID,
        InstitutionName,
        DetailedSchoolTypeID,
        BudgetingSchoolTypeID,
        FinancialSchoolTypeID,
        PersonID,
        FirstName,
        MiddleName,
        LastName,
        PublicEduNumber,
        BirthDate,
        Gender,
        SchoolYear,
        ClassOrGroupName,
        CurriculumId,
        CurriculumPartID,
        SubjectName,
        SubjectTypeName,
        Absences_Term1,
        TotalHours_Term1,
        AbsencePercent_Term1,
        Absences_Term2,
        TotalHours_Term2,
        AbsencePercent_Term2,
        TotalAbsences,
        TotalHours_WholeYear,
        TotalPercent_WholeYear,
      ],
    },
    sumAbsencesTerm1: {
      type: 'sum',
      title: 'Общо отсъствия - I срок',
      sql: 'Absences_Term1',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        PersonID,
        FirstName,
        LastName,
        SchoolYear,
        SubjectName,
        SubjectTypeName,
        Absences_Term1,
        TotalHours_Term1,
        AbsencePercent_Term1,
      ],
    },
    sumAbsencesTerm2: {
      type: 'sum',
      title: 'Общо отсъствия - II срок',
      sql: 'Absences_Term2',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        PersonID,
        FirstName,
        LastName,
        SchoolYear,
        SubjectName,
        SubjectTypeName,
        Absences_Term2,
        TotalHours_Term2,
        AbsencePercent_Term2,
      ],
    },
    sumTotalAbsences: {
      type: 'sum',
      title: 'Общо отсъствия за учебната година',
      sql: 'TotalAbsences',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        PersonID,
        FirstName,
        LastName,
        SchoolYear,
        SubjectName,
        SubjectTypeName,
        TotalAbsences,
        TotalHours_WholeYear,
        TotalPercent_WholeYear,
      ],
    },
    avgAbsencePercentTerm1: {
      type: 'avg',
      title: 'Среден процент отсъствия - I срок',
      sql: 'AbsencePercent_Term1',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        PersonID,
        FirstName,
        LastName,
        SchoolYear,
        SubjectName,
        SubjectTypeName,
        AbsencePercent_Term1,
      ],
    },
    avgAbsencePercentTerm2: {
      type: 'avg',
      title: 'Среден процент отсъствия - II срок',
      sql: 'AbsencePercent_Term2',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        PersonID,
        FirstName,
        LastName,
        SchoolYear,
        SubjectName,
        SubjectTypeName,
        AbsencePercent_Term2,
      ],
    },
    avgTotalPercentWholeYear: {
      type: 'avg',
      title: 'Среден процент отсъствия за учебната година',
      sql: 'TotalPercent_WholeYear',
      drillMembers: [
        RegionID,
        RegionName,
        InstitutionID,
        InstitutionName,
        PersonID,
        FirstName,
        LastName,
        SchoolYear,
        SubjectName,
        SubjectTypeName,
        TotalPercent_WholeYear,
      ],
    },
  },

  dimensions: {
    RegionID: {
      sql: 'RegionID',
      type: 'number',
      title: 'Код на област',
      shown: false,
    },
    RegionName: {
      sql: 'RegionName',
      type: 'string',
      title: 'Област',
    },
    MunicipalityName: {
      sql: 'MunicipalityName',
      type: 'string',
      title: 'Община',
    },
    TownName: {
      sql: 'TownName',
      type: 'string',
      title: 'Населено място',
    },
    InstitutionID: {
      sql: 'InstitutionID',
      type: 'number',
      title: 'Код по НЕИСПУО',
    },
    InstitutionName: {
      sql: 'InstitutionName',
      type: 'string',
      title: 'Име на институция',
    },
    DetailedSchoolTypeID: {
      sql: 'DetailedSchoolTypeID',
      type: 'number',
      title: 'Вид по чл. 38 (детайлен)',
      shown: false,
    },
    BudgetingSchoolTypeID: {
      sql: 'BudgetingSchoolTypeID',
      type: 'number',
      title: 'Вид по чл. 35-36 (според собствеността)',
      shown: false,
    },
    FinancialSchoolTypeID: {
      sql: 'FinancialSchoolTypeID',
      type: 'number',
      title: 'Финансиращ орган',
      shown: false,
    },
    PersonID: {
      sql: 'PersonID',
      type: 'number',
      title: 'Идентификатор на ученика',
      shown: false,
    },
    FirstName: {
      sql: 'FirstName',
      type: 'string',
      title: 'Име',
    },
    MiddleName: {
      sql: 'MiddleName',
      type: 'string',
      title: 'Презиме',
    },
    LastName: {
      sql: 'LastName',
      type: 'string',
      title: 'Фамилия',
    },
    PublicEduNumber: {
      sql: 'PublicEduNumber',
      type: 'string',
      title: 'ЛОН (личен образователен номер)',
    },
    BirthDate: {
      sql: 'BirthDate',
      type: 'time',
      title: 'Дата на раждане',
    },
    Gender: {
      sql: 'Gender',
      type: 'number',
      title: 'Пол',
      shown: false,
    },
    SchoolYear: {
      sql: 'SchoolYear',
      type: 'number',
      title: 'Учебна година',
    },
    ClassOrGroupName: {
      sql: 'ClassOrGroupName',
      type: 'string',
      title: 'Клас/група',
    },
    CurriculumId: {
      sql: 'CurriculumId',
      type: 'number',
      title: 'Код учебен план',
      shown: false,
    },
    CurriculumPartID: {
      sql: 'CurriculumPartID',
      type: 'number',
      title: 'Код част от учебен план',
      shown: false,
    },
    SubjectName: {
      sql: 'SubjectName',
      type: 'string',
      title: 'Предмет',
    },
    SubjectTypeName: {
      sql: 'SubjectTypeName',
      type: 'string',
      title: 'Тип предмет',
    },
    Absences_Term1: {
      sql: 'Absences_Term1',
      type: 'number',
      title: 'Отсъствия - I срок',
    },
    TotalHours_Term1: {
      sql: 'TotalHours_Term1',
      type: 'number',
      title: 'Общо часове - I срок',
    },
    AbsencePercent_Term1: {
      sql: 'AbsencePercent_Term1',
      type: 'number',
      title: 'Процент отсъствия - I срок',
    },
    Absences_Term2: {
      sql: 'Absences_Term2',
      type: 'number',
      title: 'Отсъствия - II срок',
    },
    TotalHours_Term2: {
      sql: 'TotalHours_Term2',
      type: 'number',
      title: 'Общо часове - II срок',
    },
    AbsencePercent_Term2: {
      sql: 'AbsencePercent_Term2',
      type: 'number',
      title: 'Процент отсъствия - II срок',
    },
    TotalAbsences: {
      sql: 'TotalAbsences',
      type: 'number',
      title: 'Общо отсъствия за учебната година',
    },
    TotalHours_WholeYear: {
      sql: 'TotalHours_WholeYear',
      type: 'number',
      title: 'Общо часове за учебната година',
    },
    TotalPercent_WholeYear: {
      sql: 'TotalPercent_WholeYear',
      type: 'number',
      title: 'Общ процент отсъствия за учебната година',
    },
  },

  dataSource: 'default',
});
