-- Migration: Create R_Students table
-- Based on reporting.R_Students view from the MS SQL server
CREATE TABLE IF NOT EXISTS R_Students (
    ParentClassID Int32,
    ClassId Int32,
    InstitutionID Int32,
    InstitutionName String,
    InstitutionAbbreviation String,
    RegionID Int32,
    RegionName String,
    MunicipalityID Int32,
    MunicipalityName String,
    TownID Int32,
    TownName String,
    LocalAreaID Int32,
    LAreaName String,
    InstitutionDepartmentID Int32,
    InstitutionDepartmentName String,
    InstType Int32,
    BasicSchoolTypeName String,
    DetailedSchoolTypeName String,
    FinancialSchoolTypeName String,
    BudgetingSchoolTypeID Int32,
    IsInnovative String,
    IsCentral String,
    IsProtected String,
    IsStateFunded String,
    HasMunDecisionFor4 String,
    RomeClassName String,
    ClassName String,
    EduFormName String,
    ClassKind String,
    ClassType String,
    ProfName String,
    SpecialtyName String,
    PositionId Int32,
    StudentsCount Int32,
    StudentCSOPCount Int32,
    StudentSOPCount Int32,
    CountMale Int32,
    CountFemale Int32,
    RepeaterCount Int32,
    CommuterCount Int32,
    IsCSOP String,
    IsCDO String,
    IsCombined String,
    IsNotPresentForm String,
    IsHourlyOrganization Int32,
    SchoolYear Int32
) ENGINE = MergeTree()
ORDER BY (RegionID, MunicipalityID, InstitutionID, ClassId, ParentClassID)