-- Migration: Create R_Institutions table
-- Based on inst_basic.R_institutions view from the MS SQL server
CREATE TABLE IF NOT EXISTS R_Institutions (
    InstitutionID Int32,
    InstitutionName String,
    ShortInstitutionName String,
    Bulstat String,
    CountryName String,
    RegionID Int32,
    RegionName String,
    MunicipalityID Int32,
    MunicipalityName String,
    TownID Int32,
    TownName String,
    LocalAreaID Int32,
    LocalAreaName String,
    BaseSchoolTypeName String,
    DetailedSchoolTypeName String,
    FinancialSchoolTypeName String,
    BudgetingSchoolTypeID Int32,
    BudgetingInstitutionName String,
    IsDelegateBudget String,
    YearlyBudget Decimal(18, 2),
    Address String,
    PhoneNumber String,
    Email String,
    Website String,
    EstablishedYear String,
    ConstitActFirst String,
    ConstitActLast String,
    SchoolShiftType String,
    IsCentral String,
    IsProtected String,
    IsInnovative String,
    IsNational String,
    IsProfSchool String,
    IsNonIndDormitory String,
    HasMunDecisionFor4 String,
    IsAppInnovSystem String,
    IsODZ String,
    IsProvideEduServ String,
    Director String,
    InstitutionPublicCouncil String,
    StaffCountAll Float32,
    PedagogStaffCount Float32,
    NonpedagogStaffCount Float32
) ENGINE = MergeTree()
ORDER BY (RegionID, MunicipalityID, InstitutionID); 