/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec, dateToLocalIsoString, dateTimeToLocalIsoString, urlWithParams } from '../encoder';
import { Observable }                                        from 'rxjs';
import { map }                                               from 'rxjs/operators';

import { AttendancesGetAllForDateVO, AttendancesGetAllForDateVOFromJSON, AttendancesGetAllForDateVOToJSON } from '../model/attendancesGetAllForDateVO';
import { AttendancesGetAllForMonthVO, AttendancesGetAllForMonthVOFromJSON, AttendancesGetAllForMonthVOToJSON } from '../model/attendancesGetAllForMonthVO';
import { AttendancesGetVO, AttendancesGetVOFromJSON, AttendancesGetVOToJSON } from '../model/attendancesGetVO';
import { CreateAttendancesCommand, CreateAttendancesCommandFromJSON, CreateAttendancesCommandToJSON } from '../model/createAttendancesCommand';
import { ExcuseAttendanceCommand, ExcuseAttendanceCommandFromJSON, ExcuseAttendanceCommandToJSON } from '../model/excuseAttendanceCommand';
import { RemoveAttendancesCommand, RemoveAttendancesCommandFromJSON, RemoveAttendancesCommandToJSON } from '../model/removeAttendancesCommand';
import { ValidationErrorResponse, ValidationErrorResponseFromJSON, ValidationErrorResponseToJSON } from '../model/validationErrorResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

export type Attendances_CreateAttendances = any;
export type Attendances_ExcuseAttendance = any;
export type Attendances_Get = AttendancesGetVO;
export type Attendances_GetAllForDate = Array<AttendancesGetAllForDateVO>;
export type Attendances_GetAllForMonth = Array<AttendancesGetAllForMonthVO>;
export type Attendances_RemoveAttendance = any;
export type Attendances_RemoveAttendances = any;


export interface Attendances_CreateAttendancesRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    date: Date;
    createAttendancesCommand: CreateAttendancesCommand;
}

export interface Attendances_ExcuseAttendanceRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    excuseAttendanceCommand: ExcuseAttendanceCommand;
}

export interface Attendances_GetRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    attendanceId: number;
}

export interface Attendances_GetAllForDateRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    date: Date;
}

export interface Attendances_GetAllForMonthRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    year: number;
    month: number;
}

export interface Attendances_RemoveAttendanceRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    attendanceId: number;
}

export interface Attendances_RemoveAttendancesRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    removeAttendancesCommand: RemoveAttendancesCommand;
}


@Injectable({
  providedIn: 'root'
})
export class AttendancesService {

    protected basePath = 'http://host.docker.internal:5001';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach((elem, index) => httpParams = this.addToHttpParamsRecursive(httpParams, elem, `${key}[${index}]`));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, dateToLocalIsoString(value as Date));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public createAttendances(requestParameters: Attendances_CreateAttendancesRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Attendances_CreateAttendances> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling createAttendances.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling createAttendances.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling createAttendances.');
        }
        let date = requestParameters.date;
        if (date === null || date === undefined) {
            throw new Error('Required parameter date was null or undefined when calling createAttendances.');
        }
        let createAttendancesCommand = requestParameters.createAttendancesCommand;
        if (createAttendancesCommand === null || createAttendancesCommand === undefined) {
            throw new Error('Required parameter createAttendancesCommand was null or undefined when calling createAttendances.');
        }

        createAttendancesCommand = CreateAttendancesCommandToJSON(createAttendancesCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<Attendances_CreateAttendances>(`${this.configuration.basePath}/api/attendances/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/createattendances/${encodeURIComponent(String(date.toISOString()))}`,
            createAttendancesCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public excuseAttendance(requestParameters: Attendances_ExcuseAttendanceRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Attendances_ExcuseAttendance> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling excuseAttendance.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling excuseAttendance.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling excuseAttendance.');
        }
        let excuseAttendanceCommand = requestParameters.excuseAttendanceCommand;
        if (excuseAttendanceCommand === null || excuseAttendanceCommand === undefined) {
            throw new Error('Required parameter excuseAttendanceCommand was null or undefined when calling excuseAttendance.');
        }

        excuseAttendanceCommand = ExcuseAttendanceCommandToJSON(excuseAttendanceCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<Attendances_ExcuseAttendance>(`${this.configuration.basePath}/api/attendances/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/excuseattendance`,
            excuseAttendanceCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public get(requestParameters: Attendances_GetRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Attendances_Get> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling get.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling get.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling get.');
        }
        let attendanceId = requestParameters.attendanceId;
        if (attendanceId === null || attendanceId === undefined) {
            throw new Error('Required parameter attendanceId was null or undefined when calling get.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<Attendances_Get>(`${this.configuration.basePath}/api/attendances/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/get/${encodeURIComponent(String(attendanceId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => AttendancesGetVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getAllForDate(requestParameters: Attendances_GetAllForDateRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Attendances_GetAllForDate> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getAllForDate.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getAllForDate.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling getAllForDate.');
        }
        let date = requestParameters.date;
        if (date === null || date === undefined) {
            throw new Error('Required parameter date was null or undefined when calling getAllForDate.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (date != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>date, 'date');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<Attendances_GetAllForDate>(`${this.configuration.basePath}/api/attendances/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/getallfordate`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => jsonValue.map(AttendancesGetAllForDateVOFromJSON))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getAllForMonth(requestParameters: Attendances_GetAllForMonthRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Attendances_GetAllForMonth> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getAllForMonth.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getAllForMonth.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling getAllForMonth.');
        }
        let year = requestParameters.year;
        if (year === null || year === undefined) {
            throw new Error('Required parameter year was null or undefined when calling getAllForMonth.');
        }
        let month = requestParameters.month;
        if (month === null || month === undefined) {
            throw new Error('Required parameter month was null or undefined when calling getAllForMonth.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (year != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>year, 'year');
        }
        if (month != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>month, 'month');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<Attendances_GetAllForMonth>(`${this.configuration.basePath}/api/attendances/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/getallformonth`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => jsonValue.map(AttendancesGetAllForMonthVOFromJSON))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public removeAttendance(requestParameters: Attendances_RemoveAttendanceRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Attendances_RemoveAttendance> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling removeAttendance.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling removeAttendance.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling removeAttendance.');
        }
        let attendanceId = requestParameters.attendanceId;
        if (attendanceId === null || attendanceId === undefined) {
            throw new Error('Required parameter attendanceId was null or undefined when calling removeAttendance.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.delete<Attendances_RemoveAttendance>(`${this.configuration.basePath}/api/attendances/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/removeattendance/${encodeURIComponent(String(attendanceId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public removeAttendances(requestParameters: Attendances_RemoveAttendancesRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Attendances_RemoveAttendances> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling removeAttendances.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling removeAttendances.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling removeAttendances.');
        }
        let removeAttendancesCommand = requestParameters.removeAttendancesCommand;
        if (removeAttendancesCommand === null || removeAttendancesCommand === undefined) {
            throw new Error('Required parameter removeAttendancesCommand was null or undefined when calling removeAttendances.');
        }

        removeAttendancesCommand = RemoveAttendancesCommandToJSON(removeAttendancesCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<Attendances_RemoveAttendances>(`${this.configuration.basePath}/api/attendances/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/removeattendances`,
            removeAttendancesCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

}
