/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec, dateToLocalIsoString, dateTimeToLocalIsoString, urlWithParams } from '../encoder';
import { Observable }                                        from 'rxjs';
import { map }                                               from 'rxjs/operators';

import { ClassBookTopicPlanItemsGetVO, ClassBookTopicPlanItemsGetVOFromJSON, ClassBookTopicPlanItemsGetVOToJSON } from '../model/classBookTopicPlanItemsGetVO';
import { CreateClassBookTopicPlanItemCommand, CreateClassBookTopicPlanItemCommandFromJSON, CreateClassBookTopicPlanItemCommandToJSON } from '../model/createClassBookTopicPlanItemCommand';
import { TableResultVOOfClassBookTopicPlanItemsGetAllVO, TableResultVOOfClassBookTopicPlanItemsGetAllVOFromJSON, TableResultVOOfClassBookTopicPlanItemsGetAllVOToJSON } from '../model/tableResultVOOfClassBookTopicPlanItemsGetAllVO';
import { UpdateClassBookTopicPlanItemCommand, UpdateClassBookTopicPlanItemCommandFromJSON, UpdateClassBookTopicPlanItemCommandToJSON } from '../model/updateClassBookTopicPlanItemCommand';
import { UpdateTakenClassBookTopicPlanItemCommand, UpdateTakenClassBookTopicPlanItemCommandFromJSON, UpdateTakenClassBookTopicPlanItemCommandToJSON } from '../model/updateTakenClassBookTopicPlanItemCommand';
import { ValidationErrorResponse, ValidationErrorResponseFromJSON, ValidationErrorResponseToJSON } from '../model/validationErrorResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

export type ClassBookTopicPlanItems_Create = any;
export type ClassBookTopicPlanItems_DownloadExcelFile = Blob;
export type ClassBookTopicPlanItems_Get = ClassBookTopicPlanItemsGetVO;
export type ClassBookTopicPlanItems_GetAll = TableResultVOOfClassBookTopicPlanItemsGetAllVO;
export type ClassBookTopicPlanItems_ImportFromExcelFile = any;
export type ClassBookTopicPlanItems_LoadFromTopicPlan = any;
export type ClassBookTopicPlanItems_Remove = any;
export type ClassBookTopicPlanItems_RemoveAll = any;
export type ClassBookTopicPlanItems_Update = any;
export type ClassBookTopicPlanItems_UpdateTaken = any;


export interface ClassBookTopicPlanItems_CreateRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    curriculumId: number;
    createClassBookTopicPlanItemCommand: CreateClassBookTopicPlanItemCommand;
}

export interface ClassBookTopicPlanItems_DownloadExcelFileRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    curriculumId: number;
}

export interface ClassBookTopicPlanItems_GetRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    classBookTopicPlanItemId: number;
}

export interface ClassBookTopicPlanItems_GetAllRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    curriculumId: number;
    offset?: number | null;
    limit?: number | null;
}

export interface ClassBookTopicPlanItems_ImportFromExcelFileRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    curriculumId: number;
    blobId: number;
}

export interface ClassBookTopicPlanItems_LoadFromTopicPlanRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    curriculumId: number;
    topicPlanId: number;
}

export interface ClassBookTopicPlanItems_RemoveRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    curriculumId: number;
    classBookTopicPlanItemId: number;
}

export interface ClassBookTopicPlanItems_RemoveAllRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    curriculumId: number;
}

export interface ClassBookTopicPlanItems_UpdateRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    curriculumId: number;
    classBookTopicPlanItemId: number;
    updateClassBookTopicPlanItemCommand: UpdateClassBookTopicPlanItemCommand;
}

export interface ClassBookTopicPlanItems_UpdateTakenRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    curriculumId: number;
    classBookTopicPlanItemId: number;
    updateTakenClassBookTopicPlanItemCommand: UpdateTakenClassBookTopicPlanItemCommand;
}


@Injectable({
  providedIn: 'root'
})
export class ClassBookTopicPlanItemsService {

    protected basePath = 'http://host.docker.internal:5001';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach((elem, index) => httpParams = this.addToHttpParamsRecursive(httpParams, elem, `${key}[${index}]`));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, dateToLocalIsoString(value as Date));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public create(requestParameters: ClassBookTopicPlanItems_CreateRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ClassBookTopicPlanItems_Create> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling create.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling create.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling create.');
        }
        let curriculumId = requestParameters.curriculumId;
        if (curriculumId === null || curriculumId === undefined) {
            throw new Error('Required parameter curriculumId was null or undefined when calling create.');
        }
        let createClassBookTopicPlanItemCommand = requestParameters.createClassBookTopicPlanItemCommand;
        if (createClassBookTopicPlanItemCommand === null || createClassBookTopicPlanItemCommand === undefined) {
            throw new Error('Required parameter createClassBookTopicPlanItemCommand was null or undefined when calling create.');
        }

        createClassBookTopicPlanItemCommand = CreateClassBookTopicPlanItemCommandToJSON(createClassBookTopicPlanItemCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<ClassBookTopicPlanItems_Create>(`${this.configuration.basePath}/api/classbooktopicplanitems/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/create/${encodeURIComponent(String(curriculumId))}`,
            createClassBookTopicPlanItemCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public downloadExcelFile(requestParameters: ClassBookTopicPlanItems_DownloadExcelFileRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/octet-stream'}): Observable<string> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling downloadExcelFile.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling downloadExcelFile.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling downloadExcelFile.');
        }
        let curriculumId = requestParameters.curriculumId;
        if (curriculumId === null || curriculumId === undefined) {
            throw new Error('Required parameter curriculumId was null or undefined when calling downloadExcelFile.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }



        return this.httpClient
            .post<{ url: string }>(
                `${this.configuration.basePath}/api/sign`,
                { url: urlWithParams({ url:`${this.configuration.basePath}/api/classbooktopicplanitems/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/downloadexcelfile/${encodeURIComponent(String(curriculumId))}` }) },
                {
                    withCredentials: this.configuration.withCredentials,
                    headers: headers
                }
            )
            .pipe(map(({ url }) => url));
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public get(requestParameters: ClassBookTopicPlanItems_GetRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ClassBookTopicPlanItems_Get> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling get.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling get.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling get.');
        }
        let classBookTopicPlanItemId = requestParameters.classBookTopicPlanItemId;
        if (classBookTopicPlanItemId === null || classBookTopicPlanItemId === undefined) {
            throw new Error('Required parameter classBookTopicPlanItemId was null or undefined when calling get.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<ClassBookTopicPlanItems_Get>(`${this.configuration.basePath}/api/classbooktopicplanitems/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/get/${encodeURIComponent(String(classBookTopicPlanItemId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => ClassBookTopicPlanItemsGetVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getAll(requestParameters: ClassBookTopicPlanItems_GetAllRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ClassBookTopicPlanItems_GetAll> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getAll.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getAll.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling getAll.');
        }
        let curriculumId = requestParameters.curriculumId;
        if (curriculumId === null || curriculumId === undefined) {
            throw new Error('Required parameter curriculumId was null or undefined when calling getAll.');
        }
        let offset = requestParameters.offset;
        let limit = requestParameters.limit;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (curriculumId != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>curriculumId, 'curriculumId');
        }
        if (offset != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>offset, 'offset');
        }
        if (limit != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>limit, 'limit');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<ClassBookTopicPlanItems_GetAll>(`${this.configuration.basePath}/api/classbooktopicplanitems/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/getall`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => TableResultVOOfClassBookTopicPlanItemsGetAllVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public importFromExcelFile(requestParameters: ClassBookTopicPlanItems_ImportFromExcelFileRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ClassBookTopicPlanItems_ImportFromExcelFile> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling importFromExcelFile.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling importFromExcelFile.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling importFromExcelFile.');
        }
        let curriculumId = requestParameters.curriculumId;
        if (curriculumId === null || curriculumId === undefined) {
            throw new Error('Required parameter curriculumId was null or undefined when calling importFromExcelFile.');
        }
        let blobId = requestParameters.blobId;
        if (blobId === null || blobId === undefined) {
            throw new Error('Required parameter blobId was null or undefined when calling importFromExcelFile.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (curriculumId != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>curriculumId, 'curriculumId');
        }
        if (blobId != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>blobId, 'blobId');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<ClassBookTopicPlanItems_ImportFromExcelFile>(`${this.configuration.basePath}/api/classbooktopicplanitems/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/importfromexcelfile`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public loadFromTopicPlan(requestParameters: ClassBookTopicPlanItems_LoadFromTopicPlanRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ClassBookTopicPlanItems_LoadFromTopicPlan> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling loadFromTopicPlan.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling loadFromTopicPlan.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling loadFromTopicPlan.');
        }
        let curriculumId = requestParameters.curriculumId;
        if (curriculumId === null || curriculumId === undefined) {
            throw new Error('Required parameter curriculumId was null or undefined when calling loadFromTopicPlan.');
        }
        let topicPlanId = requestParameters.topicPlanId;
        if (topicPlanId === null || topicPlanId === undefined) {
            throw new Error('Required parameter topicPlanId was null or undefined when calling loadFromTopicPlan.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (topicPlanId != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>topicPlanId, 'topicPlanId');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<ClassBookTopicPlanItems_LoadFromTopicPlan>(`${this.configuration.basePath}/api/classbooktopicplanitems/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/loadfromtopicplan/${encodeURIComponent(String(curriculumId))}`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public remove(requestParameters: ClassBookTopicPlanItems_RemoveRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ClassBookTopicPlanItems_Remove> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling remove.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling remove.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling remove.');
        }
        let curriculumId = requestParameters.curriculumId;
        if (curriculumId === null || curriculumId === undefined) {
            throw new Error('Required parameter curriculumId was null or undefined when calling remove.');
        }
        let classBookTopicPlanItemId = requestParameters.classBookTopicPlanItemId;
        if (classBookTopicPlanItemId === null || classBookTopicPlanItemId === undefined) {
            throw new Error('Required parameter classBookTopicPlanItemId was null or undefined when calling remove.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.delete<ClassBookTopicPlanItems_Remove>(`${this.configuration.basePath}/api/classbooktopicplanitems/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/remove/${encodeURIComponent(String(curriculumId))}/${encodeURIComponent(String(classBookTopicPlanItemId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public removeAll(requestParameters: ClassBookTopicPlanItems_RemoveAllRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ClassBookTopicPlanItems_RemoveAll> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling removeAll.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling removeAll.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling removeAll.');
        }
        let curriculumId = requestParameters.curriculumId;
        if (curriculumId === null || curriculumId === undefined) {
            throw new Error('Required parameter curriculumId was null or undefined when calling removeAll.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.delete<ClassBookTopicPlanItems_RemoveAll>(`${this.configuration.basePath}/api/classbooktopicplanitems/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/removeall/${encodeURIComponent(String(curriculumId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public update(requestParameters: ClassBookTopicPlanItems_UpdateRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ClassBookTopicPlanItems_Update> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling update.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling update.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling update.');
        }
        let curriculumId = requestParameters.curriculumId;
        if (curriculumId === null || curriculumId === undefined) {
            throw new Error('Required parameter curriculumId was null or undefined when calling update.');
        }
        let classBookTopicPlanItemId = requestParameters.classBookTopicPlanItemId;
        if (classBookTopicPlanItemId === null || classBookTopicPlanItemId === undefined) {
            throw new Error('Required parameter classBookTopicPlanItemId was null or undefined when calling update.');
        }
        let updateClassBookTopicPlanItemCommand = requestParameters.updateClassBookTopicPlanItemCommand;
        if (updateClassBookTopicPlanItemCommand === null || updateClassBookTopicPlanItemCommand === undefined) {
            throw new Error('Required parameter updateClassBookTopicPlanItemCommand was null or undefined when calling update.');
        }

        updateClassBookTopicPlanItemCommand = UpdateClassBookTopicPlanItemCommandToJSON(updateClassBookTopicPlanItemCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<ClassBookTopicPlanItems_Update>(`${this.configuration.basePath}/api/classbooktopicplanitems/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/update/${encodeURIComponent(String(curriculumId))}/${encodeURIComponent(String(classBookTopicPlanItemId))}`,
            updateClassBookTopicPlanItemCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public updateTaken(requestParameters: ClassBookTopicPlanItems_UpdateTakenRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ClassBookTopicPlanItems_UpdateTaken> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling updateTaken.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling updateTaken.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling updateTaken.');
        }
        let curriculumId = requestParameters.curriculumId;
        if (curriculumId === null || curriculumId === undefined) {
            throw new Error('Required parameter curriculumId was null or undefined when calling updateTaken.');
        }
        let classBookTopicPlanItemId = requestParameters.classBookTopicPlanItemId;
        if (classBookTopicPlanItemId === null || classBookTopicPlanItemId === undefined) {
            throw new Error('Required parameter classBookTopicPlanItemId was null or undefined when calling updateTaken.');
        }
        let updateTakenClassBookTopicPlanItemCommand = requestParameters.updateTakenClassBookTopicPlanItemCommand;
        if (updateTakenClassBookTopicPlanItemCommand === null || updateTakenClassBookTopicPlanItemCommand === undefined) {
            throw new Error('Required parameter updateTakenClassBookTopicPlanItemCommand was null or undefined when calling updateTaken.');
        }

        updateTakenClassBookTopicPlanItemCommand = UpdateTakenClassBookTopicPlanItemCommandToJSON(updateTakenClassBookTopicPlanItemCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<ClassBookTopicPlanItems_UpdateTaken>(`${this.configuration.basePath}/api/classbooktopicplanitems/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/updatetaken/${encodeURIComponent(String(curriculumId))}/${encodeURIComponent(String(classBookTopicPlanItemId))}`,
            updateTakenClassBookTopicPlanItemCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

}
