/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec, dateToLocalIsoString, dateTimeToLocalIsoString, urlWithParams } from '../encoder';
import { Observable }                                        from 'rxjs';
import { map }                                               from 'rxjs/operators';

import { ExamsReportsGetVO, ExamsReportsGetVOFromJSON, ExamsReportsGetVOToJSON } from '../model/examsReportsGetVO';
import { TableResultVOOfExamsReportsGetAllVO, TableResultVOOfExamsReportsGetAllVOFromJSON, TableResultVOOfExamsReportsGetAllVOToJSON } from '../model/tableResultVOOfExamsReportsGetAllVO';
import { TableResultVOOfExamsReportsGetItemsVO, TableResultVOOfExamsReportsGetItemsVOFromJSON, TableResultVOOfExamsReportsGetItemsVOToJSON } from '../model/tableResultVOOfExamsReportsGetItemsVO';
import { ValidationErrorResponse, ValidationErrorResponseFromJSON, ValidationErrorResponseToJSON } from '../model/validationErrorResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

export type ExamsReports_Create = number;
export type ExamsReports_DownloadExcelFile = Blob;
export type ExamsReports_Get = ExamsReportsGetVO;
export type ExamsReports_GetAll = TableResultVOOfExamsReportsGetAllVO;
export type ExamsReports_GetItems = TableResultVOOfExamsReportsGetItemsVO;
export type ExamsReports_Remove = any;


export interface ExamsReports_CreateRequestParams {
    schoolYear: number;
    instId: number;
}

export interface ExamsReports_DownloadExcelFileRequestParams {
    schoolYear: number;
    instId: number;
    examsReportId: number;
}

export interface ExamsReports_GetRequestParams {
    schoolYear: number;
    instId: number;
    examsReportId: number;
}

export interface ExamsReports_GetAllRequestParams {
    schoolYear: number;
    instId: number;
    offset?: number | null;
    limit?: number | null;
}

export interface ExamsReports_GetItemsRequestParams {
    schoolYear: number;
    instId: number;
    examsReportId: number;
    offset?: number | null;
    limit?: number | null;
}

export interface ExamsReports_RemoveRequestParams {
    schoolYear: number;
    instId: number;
    examsReportId: number;
}


@Injectable({
  providedIn: 'root'
})
export class ExamsReportsService {

    protected basePath = 'http://host.docker.internal:5001';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach((elem, index) => httpParams = this.addToHttpParamsRecursive(httpParams, elem, `${key}[${index}]`));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, dateToLocalIsoString(value as Date));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public create(requestParameters: ExamsReports_CreateRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ExamsReports_Create> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling create.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling create.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<ExamsReports_Create>(`${this.configuration.basePath}/api/examsreports/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/create`,
            null,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public downloadExcelFile(requestParameters: ExamsReports_DownloadExcelFileRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/octet-stream'}): Observable<string> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling downloadExcelFile.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling downloadExcelFile.');
        }
        let examsReportId = requestParameters.examsReportId;
        if (examsReportId === null || examsReportId === undefined) {
            throw new Error('Required parameter examsReportId was null or undefined when calling downloadExcelFile.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }



        return this.httpClient
            .post<{ url: string }>(
                `${this.configuration.basePath}/api/sign`,
                { url: urlWithParams({ url:`${this.configuration.basePath}/api/examsreports/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/downloadexcelfile/${encodeURIComponent(String(examsReportId))}` }) },
                {
                    withCredentials: this.configuration.withCredentials,
                    headers: headers
                }
            )
            .pipe(map(({ url }) => url));
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public get(requestParameters: ExamsReports_GetRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ExamsReports_Get> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling get.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling get.');
        }
        let examsReportId = requestParameters.examsReportId;
        if (examsReportId === null || examsReportId === undefined) {
            throw new Error('Required parameter examsReportId was null or undefined when calling get.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<ExamsReports_Get>(`${this.configuration.basePath}/api/examsreports/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/get/${encodeURIComponent(String(examsReportId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => ExamsReportsGetVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getAll(requestParameters: ExamsReports_GetAllRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ExamsReports_GetAll> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getAll.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getAll.');
        }
        let offset = requestParameters.offset;
        let limit = requestParameters.limit;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (offset != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>offset, 'offset');
        }
        if (limit != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>limit, 'limit');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<ExamsReports_GetAll>(`${this.configuration.basePath}/api/examsreports/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/getall`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => TableResultVOOfExamsReportsGetAllVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getItems(requestParameters: ExamsReports_GetItemsRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ExamsReports_GetItems> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getItems.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getItems.');
        }
        let examsReportId = requestParameters.examsReportId;
        if (examsReportId === null || examsReportId === undefined) {
            throw new Error('Required parameter examsReportId was null or undefined when calling getItems.');
        }
        let offset = requestParameters.offset;
        let limit = requestParameters.limit;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (offset != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>offset, 'offset');
        }
        if (limit != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>limit, 'limit');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<ExamsReports_GetItems>(`${this.configuration.basePath}/api/examsreports/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/getitems/${encodeURIComponent(String(examsReportId))}/items`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => TableResultVOOfExamsReportsGetItemsVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public remove(requestParameters: ExamsReports_RemoveRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ExamsReports_Remove> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling remove.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling remove.');
        }
        let examsReportId = requestParameters.examsReportId;
        if (examsReportId === null || examsReportId === undefined) {
            throw new Error('Required parameter examsReportId was null or undefined when calling remove.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.delete<ExamsReports_Remove>(`${this.configuration.basePath}/api/examsreports/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/remove/${encodeURIComponent(String(examsReportId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

}
