/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec, dateToLocalIsoString, dateTimeToLocalIsoString, urlWithParams } from '../encoder';
import { Observable }                                        from 'rxjs';
import { map }                                               from 'rxjs/operators';

import { CreateFinalGradePointAverageByStudentsReportCommand, CreateFinalGradePointAverageByStudentsReportCommandFromJSON, CreateFinalGradePointAverageByStudentsReportCommandToJSON } from '../model/createFinalGradePointAverageByStudentsReportCommand';
import { FinalGradePointAverageByStudentsReportsGetVO, FinalGradePointAverageByStudentsReportsGetVOFromJSON, FinalGradePointAverageByStudentsReportsGetVOToJSON } from '../model/finalGradePointAverageByStudentsReportsGetVO';
import { TableResultVOOfFinalGradePointAverageByStudentsReportsGetAllVO, TableResultVOOfFinalGradePointAverageByStudentsReportsGetAllVOFromJSON, TableResultVOOfFinalGradePointAverageByStudentsReportsGetAllVOToJSON } from '../model/tableResultVOOfFinalGradePointAverageByStudentsReportsGetAllVO';
import { TableResultVOOfFinalGradePointAverageByStudentsReportsGetItemsVO, TableResultVOOfFinalGradePointAverageByStudentsReportsGetItemsVOFromJSON, TableResultVOOfFinalGradePointAverageByStudentsReportsGetItemsVOToJSON } from '../model/tableResultVOOfFinalGradePointAverageByStudentsReportsGetItemsVO';
import { ValidationErrorResponse, ValidationErrorResponseFromJSON, ValidationErrorResponseToJSON } from '../model/validationErrorResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

export type FinalGradePointAverageByStudentsReports_Create = number;
export type FinalGradePointAverageByStudentsReports_DownloadExcelFile = Blob;
export type FinalGradePointAverageByStudentsReports_Get = FinalGradePointAverageByStudentsReportsGetVO;
export type FinalGradePointAverageByStudentsReports_GetAll = TableResultVOOfFinalGradePointAverageByStudentsReportsGetAllVO;
export type FinalGradePointAverageByStudentsReports_GetItems = TableResultVOOfFinalGradePointAverageByStudentsReportsGetItemsVO;
export type FinalGradePointAverageByStudentsReports_Remove = any;


export interface FinalGradePointAverageByStudentsReports_CreateRequestParams {
    schoolYear: number;
    instId: number;
    createFinalGradePointAverageByStudentsReportCommand: CreateFinalGradePointAverageByStudentsReportCommand;
}

export interface FinalGradePointAverageByStudentsReports_DownloadExcelFileRequestParams {
    schoolYear: number;
    instId: number;
    finalGradePointAverageByStudentsReportId: number;
}

export interface FinalGradePointAverageByStudentsReports_GetRequestParams {
    schoolYear: number;
    instId: number;
    finalGradePointAverageByStudentsReportId: number;
}

export interface FinalGradePointAverageByStudentsReports_GetAllRequestParams {
    schoolYear: number;
    instId: number;
    offset?: number | null;
    limit?: number | null;
}

export interface FinalGradePointAverageByStudentsReports_GetItemsRequestParams {
    schoolYear: number;
    instId: number;
    finalGradePointAverageByStudentsReportId: number;
    offset?: number | null;
    limit?: number | null;
}

export interface FinalGradePointAverageByStudentsReports_RemoveRequestParams {
    schoolYear: number;
    instId: number;
    finalGradePointAverageByStudentsReportId: number;
}


@Injectable({
  providedIn: 'root'
})
export class FinalGradePointAverageByStudentsReportsService {

    protected basePath = 'http://host.docker.internal:5001';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach((elem, index) => httpParams = this.addToHttpParamsRecursive(httpParams, elem, `${key}[${index}]`));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, dateToLocalIsoString(value as Date));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public create(requestParameters: FinalGradePointAverageByStudentsReports_CreateRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<FinalGradePointAverageByStudentsReports_Create> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling create.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling create.');
        }
        let createFinalGradePointAverageByStudentsReportCommand = requestParameters.createFinalGradePointAverageByStudentsReportCommand;
        if (createFinalGradePointAverageByStudentsReportCommand === null || createFinalGradePointAverageByStudentsReportCommand === undefined) {
            throw new Error('Required parameter createFinalGradePointAverageByStudentsReportCommand was null or undefined when calling create.');
        }

        createFinalGradePointAverageByStudentsReportCommand = CreateFinalGradePointAverageByStudentsReportCommandToJSON(createFinalGradePointAverageByStudentsReportCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<FinalGradePointAverageByStudentsReports_Create>(`${this.configuration.basePath}/api/finalgradepointaveragebystudentsreports/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/create`,
            createFinalGradePointAverageByStudentsReportCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public downloadExcelFile(requestParameters: FinalGradePointAverageByStudentsReports_DownloadExcelFileRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/octet-stream'}): Observable<string> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling downloadExcelFile.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling downloadExcelFile.');
        }
        let finalGradePointAverageByStudentsReportId = requestParameters.finalGradePointAverageByStudentsReportId;
        if (finalGradePointAverageByStudentsReportId === null || finalGradePointAverageByStudentsReportId === undefined) {
            throw new Error('Required parameter finalGradePointAverageByStudentsReportId was null or undefined when calling downloadExcelFile.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }



        return this.httpClient
            .post<{ url: string }>(
                `${this.configuration.basePath}/api/sign`,
                { url: urlWithParams({ url:`${this.configuration.basePath}/api/finalgradepointaveragebystudentsreports/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/downloadexcelfile/${encodeURIComponent(String(finalGradePointAverageByStudentsReportId))}` }) },
                {
                    withCredentials: this.configuration.withCredentials,
                    headers: headers
                }
            )
            .pipe(map(({ url }) => url));
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public get(requestParameters: FinalGradePointAverageByStudentsReports_GetRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<FinalGradePointAverageByStudentsReports_Get> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling get.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling get.');
        }
        let finalGradePointAverageByStudentsReportId = requestParameters.finalGradePointAverageByStudentsReportId;
        if (finalGradePointAverageByStudentsReportId === null || finalGradePointAverageByStudentsReportId === undefined) {
            throw new Error('Required parameter finalGradePointAverageByStudentsReportId was null or undefined when calling get.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<FinalGradePointAverageByStudentsReports_Get>(`${this.configuration.basePath}/api/finalgradepointaveragebystudentsreports/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/get/${encodeURIComponent(String(finalGradePointAverageByStudentsReportId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => FinalGradePointAverageByStudentsReportsGetVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getAll(requestParameters: FinalGradePointAverageByStudentsReports_GetAllRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<FinalGradePointAverageByStudentsReports_GetAll> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getAll.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getAll.');
        }
        let offset = requestParameters.offset;
        let limit = requestParameters.limit;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (offset != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>offset, 'offset');
        }
        if (limit != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>limit, 'limit');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<FinalGradePointAverageByStudentsReports_GetAll>(`${this.configuration.basePath}/api/finalgradepointaveragebystudentsreports/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/getall`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => TableResultVOOfFinalGradePointAverageByStudentsReportsGetAllVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getItems(requestParameters: FinalGradePointAverageByStudentsReports_GetItemsRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<FinalGradePointAverageByStudentsReports_GetItems> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getItems.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getItems.');
        }
        let finalGradePointAverageByStudentsReportId = requestParameters.finalGradePointAverageByStudentsReportId;
        if (finalGradePointAverageByStudentsReportId === null || finalGradePointAverageByStudentsReportId === undefined) {
            throw new Error('Required parameter finalGradePointAverageByStudentsReportId was null or undefined when calling getItems.');
        }
        let offset = requestParameters.offset;
        let limit = requestParameters.limit;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (offset != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>offset, 'offset');
        }
        if (limit != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>limit, 'limit');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<FinalGradePointAverageByStudentsReports_GetItems>(`${this.configuration.basePath}/api/finalgradepointaveragebystudentsreports/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/getitems/${encodeURIComponent(String(finalGradePointAverageByStudentsReportId))}/items`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => TableResultVOOfFinalGradePointAverageByStudentsReportsGetItemsVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public remove(requestParameters: FinalGradePointAverageByStudentsReports_RemoveRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<FinalGradePointAverageByStudentsReports_Remove> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling remove.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling remove.');
        }
        let finalGradePointAverageByStudentsReportId = requestParameters.finalGradePointAverageByStudentsReportId;
        if (finalGradePointAverageByStudentsReportId === null || finalGradePointAverageByStudentsReportId === undefined) {
            throw new Error('Required parameter finalGradePointAverageByStudentsReportId was null or undefined when calling remove.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.delete<FinalGradePointAverageByStudentsReports_Remove>(`${this.configuration.basePath}/api/finalgradepointaveragebystudentsreports/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/remove/${encodeURIComponent(String(finalGradePointAverageByStudentsReportId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

}
