/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec, dateToLocalIsoString, dateTimeToLocalIsoString, urlWithParams } from '../encoder';
import { Observable }                                        from 'rxjs';
import { map }                                               from 'rxjs/operators';

import { MyHourGetTeacherLessonAbsencesVO, MyHourGetTeacherLessonAbsencesVOFromJSON, MyHourGetTeacherLessonAbsencesVOToJSON } from '../model/myHourGetTeacherLessonAbsencesVO';
import { MyHourGetTeacherLessonGradesVO, MyHourGetTeacherLessonGradesVOFromJSON, MyHourGetTeacherLessonGradesVOToJSON } from '../model/myHourGetTeacherLessonGradesVO';
import { MyHourGetTeacherLessonVO, MyHourGetTeacherLessonVOFromJSON, MyHourGetTeacherLessonVOToJSON } from '../model/myHourGetTeacherLessonVO';
import { MyHourGetTeacherLessonsVO, MyHourGetTeacherLessonsVOFromJSON, MyHourGetTeacherLessonsVOToJSON } from '../model/myHourGetTeacherLessonsVO';
import { ValidationErrorResponse, ValidationErrorResponseFromJSON, ValidationErrorResponseToJSON } from '../model/validationErrorResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

export type MyHour_GetTeacherLesson = MyHourGetTeacherLessonVO;
export type MyHour_GetTeacherLessonAbsences = Array<MyHourGetTeacherLessonAbsencesVO>;
export type MyHour_GetTeacherLessonGrades = Array<MyHourGetTeacherLessonGradesVO>;
export type MyHour_GetTeacherLessons = Array<MyHourGetTeacherLessonsVO>;


export interface MyHour_GetTeacherLessonRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    scheduleLessonId: number;
}

export interface MyHour_GetTeacherLessonAbsencesRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    scheduleLessonId: number;
}

export interface MyHour_GetTeacherLessonGradesRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    scheduleLessonId: number;
}

export interface MyHour_GetTeacherLessonsRequestParams {
    schoolYear: number;
    instId: number;
    date: Date;
}


@Injectable({
  providedIn: 'root'
})
export class MyHourService {

    protected basePath = 'http://host.docker.internal:5001';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach((elem, index) => httpParams = this.addToHttpParamsRecursive(httpParams, elem, `${key}[${index}]`));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, dateToLocalIsoString(value as Date));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getTeacherLesson(requestParameters: MyHour_GetTeacherLessonRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<MyHour_GetTeacherLesson> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getTeacherLesson.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getTeacherLesson.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling getTeacherLesson.');
        }
        let scheduleLessonId = requestParameters.scheduleLessonId;
        if (scheduleLessonId === null || scheduleLessonId === undefined) {
            throw new Error('Required parameter scheduleLessonId was null or undefined when calling getTeacherLesson.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<MyHour_GetTeacherLesson>(`${this.configuration.basePath}/api/myhour/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/getteacherlesson/${encodeURIComponent(String(classBookId))}/${encodeURIComponent(String(scheduleLessonId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => MyHourGetTeacherLessonVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getTeacherLessonAbsences(requestParameters: MyHour_GetTeacherLessonAbsencesRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<MyHour_GetTeacherLessonAbsences> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getTeacherLessonAbsences.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getTeacherLessonAbsences.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling getTeacherLessonAbsences.');
        }
        let scheduleLessonId = requestParameters.scheduleLessonId;
        if (scheduleLessonId === null || scheduleLessonId === undefined) {
            throw new Error('Required parameter scheduleLessonId was null or undefined when calling getTeacherLessonAbsences.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<MyHour_GetTeacherLessonAbsences>(`${this.configuration.basePath}/api/myhour/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/getteacherlessonabsences/${encodeURIComponent(String(classBookId))}/${encodeURIComponent(String(scheduleLessonId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => jsonValue.map(MyHourGetTeacherLessonAbsencesVOFromJSON))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getTeacherLessonGrades(requestParameters: MyHour_GetTeacherLessonGradesRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<MyHour_GetTeacherLessonGrades> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getTeacherLessonGrades.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getTeacherLessonGrades.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling getTeacherLessonGrades.');
        }
        let scheduleLessonId = requestParameters.scheduleLessonId;
        if (scheduleLessonId === null || scheduleLessonId === undefined) {
            throw new Error('Required parameter scheduleLessonId was null or undefined when calling getTeacherLessonGrades.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<MyHour_GetTeacherLessonGrades>(`${this.configuration.basePath}/api/myhour/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/getteacherlessongrades/${encodeURIComponent(String(classBookId))}/${encodeURIComponent(String(scheduleLessonId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => jsonValue.map(MyHourGetTeacherLessonGradesVOFromJSON))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getTeacherLessons(requestParameters: MyHour_GetTeacherLessonsRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<MyHour_GetTeacherLessons> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getTeacherLessons.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getTeacherLessons.');
        }
        let date = requestParameters.date;
        if (date === null || date === undefined) {
            throw new Error('Required parameter date was null or undefined when calling getTeacherLessons.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<MyHour_GetTeacherLessons>(`${this.configuration.basePath}/api/myhour/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/getteacherlessons/${encodeURIComponent(String(date.toISOString()))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => jsonValue.map(MyHourGetTeacherLessonsVOFromJSON))
        );
    }

}
