/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec, dateToLocalIsoString, dateTimeToLocalIsoString, urlWithParams } from '../encoder';
import { Observable }                                        from 'rxjs';
import { map }                                               from 'rxjs/operators';

import { CreatePgResultCommand, CreatePgResultCommandFromJSON, CreatePgResultCommandToJSON } from '../model/createPgResultCommand';
import { PgResultsGetAllForClassBookVO, PgResultsGetAllForClassBookVOFromJSON, PgResultsGetAllForClassBookVOToJSON } from '../model/pgResultsGetAllForClassBookVO';
import { PgResultsGetAllForStudentVO, PgResultsGetAllForStudentVOFromJSON, PgResultsGetAllForStudentVOToJSON } from '../model/pgResultsGetAllForStudentVO';
import { PgResultsGetVO, PgResultsGetVOFromJSON, PgResultsGetVOToJSON } from '../model/pgResultsGetVO';
import { UpdatePgResultCommand, UpdatePgResultCommandFromJSON, UpdatePgResultCommandToJSON } from '../model/updatePgResultCommand';
import { ValidationErrorResponse, ValidationErrorResponseFromJSON, ValidationErrorResponseToJSON } from '../model/validationErrorResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

export type PgResults_CreatePgResult = number;
export type PgResults_Get = PgResultsGetVO;
export type PgResults_GetAllForClassBook = Array<PgResultsGetAllForClassBookVO>;
export type PgResults_GetAllForStudent = Array<PgResultsGetAllForStudentVO>;
export type PgResults_Remove = any;
export type PgResults_Update = any;


export interface PgResults_CreatePgResultRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    createPgResultCommand: CreatePgResultCommand;
}

export interface PgResults_GetRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    pgResultId: number;
}

export interface PgResults_GetAllForClassBookRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
}

export interface PgResults_GetAllForStudentRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    personId: number;
}

export interface PgResults_RemoveRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    pgResultId: number;
}

export interface PgResults_UpdateRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    pgResultId: number;
    updatePgResultCommand: UpdatePgResultCommand;
}


@Injectable({
  providedIn: 'root'
})
export class PgResultsService {

    protected basePath = 'http://host.docker.internal:5001';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach((elem, index) => httpParams = this.addToHttpParamsRecursive(httpParams, elem, `${key}[${index}]`));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, dateToLocalIsoString(value as Date));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public createPgResult(requestParameters: PgResults_CreatePgResultRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<PgResults_CreatePgResult> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling createPgResult.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling createPgResult.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling createPgResult.');
        }
        let createPgResultCommand = requestParameters.createPgResultCommand;
        if (createPgResultCommand === null || createPgResultCommand === undefined) {
            throw new Error('Required parameter createPgResultCommand was null or undefined when calling createPgResult.');
        }

        createPgResultCommand = CreatePgResultCommandToJSON(createPgResultCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<PgResults_CreatePgResult>(`${this.configuration.basePath}/api/pgresults/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/createpgresult`,
            createPgResultCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public get(requestParameters: PgResults_GetRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<PgResults_Get> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling get.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling get.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling get.');
        }
        let pgResultId = requestParameters.pgResultId;
        if (pgResultId === null || pgResultId === undefined) {
            throw new Error('Required parameter pgResultId was null or undefined when calling get.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<PgResults_Get>(`${this.configuration.basePath}/api/pgresults/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/get/${encodeURIComponent(String(pgResultId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => PgResultsGetVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getAllForClassBook(requestParameters: PgResults_GetAllForClassBookRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<PgResults_GetAllForClassBook> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getAllForClassBook.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getAllForClassBook.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling getAllForClassBook.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<PgResults_GetAllForClassBook>(`${this.configuration.basePath}/api/pgresults/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/getallforclassbook`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => jsonValue.map(PgResultsGetAllForClassBookVOFromJSON))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getAllForStudent(requestParameters: PgResults_GetAllForStudentRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<PgResults_GetAllForStudent> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getAllForStudent.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getAllForStudent.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling getAllForStudent.');
        }
        let personId = requestParameters.personId;
        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling getAllForStudent.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (personId != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>personId, 'personId');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<PgResults_GetAllForStudent>(`${this.configuration.basePath}/api/pgresults/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/getallforstudent`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => jsonValue.map(PgResultsGetAllForStudentVOFromJSON))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public remove(requestParameters: PgResults_RemoveRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<PgResults_Remove> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling remove.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling remove.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling remove.');
        }
        let pgResultId = requestParameters.pgResultId;
        if (pgResultId === null || pgResultId === undefined) {
            throw new Error('Required parameter pgResultId was null or undefined when calling remove.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.delete<PgResults_Remove>(`${this.configuration.basePath}/api/pgresults/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/remove/${encodeURIComponent(String(pgResultId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public update(requestParameters: PgResults_UpdateRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<PgResults_Update> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling update.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling update.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling update.');
        }
        let pgResultId = requestParameters.pgResultId;
        if (pgResultId === null || pgResultId === undefined) {
            throw new Error('Required parameter pgResultId was null or undefined when calling update.');
        }
        let updatePgResultCommand = requestParameters.updatePgResultCommand;
        if (updatePgResultCommand === null || updatePgResultCommand === undefined) {
            throw new Error('Required parameter updatePgResultCommand was null or undefined when calling update.');
        }

        updatePgResultCommand = UpdatePgResultCommandToJSON(updatePgResultCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<PgResults_Update>(`${this.configuration.basePath}/api/pgresults/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/update/${encodeURIComponent(String(pgResultId))}`,
            updatePgResultCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

}
