/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec, dateToLocalIsoString, dateTimeToLocalIsoString, urlWithParams } from '../encoder';
import { Observable }                                        from 'rxjs';
import { map }                                               from 'rxjs/operators';

import { CreateRemarkCommand, CreateRemarkCommandFromJSON, CreateRemarkCommandToJSON } from '../model/createRemarkCommand';
import { RemarkType, RemarkTypeFromJSON, RemarkTypeToJSON } from '../model/remarkType';
import { RemarksGetAllForClassBookVO, RemarksGetAllForClassBookVOFromJSON, RemarksGetAllForClassBookVOToJSON } from '../model/remarksGetAllForClassBookVO';
import { RemarksGetAllForStudentAndTypeVO, RemarksGetAllForStudentAndTypeVOFromJSON, RemarksGetAllForStudentAndTypeVOToJSON } from '../model/remarksGetAllForStudentAndTypeVO';
import { RemarksGetVO, RemarksGetVOFromJSON, RemarksGetVOToJSON } from '../model/remarksGetVO';
import { UpdateRemarkCommand, UpdateRemarkCommandFromJSON, UpdateRemarkCommandToJSON } from '../model/updateRemarkCommand';
import { ValidationErrorResponse, ValidationErrorResponseFromJSON, ValidationErrorResponseToJSON } from '../model/validationErrorResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

export type Remarks_CreateRemark = any;
export type Remarks_Get = RemarksGetVO;
export type Remarks_GetAllForClassBook = Array<RemarksGetAllForClassBookVO>;
export type Remarks_GetAllForStudentAndType = Array<RemarksGetAllForStudentAndTypeVO>;
export type Remarks_Remove = any;
export type Remarks_Update = any;


export interface Remarks_CreateRemarkRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    curriculumId: number;
    createRemarkCommand: CreateRemarkCommand;
}

export interface Remarks_GetRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    remarkId: number;
}

export interface Remarks_GetAllForClassBookRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
}

export interface Remarks_GetAllForStudentAndTypeRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    personId: number;
    type: RemarkType;
}

export interface Remarks_RemoveRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    curriculumId: number;
    remarkId: number;
}

export interface Remarks_UpdateRequestParams {
    schoolYear: number;
    instId: number;
    classBookId: number;
    curriculumId: number;
    remarkId: number;
    updateRemarkCommand: UpdateRemarkCommand;
}


@Injectable({
  providedIn: 'root'
})
export class RemarksService {

    protected basePath = 'http://host.docker.internal:5001';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach((elem, index) => httpParams = this.addToHttpParamsRecursive(httpParams, elem, `${key}[${index}]`));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, dateToLocalIsoString(value as Date));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public createRemark(requestParameters: Remarks_CreateRemarkRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Remarks_CreateRemark> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling createRemark.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling createRemark.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling createRemark.');
        }
        let curriculumId = requestParameters.curriculumId;
        if (curriculumId === null || curriculumId === undefined) {
            throw new Error('Required parameter curriculumId was null or undefined when calling createRemark.');
        }
        let createRemarkCommand = requestParameters.createRemarkCommand;
        if (createRemarkCommand === null || createRemarkCommand === undefined) {
            throw new Error('Required parameter createRemarkCommand was null or undefined when calling createRemark.');
        }

        createRemarkCommand = CreateRemarkCommandToJSON(createRemarkCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<Remarks_CreateRemark>(`${this.configuration.basePath}/api/remarks/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/createremark/${encodeURIComponent(String(curriculumId))}`,
            createRemarkCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public get(requestParameters: Remarks_GetRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Remarks_Get> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling get.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling get.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling get.');
        }
        let remarkId = requestParameters.remarkId;
        if (remarkId === null || remarkId === undefined) {
            throw new Error('Required parameter remarkId was null or undefined when calling get.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<Remarks_Get>(`${this.configuration.basePath}/api/remarks/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/get/${encodeURIComponent(String(remarkId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => RemarksGetVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getAllForClassBook(requestParameters: Remarks_GetAllForClassBookRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Remarks_GetAllForClassBook> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getAllForClassBook.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getAllForClassBook.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling getAllForClassBook.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<Remarks_GetAllForClassBook>(`${this.configuration.basePath}/api/remarks/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/getallforclassbook`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => jsonValue.map(RemarksGetAllForClassBookVOFromJSON))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getAllForStudentAndType(requestParameters: Remarks_GetAllForStudentAndTypeRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Remarks_GetAllForStudentAndType> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getAllForStudentAndType.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getAllForStudentAndType.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling getAllForStudentAndType.');
        }
        let personId = requestParameters.personId;
        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling getAllForStudentAndType.');
        }
        let type = requestParameters.type;
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling getAllForStudentAndType.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (personId != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>personId, 'personId');
        }
        if (type != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>type, 'type');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<Remarks_GetAllForStudentAndType>(`${this.configuration.basePath}/api/remarks/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/getallforstudentandtype`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => jsonValue.map(RemarksGetAllForStudentAndTypeVOFromJSON))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public remove(requestParameters: Remarks_RemoveRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Remarks_Remove> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling remove.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling remove.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling remove.');
        }
        let curriculumId = requestParameters.curriculumId;
        if (curriculumId === null || curriculumId === undefined) {
            throw new Error('Required parameter curriculumId was null or undefined when calling remove.');
        }
        let remarkId = requestParameters.remarkId;
        if (remarkId === null || remarkId === undefined) {
            throw new Error('Required parameter remarkId was null or undefined when calling remove.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<Remarks_Remove>(`${this.configuration.basePath}/api/remarks/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/remove/${encodeURIComponent(String(curriculumId))}/${encodeURIComponent(String(remarkId))}`,
            null,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public update(requestParameters: Remarks_UpdateRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Remarks_Update> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling update.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling update.');
        }
        let classBookId = requestParameters.classBookId;
        if (classBookId === null || classBookId === undefined) {
            throw new Error('Required parameter classBookId was null or undefined when calling update.');
        }
        let curriculumId = requestParameters.curriculumId;
        if (curriculumId === null || curriculumId === undefined) {
            throw new Error('Required parameter curriculumId was null or undefined when calling update.');
        }
        let remarkId = requestParameters.remarkId;
        if (remarkId === null || remarkId === undefined) {
            throw new Error('Required parameter remarkId was null or undefined when calling update.');
        }
        let updateRemarkCommand = requestParameters.updateRemarkCommand;
        if (updateRemarkCommand === null || updateRemarkCommand === undefined) {
            throw new Error('Required parameter updateRemarkCommand was null or undefined when calling update.');
        }

        updateRemarkCommand = UpdateRemarkCommandToJSON(updateRemarkCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<Remarks_Update>(`${this.configuration.basePath}/api/remarks/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/${encodeURIComponent(String(classBookId))}/update/${encodeURIComponent(String(curriculumId))}/${encodeURIComponent(String(remarkId))}`,
            updateRemarkCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

}
