/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec, dateToLocalIsoString, dateTimeToLocalIsoString, urlWithParams } from '../encoder';
import { Observable }                                        from 'rxjs';
import { map }                                               from 'rxjs/operators';

import { CreateShiftCommand, CreateShiftCommandFromJSON, CreateShiftCommandToJSON } from '../model/createShiftCommand';
import { ShiftsGetHoursUsedInScheduleVO, ShiftsGetHoursUsedInScheduleVOFromJSON, ShiftsGetHoursUsedInScheduleVOToJSON } from '../model/shiftsGetHoursUsedInScheduleVO';
import { ShiftsGetVO, ShiftsGetVOFromJSON, ShiftsGetVOToJSON } from '../model/shiftsGetVO';
import { TableResultVOOfShiftsGetAllVO, TableResultVOOfShiftsGetAllVOFromJSON, TableResultVOOfShiftsGetAllVOToJSON } from '../model/tableResultVOOfShiftsGetAllVO';
import { UpdateShiftCommand, UpdateShiftCommandFromJSON, UpdateShiftCommandToJSON } from '../model/updateShiftCommand';
import { ValidationErrorResponse, ValidationErrorResponseFromJSON, ValidationErrorResponseToJSON } from '../model/validationErrorResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

export type Shifts_CreateShift = number;
export type Shifts_Get = ShiftsGetVO;
export type Shifts_GetAll = TableResultVOOfShiftsGetAllVO;
export type Shifts_GetHoursUsedInSchedule = Array<ShiftsGetHoursUsedInScheduleVO>;
export type Shifts_Remove = any;
export type Shifts_Update = any;


export interface Shifts_CreateShiftRequestParams {
    schoolYear: number;
    instId: number;
    createShiftCommand: CreateShiftCommand;
}

export interface Shifts_GetRequestParams {
    schoolYear: number;
    instId: number;
    shiftId: number;
}

export interface Shifts_GetAllRequestParams {
    schoolYear: number;
    instId: number;
    offset?: number | null;
    limit?: number | null;
}

export interface Shifts_GetHoursUsedInScheduleRequestParams {
    schoolYear: number;
    instId: number;
    shiftId: number;
}

export interface Shifts_RemoveRequestParams {
    schoolYear: number;
    instId: number;
    shiftId: number;
}

export interface Shifts_UpdateRequestParams {
    schoolYear: number;
    instId: number;
    shiftId: number;
    updateShiftCommand: UpdateShiftCommand;
}


@Injectable({
  providedIn: 'root'
})
export class ShiftsService {

    protected basePath = 'http://host.docker.internal:5001';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach((elem, index) => httpParams = this.addToHttpParamsRecursive(httpParams, elem, `${key}[${index}]`));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, dateToLocalIsoString(value as Date));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public createShift(requestParameters: Shifts_CreateShiftRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Shifts_CreateShift> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling createShift.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling createShift.');
        }
        let createShiftCommand = requestParameters.createShiftCommand;
        if (createShiftCommand === null || createShiftCommand === undefined) {
            throw new Error('Required parameter createShiftCommand was null or undefined when calling createShift.');
        }

        createShiftCommand = CreateShiftCommandToJSON(createShiftCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<Shifts_CreateShift>(`${this.configuration.basePath}/api/shifts/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/createshift`,
            createShiftCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public get(requestParameters: Shifts_GetRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Shifts_Get> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling get.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling get.');
        }
        let shiftId = requestParameters.shiftId;
        if (shiftId === null || shiftId === undefined) {
            throw new Error('Required parameter shiftId was null or undefined when calling get.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<Shifts_Get>(`${this.configuration.basePath}/api/shifts/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/get/${encodeURIComponent(String(shiftId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => ShiftsGetVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getAll(requestParameters: Shifts_GetAllRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Shifts_GetAll> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getAll.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getAll.');
        }
        let offset = requestParameters.offset;
        let limit = requestParameters.limit;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (offset != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>offset, 'offset');
        }
        if (limit != null) {
          queryParameters = this.addToHttpParamsRecursive(queryParameters, <any>limit, 'limit');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<Shifts_GetAll>(`${this.configuration.basePath}/api/shifts/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/getall`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => TableResultVOOfShiftsGetAllVOFromJSON(jsonValue))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public getHoursUsedInSchedule(requestParameters: Shifts_GetHoursUsedInScheduleRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Shifts_GetHoursUsedInSchedule> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling getHoursUsedInSchedule.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling getHoursUsedInSchedule.');
        }
        let shiftId = requestParameters.shiftId;
        if (shiftId === null || shiftId === undefined) {
            throw new Error('Required parameter shiftId was null or undefined when calling getHoursUsedInSchedule.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<Shifts_GetHoursUsedInSchedule>(`${this.configuration.basePath}/api/shifts/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/gethoursusedinschedule/${encodeURIComponent(String(shiftId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
            map((jsonValue) => jsonValue.map(ShiftsGetHoursUsedInScheduleVOFromJSON))
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public remove(requestParameters: Shifts_RemoveRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Shifts_Remove> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling remove.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling remove.');
        }
        let shiftId = requestParameters.shiftId;
        if (shiftId === null || shiftId === undefined) {
            throw new Error('Required parameter shiftId was null or undefined when calling remove.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.delete<Shifts_Remove>(`${this.configuration.basePath}/api/shifts/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/remove/${encodeURIComponent(String(shiftId))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

    /**
     * @param requestParameters
     * @param reportProgress flag to report request and response progress.
     */
    public update(requestParameters: Shifts_UpdateRequestParams, reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<Shifts_Update> {
        let schoolYear = requestParameters.schoolYear;
        if (schoolYear === null || schoolYear === undefined) {
            throw new Error('Required parameter schoolYear was null or undefined when calling update.');
        }
        let instId = requestParameters.instId;
        if (instId === null || instId === undefined) {
            throw new Error('Required parameter instId was null or undefined when calling update.');
        }
        let shiftId = requestParameters.shiftId;
        if (shiftId === null || shiftId === undefined) {
            throw new Error('Required parameter shiftId was null or undefined when calling update.');
        }
        let updateShiftCommand = requestParameters.updateShiftCommand;
        if (updateShiftCommand === null || updateShiftCommand === undefined) {
            throw new Error('Required parameter updateShiftCommand was null or undefined when calling update.');
        }

        updateShiftCommand = UpdateShiftCommandToJSON(updateShiftCommand);

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (Bearer) required
        credential = this.configuration.lookupCredential('Bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<Shifts_Update>(`${this.configuration.basePath}/api/shifts/${encodeURIComponent(String(schoolYear))}/${encodeURIComponent(String(instId))}/update/${encodeURIComponent(String(shiftId))}`,
            updateShiftCommand,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: 'body',
                reportProgress: reportProgress
            }
        ).pipe(
        );
    }

}
