//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Kontrax.Regix.Core.RegixModels.NSSI {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NOI/RP")]
    [System.Xml.Serialization.XmlRootAttribute("EnumHack", Namespace="http://egov.bg/RegiX/NOI/RP", IsNullable=false)]
    public enum IdentifierType {
        
        /// <remarks/>
        ЕГН,
        
        /// <remarks/>
        ЛНЧ,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NOI/RP/PensionRightResponse")]
    [System.Xml.Serialization.XmlRootAttribute("PensionRightResponse", Namespace="http://egov.bg/RegiX/NOI/RP/PensionRightResponse", IsNullable=false)]
    public partial class PensionRightResponse {
        
        private string titleField;
        
        private System.DateTime forDateField;
        
        private bool forDateFieldSpecified;
        
        private string territorialDivisionNOIField;
        
        private string identifierField;
        
        private PersonNames namesField;
        
        private string statusField;
        
        private System.DateTime dateOfDeathField;
        
        private bool dateOfDeathFieldSpecified;
        
        private string contentTextField;
        
        private PensionCharacteristic[] pensionCharacteristicsField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ForDate {
            get {
                return this.forDateField;
            }
            set {
                this.forDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForDateSpecified {
            get {
                return this.forDateFieldSpecified;
            }
            set {
                this.forDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TerritorialDivisionNOI {
            get {
                return this.territorialDivisionNOIField;
            }
            set {
                this.territorialDivisionNOIField = value;
            }
        }
        
        /// <remarks/>
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public PersonNames Names {
            get {
                return this.namesField;
            }
            set {
                this.namesField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateOfDeath {
            get {
                return this.dateOfDeathField;
            }
            set {
                this.dateOfDeathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfDeathSpecified {
            get {
                return this.dateOfDeathFieldSpecified;
            }
            set {
                this.dateOfDeathFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ContentText {
            get {
                return this.contentTextField;
            }
            set {
                this.contentTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://egov.bg/RegiX/NOI/RP", IsNullable=false)]
        public PensionCharacteristic[] PensionCharacteristics {
            get {
                return this.pensionCharacteristicsField;
            }
            set {
                this.pensionCharacteristicsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NOI/RP")]
    public partial class PersonNames {
        
        private string nameField;
        
        private string surnameField;
        
        private string familyNameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NOI/RP")]
    public partial class PensionCharacteristic {
        
        private string dataTextField;
        
        private string valueTextField;
        
        /// <remarks/>
        public string DataText {
            get {
                return this.dataTextField;
            }
            set {
                this.dataTextField = value;
            }
        }
        
        /// <remarks/>
        public string ValueText {
            get {
                return this.valueTextField;
            }
            set {
                this.valueTextField = value;
            }
        }
    }
}
