def backendImage
def frontendImage
def backendImageNameTag
def frontendImageNameTag
def backendImageNameLatestTag
def frontendImageNameLatestTag
def tag
def branchName
def buildLatest = true
def userGuidesDirectory = '/home/neispuoadmin/neispuo-main-portal-rakovodstva'
def credentialsId = "${env.GIT_CREDENTIALS_ID}"
def azurePatId = "${env.AZURE_PAT_ID}"

def adoRegistry = "${env.ADO_REGISTRY_NAME}/${env.ADO_REGISTRY_PROJECT_NAME}"
def adoRegistryCredentials = env.ADO_REGISTRY_CREDENTIALS

def decodeBase64(String encoded) {
    return sh(script: "echo '${encoded}' | base64 -d", returnStdout: true).trim()
}

pipeline {
    agent { node { label 'mon-neispuo-image-builder' } }
    stages {
        stage('Run semantic-release') {
            steps {
                script {
                    branchName = "${env.GIT_BRANCH}".tokenize('/').last()
                    buildName "#${env.BUILD_NUMBER} ${branchName} TBD"
                    def lastCommitMessage = sh(script: "git log -1 | grep '.*\\[skip ci\\].*'", returnStatus: true)
                    // if (lastCommitMessage == 0) {
                    //     env.CI_SKIP = 'true'
                    //     error "'[ci skip]' found in git commit message. Aborting."
                    // }
                    def currentBranch = sh(script: "git rev-parse --abbrev-ref HEAD", returnStdout: true).trim()
                    if (currentBranch == env.BRANCH_NAME) {
                        sh('git tag -l | xargs git tag -d')
                        withCredentials([
                            gitUsernamePassword(credentialsId: "${credentialsId}",
                                gitToolName: 'git-tool'),
                            string(credentialsId: azurePatId, variable: 'AZURE_PAT_ENCODED')
                        ]) {
                            env.AZURE_PAT_DECODED = decodeBase64(env.AZURE_PAT_ENCODED)
                            sh('git fetch -t')
                            nvm('v16.13.0') {
                                sh "npm=\$(which npm)"
                                sh 'npm install'
                                sh 'npm run release'
                            }
                        }
                    }
                }
            }
        }
        stage('Preset environment details details') {
            steps {
                script {
                    branchName = "${env.GIT_BRANCH}".tokenize('/').last()
                    if (branchName == 'staging') {
                        tag = sh(returnStdout: true, script: "git tag --sort version:refname | cat | awk '/next/' | tail -1").trim()
                    } else if (branchName == 'master') {
                        buildLatest = false
                        tag = sh(returnStdout: true, script: "git tag --sort version:refname | cat | awk '!/next/' | tail -1").trim()
                    } else {
                        scmSkip(deleteBuild: true)
                    }
                    backendImageNameTag = "${adoRegistry}/${env.BACKEND_IMAGE_NAME}:${tag}"
                    frontendImageNameTag = "${adoRegistry}/${env.FRONTEND_IMAGE_NAME}:${tag}"
                    if (buildLatest) {
                        backendImageNameLatestTag = "${adoRegistry}/${env.BACKEND_IMAGE_NAME}:latest"
                        frontendImageNameLatestTag = "${adoRegistry}/${env.FRONTEND_IMAGE_NAME}:latest"
                    }
                    // https://plugins.jenkins.io/build-name-setter/
                    buildName "#${env.BUILD_NUMBER} ${branchName} ${tag}"
                }
            }
        }

        stage('Build and tag images') {
            steps {
                withCredentials([string(credentialsId: azurePatId, variable: 'AZURE_PAT')]) {
                    dir("${env.WORKSPACE}/${env.BACKEND_PROJECT_PATH}") {
                        script {
                            // Copy the guides from the files directory to the local files before build
                            sh "cp -rf ${userGuidesDirectory}/* ./files/"
                            backendImage = docker.build("${backendImageNameTag}", ". --no-cache -f ${env.WORKSPACE}/${env.BACKEND_PROJECT_PATH}/Dockerfile")
                        }
                    }
                    dir("${env.WORKSPACE}/${env.FRONTEND_PROJECT_PATH}") {
                        script {
                            sh "echo 'registry=https://registry.npmjs.org/' > .npmrc"
                            sh "echo '@${env.AZURE_SCOPE}:registry=https://pkgs.dev.azure.com/${env.AZURE_ORG}/${env.AZURE_PROJECT}/_packaging/${env.AZURE_FEED}/npm/registry/' >> .npmrc"
                            sh "echo 'always-auth=true' >> .npmrc"
                            sh "echo '//pkgs.dev.azure.com/${env.AZURE_ORG}/${env.AZURE_PROJECT}/_packaging/${env.AZURE_FEED}/npm/registry/:username=VssSessionToken' >> .npmrc"
                            sh "echo '//pkgs.dev.azure.com/${env.AZURE_ORG}/${env.AZURE_PROJECT}/_packaging/${env.AZURE_FEED}/npm/registry/:_password=${AZURE_PAT}' >> .npmrc"
                            sh "echo '//pkgs.dev.azure.com/${env.AZURE_ORG}/${env.AZURE_PROJECT}/_packaging/${env.AZURE_FEED}/npm/registry/:email=not-used@example.com' >> .npmrc"

                            frontendImage = docker.build("${frontendImageNameTag}", ". --no-cache -f ${env.WORKSPACE}/${env.FRONTEND_PROJECT_PATH}/Dockerfile --build-arg BUILD_ENV=${FRONTEND_ARGS_BUILD_ENV}")
                        }
                    }
                }
            }
        }
        stage('Push images to Azure DevOps registry') {
            steps {
                script {
                    docker.withRegistry("https://${adoRegistry}", "${adoRegistryCredentials}") {
                        backendImage.push(tag)
                        frontendImage.push(tag)
                        if (buildLatest) {
                            backendImage.push('latest')
                            frontendImage.push('latest')
                        }
                    }
                }
            }
        }
        stage('Clean up images') {
            steps {
                sh "docker rmi ${backendImageNameTag} -f"
                sh "docker rmi ${frontendImageNameTag} -f"
                script {
                    if (buildLatest) {
                        sh "docker rmi ${backendImageNameLatestTag} -f"
                        sh "docker rmi ${frontendImageNameLatestTag} -f"
                    }
                }

                sh 'docker system prune -f'
            }
        }
    }
}
