namespace SB.Domain;
public static class AttendancesModelSample
{
    public static readonly AttendancesModel Sample =
        new(
            new AttendancesModelMonth[]
            {
                new AttendancesModelMonth(
                    "септември",
                    new AttendancesModelDay[]
                    {
                        new AttendancesModelDay(1, false, false),
                        new AttendancesModelDay(2, false, false),
                        new AttendancesModelDay(3, false, false),
                        new AttendancesModelDay(4, true, true),
                        new AttendancesModelDay(5, true, true),
                        new AttendancesModelDay(6, true, true),
                        new AttendancesModelDay(7, false, false),
                        new AttendancesModelDay(8, false, false),
                        new AttendancesModelDay(9, false, false),
                        new AttendancesModelDay(10, false, false),
                        new AttendancesModelDay(11, true, true),
                        new AttendancesModelDay(12, true, true),
                        new AttendancesModelDay(13, false, false),
                        new AttendancesModelDay(14, false, false),
                        new AttendancesModelDay(15, false, false),
                        new AttendancesModelDay(16, false, false),
                        new AttendancesModelDay(17, false, false),
                        new AttendancesModelDay(18, true, true),
                        new AttendancesModelDay(19, true, true),
                        new AttendancesModelDay(20, false, false),
                        new AttendancesModelDay(21, false, false),
                        new AttendancesModelDay(22, true, true),
                        new AttendancesModelDay(23, false, false),
                        new AttendancesModelDay(24, false, false),
                        new AttendancesModelDay(25, true, true),
                        new AttendancesModelDay(26, true, true),
                        new AttendancesModelDay(27, false, false),
                        new AttendancesModelDay(28, false, false),
                        new AttendancesModelDay(29, false, false),
                        new AttendancesModelDay(30, false, false)
                    },
                    new AttendancesModelStudent[]
                    {
                        new AttendancesModelStudent(
                            1, "Валентина Кръстева",
                            false,
                            new AttendanceType?[]
                            {
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.UnexcusedAbsence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence
                            },
                            20
                        ),
                        new AttendancesModelStudent(
                            2, "Веселина Янева",
                            false,
                            new AttendanceType?[]
                            {
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.UnexcusedAbsence,
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            3, "Емилия Емилова",
                            false,
                            new AttendanceType?[]
                            {
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.UnexcusedAbsence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            4, "Йорданка Лазарова",
                            false,
                            new AttendanceType?[]
                            {
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence
                            },
                            22
                        ),
                    },
                    new int[] { 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2 },
                    80,
                    3
                ),
                new AttendancesModelMonth(
                    "октомври",
                    new AttendancesModelDay[]
                    {
                        new AttendancesModelDay(1, true, true),
                        new AttendancesModelDay(2, true, true),
                        new AttendancesModelDay(3, false, false),
                        new AttendancesModelDay(4, false, false),
                        new AttendancesModelDay(5, false, false),
                        new AttendancesModelDay(6, false, false),
                        new AttendancesModelDay(7, false, false),
                        new AttendancesModelDay(8, true, true),
                        new AttendancesModelDay(9, true, true),
                        new AttendancesModelDay(10, false, false),
                        new AttendancesModelDay(11, false, false),
                        new AttendancesModelDay(12, false, false),
                        new AttendancesModelDay(13, false, false),
                        new AttendancesModelDay(14, false, false),
                        new AttendancesModelDay(15, true, true),
                        new AttendancesModelDay(16, true, true),
                        new AttendancesModelDay(17, false, false),
                        new AttendancesModelDay(18, false, false),
                        new AttendancesModelDay(19, false, false),
                        new AttendancesModelDay(20, false, false),
                        new AttendancesModelDay(21, false, false),
                        new AttendancesModelDay(22, true, true),
                        new AttendancesModelDay(23, true, true),
                        new AttendancesModelDay(24, false, false),
                        new AttendancesModelDay(25, false, false),
                        new AttendancesModelDay(26, false, false),
                        new AttendancesModelDay(27, false, false),
                        new AttendancesModelDay(28, false, false),
                        new AttendancesModelDay(29, true, true),
                        new AttendancesModelDay(30, true, true),
                        new AttendancesModelDay(31, false, false)
                    },
                    new AttendancesModelStudent[]
                    {
                        new AttendancesModelStudent(
                            1, "Валентина Кръстева",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            2, "Веселина Янева",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            3, "Емилия Емилова",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.UnexcusedAbsence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.UnexcusedAbsence
                            },
                            20
                        ),
                        new AttendancesModelStudent(
                            4, "Йорданка Лазарова",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            19
                        ),
                    },
                    new int[] { 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3},
                    82,
                    4
                ),
                new AttendancesModelMonth(
                    "ноември",
                    new AttendancesModelDay[]
                    {
                        new AttendancesModelDay(1, false, false),
                        new AttendancesModelDay(2, false, false),
                        new AttendancesModelDay(3, false, false),
                        new AttendancesModelDay(4, true, true),
                        new AttendancesModelDay(5, true, true),
                        new AttendancesModelDay(6, true, true),
                        new AttendancesModelDay(7, false, false),
                        new AttendancesModelDay(8, false, false),
                        new AttendancesModelDay(9, false, false),
                        new AttendancesModelDay(10, false, false),
                        new AttendancesModelDay(11, true, true),
                        new AttendancesModelDay(12, true, true),
                        new AttendancesModelDay(13, false, false),
                        new AttendancesModelDay(14, false, false),
                        new AttendancesModelDay(15, false, false),
                        new AttendancesModelDay(16, false, false),
                        new AttendancesModelDay(17, false, false),
                        new AttendancesModelDay(18, true, true),
                        new AttendancesModelDay(19, true, true),
                        new AttendancesModelDay(20, false, false),
                        new AttendancesModelDay(21, false, false),
                        new AttendancesModelDay(22, true, true),
                        new AttendancesModelDay(23, false, false),
                        new AttendancesModelDay(24, false, false),
                        new AttendancesModelDay(25, true, true),
                        new AttendancesModelDay(26, true, true),
                        new AttendancesModelDay(27, false, false),
                        new AttendancesModelDay(28, false, false),
                        new AttendancesModelDay(29, false, false),
                        new AttendancesModelDay(30, false, false)
                    },
                    new AttendancesModelStudent[]
                    {
                        new AttendancesModelStudent(
                            1, "Валентина Кръстева",
                            false,
                            new AttendanceType?[]
                            {
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.UnexcusedAbsence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence
                            },
                            20
                        ),
                        new AttendancesModelStudent(
                            2, "Веселина Янева",
                            false,
                            new AttendanceType?[]
                            {
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.UnexcusedAbsence,
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            3, "Емилия Емилова",
                            false,
                            new AttendanceType?[]
                            {
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.UnexcusedAbsence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            4, "Йорданка Лазарова",
                            false,
                            new AttendanceType?[]
                            {
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence
                            },
                            22
                        ),
                    },
                    new int[] { 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2},
                    80,
                    3
                ),
                new AttendancesModelMonth(
                    "декември",
                    new AttendancesModelDay[]
                    {
                        new AttendancesModelDay(1, true, true),
                        new AttendancesModelDay(2, true, true),
                        new AttendancesModelDay(3, false, false),
                        new AttendancesModelDay(4, false, false),
                        new AttendancesModelDay(5, false, false),
                        new AttendancesModelDay(6, false, false),
                        new AttendancesModelDay(7, false, false),
                        new AttendancesModelDay(8, true, true),
                        new AttendancesModelDay(9, true, true),
                        new AttendancesModelDay(10, false, false),
                        new AttendancesModelDay(11, false, false),
                        new AttendancesModelDay(12, false, false),
                        new AttendancesModelDay(13, false, false),
                        new AttendancesModelDay(14, false, false),
                        new AttendancesModelDay(15, true, true),
                        new AttendancesModelDay(16, true, true),
                        new AttendancesModelDay(17, false, false),
                        new AttendancesModelDay(18, false, false),
                        new AttendancesModelDay(19, false, false),
                        new AttendancesModelDay(20, false, false),
                        new AttendancesModelDay(21, false, false),
                        new AttendancesModelDay(22, true, true),
                        new AttendancesModelDay(23, true, true),
                        new AttendancesModelDay(24, true, true),
                        new AttendancesModelDay(25, true, true),
                        new AttendancesModelDay(26, true, true),
                        new AttendancesModelDay(27, true, true),
                        new AttendancesModelDay(28, true, true),
                        new AttendancesModelDay(29, true, true),
                        new AttendancesModelDay(30, true, true),
                        new AttendancesModelDay(31, false, false)
                    },
                    new AttendancesModelStudent[]
                    {
                        new AttendancesModelStudent(
                            1, "Валентина Кръстева",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            2, "Веселина Янева",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            3, "Емилия Емилова",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.UnexcusedAbsence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                AttendanceType.UnexcusedAbsence
                            },
                            20
                        ),
                        new AttendancesModelStudent(
                            4, "Йорданка Лазарова",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            19
                        ),
                    },
                    new int[] { 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3},
                    73,
                    4
                ),
                new AttendancesModelMonth(
                    "януари",
                    new AttendancesModelDay[]
                    {
                        new AttendancesModelDay(1, true, true),
                        new AttendancesModelDay(2, true, true),
                        new AttendancesModelDay(3, false, false),
                        new AttendancesModelDay(4, false, false),
                        new AttendancesModelDay(5, false, false),
                        new AttendancesModelDay(6, false, false),
                        new AttendancesModelDay(7, false, false),
                        new AttendancesModelDay(8, true, true),
                        new AttendancesModelDay(9, true, true),
                        new AttendancesModelDay(10, false, false),
                        new AttendancesModelDay(11, false, false),
                        new AttendancesModelDay(12, false, false),
                        new AttendancesModelDay(13, false, false),
                        new AttendancesModelDay(14, false, false),
                        new AttendancesModelDay(15, true, true),
                        new AttendancesModelDay(16, true, true),
                        new AttendancesModelDay(17, false, false),
                        new AttendancesModelDay(18, false, false),
                        new AttendancesModelDay(19, false, false),
                        new AttendancesModelDay(20, false, false),
                        new AttendancesModelDay(21, false, false),
                        new AttendancesModelDay(22, true, true),
                        new AttendancesModelDay(23, true, true),
                        new AttendancesModelDay(24, false, false),
                        new AttendancesModelDay(25, false, false),
                        new AttendancesModelDay(26, false, false),
                        new AttendancesModelDay(27, false, false),
                        new AttendancesModelDay(28, false, false),
                        new AttendancesModelDay(29, true, true),
                        new AttendancesModelDay(30, true, true),
                        new AttendancesModelDay(31, false, false)
                    },
                    new AttendancesModelStudent[]
                    {
                        new AttendancesModelStudent(
                            1, "Валентина Кръстева",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            2, "Веселина Янева",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            3, "Емилия Емилова",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.UnexcusedAbsence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.UnexcusedAbsence
                            },
                            20
                        ),
                        new AttendancesModelStudent(
                            4, "Йорданка Лазарова",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            19
                        ),
                    },
                    new int[] { 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3},
                    82,
                    4
                ),
                new AttendancesModelMonth(
                    "февруари",
                    new AttendancesModelDay[]
                    {
                        new AttendancesModelDay(1, true, true),
                        new AttendancesModelDay(2, true, true),
                        new AttendancesModelDay(3, false, false),
                        new AttendancesModelDay(4, false, false),
                        new AttendancesModelDay(5, false, false),
                        new AttendancesModelDay(6, false, false),
                        new AttendancesModelDay(7, false, false),
                        new AttendancesModelDay(8, true, true),
                        new AttendancesModelDay(9, true, true),
                        new AttendancesModelDay(10, false, false),
                        new AttendancesModelDay(11, false, false),
                        new AttendancesModelDay(12, false, false),
                        new AttendancesModelDay(13, false, false),
                        new AttendancesModelDay(14, false, false),
                        new AttendancesModelDay(15, true, true),
                        new AttendancesModelDay(16, true, true),
                        new AttendancesModelDay(17, false, false),
                        new AttendancesModelDay(18, false, false),
                        new AttendancesModelDay(19, false, false),
                        new AttendancesModelDay(20, false, false),
                        new AttendancesModelDay(21, false, false),
                        new AttendancesModelDay(22, true, true),
                        new AttendancesModelDay(23, true, true),
                        new AttendancesModelDay(24, false, false),
                        new AttendancesModelDay(25, false, false),
                        new AttendancesModelDay(26, false, false),
                        new AttendancesModelDay(27, false, false),
                        new AttendancesModelDay(28, false, false)
                    },
                    new AttendancesModelStudent[]
                    {
                        new AttendancesModelStudent(
                            1, "Валентина Кръстева",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence
                            },
                            20
                        ),
                        new AttendancesModelStudent(
                            2, "Веселина Янева",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence
                            },
                            20
                        ),
                        new AttendancesModelStudent(
                            3, "Емилия Емилова",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.UnexcusedAbsence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence
                            },
                            18
                        ),
                        new AttendancesModelStudent(
                            4, "Йорданка Лазарова",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence
                            },
                            17
                        ),
                    },
                    new int[] { 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3 },
                    82,
                    4
                ),
                new AttendancesModelMonth(
                    "март",
                    new AttendancesModelDay[]
                    {
                        new AttendancesModelDay(1, true, true),
                        new AttendancesModelDay(2, true, true),
                        new AttendancesModelDay(3, false, false),
                        new AttendancesModelDay(4, false, false),
                        new AttendancesModelDay(5, false, false),
                        new AttendancesModelDay(6, false, false),
                        new AttendancesModelDay(7, false, false),
                        new AttendancesModelDay(8, true, true),
                        new AttendancesModelDay(9, true, true),
                        new AttendancesModelDay(10, false, false),
                        new AttendancesModelDay(11, false, false),
                        new AttendancesModelDay(12, false, false),
                        new AttendancesModelDay(13, false, false),
                        new AttendancesModelDay(14, false, false),
                        new AttendancesModelDay(15, true, true),
                        new AttendancesModelDay(16, true, true),
                        new AttendancesModelDay(17, false, false),
                        new AttendancesModelDay(18, false, false),
                        new AttendancesModelDay(19, false, false),
                        new AttendancesModelDay(20, false, false),
                        new AttendancesModelDay(21, false, false),
                        new AttendancesModelDay(22, true, true),
                        new AttendancesModelDay(23, true, true),
                        new AttendancesModelDay(24, false, false),
                        new AttendancesModelDay(25, false, false),
                        new AttendancesModelDay(26, false, false),
                        new AttendancesModelDay(27, false, false),
                        new AttendancesModelDay(28, false, false),
                        new AttendancesModelDay(29, true, true),
                        new AttendancesModelDay(30, true, true),
                        new AttendancesModelDay(31, false, false)
                    },
                    new AttendancesModelStudent[]
                    {
                        new AttendancesModelStudent(
                            1, "Валентина Кръстева",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            2, "Веселина Янева",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            3, "Емилия Емилова",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.UnexcusedAbsence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.UnexcusedAbsence
                            },
                            20
                        ),
                        new AttendancesModelStudent(
                            4, "Йорданка Лазарова",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            19
                        ),
                    },
                    new int[] { 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3},
                    82,
                    4
                ),
                new AttendancesModelMonth(
                    "април",
                    new AttendancesModelDay[]
                    {
                        new AttendancesModelDay(1, false, false),
                        new AttendancesModelDay(2, false, false),
                        new AttendancesModelDay(3, false, false),
                        new AttendancesModelDay(4, true, true),
                        new AttendancesModelDay(5, true, true),
                        new AttendancesModelDay(6, true, true),
                        new AttendancesModelDay(7, false, false),
                        new AttendancesModelDay(8, false, false),
                        new AttendancesModelDay(9, false, false),
                        new AttendancesModelDay(10, false, false),
                        new AttendancesModelDay(11, true, true),
                        new AttendancesModelDay(12, true, true),
                        new AttendancesModelDay(13, false, false),
                        new AttendancesModelDay(14, false, false),
                        new AttendancesModelDay(15, false, false),
                        new AttendancesModelDay(16, false, false),
                        new AttendancesModelDay(17, false, false),
                        new AttendancesModelDay(18, true, true),
                        new AttendancesModelDay(19, true, true),
                        new AttendancesModelDay(20, false, false),
                        new AttendancesModelDay(21, false, false),
                        new AttendancesModelDay(22, true, true),
                        new AttendancesModelDay(23, false, false),
                        new AttendancesModelDay(24, false, false),
                        new AttendancesModelDay(25, true, true),
                        new AttendancesModelDay(26, true, true),
                        new AttendancesModelDay(27, false, false),
                        new AttendancesModelDay(28, false, false),
                        new AttendancesModelDay(29, false, false),
                        new AttendancesModelDay(30, false, false)
                    },
                    new AttendancesModelStudent[]
                    {
                        new AttendancesModelStudent(
                            1, "Валентина Кръстева",
                            false,
                            new AttendanceType?[]
                            {
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.UnexcusedAbsence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence
                            },
                            20
                        ),
                        new AttendancesModelStudent(
                            2, "Веселина Янева",
                            false,
                            new AttendanceType?[]
                            {
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.UnexcusedAbsence,
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            3, "Емилия Емилова",
                            false,
                            new AttendanceType?[]
                            {
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.UnexcusedAbsence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            4, "Йорданка Лазарова",
                            false,
                            new AttendanceType?[]
                            {
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence
                            },
                            22
                        ),
                    },
                    new int[] { 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2},
                    80,
                    3
                ),
                new AttendancesModelMonth(
                    "май",
                    new AttendancesModelDay[]
                    {
                        new AttendancesModelDay(1, true, true),
                        new AttendancesModelDay(2, true, true),
                        new AttendancesModelDay(3, false, false),
                        new AttendancesModelDay(4, false, false),
                        new AttendancesModelDay(5, false, false),
                        new AttendancesModelDay(6, false, false),
                        new AttendancesModelDay(7, false, false),
                        new AttendancesModelDay(8, true, true),
                        new AttendancesModelDay(9, true, true),
                        new AttendancesModelDay(10, false, false),
                        new AttendancesModelDay(11, false, false),
                        new AttendancesModelDay(12, false, false),
                        new AttendancesModelDay(13, false, false),
                        new AttendancesModelDay(14, false, false),
                        new AttendancesModelDay(15, true, true),
                        new AttendancesModelDay(16, true, true),
                        new AttendancesModelDay(17, false, false),
                        new AttendancesModelDay(18, false, false),
                        new AttendancesModelDay(19, false, false),
                        new AttendancesModelDay(20, false, false),
                        new AttendancesModelDay(21, false, false),
                        new AttendancesModelDay(22, true, true),
                        new AttendancesModelDay(23, true, true),
                        new AttendancesModelDay(24, false, false),
                        new AttendancesModelDay(25, false, false),
                        new AttendancesModelDay(26, false, false),
                        new AttendancesModelDay(27, false, false),
                        new AttendancesModelDay(28, false, false),
                        new AttendancesModelDay(29, true, true),
                        new AttendancesModelDay(30, true, true),
                        new AttendancesModelDay(31, false, false)
                    },
                    new AttendancesModelStudent[]
                    {
                        new AttendancesModelStudent(
                            1, "Валентина Кръстева",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            2, "Веселина Янева",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            22
                        ),
                        new AttendancesModelStudent(
                            3, "Емилия Емилова",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.UnexcusedAbsence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.UnexcusedAbsence
                            },
                            20
                        ),
                        new AttendancesModelStudent(
                            4, "Йорданка Лазарова",
                            false,
                            new AttendanceType?[]
                            {
                                null,
                                null,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.ExcusedAbsence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                AttendanceType.Presence,
                                null,
                                null,
                                AttendanceType.Presence
                            },
                            19
                        ),
                    },
                    new int[] { 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3},
                    82,
                    4
                )
            }
        );
}
