namespace SB.Domain;

public static class StudentAttendancesModelSample
{
    public static readonly StudentAttendancesModel Sample =
        new(
            new StudentAttendancesModelMonth[]
            {
                new StudentAttendancesModelMonth(
                    "септември",
                    new StudentAttendancesModelDay[]
                    {
                        new StudentAttendancesModelDay(1, false, false),
                        new StudentAttendancesModelDay(2, false, false),
                        new StudentAttendancesModelDay(3, false, false),
                        new StudentAttendancesModelDay(4, true, true),
                        new StudentAttendancesModelDay(5, true, true),
                        new StudentAttendancesModelDay(6, true, true),
                        new StudentAttendancesModelDay(7, false, false),
                        new StudentAttendancesModelDay(8, false, false),
                        new StudentAttendancesModelDay(9, false, false),
                        new StudentAttendancesModelDay(10, false, false),
                        new StudentAttendancesModelDay(11, true, true),
                        new StudentAttendancesModelDay(12, true, true),
                        new StudentAttendancesModelDay(13, false, false),
                        new StudentAttendancesModelDay(14, false, false),
                        new StudentAttendancesModelDay(15, false, false),
                        new StudentAttendancesModelDay(16, false, false),
                        new StudentAttendancesModelDay(17, false, false),
                        new StudentAttendancesModelDay(18, true, true),
                        new StudentAttendancesModelDay(19, true, true),
                        new StudentAttendancesModelDay(20, false, false),
                        new StudentAttendancesModelDay(21, false, false),
                        new StudentAttendancesModelDay(22, true, true),
                        new StudentAttendancesModelDay(23, false, false),
                        new StudentAttendancesModelDay(24, false, false),
                        new StudentAttendancesModelDay(25, true, true),
                        new StudentAttendancesModelDay(26, true, true),
                        new StudentAttendancesModelDay(27, false, false),
                        new StudentAttendancesModelDay(28, false, false),
                        new StudentAttendancesModelDay(29, false, false),
                        new StudentAttendancesModelDay(30, false, false)
                    },
                    new StudentAttendancesModelAttendance(
                        new AttendanceType?[]
                        {
                            AttendanceType.ExcusedAbsence,
                            AttendanceType.UnexcusedAbsence,
                            AttendanceType.Presence,
                            null,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence
                        },
                        20
                    )
                ),
                new StudentAttendancesModelMonth(
                    "октомври",
                    new StudentAttendancesModelDay[]
                    {
                        new StudentAttendancesModelDay(1, true, true),
                        new StudentAttendancesModelDay(2, true, true),
                        new StudentAttendancesModelDay(3, false, false),
                        new StudentAttendancesModelDay(4, false, false),
                        new StudentAttendancesModelDay(5, false, false),
                        new StudentAttendancesModelDay(6, false, false),
                        new StudentAttendancesModelDay(7, false, false),
                        new StudentAttendancesModelDay(8, true, true),
                        new StudentAttendancesModelDay(9, true, true),
                        new StudentAttendancesModelDay(10, false, false),
                        new StudentAttendancesModelDay(11, false, false),
                        new StudentAttendancesModelDay(12, false, false),
                        new StudentAttendancesModelDay(13, false, false),
                        new StudentAttendancesModelDay(14, false, false),
                        new StudentAttendancesModelDay(15, true, true),
                        new StudentAttendancesModelDay(16, true, true),
                        new StudentAttendancesModelDay(17, false, false),
                        new StudentAttendancesModelDay(18, false, false),
                        new StudentAttendancesModelDay(19, false, false),
                        new StudentAttendancesModelDay(20, false, false),
                        new StudentAttendancesModelDay(21, false, false),
                        new StudentAttendancesModelDay(22, true, true),
                        new StudentAttendancesModelDay(23, true, true),
                        new StudentAttendancesModelDay(24, false, false),
                        new StudentAttendancesModelDay(25, false, false),
                        new StudentAttendancesModelDay(26, false, false),
                        new StudentAttendancesModelDay(27, false, false),
                        new StudentAttendancesModelDay(28, false, false),
                        new StudentAttendancesModelDay(29, true, true),
                        new StudentAttendancesModelDay(30, true, true),
                        new StudentAttendancesModelDay(31, false, false)
                    },
                    new StudentAttendancesModelAttendance(
                        new AttendanceType?[]
                        {
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence
                        },
                        22
                    )
                ),
                new StudentAttendancesModelMonth(
                    "ноември",
                    new StudentAttendancesModelDay[]
                    {
                        new StudentAttendancesModelDay(1, false, false),
                        new StudentAttendancesModelDay(2, false, false),
                        new StudentAttendancesModelDay(3, false, false),
                        new StudentAttendancesModelDay(4, true, true),
                        new StudentAttendancesModelDay(5, true, true),
                        new StudentAttendancesModelDay(6, true, true),
                        new StudentAttendancesModelDay(7, false, false),
                        new StudentAttendancesModelDay(8, false, false),
                        new StudentAttendancesModelDay(9, false, false),
                        new StudentAttendancesModelDay(10, false, false),
                        new StudentAttendancesModelDay(11, true, true),
                        new StudentAttendancesModelDay(12, true, true),
                        new StudentAttendancesModelDay(13, false, false),
                        new StudentAttendancesModelDay(14, false, false),
                        new StudentAttendancesModelDay(15, false, false),
                        new StudentAttendancesModelDay(16, false, false),
                        new StudentAttendancesModelDay(17, false, false),
                        new StudentAttendancesModelDay(18, true, true),
                        new StudentAttendancesModelDay(19, true, true),
                        new StudentAttendancesModelDay(20, false, false),
                        new StudentAttendancesModelDay(21, false, false),
                        new StudentAttendancesModelDay(22, true, true),
                        new StudentAttendancesModelDay(23, false, false),
                        new StudentAttendancesModelDay(24, false, false),
                        new StudentAttendancesModelDay(25, true, true),
                        new StudentAttendancesModelDay(26, true, true),
                        new StudentAttendancesModelDay(27, false, false),
                        new StudentAttendancesModelDay(28, false, false),
                        new StudentAttendancesModelDay(29, false, false),
                        new StudentAttendancesModelDay(30, false, false)
                    },
                    new StudentAttendancesModelAttendance(
                        new AttendanceType?[]
                        {
                            AttendanceType.ExcusedAbsence,
                            AttendanceType.UnexcusedAbsence,
                            AttendanceType.Presence,
                            null,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence
                        },
                        20
                    )
                ),
                new StudentAttendancesModelMonth(
                    "декември",
                    new StudentAttendancesModelDay[]
                    {
                        new StudentAttendancesModelDay(1, true, true),
                        new StudentAttendancesModelDay(2, true, true),
                        new StudentAttendancesModelDay(3, false, false),
                        new StudentAttendancesModelDay(4, false, false),
                        new StudentAttendancesModelDay(5, false, false),
                        new StudentAttendancesModelDay(6, false, false),
                        new StudentAttendancesModelDay(7, false, false),
                        new StudentAttendancesModelDay(8, true, true),
                        new StudentAttendancesModelDay(9, true, true),
                        new StudentAttendancesModelDay(10, false, false),
                        new StudentAttendancesModelDay(11, false, false),
                        new StudentAttendancesModelDay(12, false, false),
                        new StudentAttendancesModelDay(13, false, false),
                        new StudentAttendancesModelDay(14, false, false),
                        new StudentAttendancesModelDay(15, true, true),
                        new StudentAttendancesModelDay(16, true, true),
                        new StudentAttendancesModelDay(17, false, false),
                        new StudentAttendancesModelDay(18, false, false),
                        new StudentAttendancesModelDay(19, false, false),
                        new StudentAttendancesModelDay(20, false, false),
                        new StudentAttendancesModelDay(21, false, false),
                        new StudentAttendancesModelDay(22, true, true),
                        new StudentAttendancesModelDay(23, true, true),
                        new StudentAttendancesModelDay(24, true, true),
                        new StudentAttendancesModelDay(25, true, true),
                        new StudentAttendancesModelDay(26, true, true),
                        new StudentAttendancesModelDay(27, true, true),
                        new StudentAttendancesModelDay(28, true, true),
                        new StudentAttendancesModelDay(29, true, true),
                        new StudentAttendancesModelDay(30, true, true),
                        new StudentAttendancesModelDay(31, false, false)
                    },
                    new StudentAttendancesModelAttendance(
                        new AttendanceType?[]
                        {
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            null,
                            null,
                            null,
                            null,
                            null,
                            null,
                            null,
                            AttendanceType.Presence
                        },
                        22
                    )
                ),
                new StudentAttendancesModelMonth(
                    "януари",
                    new StudentAttendancesModelDay[]
                    {
                        new StudentAttendancesModelDay(1, true, true),
                        new StudentAttendancesModelDay(2, true, true),
                        new StudentAttendancesModelDay(3, false, false),
                        new StudentAttendancesModelDay(4, false, false),
                        new StudentAttendancesModelDay(5, false, false),
                        new StudentAttendancesModelDay(6, false, false),
                        new StudentAttendancesModelDay(7, false, false),
                        new StudentAttendancesModelDay(8, true, true),
                        new StudentAttendancesModelDay(9, true, true),
                        new StudentAttendancesModelDay(10, false, false),
                        new StudentAttendancesModelDay(11, false, false),
                        new StudentAttendancesModelDay(12, false, false),
                        new StudentAttendancesModelDay(13, false, false),
                        new StudentAttendancesModelDay(14, false, false),
                        new StudentAttendancesModelDay(15, true, true),
                        new StudentAttendancesModelDay(16, true, true),
                        new StudentAttendancesModelDay(17, false, false),
                        new StudentAttendancesModelDay(18, false, false),
                        new StudentAttendancesModelDay(19, false, false),
                        new StudentAttendancesModelDay(20, false, false),
                        new StudentAttendancesModelDay(21, false, false),
                        new StudentAttendancesModelDay(22, true, true),
                        new StudentAttendancesModelDay(23, true, true),
                        new StudentAttendancesModelDay(24, false, false),
                        new StudentAttendancesModelDay(25, false, false),
                        new StudentAttendancesModelDay(26, false, false),
                        new StudentAttendancesModelDay(27, false, false),
                        new StudentAttendancesModelDay(28, false, false),
                        new StudentAttendancesModelDay(29, true, true),
                        new StudentAttendancesModelDay(30, true, true),
                        new StudentAttendancesModelDay(31, false, false)
                    },
                    new StudentAttendancesModelAttendance(
                        new AttendanceType?[]
                        {
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence
                        },
                        22
                    )
                ),
                new StudentAttendancesModelMonth(
                    "февруари",
                    new StudentAttendancesModelDay[]
                    {
                        new StudentAttendancesModelDay(1, true, true),
                        new StudentAttendancesModelDay(2, true, true),
                        new StudentAttendancesModelDay(3, false, false),
                        new StudentAttendancesModelDay(4, false, false),
                        new StudentAttendancesModelDay(5, false, false),
                        new StudentAttendancesModelDay(6, false, false),
                        new StudentAttendancesModelDay(7, false, false),
                        new StudentAttendancesModelDay(8, true, true),
                        new StudentAttendancesModelDay(9, true, true),
                        new StudentAttendancesModelDay(10, false, false),
                        new StudentAttendancesModelDay(11, false, false),
                        new StudentAttendancesModelDay(12, false, false),
                        new StudentAttendancesModelDay(13, false, false),
                        new StudentAttendancesModelDay(14, false, false),
                        new StudentAttendancesModelDay(15, true, true),
                        new StudentAttendancesModelDay(16, true, true),
                        new StudentAttendancesModelDay(17, false, false),
                        new StudentAttendancesModelDay(18, false, false),
                        new StudentAttendancesModelDay(19, false, false),
                        new StudentAttendancesModelDay(20, false, false),
                        new StudentAttendancesModelDay(21, false, false),
                        new StudentAttendancesModelDay(22, true, true),
                        new StudentAttendancesModelDay(23, true, true),
                        new StudentAttendancesModelDay(24, false, false),
                        new StudentAttendancesModelDay(25, false, false),
                        new StudentAttendancesModelDay(26, false, false),
                        new StudentAttendancesModelDay(27, false, false),
                        new StudentAttendancesModelDay(28, false, false)
                    },
                    new StudentAttendancesModelAttendance(
                        new AttendanceType?[]
                        {
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence
                        },
                        20
                    )
                ),
                new StudentAttendancesModelMonth(
                    "март",
                    new StudentAttendancesModelDay[]
                    {
                        new StudentAttendancesModelDay(1, true, true),
                        new StudentAttendancesModelDay(2, true, true),
                        new StudentAttendancesModelDay(3, false, false),
                        new StudentAttendancesModelDay(4, false, false),
                        new StudentAttendancesModelDay(5, false, false),
                        new StudentAttendancesModelDay(6, false, false),
                        new StudentAttendancesModelDay(7, false, false),
                        new StudentAttendancesModelDay(8, true, true),
                        new StudentAttendancesModelDay(9, true, true),
                        new StudentAttendancesModelDay(10, false, false),
                        new StudentAttendancesModelDay(11, false, false),
                        new StudentAttendancesModelDay(12, false, false),
                        new StudentAttendancesModelDay(13, false, false),
                        new StudentAttendancesModelDay(14, false, false),
                        new StudentAttendancesModelDay(15, true, true),
                        new StudentAttendancesModelDay(16, true, true),
                        new StudentAttendancesModelDay(17, false, false),
                        new StudentAttendancesModelDay(18, false, false),
                        new StudentAttendancesModelDay(19, false, false),
                        new StudentAttendancesModelDay(20, false, false),
                        new StudentAttendancesModelDay(21, false, false),
                        new StudentAttendancesModelDay(22, true, true),
                        new StudentAttendancesModelDay(23, true, true),
                        new StudentAttendancesModelDay(24, false, false),
                        new StudentAttendancesModelDay(25, false, false),
                        new StudentAttendancesModelDay(26, false, false),
                        new StudentAttendancesModelDay(27, false, false),
                        new StudentAttendancesModelDay(28, false, false),
                        new StudentAttendancesModelDay(29, true, true),
                        new StudentAttendancesModelDay(30, true, true),
                        new StudentAttendancesModelDay(31, false, false)
                    },
                    new StudentAttendancesModelAttendance(
                        new AttendanceType?[]
                        {
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence
                        },
                        22
                    )
                ),
                new StudentAttendancesModelMonth(
                    "април",
                    new StudentAttendancesModelDay[]
                    {
                        new StudentAttendancesModelDay(1, false, false),
                        new StudentAttendancesModelDay(2, false, false),
                        new StudentAttendancesModelDay(3, false, false),
                        new StudentAttendancesModelDay(4, true, true),
                        new StudentAttendancesModelDay(5, true, true),
                        new StudentAttendancesModelDay(6, true, true),
                        new StudentAttendancesModelDay(7, false, false),
                        new StudentAttendancesModelDay(8, false, false),
                        new StudentAttendancesModelDay(9, false, false),
                        new StudentAttendancesModelDay(10, false, false),
                        new StudentAttendancesModelDay(11, true, true),
                        new StudentAttendancesModelDay(12, true, true),
                        new StudentAttendancesModelDay(13, false, false),
                        new StudentAttendancesModelDay(14, false, false),
                        new StudentAttendancesModelDay(15, false, false),
                        new StudentAttendancesModelDay(16, false, false),
                        new StudentAttendancesModelDay(17, false, false),
                        new StudentAttendancesModelDay(18, true, true),
                        new StudentAttendancesModelDay(19, true, true),
                        new StudentAttendancesModelDay(20, false, false),
                        new StudentAttendancesModelDay(21, false, false),
                        new StudentAttendancesModelDay(22, true, true),
                        new StudentAttendancesModelDay(23, false, false),
                        new StudentAttendancesModelDay(24, false, false),
                        new StudentAttendancesModelDay(25, true, true),
                        new StudentAttendancesModelDay(26, true, true),
                        new StudentAttendancesModelDay(27, false, false),
                        new StudentAttendancesModelDay(28, false, false),
                        new StudentAttendancesModelDay(29, false, false),
                        new StudentAttendancesModelDay(30, false, false)
                    },
                    new StudentAttendancesModelAttendance(
                        new AttendanceType?[]
                        {
                            AttendanceType.ExcusedAbsence,
                            AttendanceType.UnexcusedAbsence,
                            AttendanceType.Presence,
                            null,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence
                        },
                        20
                    )
                ),
                new StudentAttendancesModelMonth(
                    "май",
                    new StudentAttendancesModelDay[]
                    {
                        new StudentAttendancesModelDay(1, true, true),
                        new StudentAttendancesModelDay(2, true, true),
                        new StudentAttendancesModelDay(3, false, false),
                        new StudentAttendancesModelDay(4, false, false),
                        new StudentAttendancesModelDay(5, false, false),
                        new StudentAttendancesModelDay(6, false, false),
                        new StudentAttendancesModelDay(7, false, false),
                        new StudentAttendancesModelDay(8, true, true),
                        new StudentAttendancesModelDay(9, true, true),
                        new StudentAttendancesModelDay(10, false, false),
                        new StudentAttendancesModelDay(11, false, false),
                        new StudentAttendancesModelDay(12, false, false),
                        new StudentAttendancesModelDay(13, false, false),
                        new StudentAttendancesModelDay(14, false, false),
                        new StudentAttendancesModelDay(15, true, true),
                        new StudentAttendancesModelDay(16, true, true),
                        new StudentAttendancesModelDay(17, false, false),
                        new StudentAttendancesModelDay(18, false, false),
                        new StudentAttendancesModelDay(19, false, false),
                        new StudentAttendancesModelDay(20, false, false),
                        new StudentAttendancesModelDay(21, false, false),
                        new StudentAttendancesModelDay(22, true, true),
                        new StudentAttendancesModelDay(23, true, true),
                        new StudentAttendancesModelDay(24, false, false),
                        new StudentAttendancesModelDay(25, false, false),
                        new StudentAttendancesModelDay(26, false, false),
                        new StudentAttendancesModelDay(27, false, false),
                        new StudentAttendancesModelDay(28, false, false),
                        new StudentAttendancesModelDay(29, true, true),
                        new StudentAttendancesModelDay(30, true, true),
                        new StudentAttendancesModelDay(31, false, false)
                    },
                    new StudentAttendancesModelAttendance(
                        new AttendanceType?[]
                        {
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            AttendanceType.Presence,
                            null,
                            null,
                            AttendanceType.Presence
                        },
                        22
                    )
                )
            }
        );
}
