import { Injectable, Logger, OnApplicationBootstrap } from '@nestjs/common';
import { CONSTANTS } from 'src/common/constants/constants';
import { VariablesRepository } from '../variables.repository';

@Injectable()
export class VariablesService implements OnApplicationBootstrap {
    private logger = new Logger(VariablesService.name);

    static CRON_JOB_TOP_VALUE: string;

    static CRON_JOB_TOP_ORGANIZATIONS_CREATE_VALUE: string;

    static CRON_JOB_TOP_ORGANIZATIONS_UPDATE_VALUE: string;

    static CRON_JOB_TOP_ORGANIZATIONS_DELETE_VALUE: string;

    static CRON_JOB_TOP_ENROLLMENTS_STUDENT_TO_CLASS_CREATE_VALUE: string;

    static CRON_JOB_TOP_ENROLLMENTS_STUDENT_TO_CLASS_DELETE_VALUE: string;

    static CRON_JOB_TOP_ENROLLMENTS_TEACHER_TO_CLASS_CREATE_VALUE: string;

    static CRON_JOB_TOP_ENROLLMENTS_TEACHER_TO_CLASS_DELETE_VALUE: string;

    static CRON_JOB_TOP_ENROLLMENTS_STUDENT_TO_SCHOOL_CREATE_VALUE: string;

    static CRON_JOB_TOP_ENROLLMENTS_STUDENT_TO_SCHOOL_DELETE_VALUE: string;

    static CRON_JOB_TOP_ENROLLMENTS_TEACHER_TO_SCHOOL_CREATE_VALUE: string;

    static CRON_JOB_TOP_ENROLLMENTS_TEACHER_TO_SCHOOL_DELETE_VALUE: string;

    static CRON_JOB_TOP_USERS_CREATE_VALUE: string;

    static CRON_JOB_TOP_USERS_UPDATE_VALUE: string;

    static CRON_JOB_TOP_USERS_DELETE_VALUE: string;

    static CRON_JOB_TOP_CLASSES_CREATE_VALUE: string;

    static CRON_JOB_TOP_CLASSES_UPDATE_VALUE: string;

    static CRON_JOB_TOP_CLASSES_DELETE_VALUE: string;

    constructor(private variablesRepository: VariablesRepository) {}

    onApplicationBootstrap() {
        this.loadVariables();
    }

    async loadVariables() {
        const jobVariables = await this.variablesRepository.getAllVariables();
        const map = new Map(jobVariables.map((element) => [element.name, element.value]));
        VariablesService.CRON_JOB_TOP_VALUE =
            map.get(CONSTANTS.JOBS_VARIABLES_TOP) || CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_ENROLLMENTS_STUDENT_TO_CLASS_CREATE_VALUE =
            map.get(CONSTANTS.JOBS_ENROLLMENTS_STUDENT_TO_CLASS_CREATE_DEFAULT_TOP_NAME) ||
            CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_ENROLLMENTS_STUDENT_TO_CLASS_DELETE_VALUE =
            map.get(CONSTANTS.JOBS_ENROLLMENTS_STUDENT_TO_CLASS_DELETE_DEFAULT_TOP_NAME) ||
            CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_ENROLLMENTS_TEACHER_TO_CLASS_CREATE_VALUE =
            map.get(CONSTANTS.JOBS_ENROLLMENTS_TEACHER_TO_CLASS_CREATE_DEFAULT_TOP_NAME) ||
            CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_ENROLLMENTS_TEACHER_TO_CLASS_DELETE_VALUE =
            map.get(CONSTANTS.JOBS_ENROLLMENTS_TEACHER_TO_CLASS_DELETE_DEFAULT_TOP_NAME) ||
            CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_ENROLLMENTS_STUDENT_TO_SCHOOL_CREATE_VALUE =
            map.get(CONSTANTS.JOBS_ENROLLMENTS_STUDENT_TO_SCHOOL_CREATE_DEFAULT_TOP_NAME) ||
            CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_ENROLLMENTS_STUDENT_TO_SCHOOL_DELETE_VALUE =
            map.get(CONSTANTS.JOBS_ENROLLMENTS_STUDENT_TO_SCHOOL_DELETE_DEFAULT_TOP_NAME) ||
            CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_ENROLLMENTS_TEACHER_TO_SCHOOL_CREATE_VALUE =
            map.get(CONSTANTS.JOBS_ENROLLMENTS_TEACHER_TO_SCHOOL_CREATE_DEFAULT_TOP_NAME) ||
            CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_ENROLLMENTS_TEACHER_TO_SCHOOL_DELETE_VALUE =
            map.get(CONSTANTS.JOBS_ENROLLMENTS_TEACHER_TO_SCHOOL_DELETE_DEFAULT_TOP_NAME) ||
            CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_USERS_CREATE_VALUE =
            map.get(CONSTANTS.JOBS_USERS_CREATE_DEFAULT_TOP_NAME) || CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_USERS_UPDATE_VALUE =
            map.get(CONSTANTS.JOBS_USERS_UPDATE_DEFAULT_TOP_NAME) || CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_USERS_DELETE_VALUE =
            map.get(CONSTANTS.JOBS_USERS_DELETE_DEFAULT_TOP_NAME) || CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_CLASSES_CREATE_VALUE =
            map.get(CONSTANTS.JOBS_CLASSES_CREATE_DEFAULT_TOP_NAME) || CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_CLASSES_UPDATE_VALUE =
            map.get(CONSTANTS.JOBS_CLASSES_UPDATE_DEFAULT_TOP_NAME) || CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_CLASSES_DELETE_VALUE =
            map.get(CONSTANTS.JOBS_CLASSES_DELETE_DEFAULT_TOP_NAME) || CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_ORGANIZATIONS_CREATE_VALUE =
            map.get(CONSTANTS.JOBS_ORGANIZATIONS_CREATE_DEFAULT_TOP_NAME) || CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_ORGANIZATIONS_UPDATE_VALUE =
            map.get(CONSTANTS.JOBS_ORGANIZATIONS_UPDATE_DEFAULT_TOP_NAME) || CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
        VariablesService.CRON_JOB_TOP_ORGANIZATIONS_DELETE_VALUE =
            map.get(CONSTANTS.JOBS_ORGANIZATIONS_DELETE_DEFAULT_TOP_NAME) || CONSTANTS.JOBS_VARIABLES_DEFAULT_TOP;
    }
}
