export enum RoleEnum {
  INSTITUTION = 0,
  MON_ADMIN = 1,
  RUO = 2,
  MUNICIPALITY = 3,
  BUDGETING_INSTITUTION = 4,
  TEACHER = 5,
  STUDENT = 6,
  PARENT = 7,
  CLASS_TEACHER = 8,
  RUO_EXPERT = 9,
  CIOO = 10,
  EXTERNAL_INSTITUTIONS_EXPERT = 11,
  MON_EXPERT = 12,
  MON_USER_ADMIN = 13,
  TECHNICAL_INSTITUTION = 14,
  MON_OBGUM = 15,
  MON_OBGUM_FINANCES = 16,
  MON_CHRAO = 17,
  CONSORTIUM_HELPDESK = 18,
  NIO = 19,
  ACCOUNTANT = 20
}

export const RoleEnumTranslation: { [key in RoleEnum]: string } = {
  0: 'Институция',
  1: 'МОН - Администратор',
  2: 'РУО - Експерт ИО/АИ',
  3: 'Община',
  4: 'Финансираща институция',
  5: 'Учител',
  6: 'Ученик',
  7: 'Родител',
  8: 'Класен Ръководител',
  9: 'РУО - Експерт',
  10: 'ЦИОO',
  11: 'Експерти от външни институции',
  12: 'МОН - експерт',
  13: 'МОН - Администратор потребители',
  14: 'Институция (IT Администратор)',
  15: 'МОН – д. ОБГУМ',
  16: 'МОН – д. ОБГУМи д. "Финанси"',
  17: 'МОН – д. ЧРАО',
  18: 'Консорциум - Helpdesk',
  19: 'НИО',
  20: 'Счетоводител'
};
