// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Helpdesk.DataAccess
{
    public partial class HelpdeskContext : DbContext
    {
        public HelpdeskContext()
        {
        }

        public HelpdeskContext(DbContextOptions<HelpdeskContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AuditModule> AuditModules { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<ClassGroup> ClassGroups { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CurrentYear> CurrentYears { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<EducationalState> EducationalStates { get; set; }
        public virtual DbSet<Faquestion> Faquestions { get; set; }
        public virtual DbSet<HelpdeskSetting> HelpdeskSettings { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<InstitutionDepartment> InstitutionDepartments { get; set; }
        public virtual DbSet<InstitutionDetail> InstitutionDetails { get; set; }
        public virtual DbSet<InstitutionSchoolYear> InstitutionSchoolYears { get; set; }
        public virtual DbSet<Issue> Issues { get; set; }
        public virtual DbSet<IssueAttachment> IssueAttachments { get; set; }
        public virtual DbSet<IssueComment> IssueComments { get; set; }
        public virtual DbSet<IssueCommentAttachment> IssueCommentAttachments { get; set; }
        public virtual DbSet<IssueReadActivity> IssueReadActivities { get; set; }
        public virtual DbSet<IssueStatusHistory> IssueStatusHistories { get; set; }
        public virtual DbSet<LocalArea> LocalAreas { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Municipality> Municipalities { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RelativeChild> RelativeChildren { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<SysRole> SysRoles { get; set; }
        public virtual DbSet<SysUser> SysUsers { get; set; }
        public virtual DbSet<SysUserSysRole> SysUserSysRoles { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<Uierror> Uierrors { get; set; }
        public virtual DbSet<VCategoryStat> VCategoryStats { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("core");

            modelBuilder.Entity<AuditModule>(entity =>
            {
                entity.ToTable("AuditModule", "logs");

                entity.Property(e => e.AuditModuleId).ValueGeneratedNever();

                entity.Property(e => e.Name).IsRequired();
            });

            modelBuilder.Entity<Category>(entity =>
            {
                entity.ToTable("Category", "helpdesk");

                entity.HasIndex(e => e.ParentId, "IX_Helpdesk_Category_ParentId");

                entity.Property(e => e.Description).HasMaxLength(2048);

                entity.Property(e => e.ForRoles).HasMaxLength(100);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.NotificationEmail).HasMaxLength(255);

                entity.Property(e => e.ValidFrom).HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.AutoAssignToSysUser)
                    .WithMany(p => p.Categories)
                    .HasForeignKey(d => d.AutoAssignToSysUserId)
                    .HasConstraintName("FK_Category_SysUserId");

                entity.HasOne(d => d.Parent)
                    .WithMany(p => p.InverseParent)
                    .HasForeignKey(d => d.ParentId)
                    .HasConstraintName("FK_Helpdesk_Category_Self");
            });

            modelBuilder.Entity<Certificate>(entity =>
            {
                entity.ToTable("Certificate");

                entity.Property(e => e.Contents).IsRequired();

                entity.Property(e => e.CreatedBySysUserId).HasColumnName("CreatedBySysUserID");

                entity.Property(e => e.Description).HasMaxLength(2048);

                entity.Property(e => e.Issuer)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.Name).IsRequired();

                entity.Property(e => e.SerialNumber)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.Subject)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.Thumbprint)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.HasOne(d => d.CreatedBySysUser)
                    .WithMany(p => p.CertificateCreatedBySysUsers)
                    .HasForeignKey(d => d.CreatedBySysUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Certificate_Creator_SysUser");

                entity.HasOne(d => d.ModifiedBySysUser)
                    .WithMany(p => p.CertificateModifiedBySysUsers)
                    .HasForeignKey(d => d.ModifiedBySysUserId)
                    .HasConstraintName("FK_Certificate_Updater_SysUser");
            });

            modelBuilder.Entity<ClassGroup>(entity =>
            {
                entity.HasKey(e => e.ClassId);

                entity.ToTable("ClassGroup", "inst_year");

                entity.HasComment("Паралелки/Групи");

                entity.HasIndex(e => e.ClassSpecialityId, "IX_ClassGroup_ClassSpecialityId");

                entity.HasIndex(e => e.InstitutionDepartmentId, "IX_ClassGroup_InstitutionDepartmentId");

                entity.HasIndex(e => new { e.InstitutionId, e.SchoolYear }, "IX_ClassGroup_InstitutionId");

                entity.HasIndex(e => e.ParentClassId, "IX_ClassGroup_ParentClassId");

                entity.Property(e => e.ClassId)
                    .HasColumnName("ClassID")
                    .HasComment("Уникален идентификатор на запи");

                entity.Property(e => e.AreaId)
                    .HasColumnName("AreaID")
                    .HasComment("Профил (отнася се за групите в");

                entity.Property(e => e.BasicClassId)
                    .HasColumnName("BasicClassID")
                    .HasComment("Идентификатор на випуска (възр");

                entity.Property(e => e.BudgetingClassTypeId)
                    .HasColumnName("BudgetingClassTypeID")
                    .HasComment("От кого се финансира");

                entity.Property(e => e.ClassEduDurationId)
                    .HasColumnName("ClassEduDurationID")
                    .HasComment("Срок на обучение на паралелкат");

                entity.Property(e => e.ClassEduFormId)
                    .HasColumnName("ClassEduFormID")
                    .HasComment("Форма на обучение на паралелка");

                entity.Property(e => e.ClassGroupNum).HasComment("Пореден номер на групата");

                entity.Property(e => e.ClassName)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasComment("Наименование на паралелката/гр");

                entity.Property(e => e.ClassShiftId)
                    .HasColumnName("ClassShiftID")
                    .HasComment("форма на организация на учебни");

                entity.Property(e => e.ClassSpecialityId)
                    .HasColumnName("ClassSpecialityID")
                    .HasComment("Специалност");

                entity.Property(e => e.ClassTypeId)
                    .HasColumnName("ClassTypeID")
                    .HasComment("Вид на паралелката/групата");

                entity.Property(e => e.EntranceLevelId)
                    .HasColumnName("EntranceLevelID")
                    .HasComment("Прием след:");

                entity.Property(e => e.ExternalId)
                    .HasMaxLength(100)
                    .HasColumnName("ExternalID");

                entity.Property(e => e.Flid)
                    .HasColumnName("FLID")
                    .HasComment("Чужд език");

                entity.Property(e => e.FltypeId)
                    .HasColumnName("FLTypeID")
                    .HasComment("Начин на изучаване на чуждия е");

                entity.Property(e => e.InstitutionDepartmentId)
                    .HasColumnName("InstitutionDepartmentID")
                    .HasComment("Уникален идентификатор на адре");

                entity.Property(e => e.InstitutionId)
                    .HasColumnName("InstitutionID")
                    .HasComment("Код на институцията");

                entity.Property(e => e.IsCombined)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"Слята паралелка\"");

                entity.Property(e => e.IsNoList)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"Не се прилага списък н");

                entity.Property(e => e.IsNotPresentForm)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"За неприсъствени форми");

                entity.Property(e => e.IsProfModule).HasComment("Маркер \"Професионално обучение");

                entity.Property(e => e.IsSpecNeed)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"Специална паралелка/гр");

                entity.Property(e => e.IsValid)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.IsWholeClass)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"Цяла паралелка/група\"");

                entity.Property(e => e.Notes)
                    .HasMaxLength(1024)
                    .HasComment("Бележки");

                entity.Property(e => e.ParalellClassName)
                    .HasMaxLength(255)
                    .HasComment("Име на паралелката/групата (на");

                entity.Property(e => e.ParentClassId)
                    .HasColumnName("ParentClassID")
                    .HasComment("Уникален идентификатор на базо");

                entity.Property(e => e.SchoolYear).HasComment("Учебна година");

                entity.Property(e => e.StudentCountPlaces).HasComment("Брой места");

                entity.Property(e => e.SysUserId)
                    .HasColumnName("SysUserID")
                    .HasComment("Потребител");

                entity.Property(e => e.TmpClassId)
                    .HasColumnName("tmp_ClassID")
                    .HasComment("Временно поле, използва се при");

                entity.Property(e => e.ValidFrom)
                    .HasDefaultValueSql("(sysutcdatetime())")
                    .HasComment("Дата, от която е валидна стойн");

                entity.Property(e => e.ValidTo)
                    .HasDefaultValueSql("(CONVERT([datetime2],'9999-12-31 23:59:59.9999999'))")
                    .HasComment("Дата, до която е валидна стойн");

                entity.HasOne(d => d.InstitutionDepartment)
                    .WithMany(p => p.ClassGroups)
                    .HasForeignKey(d => d.InstitutionDepartmentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ClassGroupInstitutionDepartment");

                entity.HasOne(d => d.ParentClass)
                    .WithMany(p => p.InverseParentClass)
                    .HasForeignKey(d => d.ParentClassId)
                    .HasConstraintName("FK_ClassGroupParentClass");

                entity.HasOne(d => d.SchoolYearNavigation)
                    .WithMany(p => p.ClassGroups)
                    .HasForeignKey(d => d.SchoolYear)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ClassGroupCurrentYear");

                entity.HasOne(d => d.SysUser)
                    .WithMany(p => p.ClassGroups)
                    .HasForeignKey(d => d.SysUserId)
                    .HasConstraintName("FK_ClassGroupSysUser");

                entity.HasOne(d => d.InstitutionSchoolYear)
                    .WithMany(p => p.ClassGroups)
                    .HasForeignKey(d => new { d.InstitutionId, d.SchoolYear })
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ClassGroupInstitution");
            });

            modelBuilder.Entity<Country>(entity =>
            {
                entity.ToTable("Country", "location");

                entity.Property(e => e.CountryId)
                    .ValueGeneratedNever()
                    .HasColumnName("CountryID");

                entity.Property(e => e.Code)
                    .IsRequired()
                    .HasMaxLength(1024);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(1024);
            });

            modelBuilder.Entity<CurrentYear>(entity =>
            {
                entity.ToTable("CurrentYear", "inst_basic");

                entity.HasIndex(e => e.TempCurrentYearId, "AK_CurrentYear_TempCurrentYearID")
                    .IsUnique();

                entity.Property(e => e.CurrentYearId)
                    .ValueGeneratedNever()
                    .HasColumnName("CurrentYearID");

                entity.Property(e => e.ChangeYearFrom).HasColumnType("datetime");

                entity.Property(e => e.ChangeYearTo).HasColumnType("datetime");

                entity.Property(e => e.Description).HasMaxLength(2048);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.TempCurrentYearId).HasColumnName("TempCurrentYearID");

                entity.Property(e => e.ValidFrom).HasColumnType("datetime");

                entity.Property(e => e.ValidTo).HasColumnType("datetime");
            });

            modelBuilder.Entity<Document>(entity =>
            {
                entity.ToTable("Document", "helpdesk");

                entity.HasIndex(e => e.Rowguid, "UQ__Document__6225F3C13E786B3A")
                    .IsUnique();

                entity.Property(e => e.ContentType).HasMaxLength(255);

                entity.Property(e => e.CreateDate).HasDefaultValueSql("(sysutcdatetime())");

                entity.Property(e => e.CreatedBySysUserId).HasColumnName("CreatedBySysUserID");

                entity.Property(e => e.Description).HasMaxLength(4000);

                entity.Property(e => e.FileName).HasMaxLength(255);

                entity.Property(e => e.Rowguid).HasDefaultValueSql("(newid())");

                entity.HasOne(d => d.CreatedBySysUser)
                    .WithMany(p => p.DocumentCreatedBySysUsers)
                    .HasForeignKey(d => d.CreatedBySysUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Helpdesk_Document_Creator_SysUser");

                entity.HasOne(d => d.ModifiedBySysUser)
                    .WithMany(p => p.DocumentModifiedBySysUsers)
                    .HasForeignKey(d => d.ModifiedBySysUserId)
                    .HasConstraintName("FK_Helpdesk_Document_Updater_SysUserd");
            });

            modelBuilder.Entity<EducationalState>(entity =>
            {
                entity.ToTable("EducationalState");

                entity.HasComment("Актуален статус в образователн");

                entity.HasIndex(e => new { e.PersonId, e.InstitutionId, e.PositionId }, "AK_EducationalState_PersonId_InstitutionId_PositionId")
                    .IsUnique();

                entity.HasIndex(e => e.InstitutionId, "IX_EducationalState_InstitutionId");

                entity.HasIndex(e => e.PersonId, "IX_EducationalState_PersonId");

                entity.Property(e => e.EducationalStateId)
                    .HasColumnName("EducationalStateID")
                    .HasComment("Уникален идентификатор на запи");

                entity.Property(e => e.InstitutionId)
                    .HasColumnName("InstitutionID")
                    .HasComment("Код на институцията");

                entity.Property(e => e.PersonId)
                    .HasColumnName("PersonID")
                    .HasComment("Връзка човек");

                entity.Property(e => e.PositionId)
                    .HasColumnName("PositionID")
                    .HasComment("Позиция в образователната сист");

                entity.HasOne(d => d.Institution)
                    .WithMany(p => p.EducationalStates)
                    .HasForeignKey(d => d.InstitutionId)
                    .HasConstraintName("FK_EducationalState_Institution");

                entity.HasOne(d => d.Person)
                    .WithMany(p => p.EducationalStates)
                    .HasForeignKey(d => d.PersonId)
                    .HasConstraintName("FK_EducationalState_Person");

                entity.HasOne(d => d.Position)
                    .WithMany(p => p.EducationalStates)
                    .HasForeignKey(d => d.PositionId)
                    .HasConstraintName("FK_EducationalState_Position");
            });

            modelBuilder.Entity<Faquestion>(entity =>
            {
                entity.ToTable("FAQuestion", "helpdesk");

                entity.Property(e => e.Answer).IsRequired();

                entity.Property(e => e.CreatedBySysUserId).HasColumnName("CreatedBySysUserID");

                entity.Property(e => e.Question)
                    .IsRequired()
                    .HasMaxLength(2048);

                entity.HasOne(d => d.CreatedBySysUser)
                    .WithMany(p => p.FaquestionCreatedBySysUsers)
                    .HasForeignKey(d => d.CreatedBySysUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Question_Creator_SysUser");

                entity.HasOne(d => d.ModifiedBySysUser)
                    .WithMany(p => p.FaquestionModifiedBySysUsers)
                    .HasForeignKey(d => d.ModifiedBySysUserId)
                    .HasConstraintName("FK_Question_Updater_SysUser");
            });

            modelBuilder.Entity<HelpdeskSetting>(entity =>
            {
                entity.HasKey(e => e.Key)
                    .HasName("PK__Helpdesk__C41E02881F893AE4");

                entity.ToTable("HelpdeskSettings", "helpdesk");

                entity.Property(e => e.Key).HasMaxLength(255);
            });

            modelBuilder.Entity<Institution>(entity =>
            {
                entity.ToTable("Institution");

                entity.HasComment("Данни за институциите");

                entity.Property(e => e.InstitutionId)
                    .ValueGeneratedNever()
                    .HasColumnName("InstitutionID")
                    .HasComment("Код на институцията");

                entity.Property(e => e.Abbreviation)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasComment("Кратко наименование");

                entity.Property(e => e.BaseSchoolTypeId)
                    .HasColumnName("BaseSchoolTypeID")
                    .HasComment("Вид по чл. 37 (общ, според вид");

                entity.Property(e => e.BudgetingSchoolTypeId)
                    .HasColumnName("BudgetingSchoolTypeID")
                    .HasComment("Вид по чл. 35-36 (според собст");

                entity.Property(e => e.Bulstat)
                    .HasMaxLength(13)
                    .HasComment("Булстат/ЕИК");

                entity.Property(e => e.CountryId)
                    .HasColumnName("CountryID")
                    .HasComment("Код на държава");

                entity.Property(e => e.DetailedSchoolTypeId)
                    .HasColumnName("DetailedSchoolTypeID")
                    .HasComment("Вид по чл. 38 (детайлен)");

                entity.Property(e => e.FinancialSchoolTypeId)
                    .HasColumnName("FinancialSchoolTypeID")
                    .HasComment("Източник на финансиране");

                entity.Property(e => e.LocalAreaId)
                    .HasColumnName("LocalAreaID")
                    .HasComment("Код на район (основен адрес)");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(1024)
                    .HasComment("Пълно наименование");

                entity.Property(e => e.SysUserId).HasColumnName("SysUserID");

                entity.Property(e => e.TownId)
                    .HasColumnName("TownID")
                    .HasComment("Код на населеното място (основ");

                entity.HasOne(d => d.Country)
                    .WithMany(p => p.Institutions)
                    .HasForeignKey(d => d.CountryId)
                    .HasConstraintName("FK_Institution_Country");

                entity.HasOne(d => d.LocalArea)
                    .WithMany(p => p.Institutions)
                    .HasForeignKey(d => d.LocalAreaId)
                    .HasConstraintName("FK_Institution_LocalArea");

                entity.HasOne(d => d.SysUser)
                    .WithMany(p => p.Institutions)
                    .HasForeignKey(d => d.SysUserId)
                    .HasConstraintName("FK_Institution_SysUser");

                entity.HasOne(d => d.Town)
                    .WithMany(p => p.Institutions)
                    .HasForeignKey(d => d.TownId)
                    .HasConstraintName("FK_Institution_Town");
            });

            modelBuilder.Entity<InstitutionDepartment>(entity =>
            {
                entity.ToTable("InstitutionDepartment", "inst_basic");

                entity.HasComment("Други адреси за осъществяване ");

                entity.HasIndex(e => e.InstitutionId, "IX_InstitutionDepartment_InstitutionId");

                entity.Property(e => e.InstitutionDepartmentId)
                    .HasColumnName("InstitutionDepartmentID")
                    .HasComment("ID на записа (autoincrement)");

                entity.Property(e => e.Address)
                    .HasMaxLength(255)
                    .HasComment("Адрес");

                entity.Property(e => e.CountryId)
                    .HasColumnName("CountryID")
                    .HasComment("Код на държава");

                entity.Property(e => e.InstitutionId)
                    .HasColumnName("InstitutionID")
                    .HasComment("Код на институцията");

                entity.Property(e => e.IsMain)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"Основен адрес\"");

                entity.Property(e => e.IsValid).HasComment("Активен адрес");

                entity.Property(e => e.LocalAreaId)
                    .HasColumnName("LocalAreaID")
                    .HasComment("Код на район");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasComment("Наименование на другия адрес н");

                entity.Property(e => e.PostCode).HasComment("Пощенски код");

                entity.Property(e => e.SysUserId)
                    .HasColumnName("SysUserID")
                    .HasComment("Потребител");

                entity.Property(e => e.TmpDepId).HasColumnName("tmp_DepID");

                entity.Property(e => e.TmpSchoolYear).HasColumnName("tmp_SchoolYear");

                entity.Property(e => e.TownId)
                    .HasColumnName("TownID")
                    .HasComment("Код на населено място");

                entity.Property(e => e.ValidFrom)
                    .HasDefaultValueSql("(sysutcdatetime())")
                    .HasComment("Дата, от която е валидна стойн");

                entity.Property(e => e.ValidTo)
                    .HasDefaultValueSql("(CONVERT([datetime2],'9999-12-31 23:59:59.9999999'))")
                    .HasComment("Дата, до която е валидна стойн");

                entity.HasOne(d => d.Country)
                    .WithMany(p => p.InstitutionDepartments)
                    .HasForeignKey(d => d.CountryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_InstDep_Country");

                entity.HasOne(d => d.LocalArea)
                    .WithMany(p => p.InstitutionDepartments)
                    .HasForeignKey(d => d.LocalAreaId)
                    .HasConstraintName("FK_InstDep_LocalArea");

                entity.HasOne(d => d.SysUser)
                    .WithMany(p => p.InstitutionDepartments)
                    .HasForeignKey(d => d.SysUserId)
                    .HasConstraintName("FK_InstDep_SysUser");

                entity.HasOne(d => d.Town)
                    .WithMany(p => p.InstitutionDepartments)
                    .HasForeignKey(d => d.TownId)
                    .HasConstraintName("FK_InstDep_Town");
            });

            modelBuilder.Entity<InstitutionDetail>(entity =>
            {
                entity.HasKey(e => e.InstitutionId);

                entity.ToTable("InstitutionDetail", "inst_basic");

                entity.HasComment("Допълнителни данни за институц");

                entity.Property(e => e.InstitutionId)
                    .ValueGeneratedNever()
                    .HasColumnName("InstitutionID")
                    .HasComment("Код на институцията");

                entity.Property(e => e.BankAccountHolder)
                    .HasMaxLength(255)
                    .HasComment("Титуляр на банковата сметка");

                entity.Property(e => e.BankBic)
                    .HasMaxLength(255)
                    .HasColumnName("BankBIC")
                    .HasComment("Код на банката");

                entity.Property(e => e.BankIban)
                    .HasMaxLength(255)
                    .HasColumnName("BankIBAN")
                    .HasComment("Банкова сметка на институцията");

                entity.Property(e => e.BankName)
                    .HasMaxLength(255)
                    .HasComment("Наименование на банката");

                entity.Property(e => e.ConstitActFirst)
                    .HasMaxLength(1024)
                    .HasComment("Акт за учредяване или преобраз");

                entity.Property(e => e.ConstitActLast)
                    .HasMaxLength(1024)
                    .HasComment("Акт за учредяване или собствен");

                entity.Property(e => e.Email)
                    .HasMaxLength(255)
                    .HasComment("Електронна поща");

                entity.Property(e => e.EstablishedYear)
                    .HasMaxLength(255)
                    .HasComment("Година на основаване");

                entity.Property(e => e.IsAppInnovSystem)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"ДГ прилага иновативна ");

                entity.Property(e => e.IsDelegateBudget)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"На делегиран бюджет\"");

                entity.Property(e => e.IsInternContract)
                    .HasDefaultValueSql("((0))")
                    .HasComment("не се използва");

                entity.Property(e => e.IsNational)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"С национално значение\"");

                entity.Property(e => e.IsNonIndDormitory)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"Към училището има неса");

                entity.Property(e => e.IsOdz)
                    .HasColumnName("IsODZ")
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"Към ДГ има яслена груп");

                entity.Property(e => e.IsProfSchool)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"Осигурява професионалн");

                entity.Property(e => e.IsProvideEduServ)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Маркер \"Oрганизира допълнителн");

                entity.Property(e => e.SysUserId)
                    .HasColumnName("SysUserID")
                    .HasComment("Потребител");

                entity.Property(e => e.Website)
                    .HasMaxLength(50)
                    .HasComment("Интернет адрес");

                entity.HasOne(d => d.Institution)
                    .WithOne(p => p.InstitutionDetail)
                    .HasForeignKey<InstitutionDetail>(d => d.InstitutionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_InstitutionDetailInstitution");

                entity.HasOne(d => d.SysUser)
                    .WithMany(p => p.InstitutionDetails)
                    .HasForeignKey(d => d.SysUserId)
                    .HasConstraintName("FK_InstDetails_SysUser");
            });

            modelBuilder.Entity<InstitutionSchoolYear>(entity =>
            {
                entity.HasKey(e => new { e.InstitutionId, e.SchoolYear });

                entity.ToTable("InstitutionSchoolYear");

                entity.HasComment("Основни данни за институцията ");

                entity.Property(e => e.InstitutionId).HasComment("Код на институцията");

                entity.Property(e => e.SchoolYear).HasComment("Учебна година");

                entity.Property(e => e.Abbreviation)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasComment("Кратко наименование");

                entity.Property(e => e.BaseSchoolTypeId)
                    .HasColumnName("BaseSchoolTypeID")
                    .HasComment("Вид по чл. 37 (общ, според вид");

                entity.Property(e => e.BudgetingSchoolTypeId)
                    .HasColumnName("BudgetingSchoolTypeID")
                    .HasComment("Вид по чл. 35-36 (според собст");

                entity.Property(e => e.Bulstat)
                    .HasMaxLength(13)
                    .HasComment("БУЛСТАТ");

                entity.Property(e => e.CountryId)
                    .HasColumnName("CountryID")
                    .HasComment("Код на държава");

                entity.Property(e => e.DetailedSchoolTypeId)
                    .HasColumnName("DetailedSchoolTypeID")
                    .HasComment("Вид по чл. 38 (детайлен)");

                entity.Property(e => e.FinancialSchoolTypeId)
                    .HasColumnName("FinancialSchoolTypeID")
                    .HasComment("Източник на финансиране");

                entity.Property(e => e.IsFinalized).HasComment("Финализирана");

                entity.Property(e => e.LocalAreaId)
                    .HasColumnName("LocalAreaID")
                    .HasComment("Код на район (основен адрес)");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(1024)
                    .HasComment("Наименование");

                entity.Property(e => e.SysUserId)
                    .HasColumnName("SysUserID")
                    .HasComment("Потребител");

                entity.Property(e => e.TownId)
                    .HasColumnName("TownID")
                    .HasComment("Код на града (основен адрес)");

                entity.Property(e => e.ValidFrom)
                    .HasDefaultValueSql("(sysutcdatetime())")
                    .HasComment("Дата, от която е валидна стойн");

                entity.Property(e => e.ValidTo)
                    .HasDefaultValueSql("(CONVERT([datetime2],'9999-12-31 23:59:59.9999999'))")
                    .HasComment("Дата, до която е валидна стойн");

                entity.HasOne(d => d.Country)
                    .WithMany(p => p.InstitutionSchoolYears)
                    .HasForeignKey(d => d.CountryId)
                    .HasConstraintName("FK_InstitutionSchoolYear_Country");

                entity.HasOne(d => d.LocalArea)
                    .WithMany(p => p.InstitutionSchoolYears)
                    .HasForeignKey(d => d.LocalAreaId)
                    .HasConstraintName("FK_InstitutionSchoolYear_LocalArea");

                entity.HasOne(d => d.SchoolYearNavigation)
                    .WithMany(p => p.InstitutionSchoolYears)
                    .HasForeignKey(d => d.SchoolYear)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_InstitutionSchoolYear_CurrentYear");

                entity.HasOne(d => d.SysUser)
                    .WithMany(p => p.InstitutionSchoolYears)
                    .HasForeignKey(d => d.SysUserId)
                    .HasConstraintName("FK_InstitutionSchoolYear_SysUser");

                entity.HasOne(d => d.Town)
                    .WithMany(p => p.InstitutionSchoolYears)
                    .HasForeignKey(d => d.TownId)
                    .HasConstraintName("FK_InstitutionSchoolYear_Town");
            });

            modelBuilder.Entity<Issue>(entity =>
            {
                entity.ToTable("Issue", "helpdesk");

                entity.HasIndex(e => e.SubmitterSysUserId, "IX_Issue_SubmitterSysUserId");

                entity.Property(e => e.CreatedBySysUserId).HasColumnName("CreatedBySysUserID");

                entity.Property(e => e.Description).IsRequired();

                entity.Property(e => e.Phone).HasMaxLength(255);

                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.AssignedToSysUser)
                    .WithMany(p => p.IssueAssignedToSysUsers)
                    .HasForeignKey(d => d.AssignedToSysUserId)
                    .HasConstraintName("FK_Issue_Assigned_SysUser");

                entity.HasOne(d => d.Category)
                    .WithMany(p => p.IssueCategories)
                    .HasForeignKey(d => d.CategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Issue_Category");

                entity.HasOne(d => d.CreatedBySysUser)
                    .WithMany(p => p.IssueCreatedBySysUsers)
                    .HasForeignKey(d => d.CreatedBySysUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Issue_Creator_SysUser");

                entity.HasOne(d => d.ModifiedBySysUser)
                    .WithMany(p => p.IssueModifiedBySysUsers)
                    .HasForeignKey(d => d.ModifiedBySysUserId)
                    .HasConstraintName("FK_Issue_Updater_SysUser");

                entity.HasOne(d => d.Priority)
                    .WithMany(p => p.Issues)
                    .HasForeignKey(d => d.PriorityId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Issue_Priority");

                entity.HasOne(d => d.Status)
                    .WithMany(p => p.Issues)
                    .HasForeignKey(d => d.StatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Issue_status");

                entity.HasOne(d => d.Subcategory)
                    .WithMany(p => p.IssueSubcategories)
                    .HasForeignKey(d => d.SubcategoryId)
                    .HasConstraintName("FK_Helpdesk_Issue_Subcategory");

                entity.HasOne(d => d.SubmitterSysRole)
                    .WithMany(p => p.Issues)
                    .HasForeignKey(d => d.SubmitterSysRoleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Issue_Submitter_SysRole");

                entity.HasOne(d => d.SubmitterSysUser)
                    .WithMany(p => p.IssueSubmitterSysUsers)
                    .HasForeignKey(d => d.SubmitterSysUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Issue_Submitter_SysUser");

                entity.HasOne(d => d.InstitutionSchoolYear)
                    .WithMany(p => p.Issues)
                    .HasForeignKey(d => new { d.InstitutionId, d.SchoolYear })
                    .HasConstraintName("FK_Issue_InstitutionSchoolYear_Institution");
            });

            modelBuilder.Entity<IssueAttachment>(entity =>
            {
                entity.ToTable("IssueAttachment", "helpdesk");

                entity.HasIndex(e => e.IssueId, "IX_IssueAttachment_IssueId");

                entity.HasOne(d => d.Document)
                    .WithMany(p => p.IssueAttachments)
                    .HasForeignKey(d => d.DocumentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_IssueAttachment_Document");

                entity.HasOne(d => d.Issue)
                    .WithMany(p => p.IssueAttachments)
                    .HasForeignKey(d => d.IssueId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_IssueAttachment_Issue");
            });

            modelBuilder.Entity<IssueComment>(entity =>
            {
                entity.ToTable("IssueComment", "helpdesk");

                entity.HasIndex(e => e.IssueId, "IX_IssueComment_IssueId");

                entity.Property(e => e.Comment).IsRequired();

                entity.Property(e => e.CreatedBySysUserId).HasColumnName("CreatedBySysUserID");

                entity.HasOne(d => d.CreatedBySysUser)
                    .WithMany(p => p.IssueCommentCreatedBySysUsers)
                    .HasForeignKey(d => d.CreatedBySysUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_IssueComment_Creator_SysUser");

                entity.HasOne(d => d.Issue)
                    .WithMany(p => p.IssueComments)
                    .HasForeignKey(d => d.IssueId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_IssueComment_Issue");

                entity.HasOne(d => d.ModifiedBySysUser)
                    .WithMany(p => p.IssueCommentModifiedBySysUsers)
                    .HasForeignKey(d => d.ModifiedBySysUserId)
                    .HasConstraintName("FK_IssueComment_Updater_SysUser");
            });

            modelBuilder.Entity<IssueCommentAttachment>(entity =>
            {
                entity.ToTable("IssueCommentAttachment", "helpdesk");

                entity.HasIndex(e => e.IssueCommentId, "IX_IssueCommentAttachment_IssueCommentId");

                entity.HasOne(d => d.Document)
                    .WithMany(p => p.IssueCommentAttachments)
                    .HasForeignKey(d => d.DocumentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_IssueCommentAttachment_Document");

                entity.HasOne(d => d.IssueComment)
                    .WithMany(p => p.IssueCommentAttachments)
                    .HasForeignKey(d => d.IssueCommentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_IssueCommentAttachment_IssueComment");
            });

            modelBuilder.Entity<IssueReadActivity>(entity =>
            {
                entity.ToTable("IssueReadActivity", "helpdesk");

                entity.Property(e => e.CreatedBySysUserId).HasColumnName("CreatedBySysUserID");

                entity.Property(e => e.LastActivityDate).HasComputedColumnSql("(isnull([ModifyDate],[CreateDate]))", true);

                entity.HasOne(d => d.CreatedBySysUser)
                    .WithMany(p => p.IssueReadActivityCreatedBySysUsers)
                    .HasForeignKey(d => d.CreatedBySysUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_IssueReadActivity_Creator_SysUser");

                entity.HasOne(d => d.Issue)
                    .WithMany(p => p.IssueReadActivities)
                    .HasForeignKey(d => d.IssueId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_IssueReadActivity_Issue");

                entity.HasOne(d => d.ModifiedBySysUser)
                    .WithMany(p => p.IssueReadActivityModifiedBySysUsers)
                    .HasForeignKey(d => d.ModifiedBySysUserId)
                    .HasConstraintName("FK_IssueReadActivity_Updater_SysUser");
            });

            modelBuilder.Entity<IssueStatusHistory>(entity =>
            {
                entity.ToTable("IssueStatusHistory", "helpdesk");

                entity.HasIndex(e => e.IssueId, "IX_IssueStatusHistory_IssueId");

                entity.Property(e => e.Comment).IsRequired();

                entity.Property(e => e.CreatedBySysUserId).HasColumnName("CreatedBySysUserID");

                entity.HasOne(d => d.CreatedBySysUser)
                    .WithMany(p => p.IssueStatusHistoryCreatedBySysUsers)
                    .HasForeignKey(d => d.CreatedBySysUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_IssueStatusHistory_Creator_SysUser");

                entity.HasOne(d => d.Issue)
                    .WithMany(p => p.IssueStatusHistories)
                    .HasForeignKey(d => d.IssueId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_IssueStatusHistory_Issue");

                entity.HasOne(d => d.ModifiedBySysUser)
                    .WithMany(p => p.IssueStatusHistoryModifiedBySysUsers)
                    .HasForeignKey(d => d.ModifiedBySysUserId)
                    .HasConstraintName("FK_IssueStatusHistory_Updater_SysUser");

                entity.HasOne(d => d.Status)
                    .WithMany(p => p.IssueStatusHistories)
                    .HasForeignKey(d => d.StatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_IssueStatusHistory_Status");
            });

            modelBuilder.Entity<LocalArea>(entity =>
            {
                entity.ToTable("LocalArea", "location");

                entity.Property(e => e.LocalAreaId)
                    .ValueGeneratedNever()
                    .HasColumnName("LocalAreaID");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(1024);

                entity.HasOne(d => d.TownCodeNavigation)
                    .WithMany(p => p.LocalAreas)
                    .HasForeignKey(d => d.TownCode)
                    .HasConstraintName("FK_LocalArea_Town");
            });

            modelBuilder.Entity<Message>(entity =>
            {
                entity.ToTable("Message", "student");

                entity.HasIndex(e => e.ReceiverId, "IX_Message_ReceiverId");

                entity.Property(e => e.Contents).IsRequired();

                entity.Property(e => e.CreatedBySysUserId).HasColumnName("CreatedBySysUserID");

                entity.Property(e => e.Subject)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.HasOne(d => d.CreatedBySysUser)
                    .WithMany(p => p.MessageCreatedBySysUsers)
                    .HasForeignKey(d => d.CreatedBySysUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Message_Creator_SysUser");

                entity.HasOne(d => d.ModifiedBySysUser)
                    .WithMany(p => p.MessageModifiedBySysUsers)
                    .HasForeignKey(d => d.ModifiedBySysUserId)
                    .HasConstraintName("FK_Message_Updater_SysUser");

                entity.HasOne(d => d.Receiver)
                    .WithMany(p => p.MessageReceivers)
                    .HasForeignKey(d => d.ReceiverId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Message_Receiver_SysUser");

                entity.HasOne(d => d.Sender)
                    .WithMany(p => p.MessageSenders)
                    .HasForeignKey(d => d.SenderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Message_Sender_SysUser");
            });

            modelBuilder.Entity<Municipality>(entity =>
            {
                entity.ToTable("Municipality", "location");

                entity.Property(e => e.MunicipalityId)
                    .ValueGeneratedNever()
                    .HasColumnName("MunicipalityID");

                entity.Property(e => e.Code)
                    .IsRequired()
                    .HasMaxLength(1024);

                entity.Property(e => e.Description).HasMaxLength(2048);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(1024);

                entity.Property(e => e.RegionId).HasColumnName("RegionID");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.Municipalities)
                    .HasForeignKey(d => d.RegionId)
                    .HasConstraintName("FK_Municipality_Region");
            });

            modelBuilder.Entity<Person>(entity =>
            {
                entity.ToTable("Person");

                entity.HasComment("Персонал, ученици, родители - ")
                    .ToTable(tb => tb.IsTemporal(ttb =>
    {
        ttb.UseHistoryTable("PersonHistory", "core");
        ttb
            .HasPeriodStart("ValidFrom")
            .HasColumnName("ValidFrom");
        ttb
            .HasPeriodEnd("ValidTo")
            .HasColumnName("ValidTo");
    }
));

                entity.HasIndex(e => e.PersonalId, "UQ_Person_PersonalID")
                    .IsUnique()
                    .HasFilter("([PersonalID] IS NOT NULL)");

                entity.Property(e => e.PersonId)
                    .HasColumnName("PersonID")
                    .HasComment("Уникален идентификатор на запи");

                entity.Property(e => e.AzureId)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("AzureID");

                entity.Property(e => e.BirthDate)
                    .HasColumnType("date")
                    .HasComment("Дата на раждане");

                entity.Property(e => e.BirthPlace).HasMaxLength(255);

                entity.Property(e => e.BirthPlaceCountry).HasComment("Месторождение - Държава");

                entity.Property(e => e.BirthPlaceTownId)
                    .HasColumnName("BirthPlaceTownID")
                    .HasComment("Месторождение - населено място");

                entity.Property(e => e.CurrentAddress)
                    .HasMaxLength(2048)
                    .HasComment("Настоящ адрес");

                entity.Property(e => e.CurrentTownId)
                    .HasColumnName("CurrentTownID")
                    .HasComment("Настоящ адрес - населено място");

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasComment("Име");

                entity.Property(e => e.Gender).HasComment("Пол");

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasComment("Фамилия");

                entity.Property(e => e.MiddleName)
                    .HasMaxLength(255)
                    .HasComment("Презиме");

                entity.Property(e => e.NationalityId)
                    .HasColumnName("NationalityID")
                    .HasComment("Гражданство");

                entity.Property(e => e.PermanentAddress)
                    .HasMaxLength(2048)
                    .HasComment("Постоянен адрес");

                entity.Property(e => e.PermanentTownId)
                    .HasColumnName("PermanentTownID")
                    .HasComment("Постоянен адрес - населено мяс");

                entity.Property(e => e.PersonalId)
                    .HasMaxLength(255)
                    .HasColumnName("PersonalID")
                    .HasComment("ЕГН/ЛНЧ/Личен номер на чуждене");

                entity.Property(e => e.PersonalIdtype)
                    .HasColumnName("PersonalIDType")
                    .HasComment("Вид идентификатор");

                entity.Property(e => e.PublicEduNumber).HasComment("Личен образователен номер");

                entity.Property(e => e.SchoolBooksCodesId)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("SchoolBooksCodesID");

                entity.HasOne(d => d.BirthPlaceCountryNavigation)
                    .WithMany(p => p.PersonBirthPlaceCountryNavigations)
                    .HasForeignKey(d => d.BirthPlaceCountry)
                    .HasConstraintName("FK_Person_Country_BirthPlace");

                entity.HasOne(d => d.BirthPlaceTown)
                    .WithMany(p => p.PersonBirthPlaceTowns)
                    .HasForeignKey(d => d.BirthPlaceTownId)
                    .HasConstraintName("FK_Person_Town_BirthPlace");

                entity.HasOne(d => d.CurrentTown)
                    .WithMany(p => p.PersonCurrentTowns)
                    .HasForeignKey(d => d.CurrentTownId)
                    .HasConstraintName("FK_Person_Town_Current");

                entity.HasOne(d => d.Nationality)
                    .WithMany(p => p.PersonNationalities)
                    .HasForeignKey(d => d.NationalityId)
                    .HasConstraintName("FK_Person_Country");

                entity.HasOne(d => d.PermanentTown)
                    .WithMany(p => p.PersonPermanentTowns)
                    .HasForeignKey(d => d.PermanentTownId)
                    .HasConstraintName("FK_Person_Town_Permanent");
            });

            modelBuilder.Entity<Position>(entity =>
            {
                entity.ToTable("Position");

                entity.Property(e => e.PositionId).HasColumnName("PositionID");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(2048);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.SysRoleId).HasColumnName("SysRoleID");

                entity.Property(e => e.ValidFrom).HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.SysRole)
                    .WithMany(p => p.Positions)
                    .HasForeignKey(d => d.SysRoleId)
                    .HasConstraintName("FK_Position_SysRole");
            });

            modelBuilder.Entity<Priority>(entity =>
            {
                entity.ToTable("Priority", "helpdesk");

                entity.Property(e => e.Code)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.Color).HasMaxLength(10);

                entity.Property(e => e.Description).HasMaxLength(2048);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.ValidFrom).HasDefaultValueSql("(getdate())");
            });

            modelBuilder.Entity<Region>(entity =>
            {
                entity.ToTable("Region", "location");

                entity.Property(e => e.RegionId)
                    .ValueGeneratedNever()
                    .HasColumnName("RegionID");

                entity.Property(e => e.Code)
                    .IsRequired()
                    .HasMaxLength(1024);

                entity.Property(e => e.Description).HasMaxLength(2048);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(1024);
            });

            modelBuilder.Entity<RelativeChild>(entity =>
            {
                entity.HasKey(e => new { e.RelativeId, e.ChildId, e.RelativeTypeId });

                entity.ToTable("RelativeChild");

                entity.Property(e => e.RelativeId).HasColumnName("RelativeID");

                entity.Property(e => e.ChildId).HasColumnName("ChildID");

                entity.Property(e => e.RelativeTypeId).HasColumnName("RelativeTypeID");
            });

            modelBuilder.Entity<Status>(entity =>
            {
                entity.ToTable("Status", "helpdesk");

                entity.Property(e => e.Code)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.Color).HasMaxLength(10);

                entity.Property(e => e.Description).HasMaxLength(2048);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.ValidFrom).HasDefaultValueSql("(getdate())");
            });

            modelBuilder.Entity<SysRole>(entity =>
            {
                entity.ToTable("SysRole");

                entity.HasIndex(e => e.Name, "UQ_SysRole")
                    .IsUnique();

                entity.Property(e => e.SysRoleId).HasColumnName("SysRoleID");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(2048);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(255);
            });

            modelBuilder.Entity<SysUser>(entity =>
            {
                entity.ToTable("SysUser");

                entity.HasComment("Потребители")
                    .ToTable(tb => tb.IsTemporal(ttb =>
    {
        ttb.UseHistoryTable("SysUserHistory", "core");
        ttb
            .HasPeriodStart("ValidFrom")
            .HasColumnName("ValidFrom");
        ttb
            .HasPeriodEnd("ValidTo")
            .HasColumnName("ValidTo");
    }
));

                entity.HasIndex(e => e.PersonId, "uqOneToOneSysUserPersonByCondition")
                    .IsUnique()
                    .HasFilter("([DeletedOn] IS NULL)");

                entity.HasIndex(e => e.Username, "uqSysUserUsername")
                    .IsUnique()
                    .HasFilter("([DeletedOn] IS NULL)");

                entity.Property(e => e.SysUserId)
                    .HasColumnName("SysUserID")
                    .HasComment("Уникален идентификатор");

                entity.Property(e => e.InitialPassword).HasMaxLength(255);

                entity.Property(e => e.IsAzureSynced).HasColumnName("isAzureSynced");

                entity.Property(e => e.IsAzureUser)
                    .IsRequired()
                    .HasDefaultValueSql("('FALSE')");

                entity.Property(e => e.Password)
                    .HasMaxLength(255)
                    .HasComment("Парола");

                entity.Property(e => e.PersonId)
                    .HasColumnName("PersonID")
                    .HasDefaultValueSql("((-1))");

                entity.Property(e => e.Username)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasComment("Потребителско име");

                entity.HasOne(d => d.Person)
                    .WithOne(p => p.SysUser)
                    .HasForeignKey<SysUser>(d => d.PersonId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_SysUser_Person");
            });

            modelBuilder.Entity<SysUserSysRole>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("SysUserSysRole");

                entity.HasIndex(e => e.SysUserId, "IX_SysUserSysRole_SysUserID");

                entity.Property(e => e.BudgetingInstitutionId).HasColumnName("BudgetingInstitutionID");

                entity.Property(e => e.InstitutionId).HasColumnName("InstitutionID");

                entity.Property(e => e.MunicipalityId).HasColumnName("MunicipalityID");

                entity.Property(e => e.RegionId).HasColumnName("RegionID");

                entity.Property(e => e.SysRoleId).HasColumnName("SysRoleID");

                entity.Property(e => e.SysUserId).HasColumnName("SysUserID");

                entity.HasOne(d => d.Institution)
                    .WithMany()
                    .HasForeignKey(d => d.InstitutionId)
                    .HasConstraintName("FK_SysUserSysRole_Institution");

                entity.HasOne(d => d.Municipality)
                    .WithMany()
                    .HasForeignKey(d => d.MunicipalityId)
                    .HasConstraintName("FK_SysUserSysRole_Municipality");

                entity.HasOne(d => d.Region)
                    .WithMany()
                    .HasForeignKey(d => d.RegionId)
                    .HasConstraintName("FK_SysUserSysRole_Region");

                entity.HasOne(d => d.SysRole)
                    .WithMany()
                    .HasForeignKey(d => d.SysRoleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_SysUserSysRole_SysRole");

                entity.HasOne(d => d.SysUser)
                    .WithMany()
                    .HasForeignKey(d => d.SysUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_SysUserSysRole_SysUser");
            });

            modelBuilder.Entity<Town>(entity =>
            {
                entity.ToTable("Town", "location");

                entity.Property(e => e.TownId)
                    .ValueGeneratedNever()
                    .HasColumnName("TownID");

                entity.Property(e => e.Description).HasMaxLength(2048);

                entity.Property(e => e.Latitude).HasColumnType("decimal(5, 2)");

                entity.Property(e => e.Longtitude).HasColumnType("decimal(5, 2)");

                entity.Property(e => e.MunicipalityId).HasColumnName("MunicipalityID");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(1024);

                entity.Property(e => e.Type)
                    .IsRequired()
                    .HasMaxLength(1024);

                entity.HasOne(d => d.Municipality)
                    .WithMany(p => p.Towns)
                    .HasForeignKey(d => d.MunicipalityId)
                    .HasConstraintName("FK_Town_Municipality");
            });

            modelBuilder.Entity<Uierror>(entity =>
            {
                entity.HasKey(e => new { e.CreateDate, e.Id });

                entity.ToTable("UIError", "logs");

                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                entity.Property(e => e.CreatedBySysUserId).HasColumnName("CreatedBySysUserID");

                entity.Property(e => e.Ipaddress)
                    .HasMaxLength(100)
                    .HasColumnName("IPAddress");

                entity.Property(e => e.Message).IsRequired();

                entity.HasOne(d => d.AuditModule)
                    .WithMany(p => p.Uierrors)
                    .HasForeignKey(d => d.AuditModuleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_UIError_AuditModuleId");
            });

            modelBuilder.Entity<VCategoryStat>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("v_CategoryStat", "helpdesk");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(255);
            });

            modelBuilder.HasSequence<int>("AbsenceIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("AdditionalActivityIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("AttendanceIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("BlobContentsIdSequence", "blobs").StartsAt(1000);

            modelBuilder.HasSequence<int>("BlobsIdSequence", "blobs").StartsAt(1000);

            modelBuilder.HasSequence<int>("ClassBookIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("ClassBookPrintIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("ExamDutyProtocolIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("ExamIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("ExamResultProtocolIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("ExamResultsBookRecordIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("FirstGradeResultIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("GradeChangeExamsAdmProtocolIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("GradeIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("GradeResultIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("GraduationThesisDefenseProtocolIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("HighSchoolCertificateProtocolIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("IndividualWorkIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("LiableBookRecordIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("MainBookRecordIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("MissingTopicsReportIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("MissingTopicsReportItemIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("NoteIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("NvoExamDutyProtocolIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("OffDayIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("ParentMeetingIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("PgResultIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("PublicationIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("QualificationAcquisitionProtocolIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("QualificationExamResultProtocolIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("QueueMessageIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("RegBookCertificateDuplicateIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("RegBookCertificateIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("RegBookQualificationDuplicateIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("RegBookQualificationIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("RemarkIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("SanctionIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("ScheduleIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("ScheduleLessonIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("SchoolYearDateInfoIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("ShiftIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("SkillsCheckExamDutyProtocolIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("SkillsCheckExamResultProtocolEvaluatorIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("SkillsCheckExamResultProtocolIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("SpbsBookRecordIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("StateExamDutyProtocolIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("StateExamsAdmProtocolIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("SupportActivityIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("SupportDifficultyIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("SupportIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("TeacherAbsenceIdSequence", "school_books").StartsAt(100000);

            modelBuilder.HasSequence<int>("TopicIdSequence", "school_books").StartsAt(100000);

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}