// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Helpdesk.DataAccess
{
    /// <summary>
    /// Други адреси за осъществяване 
    /// </summary>
    public partial class InstitutionDepartment
    {
        public InstitutionDepartment()
        {
            ClassGroups = new HashSet<ClassGroup>();
        }

        /// <summary>
        /// ID на записа (autoincrement)
        /// </summary>
        public int InstitutionDepartmentId { get; set; }
        /// <summary>
        /// Код на институцията
        /// </summary>
        public int InstitutionId { get; set; }
        /// <summary>
        /// Наименование на другия адрес н
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Код на държава
        /// </summary>
        public int CountryId { get; set; }
        /// <summary>
        /// Код на населено място
        /// </summary>
        public int? TownId { get; set; }
        /// <summary>
        /// Код на район
        /// </summary>
        public int? LocalAreaId { get; set; }
        /// <summary>
        /// Адрес
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// Пощенски код
        /// </summary>
        public int? PostCode { get; set; }
        /// <summary>
        /// Маркер &quot;Основен адрес&quot;
        /// </summary>
        public bool? IsMain { get; set; }
        /// <summary>
        /// Дата, от която е валидна стойн
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Дата, до която е валидна стойн
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Потребител
        /// </summary>
        public int? SysUserId { get; set; }
        public int? TmpDepId { get; set; }
        public short? TmpSchoolYear { get; set; }
        /// <summary>
        /// Активен адрес
        /// </summary>
        public bool? IsValid { get; set; }

        public virtual Country Country { get; set; }
        public virtual LocalArea LocalArea { get; set; }
        public virtual SysUser SysUser { get; set; }
        public virtual Town Town { get; set; }
        public virtual ICollection<ClassGroup> ClassGroups { get; set; }
    }
}