// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Helpdesk.DataAccess
{
    public partial class Status
    {
        public Status()
        {
            IssueStatusHistories = new HashSet<IssueStatusHistory>();
            Issues = new HashSet<Issue>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string Color { get; set; }
        public bool IsValid { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }

        public virtual ICollection<IssueStatusHistory> IssueStatusHistories { get; set; }
        public virtual ICollection<Issue> Issues { get; set; }
    }
}