// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Helpdesk.DataAccess
{
    public partial class Uierror
    {
        public int Id { get; set; }
        public short Severity { get; set; }
        public int AuditModuleId { get; set; }
        public string Message { get; set; }
        public string Trace { get; set; }
        public string Ipaddress { get; set; }
        public string UserAgent { get; set; }
        public string AdditionalInformation { get; set; }
        public int? CreatedBySysUserId { get; set; }
        public DateTime CreateDate { get; set; }

        public virtual AuditModule AuditModule { get; set; }
    }
}