export default Object.freeze({
  DATEPICKER_FORMAT: 'DD/MM/YYYY',
  SEARCH_INPUT_MIN_LENGTH: 2,
  MALE: 2,
  FEMALE: 1,
  DISPLAY_TIME_FORMAT : 'HH:mm:ss',
  SEVENTH_GRADE: 7,
  SIXTH_GRADE: 6,
  STUDENT_SCHOLARSHIP_AMOUNT_RATE: 100,
  KINDERGARTEN_BASE_SCHOOL_TYPE_ID: 15,
  PIN_TYPE_EGN: 0,
  PIN_TYPE_LNCH: 1,
  PIN_TYPE_IDN: 2,
  AnonymizedEgn: 'XXXXXXXXXX'
});