import { UserRole } from '@/enums/enums';
import i18n from '@/language/language';

export default Object.freeze({
  DATEPICKER_FORMAT: 'DD/MM/YYYY',
  DATEPICKER_FORMAT_DOTS: 'DD.MM.YYYY',
  SEARCH_INPUT_MIN_LENGTH: 2,
  MALE: 2,
  FEMALE: 1,
  DISPLAY_TIME_FORMAT : 'HH:mm:ss',
  DATE_AND_TIME_FORMAT: 'DD/MM/YYYY HH:mm:ss',
  DATE_FORMAT: 'DD/MM/YYYY',
  SEVENTH_GRADE: 7,
  SIXTH_GRADE: 6,
  ELEVENTH_GRADE: 11,
  TWELFTH_GRADE: 12,
  FIRST_GRADE: 1,
  SECOND_GRADE: 2,
  STUDENT_SCHOLARSHIP_AMOUNT_RATE: 100,
  KINDERGARTEN_BASE_SCHOOL_TYPE_ID: 15,
  PIN_TYPE_EGN: 0,
  PIN_TYPE_LNCH: 1,
  PIN_TYPE_IDN: 2,
  AnonymizedEgn: 'XXXXXXXXXX',
  STUDENT_DID_NOT_APPEAR_GRADE_ID: 7,
  PERSON_INFORMATION_FIELD_IDS: ['birthDate', 'personalId', 'personalIdType', 'gender', 'firstName', 'middleName', 'lastName', 'nationalExternalEvaluation', 'levelOfEKR', 'levelOfNKR', 'gpa', 'gpatext'],
  INSTITUTION_INFORMATION_FIELD_IDS: ['institution', 'institutionTown', 'institutionMunicipality', 'institutionLocalArea', 'institutionRegion'],
  FIRST_MAJOR_COURSE: 1,
  SECOND_MAJOR_COURSE: 2,
  THIRD_MAJOR_COURSE: 3,
  FOURTH_MAJOR_COURSE: 4,
  SqlToMomentFormatsMapper: {
    '104': 'DD/MM/YYYY'
  },
  personalDevelopmentResourceSupportReasonTypeId: 8,
  FTACOutsorcedInstitutionTypeId: 4,
  FieldOutlined: false,
  FieldPersistentPlaceholder: false,
  BULGARIA_COUNTRY_ID:34,
  STUDENTS_MODULE_ALLOWED_ROLES: [UserRole.School, UserRole.Mon, UserRole.Ruo, UserRole.MonExpert,
    UserRole.RuoExpert, UserRole.Teacher, UserRole.Cioo, UserRole.Consortium, UserRole.MonOBGUM,
    UserRole.MonOBGUM_Finance, UserRole.MonHR, UserRole.ExternalExpert],
  DynamicField: {
    FieldTypeOptions: [
      { value: 'AutoComplete', text: 'AutoComplete' },
      { value: 'Combobox', text: 'Combobox' },
      { value: 'BooleanField', text: 'BooleanField' },
      { value: 'DateField', text: 'DateField' },
      { value: 'LabelField', text: 'LabelField' },
      { value: 'NumberField', text: 'NumberField' },
      { value: 'PersonUniqueIdField', text: 'PersonUniqueIdField' },
      { value: 'SchoolYearField', text: 'SchoolYearField' },
      { value: 'SelectList', text: 'SelectList' },
      { value: 'TextField', text: 'TextField' },
      { value: 'TextAreaField', text: 'TextAreaField' },
      { value: 'YearPicker', text: 'YearPicker' },
      { value: 'YearPickerCombo', text: 'YearPickerCombo' },
    ],
    ColsOptions: [
      { value: '1', text: '1' },
      { value: '2', text: '2' },
      { value: '3', text: '3' },
      { value: '4', text: '4' },
      { value: '5', text: '5' },
      { value: '6', text: '6' },
      { value: '7', text: '7' },
      { value: '8', text: '8' },
      { value: '9', text: '9' },
      { value: '10', text: '10' },
      { value: '11', text: '11' },
      { value: '12', text: '12' },
    ],
    FieldsWithApiCall: ['SelectList', 'AutoComplete', 'Combobox'],
    FieldIds: [
      { value: 'ministry', text: 'ministry' },
      { value: 'institution', text: 'institution' },
      { value: 'institutionTown', text: 'institutionTown' },
      { value: 'institutionMunicipality', text: 'institutionMunicipality' },
      { value: 'institutionLocalArea', text: 'institutionLocalArea' },
      { value: 'institutionRegion', text: 'institutionRegion' },
      { value: 'gender', text: 'gender' },
      { value: 'birthPlaceTown', text: 'birthPlaceTown' },
      { value: 'birthPlaceMunicipality', text: 'birthPlaceMunicipality' },
      { value: 'birthPlaceRegion', text: 'birthPlaceRegion' },
      { value: 'birthPlaceLocalArea', text: 'birthPlaceLocalArea' },
      { value: 'speciality', text: 'speciality' },
      { value: 'eduForm', text: 'eduForm' },
      { value: 'educationType', text: 'educationType' },
      { value: 'sppooProfession', text: 'sppooProfession' },
      { value: 'sppooSpeciality', text: 'sppooSpeciality' },
      { value: 'sppooProfessionName', text: 'sppooProfessionName' },
      { value: 'sppooSpecialityName', text: 'sppooSpecialityName' },
      { value: 'registrationNumberTotal', text: 'registrationNumberTotal' },
      { value: 'registrationNumberYear', text: 'registrationNumberYear' },
      { value: 'registrationDate', text: 'registrationDate' },
      { value: 'personalId', text: 'personalId' },
      { value: 'firstName', text: 'firstName' },
      { value: 'firstNameLatin', text: 'firstNameLatin' },
      { value: 'middleName', text: 'middleName' },
      { value: 'middleNameLatin', text: 'middleNameLatin' },
      { value: 'lastName', text: 'lastName' },
      { value: 'lastNameLatin', text: 'lastNameLatin' },
      { value: 'nationality', text: 'nationality' },
      { value: 'examSubject', text: 'examSubject' },
      { value: 'basicClass', text: 'basicClass' },
      { value: 'yearGraduated', text: 'yearGraduated' },
      { value: 'schoolYear', text: 'schoolYear' },
      { value: 'factoryNumber', text: 'factoryNumber' },
      { value: 'series', text: 'series' },
      { value: 'protocolNumber', text: 'protocolNumber' },
      { value: 'protocolDate', text: 'protocolDate' },
      { value: 'eduDuration', text: 'eduDuration' },
      { value: 'orderNumber', text: 'orderNumber' },
      { value: 'orderDate', text: 'orderDate' },
      { value: 'principal', text: 'principal' },
      { value: 'leadTeacher', text: 'leadTeacher' },
      { value: 'deputy', text: 'deputy' },
      { value: 'examType', text: 'examType' },
      { value: 'birthDate', text: 'birthDate' },
      { value: 'graduationCommissionHead', text: 'graduationCommissionHead' },
      { value: 'gpa', text: 'gpa' },
      { value: 'gpaText', text: 'gpaText' },
      { value: 'stateExamQualificationGrade', text: 'stateExamQualificationGrade' },
      { value: 'stateExamQualificationGradeText', text: 'stateExamQualificationGradeText' },
      { value: 'relatedDiplomaSeries', text: 'relatedDiplomaSeries' },
      { value: 'relatedDiplomaFactoryNumber', text: 'relatedDiplomaFactoryNumber' },
      { value: 'relatedDiplomaRegistrationNumber', text: 'relatedDiplomaRegistrationNumber' },
      { value: 'relatedDiplomaRegistrationDate', text: 'relatedDiplomaRegistrationDate' },
      { value: 'relatedDiplomaInstitution', text: 'relatedDiplomaInstitution' },
      { value: 'relatedDiplomaInstitutionTown', text: 'relatedDiplomaInstitutionTown' },
      { value: 'relatedDiplomaInstitutionMunicipality', text: 'relatedDiplomaInstitutionMunicipality' },
      { value: 'relatedDiplomaInstitutionLocalArea', text: 'relatedDiplomaInstitutionLocalArea' },
      { value: 'relatedDiplomaInstitutionRegion', text: 'relatedDiplomaInstitutionRegion' },
      { value: 'description', text: 'description' },
      { value: 'ekr', text: 'ekr' },
      { value: 'nkr', text: 'nkr' },
      { value: 'classType', text: 'classType' },
      { value: 'classTypeName', text: 'classTypeName' },
      { value: 'qualification', text: 'vetQualification' },
      { value: 'vetLevel', text: 'vetLevel' },
      { value: 'itLevel', text: 'itLevel' },
      { value: 'flgeLevel', text: 'flgeLevel' },
      { value: 'birthPlaceTownForeign', text: 'birthPlaceTownForeign' },
      { value: 'birthPlaceRegionForeign', text: 'birthPlaceRegionForeign' },
      { value: 'birthPlaceMunicipalityForeign', text: 'birthPlaceMunicipalityForeign' },
      { value: 'nationalityForeign', text: 'nationalityForeign' },
      { value: 'institutionTownForeign', text: 'institutionTownForeign' },
      { value: 'institutionRegionForeign', text: 'institutionRegionForeign' },
      { value: 'institutionMunicipalityForeign', text: 'institutionMunicipalityForeign' },
      { value: 'institutionLocalAreaForeign', text: 'institutionLocalAreaForeign' },
      { value: 'institutionForeign', text: 'institutionForeign' },
    ],
      PredefinedFields: [
        { value: '/api/lookups/GetMinistryOptions', text: 'ministry - /api/lookups/GetMinistryOptions', name: 'ministry', type: 'SelectList', label: 'Министерство', returnObject: true, deferOptionsLoading: false },
        { value: '/api/lookups/GetInstitutionOptions', text: 'institution - /api/lookups/GetInstitutionOptions', name: 'institution', type: 'AutoComplete', label: 'Наименование на институцията', returnObject: true },
        { value: '/api/lookups/GetCities', text: 'institutionTown - /api/lookups/GetCities', name: 'institutionTown', type: 'SelectList', label: 'Град/село' },
        { value: '/api/lookups/GetMunicipalities', text: 'institutionMunicipality - /api/lookups/GetMunicipalities', name: 'institutionMunicipality', type: 'SelectList', label: 'Община' },
        { value: '/api/lookups/GetLocalAreasOptions', text: 'institutionLocalArea - /api/lookups/GetLocalAreasOptions', name: 'institutionLocalArea', type: 'SelectList', label: 'Район' },
        { value: '/api/lookups/GetDistricts', text: 'institutionRegion - /api/lookups/GetDistricts', name: 'institutionRegion', type: 'SelectList', label: 'Област' },
        { value: '/api/lookups/GetGenders', text: 'gender - /api/lookups/GetGenders', name: 'gender', type: 'SelectList', label: 'Пол' },
        { value: '/api/lookups/GetCities', text: 'birthPlaceTown - /api/lookups/GetCities', name: 'birthPlaceTown', type: 'AutoComplete', label: 'Град/село', itemValue: 'text', itemText: 'text', returnObject: false },
        { value: '/api/lookups/GetMunicipalities', text: 'birthPlaceMunicipality - /api/lookups/GetMunicipalities', name: 'birthPlaceMunicipality', type: 'AutoComplete', label: 'Община', itemValue: 'text', itemText: 'text', returnObject: false },
        { value: '/api/lookups/GetLocalAreasOptions', text: 'birthPlaceLocalArea - /api/lookups/GetLocalAreasOptions', name: 'birthPlaceLocalArea', type: 'AutoComplete', label: 'Район', itemValue: 'text', itemText: 'text', returnObject: false },
        { value: '/api/lookups/GetDistricts', text: 'birthPlaceRegion - /api/lookups/GetDistricts', name: 'birthPlaceRegion', type: 'SelectList', label: 'Област', itemValue: 'text', itemText: 'text', returnObject: false },
        { value: '/api/lookups/GetSpecialityOptions', text: 'speciality - /api/lookups/GetSpecialityOptions', name: 'speciality', type: 'AutoComplete', label: 'Специалност' },
        { value: '/api/lookups/GetEducationFormDiplomaOptions', text: 'eduForm - /api/lookups/GetEducationFormDiplomaOptions', name: 'eduForm', type: 'AutoComplete', label: 'Форма на обучение', required: true, deferOptionsLoading: false },
        { value: '/api/lookups/GetDocumentEducationTypeOptions', text: 'educationType - /api/lookups/GetDocumentEducationTypeOptions', name: 'educationType', type: 'AutoComplete', label: 'Тип на обучение', required: false, deferOptionsLoading: false },
        { value: '/api/lookups/GetSPPOOProfession', text: 'sppooProfession - /api/lookups/GetSPPOOProfession', name: 'sppooProfession', type: 'AutoComplete', label: 'Професия' },
        { value: '/api/lookups/GetSPPOOSpeciality', text: 'sppooSpeciality - /api/lookups/GetSPPOOSpeciality', name: 'sppooSpeciality', type: 'AutoComplete', label: 'Специалност' },
        { value: '/api/lookups/GetEKROptions', text: 'ekr - /api/lookups/GetEKROptions', name: 'ekr', type: 'AutoComplete', label: 'Ниво по ЕКР' },
        { value: '/api/lookups/GetNKROptions', text: 'ekr - /api/lookups/GetNKROptions', name: 'nkr', type: 'AutoComplete', label: 'Ниво по НКР' },
        { value: null, text: null, name: 'registrationNumberTotal', type: 'TextField', required: true, label: 'Рег.No' },
        { value: null, text: null, name: 'registrationNumberYear', type: 'TextField', required: true, label: 'Рег.No за годината' },
        { value: null, text: null, name: 'registrationDate', type: 'DateField', required: true, label: 'Дата на регистрация' },
        { value: null, text: null, name: 'personalId', type: 'PersonUniqueIdField', required: true, label: '' },
        { value: null, text: null, name: 'firstName', type: 'TextField', required: true, label: 'Име' },
        { value: null, text: null, name: 'firstNameLatin', type: 'TextField', required: false, label: 'Име на латиница' },
        { value: null, text: null, name: 'middleName', type: 'TextField', required: false, label: 'Презиме' },
        { value: null, text: null, name: 'middleNameLatin', type: 'TextField', required: false, label: 'Презиме на латиница' },
        { value: null, text: null, name: 'lastName', type: 'TextField', required: true, label: 'Фамилия' },
        { value: null, text: null, name: 'lastNameLatin', type: 'TextField', required: false, label: 'Фамилия на латиница' },
        { value: '/api/lookups/GetCountriesBySearchString', text: 'nationality - /api/lookups/GetCountriesBySearchString', name: 'nationality', type: 'AutoComplete', required: false, label: 'Гражданство', returnObject: true },
        { value: '/api/lookups/GetSubjectOptions', text: 'examSubject - /api/lookups/GetSubjectOptions', name: 'examSubject', type: 'AutoComplete', required: false, label: 'Учебен предмет' },
        { value: '/api/lookups/GetBasicClassOptions', text: 'basicClass - /api/lookups/GetBasicClassOptions', name: 'basicClass', type: 'AutoComplete', required: false, label: 'Клас' },
        { value: '', text: '', name: 'schoolYear', type: 'SchoolYearField', required: true, label: 'Учебна година' },
        { value: '', text: '', name: 'yearGraduated', type: 'YearPicker', required: false, label: 'Година за завършване' },
        { value: '', text: '', name: 'factoryNumber', type: 'TextField', required: false, label: 'Фабричен номер' },
        { value: '', text: '', name: 'series', type: 'TextField', required: false, label: 'Серия' },
        { value: '', text: '', name: 'protocolNumber', type: 'TextField', required: false, label: 'Протокол №' },
        { value: '', text: '', name: 'protocolDate', type: 'DateField', required: false, label: 'Протокол дата' },
        { value: '', text: '', name: 'eduDuration', type: 'NumberField', required: false, label: 'Срок на обучение (години)' },
        { value: '', text: '', name: 'orderNumber', type: 'TextField', required: false, label: 'Заповед №' },
        { value: '', text: '', name: 'orderDate', type: 'DateField', required: false, label: 'Заповед дата' },
        { value: '', text: '', name: 'principal', type: 'TextField', required: true, label: 'Директор: Име и фамилия' },
        { value: '', text: '', name: 'deputy', type: 'TextField', required: false, label: 'Пълномощник: Име и фамилия' },
        { value: '', text: '', name: 'graduationCommissionHead', type: 'TextField', required: false, label: 'Председател на изпитна комисия: Име и фамилия' },
        { value: '', text: '', name: 'leadTeacher', type: 'TextField', required: true, label: 'Класен ръководител: Име и фамилия' },
        { value: '/api/lookups/GetExamTypeOptions', text: 'examType - /api/lookups/GetExamTypeOptions', name: 'examType', type: 'AutoComplete', required: false, label: 'Вид изпит' },
        { value: '', text: '', name: 'birthDate', type: 'DateField', required: false, label: 'Дата на раждане' },
        { value: '', text: '', name: 'gpa', type: 'NumberField', required: true, label: 'Успех с цифри', min: 3, max: 6 },
        { value: '', text: '', name: 'gpaText', type: 'TextField', required: true, label: 'Успех с думи' },
        { value: '', text: '', name: 'stateExamQualificationGrade', type: 'TextField', required: false, label: 'Успех с цифри (Държавен изпит за придобиване на професионална квалификация)'},
        { value: '', text: '', name: 'stateExamQualificationGradeText', type: 'TextField', required: false, label: 'Успех с думи (Държавен изпит за придобиване на професионална квалификация)' },
        { value: '', text: '', name: 'relatedDiplomaSeries', type: 'TextField', required: false, label: 'Серия' },
        { value: '', text: '', name: 'relatedDiplomaFactoryNumber', type: 'TextField', required: false, label: 'Фабричен номер' },
        { value: '', text: '', name: 'description', type: 'TextAreaField', required: false, label: 'Резултати/ Описание' },
        { value: null, text: null, name: 'relatedDiplomaRegistrationNumber', type: 'TextField', required: true, label: 'Рег.No' },
        { value: null, text: null, name: 'relatedDiplomaRegistrationDate', type: 'DateField', required: true, label: 'Дата на регистрация' },
        { value: '/api/lookups/GetInstitutionOptions', text: 'relatedDiplomaInstitution =/api/lookups/GetInstitutionOptions', name: 'relatedDiplomaInstitution', type: 'SelectList', required: true, label: 'Училище издало дипломата' },
        { value: '/api/lookups/GetCities', text: 'relatedDiplomaInstitutionTown - /api/lookups/GetCities', name: 'relatedDiplomaInstitutionTown', type: 'SelectList', required: false, label: 'Град/село' },
        { value: '/api/lookups/GetMunicipalities', text: 'relatedDiplomaInstitutionMunicipality - /api/lookups/GetMunicipalities', name: 'relatedDiplomaInstitutionMunicipality', type: 'SelectList', label: 'Община' },
        { value: '/api/lookups/GetLocalAreasOptions', text: 'relatedDiplomaInstitutionLocalArea - /api/lookups/GetLocalAreasOptions', name: 'relatedDiplomaInstitutionLocalArea', type: 'SelectList', label: 'Район' },
        { value: '/api/lookups/GetDistricts', text: 'relatedDiplomaInstitutionRegion - /api/lookups/GetDistricts', name: 'relatedDiplomaInstitutionRegion', type: 'SelectList', label: 'Област' },
        { value: '/api/lookups/GetClassTypeDiplomaOptions', text: 'classType - /api/lookups/GetClassTypeDiplomaOptions', name: 'classType', type: 'SelectList', label: 'Профил' },
        { value: '', text: '', name: 'classTypeName', type: 'TextField', label: 'Профил при печат', clearable: true},
        { value: '', text: '', name: 'sppooProfessionName', type: 'TextField', label: 'Професия при печат', clearable: true},
        { value: '', text: '', name: 'sppooSpecialityName', type: 'TextField', label: 'Специалност при печат', clearable: true},
        { value: '', text: '', name: 'qualification', type: 'TextField', required: false, label: 'Квалификация' },
        { value: '/api/lookups/GetVetLevelOptions', text: 'velLevel - /api/lookups/GetVetLevelOptions', name: 'vetLevel', type: 'AutoComplete', required: false, label: 'Степен на професионална квалификация', returnObject: false, itemValue: 'value', itemText: 'text' },
        { value: '/api/lookups/GetITLevelOptions', text: 'itLevel - /api/lookups/GetITLevelOptions', name: 'itLevel', type: 'AutoComplete', required: false, label: 'Ниво от Европейската референтна рамка за дигитални компетентности' },
        { value: '/api/lookups/GetFLLevelOptions', text: 'flgeLevel - /api/lookups/GetFLLevelOptions', name: 'flgeLevel', type: 'AutoComplete', required: false, label: 'Ниво от Общата европейска езикова рамка', itemValue:"text",  itemText:"text" },
        { value: '', text: '', name: 'birthPlaceTownForeign', type: 'TextField', required: true, label: 'Град/село на латиница' },
        { value: '', text: '', name: 'birthPlaceRegionForeign', type: 'TextField', required: true, label: 'Област на латиница' },
        { value: '', text: '', name: 'birthPlaceMunicipalityForeign', type: 'TextField', required: true, label: 'Община на латиница' },
        { value: '', text: '', name: 'nationalityForeign', type: 'TextField', required: true, label: 'Гражданство на латиница' },
        { value: '', text: '', name: 'institutionTownForeign', type: 'TextField', required: true, label: 'Град/село на латиница' },
        { value: '', text: '', name: 'institutionLocalAreaForeign', type: 'TextField', required: true, label: 'Район на латиница' },
        { value: '', text: '', name: 'institutionMunicipalityForeign', type: 'TextField', required: true, label: 'Община на латиница' },
        { value: '', text: '', name: 'institutionRegionForeign', type: 'TextField', required: true, label: 'Област на латиница' },
        { value: '', text: '', name: 'institutionForeign', type: 'TextField', required: true, label: 'Наименование на институцията на латиница' },
      ],
  },
  gradeCategoryOptions: [
    { value: 1, text: 'Оценка' },
    { value: 2, text: 'СОП' },
    { value: 3, text: 'Друга' },
    { value: 4, text: 'Качествена' },
  ],
  ectsGradeOptions: [
    { value: 'A', text: 'A' },
    { value: 'B', text: 'B' },
    { value: 'C', text: 'C' },
    { value: 'D', text: 'D' },
    { value: 'E', text: 'E' },
  ],
  gradeTextOptions: [
    { value: 'Слаб', min: Number.MIN_VALUE, max: 3 },
    { value: 'Среден', min: 3, max: 3.5 },
    { value: 'Добър', min: 3.5, max: 4.5 },
    { value: 'Много добър', min: 4.5, max: 5.5 },
    { value: 'Отличен', min: 5.5, max: Number.MAX_VALUE }
  ],
  subjectTypeToModulesLimit: [152,153,154,155,156],
  moduleSubjectTypeOptions: [
    { value: 105, text: 'ПП/зад.модул' },
    { value: 151, text: 'ПП/изб.модул' },
  ],
  profilingSubjectTypes: ['ПП/изб.модул', 'ПП (I профилиращ предмет)', 'ПП (II профилиращ предмет)', 'ПП (III профилиращ предмет)', 'ПП (IV профилиращ предмет)'],
  EqualizationEnableClassReasonId: 1,
  OopSubjectTypeId: 101,
  OresInheritanceTypeOptions: [
    { value: 'institution', text: i18n.t('common.institution') },
    { value: 'class', text: i18n.t('student.class') },
    { value: 'student', text: i18n.tc('student.title', 1) },
  ],
  ReassessmentEnableClassReasonId: 1,
});
