namespace SB.Domain;

using System;

public static class SchedulesModelSample
{
    public static readonly SchedulesModel Sample =
        new(
            new SchedulesModelSchedule[]
            {
                new SchedulesModelSchedule(
                    null,
                    null,
                    new DateTime(2021, 09, 15),
                    new DateTime(2022, 02, 01),
                    new SchedulesModelScheduleLessons[]
                    {
                        new SchedulesModelScheduleLessons(1, 1, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(1, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(1, 3, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(1, 4, "Изобразително изкуство", "ООП"),
                        new SchedulesModelScheduleLessons(1, 5, "Изобразително изкуство", "ООП"),
                        new SchedulesModelScheduleLessons(1, 6, "Час на класа", "…"),
                        new SchedulesModelScheduleLessons(2, 1, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(2, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(2, 3, "Чужд език - Английски език", "ООП"),
                        new SchedulesModelScheduleLessons(2, 4, "Чужд език - Английски език", "РП/УП-А"),
                        new SchedulesModelScheduleLessons(2, 5, "Музика", "ООП"),
                        new SchedulesModelScheduleLessons(2, 6, "Татковина", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(3, 1, "Физическо възпитание и спорт", "ООП"),
                        new SchedulesModelScheduleLessons(3, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(3, 3, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(3, 4, "Технологии и предприемачество", "ООП"),
                        new SchedulesModelScheduleLessons(3, 5, "Околен свят", "ООП"),
                        new SchedulesModelScheduleLessons(3, 6, "Родина", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(4, 1, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(4, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(4, 3, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(4, 4, "Музика", "ООП"),
                        new SchedulesModelScheduleLessons(4, 5, "Спортни дейности (лека атлетика)", "…"),
                        new SchedulesModelScheduleLessons(5, 1, "Физическо възпитание и спорт", "ООП"),
                        new SchedulesModelScheduleLessons(5, 2, "Български език и литература", "РП/УП-А"),
                        new SchedulesModelScheduleLessons(5, 3, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(5, 4, "Чужд език - Английски език", "ООП"),
                        new SchedulesModelScheduleLessons(5, 5, "Чужд език - Английски език", "РП/УП-А"),
                        new SchedulesModelScheduleLessons(5, 6, "Трудово", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(5, 7, "Трудово", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(5, 8, "Трудово", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(5, 9, "Трудово", "ДП/ДрУП"),
                    }),
                new SchedulesModelSchedule(
                    null,
                    null,
                    new DateTime(2021, 11, 15),
                    new DateTime(2021, 11, 28),
                    new SchedulesModelScheduleLessons[]
                    {
                        new SchedulesModelScheduleLessons(1, 1, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(1, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(1, 3, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(1, 4, "Изобразително изкуство", "ООП"),
                        new SchedulesModelScheduleLessons(1, 5, "Изобразително изкуство", "ООП"),
                        new SchedulesModelScheduleLessons(1, 6, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(2, 1, "Татковина", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(2, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(2, 3, "Чужд език - Английски език", "ООП"),
                        new SchedulesModelScheduleLessons(2, 4, "Чужд език - Английски език", "РП/УП-А"),
                        new SchedulesModelScheduleLessons(2, 5, "Музика", "ООП"),
                        new SchedulesModelScheduleLessons(2, 6, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(3, 1, "Физическо възпитание и спорт", "ООП"),
                        new SchedulesModelScheduleLessons(3, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(3, 3, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(3, 4, "Технологии и предприемачество", "ООП"),
                        new SchedulesModelScheduleLessons(3, 5, "Околен свят", "ООП"),
                        new SchedulesModelScheduleLessons(3, 6, "Родина", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(4, 1, "Час на класа", "…"),
                        new SchedulesModelScheduleLessons(4, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(4, 3, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(4, 4, "Музика", "ООП"),
                        new SchedulesModelScheduleLessons(4, 5, "Спортни дейности (лека атлетика)", "…"),
                        new SchedulesModelScheduleLessons(5, 1, "Физическо възпитание и спорт", "ООП"),
                        new SchedulesModelScheduleLessons(5, 2, "Български език и литература", "РП/УП-А"),
                        new SchedulesModelScheduleLessons(5, 3, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(5, 4, "Чужд език - Английски език", "ООП"),
                        new SchedulesModelScheduleLessons(5, 5, "Чужд език - Английски език", "РП/УП-А"),
                        new SchedulesModelScheduleLessons(5, 6, "Трудово", "ДП/ДрУП"),
                    }),
                new SchedulesModelSchedule(
                    null,
                    null,
                    new DateTime(2021, 11, 29),
                    new DateTime(2021, 12, 05),
                    new SchedulesModelScheduleLessons[]
                    {
                        new SchedulesModelScheduleLessons(1, 1, "Час на класа", "…"),
                        new SchedulesModelScheduleLessons(1, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(1, 3, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(1, 4, "Изобразително изкуство", "ООП"),
                        new SchedulesModelScheduleLessons(1, 5, "Изобразително изкуство", "ООП"),
                        new SchedulesModelScheduleLessons(1, 6, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(2, 1, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(2, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(2, 3, "Чужд език - Английски език", "ООП"),
                        new SchedulesModelScheduleLessons(2, 4, "Чужд език - Английски език", "РП/УП-А"),
                        new SchedulesModelScheduleLessons(2, 5, "Музика", "ООП"),
                        new SchedulesModelScheduleLessons(2, 6, "Татковина", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(3, 1, "Физическо възпитание и спорт", "ООП"),
                        new SchedulesModelScheduleLessons(3, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(3, 3, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(3, 4, "Технологии и предприемачество", "ООП"),
                        new SchedulesModelScheduleLessons(3, 5, "Околен свят", "ООП"),
                        new SchedulesModelScheduleLessons(3, 6, "Родина", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(4, 1, "Музика", "ООП"),
                        new SchedulesModelScheduleLessons(4, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(4, 3, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(4, 4, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(4, 5, "Спортни дейности (лека атлетика)", "…"),
                        new SchedulesModelScheduleLessons(5, 1, "Физическо възпитание и спорт", "ООП"),
                        new SchedulesModelScheduleLessons(5, 2, "Български език и литература", "РП/УП-А"),
                        new SchedulesModelScheduleLessons(5, 3, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(5, 4, "Чужд език - Английски език", "ООП"),
                        new SchedulesModelScheduleLessons(5, 5, "Чужд език - Английски език", "РП/УП-А"),
                        new SchedulesModelScheduleLessons(5, 6, "Трудово", "ДП/ДрУП"),
                    }),
                new SchedulesModelSchedule(
                    null,
                    null,
                    new DateTime(2022, 02, 02),
                    new DateTime(2022, 06, 30),
                    new SchedulesModelScheduleLessons[]
                    {
                        new SchedulesModelScheduleLessons(1, 1, "Час на класа", "…"),
                        new SchedulesModelScheduleLessons(1, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(1, 3, "Чужд език - Английски език", "ООП"),
                        new SchedulesModelScheduleLessons(1, 4, "Чужд език - Английски език", "ООП"),
                        new SchedulesModelScheduleLessons(1, 5, "Спортни дейности (лека атлетика)", "…"),
                        new SchedulesModelScheduleLessons(1, 6, "Музика", "ООП"),
                        new SchedulesModelScheduleLessons(2, 1, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(2, 2, "Физическо възпитание и спорт", "ООП"),
                        new SchedulesModelScheduleLessons(2, 3, "Чужд език - Английски език", "РП/УП-А"),
                        new SchedulesModelScheduleLessons(2, 4, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(2, 5, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(2, 6, "Татковина", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(3, 1, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(3, 2, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(3, 3, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(3, 4, "Изобразително изкуство", "ООП"),
                        new SchedulesModelScheduleLessons(3, 5, "Рисуване", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(4, 1, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(4, 2, "Математика", "ООП"),
                        new SchedulesModelScheduleLessons(4, 3, "Чужд език - Английски език", "РП/УП-А"),
                        new SchedulesModelScheduleLessons(4, 4, "Околен свят", "ООП"),
                        new SchedulesModelScheduleLessons(4, 5, "Родина", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(4, 6, "Музика", "ООП"),
                        new SchedulesModelScheduleLessons(5, 1, "Български език и литература", "ООП"),
                        new SchedulesModelScheduleLessons(5, 2, "Български език и литература", "РП/УП-А"),
                        new SchedulesModelScheduleLessons(5, 3, "Физическо възпитание и спорт", "ООП"),
                        new SchedulesModelScheduleLessons(5, 4, "Технологии и предприемачество", "ООП"),
                        new SchedulesModelScheduleLessons(5, 5, "Трудово", "ДП/ДрУП"),
                        new SchedulesModelScheduleLessons(5, 6, "Татковина", "ДП/ДрУП"),
                    }),
            },
            Array.Empty<SchedulesModelSchedule>()
        );
}
