def backendImage
def backendImageNameTag
def backendImageNameLatestTag
def tag
def branchName
def buildLatest = true
def prodKeysDirectory = '/home/neispuoadmin/oidc-prod-keys'

def adoRegistry = "${env.ADO_REGISTRY_NAME}/${env.ADO_REGISTRY_PROJECT_NAME}"
def adoRegistryCredentials = env.ADO_REGISTRY_CREDENTIALS

def azurePatId = "${env.AZURE_PAT_ID}"

def decodeBase64(String encoded) {
    return sh(script: "echo '${encoded}' | base64 -d", returnStdout: true).trim()
}

pipeline {
    agent { node { label 'mon-neispuo-image-builder' } }
    stages {
        stage('Run semantic-release') {
            steps {
                script {
                    branchName = "${env.GIT_BRANCH}".tokenize('/').last()
                    buildName "#${env.BUILD_NUMBER} ${branchName} TBD"
                    def lastCommitMessage = sh(script: "git log -1 | grep '.*\\[skip ci\\].*'", returnStatus: true)
                    // if (lastCommitMessage == 0) {
                    //     env.CI_SKIP = 'true'
                    //     error "'[ci skip]' found in git commit message. Aborting."
                    // }
                    def currentBranch = sh(script: "git rev-parse --abbrev-ref HEAD", returnStdout: true).trim()
                    if (currentBranch == env.BRANCH_NAME) {
                        sh('git tag -l | xargs git tag -d')
                        withCredentials([
                            gitUsernamePassword(
                                credentialsId: "${env.REPO_CREDENTIALS}",
                                gitToolName: 'git-tool'
                            ),
                            string(
                                credentialsId: azurePatId,
                                variable: 'AZURE_PAT_ENCODED'
                            )
                        ]) {
                            env.AZURE_PAT_DECODED = decodeBase64(env.AZURE_PAT_ENCODED)
                            sh('git fetch -t')
                            nvm('v16.13.0') {
                                sh "npm=\$(which npm)"
                                sh 'npm install'
                                sh 'npm run release'
                            }
                        }
                    }
                }
            }
        }
        stage('Preset environment details details') {
            steps {
                script {
                    branchName = "${env.GIT_BRANCH}".tokenize('/').last()
                    if (branchName == 'staging') {
                        tag = sh(returnStdout: true, script: "git tag --sort version:refname | cat | awk '/next/' | tail -1").trim()
                    } else if (branchName == 'master') {
                        buildLatest = false
                        tag = sh(returnStdout: true, script: "git tag --sort version:refname | cat | awk '!/next/' | tail -1").trim()
                    } else {
                        scmSkip(deleteBuild: true)
                    }
                    backendImageNameTag = "${adoRegistry}/${env.BACKEND_IMAGE_NAME}:${tag}"
                    if (buildLatest) {
                        backendImageNameLatestTag = "${adoRegistry}/${env.BACKEND_IMAGE_NAME}:latest"
                    }
                    // https://plugins.jenkins.io/build-name-setter/
                    buildName "#${env.BUILD_NUMBER} ${branchName} ${tag}"
                }
            }
        }

        stage('Build and tag images') {
            steps {
                    dir("${env.WORKSPACE}/${env.BACKEND_PROJECT_PATH}") {
                        script {
                            sh "cp ${prodKeysDirectory}/* app/support/"
                            backendImage = docker.build("${backendImageNameTag}", ". --no-cache -f ${env.WORKSPACE}/${env.BACKEND_PROJECT_PATH}/Dockerfile")
                        }
                    }
            }
        }
        stage('Push images to Azure DevOps registry') {
            steps {
                script {
                    docker.withRegistry("https://${adoRegistry}", "${adoRegistryCredentials}") {
                        backendImage.push(tag)
                        if (buildLatest) {
                            backendImage.push('latest')
                        }
                    }
                }
            }
        }
        stage('Clean up images') {
            steps {
                sh "docker rmi ${backendImageNameTag} -f"
                script {
                    if (buildLatest) {
                        sh "docker rmi ${backendImageNameLatestTag} -f"
                    }
                }

                sh 'docker system prune -f'
            }
        }
    }
}
