/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export type AbsenceType = 'Late' | 'Unexcused' | 'Excused' | 'DplrAbsence' | 'DplrAttendance';

export const AbsenceType = {
    Late: 'Late' as AbsenceType,
    Unexcused: 'Unexcused' as AbsenceType,
    Excused: 'Excused' as AbsenceType,
    DplrAbsence: 'DplrAbsence' as AbsenceType,
    DplrAttendance: 'DplrAttendance' as AbsenceType
};

export function AbsenceTypeFromJSON(json: any): AbsenceType {
    return json as AbsenceType;
}

export function AbsenceTypeToJSON(value?: AbsenceType | null): any {
    return value as any;
}

