/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface AddConversationMessageCommand { 
    conversationId: number;
    message: string;
}

export function AddConversationMessageCommandFromJSON(json: any): AddConversationMessageCommand {
    if (json == null) {
        return json;
    }

    return {
        'conversationId': json['conversationId'],
        'message': json['message'],
    };
}

export function AddConversationMessageCommandToJSON(value?: AddConversationMessageCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        'conversationId': value.conversationId,
        'message': value.message,
    };
}

