/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface AdditionalActivitiesGetAllAdditionalActivitiesForWeekVO { 
    additionalActivityId: number;
    activity: string;
    hasCreatorAccess: boolean;
}

export function AdditionalActivitiesGetAllAdditionalActivitiesForWeekVOFromJSON(json: any): AdditionalActivitiesGetAllAdditionalActivitiesForWeekVO {
    if (json == null) {
        return json;
    }

    return {
        'additionalActivityId': json['additionalActivityId'],
        'activity': json['activity'],
        'hasCreatorAccess': json['hasCreatorAccess'],
    };
}

export function AdditionalActivitiesGetAllAdditionalActivitiesForWeekVOToJSON(value?: AdditionalActivitiesGetAllAdditionalActivitiesForWeekVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'additionalActivityId': value.additionalActivityId,
        'activity': value.activity,
        'hasCreatorAccess': value.hasCreatorAccess,
    };
}

