/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { AttendanceType, AttendanceTypeFromJSON, AttendanceTypeToJSON } from './attendanceType';


export interface AttendancesGetVO { 
    attendanceId: number;
    personId: number;
    date: Date;
    type: AttendanceType;
    excusedReasonId?: number | null;
    excusedReasonName?: string | null;
    excusedReasonComment?: string | null;
    createDate: Date;
    createdBySysUserId: number;
    createdBySysUserFirstName: string;
    createdBySysUserMiddleName?: string | null;
    createdBySysUserLastName: string;
    modifyDate: Date;
    modifiedBySysUserId: number;
    modifiedBySysUserFirstName: string;
    modifiedBySysUserMiddleName?: string | null;
    modifiedBySysUserLastName: string;
    hasExcuseAccess: boolean;
    hasUndoAccess: boolean;
    hasRemoveAccess: boolean;
}

export function AttendancesGetVOFromJSON(json: any): AttendancesGetVO {
    if (json == null) {
        return json;
    }

    return {
        'attendanceId': json['attendanceId'],
        'personId': json['personId'],
        'date': isoStringToLocalDateTime(json['date']),
        'type': AttendanceTypeFromJSON(json['type']),
        'excusedReasonId': json['excusedReasonId'],
        'excusedReasonName': json['excusedReasonName'],
        'excusedReasonComment': json['excusedReasonComment'],
        'createDate': isoStringToLocalDateTime(json['createDate']),
        'createdBySysUserId': json['createdBySysUserId'],
        'createdBySysUserFirstName': json['createdBySysUserFirstName'],
        'createdBySysUserMiddleName': json['createdBySysUserMiddleName'],
        'createdBySysUserLastName': json['createdBySysUserLastName'],
        'modifyDate': isoStringToLocalDateTime(json['modifyDate']),
        'modifiedBySysUserId': json['modifiedBySysUserId'],
        'modifiedBySysUserFirstName': json['modifiedBySysUserFirstName'],
        'modifiedBySysUserMiddleName': json['modifiedBySysUserMiddleName'],
        'modifiedBySysUserLastName': json['modifiedBySysUserLastName'],
        'hasExcuseAccess': json['hasExcuseAccess'],
        'hasUndoAccess': json['hasUndoAccess'],
        'hasRemoveAccess': json['hasRemoveAccess'],
    };
}

export function AttendancesGetVOToJSON(value?: AttendancesGetVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'attendanceId': value.attendanceId,
        'personId': value.personId,
        'date': dateTimeToLocalIsoString(value.date),
        'type': AttendanceTypeToJSON(value.type),
        'excusedReasonId': value.excusedReasonId,
        'excusedReasonName': value.excusedReasonName,
        'excusedReasonComment': value.excusedReasonComment,
        'createDate': dateTimeToLocalIsoString(value.createDate),
        'createdBySysUserId': value.createdBySysUserId,
        'createdBySysUserFirstName': value.createdBySysUserFirstName,
        'createdBySysUserMiddleName': value.createdBySysUserMiddleName,
        'createdBySysUserLastName': value.createdBySysUserLastName,
        'modifyDate': dateTimeToLocalIsoString(value.modifyDate),
        'modifiedBySysUserId': value.modifiedBySysUserId,
        'modifiedBySysUserFirstName': value.modifiedBySysUserFirstName,
        'modifiedBySysUserMiddleName': value.modifiedBySysUserMiddleName,
        'modifiedBySysUserLastName': value.modifiedBySysUserLastName,
        'hasExcuseAccess': value.hasExcuseAccess,
        'hasUndoAccess': value.hasUndoAccess,
        'hasRemoveAccess': value.hasRemoveAccess,
    };
}

