/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { ClassBookPrintStatus, ClassBookPrintStatusFromJSON, ClassBookPrintStatusToJSON } from './classBookPrintStatus';


export interface ClassBooksAdminGetStudentPrintsVO { 
    createDate: Date;
    createBySysUserFirstName: string;
    createBySysUserLastName: string;
    studentName: string;
    status: ClassBookPrintStatus;
    blobDownloadUrl?: string | null;
}

export function ClassBooksAdminGetStudentPrintsVOFromJSON(json: any): ClassBooksAdminGetStudentPrintsVO {
    if (json == null) {
        return json;
    }

    return {
        'createDate': isoStringToLocalDateTime(json['createDate']),
        'createBySysUserFirstName': json['createBySysUserFirstName'],
        'createBySysUserLastName': json['createBySysUserLastName'],
        'studentName': json['studentName'],
        'status': ClassBookPrintStatusFromJSON(json['status']),
        'blobDownloadUrl': json['blobDownloadUrl'],
    };
}

export function ClassBooksAdminGetStudentPrintsVOToJSON(value?: ClassBooksAdminGetStudentPrintsVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'createDate': dateTimeToLocalIsoString(value.createDate),
        'createBySysUserFirstName': value.createBySysUserFirstName,
        'createBySysUserLastName': value.createBySysUserLastName,
        'studentName': value.studentName,
        'status': ClassBookPrintStatusToJSON(value.status),
        'blobDownloadUrl': value.blobDownloadUrl,
    };
}

