/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface ClassBookTopicPlanItemsGetVO { 
    number: number;
    title: string;
    taken: boolean;
    note?: string | null;
}

export function ClassBookTopicPlanItemsGetVOFromJSON(json: any): ClassBookTopicPlanItemsGetVO {
    if (json == null) {
        return json;
    }

    return {
        'number': json['number'],
        'title': json['title'],
        'taken': json['taken'],
        'note': json['note'],
    };
}

export function ClassBookTopicPlanItemsGetVOToJSON(value?: ClassBookTopicPlanItemsGetVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'number': value.number,
        'title': value.title,
        'taken': value.taken,
        'note': value.note,
    };
}

