/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export type ClassBookPrintStatus = 'Pending' | 'Processed' | 'Errored';

export const ClassBookPrintStatus = {
    Pending: 'Pending' as ClassBookPrintStatus,
    Processed: 'Processed' as ClassBookPrintStatus,
    Errored: 'Errored' as ClassBookPrintStatus
};

export function ClassBookPrintStatusFromJSON(json: any): ClassBookPrintStatus {
    return json as ClassBookPrintStatus;
}

export function ClassBookPrintStatusToJSON(value?: ClassBookPrintStatus | null): any {
    return value as any;
}

