/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { ClassBooksAdminGetStudentsVOParent, ClassBooksAdminGetStudentsVOParentFromJSON, ClassBooksAdminGetStudentsVOParentToJSON } from './classBooksAdminGetStudentsVOParent';


export interface ClassBooksAdminGetStudentsVO { 
    personId: number;
    classNumber?: number | null;
    isTransferred: boolean;
    studentFullName: string;
    hasSpecialNeeds: boolean;
    hasGradelessSubjects: boolean;
    activities?: string | null;
    speciality?: string | null;
    parents: Array<ClassBooksAdminGetStudentsVOParent>;
}

export function ClassBooksAdminGetStudentsVOFromJSON(json: any): ClassBooksAdminGetStudentsVO {
    if (json == null) {
        return json;
    }

    return {
        'personId': json['personId'],
        'classNumber': json['classNumber'],
        'isTransferred': json['isTransferred'],
        'studentFullName': json['studentFullName'],
        'hasSpecialNeeds': json['hasSpecialNeeds'],
        'hasGradelessSubjects': json['hasGradelessSubjects'],
        'activities': json['activities'],
        'speciality': json['speciality'],
        'parents': (json['parents'] as Array<any>)?.map(ClassBooksAdminGetStudentsVOParentFromJSON),
    };
}

export function ClassBooksAdminGetStudentsVOToJSON(value?: ClassBooksAdminGetStudentsVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'personId': value.personId,
        'classNumber': value.classNumber,
        'isTransferred': value.isTransferred,
        'studentFullName': value.studentFullName,
        'hasSpecialNeeds': value.hasSpecialNeeds,
        'hasGradelessSubjects': value.hasGradelessSubjects,
        'activities': value.activities,
        'speciality': value.speciality,
        'parents': (value.parents as Array<any>)?.map(ClassBooksAdminGetStudentsVOParentToJSON),
    };
}

