/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export type ClassBookTypeError = 'UnknownClassKind' | 'InvalidBasicClass' | 'Lvl1RegularOrLvl2CombinedMissingBasicClass' | 'Lvl1CombinedHasNoChildClassGroups' | 'NoCommonClassBookType' | 'IsLvl2Regular';

export const ClassBookTypeError = {
    UnknownClassKind: 'UnknownClassKind' as ClassBookTypeError,
    InvalidBasicClass: 'InvalidBasicClass' as ClassBookTypeError,
    Lvl1RegularOrLvl2CombinedMissingBasicClass: 'Lvl1RegularOrLvl2CombinedMissingBasicClass' as ClassBookTypeError,
    Lvl1CombinedHasNoChildClassGroups: 'Lvl1CombinedHasNoChildClassGroups' as ClassBookTypeError,
    NoCommonClassBookType: 'NoCommonClassBookType' as ClassBookTypeError,
    IsLvl2Regular: 'IsLvl2Regular' as ClassBookTypeError
};

export function ClassBookTypeErrorFromJSON(json: any): ClassBookTypeError {
    return json as ClassBookTypeError;
}

export function ClassBookTypeErrorToJSON(value?: ClassBookTypeError | null): any {
    return value as any;
}

