/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export type ClassBookType = 'Book_PG' | 'Book_I_III' | 'Book_IV' | 'Book_V_XII' | 'Book_CDO' | 'Book_DPLR' | 'Book_CSOP';

export const ClassBookType = {
    Book_PG: 'Book_PG' as ClassBookType,
    Book_I_III: 'Book_I_III' as ClassBookType,
    Book_IV: 'Book_IV' as ClassBookType,
    Book_V_XII: 'Book_V_XII' as ClassBookType,
    Book_CDO: 'Book_CDO' as ClassBookType,
    Book_DPLR: 'Book_DPLR' as ClassBookType,
    Book_CSOP: 'Book_CSOP' as ClassBookType
};

export function ClassBookTypeFromJSON(json: any): ClassBookType {
    return json as ClassBookType;
}

export function ClassBookTypeToJSON(value?: ClassBookType | null): any {
    return value as any;
}

