/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface ClassBooksAdminGetSchoolYearProgramVO { 
    classBookId: number;
    schoolYearProgram?: string | null;
}

export function ClassBooksAdminGetSchoolYearProgramVOFromJSON(json: any): ClassBooksAdminGetSchoolYearProgramVO {
    if (json == null) {
        return json;
    }

    return {
        'classBookId': json['classBookId'],
        'schoolYearProgram': json['schoolYearProgram'],
    };
}

export function ClassBooksAdminGetSchoolYearProgramVOToJSON(value?: ClassBooksAdminGetSchoolYearProgramVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'classBookId': value.classBookId,
        'schoolYearProgram': value.schoolYearProgram,
    };
}

