/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface ConversationsCreatedConversationVO { 
    conversationId: number;
    schoolYear: number;
}

export function ConversationsCreatedConversationVOFromJSON(json: any): ConversationsCreatedConversationVO {
    if (json == null) {
        return json;
    }

    return {
        'conversationId': json['conversationId'],
        'schoolYear': json['schoolYear'],
    };
}

export function ConversationsCreatedConversationVOToJSON(value?: ConversationsCreatedConversationVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'conversationId': value.conversationId,
        'schoolYear': value.schoolYear,
    };
}

