/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface ConversationsGetConversationMessagesVO { 
    messageId: number;
    content: string;
    createdByParticipantId: number;
    createDate: Date;
}

export function ConversationsGetConversationMessagesVOFromJSON(json: any): ConversationsGetConversationMessagesVO {
    if (json == null) {
        return json;
    }

    return {
        'messageId': json['messageId'],
        'content': json['content'],
        'createdByParticipantId': json['createdByParticipantId'],
        'createDate': isoStringToLocalDateTime(json['createDate']),
    };
}

export function ConversationsGetConversationMessagesVOToJSON(value?: ConversationsGetConversationMessagesVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'messageId': value.messageId,
        'content': value.content,
        'createdByParticipantId': value.createdByParticipantId,
        'createDate': dateTimeToLocalIsoString(value.createDate),
    };
}

