/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface ConversationsGetUnreadConversationsVO { 
    schoolYear: number;
    conversationId: number;
    title: string;
    messageDate: Date;
}

export function ConversationsGetUnreadConversationsVOFromJSON(json: any): ConversationsGetUnreadConversationsVO {
    if (json == null) {
        return json;
    }

    return {
        'schoolYear': json['schoolYear'],
        'conversationId': json['conversationId'],
        'title': json['title'],
        'messageDate': isoStringToLocalDateTime(json['messageDate']),
    };
}

export function ConversationsGetUnreadConversationsVOToJSON(value?: ConversationsGetUnreadConversationsVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'schoolYear': value.schoolYear,
        'conversationId': value.conversationId,
        'title': value.title,
        'messageDate': dateTimeToLocalIsoString(value.messageDate),
    };
}

