/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface CreateSupportActivityCommand { 
    supportActivityTypeId: number;
    date?: Date | null;
    target?: string | null;
    result?: string | null;
}

export function CreateSupportActivityCommandFromJSON(json: any): CreateSupportActivityCommand {
    if (json == null) {
        return json;
    }

    return {
        'supportActivityTypeId': json['supportActivityTypeId'],
        'date': isoStringToLocalDateTime(json['date']),
        'target': json['target'],
        'result': json['result'],
    };
}

export function CreateSupportActivityCommandToJSON(value?: CreateSupportActivityCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        'supportActivityTypeId': value.supportActivityTypeId,
        'date': dateTimeToLocalIsoString(value.date),
        'target': value.target,
        'result': value.result,
    };
}

