/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface CreateTopicsCommandTopic { 
    title?: string | null;
    classBookTopicPlanItemIds?: Array<number> | null;
    date: Date;
    scheduleLessonId: number;
    teacherAbsenceId?: number | null;
}

export function CreateTopicsCommandTopicFromJSON(json: any): CreateTopicsCommandTopic {
    if (json == null) {
        return json;
    }

    return {
        'title': json['title'],
        'classBookTopicPlanItemIds': (json['classBookTopicPlanItemIds']),
        'date': isoStringToLocalDateTime(json['date']),
        'scheduleLessonId': json['scheduleLessonId'],
        'teacherAbsenceId': json['teacherAbsenceId'],
    };
}

export function CreateTopicsCommandTopicToJSON(value?: CreateTopicsCommandTopic | null): any {
    if (value == null) {
        return value;
    }
    return {
        'title': value.title,
        'classBookTopicPlanItemIds': (value.classBookTopicPlanItemIds),
        'date': dateTimeToLocalIsoString(value.date),
        'scheduleLessonId': value.scheduleLessonId,
        'teacherAbsenceId': value.teacherAbsenceId,
    };
}

