/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { CreateGradeChangeExamsAdmProtocolStudentCommandSubject, CreateGradeChangeExamsAdmProtocolStudentCommandSubjectFromJSON, CreateGradeChangeExamsAdmProtocolStudentCommandSubjectToJSON } from './createGradeChangeExamsAdmProtocolStudentCommandSubject';


export interface CreateGradeChangeExamsAdmProtocolStudentCommand { 
    classId: number;
    personId: number;
    subjects: Array<CreateGradeChangeExamsAdmProtocolStudentCommandSubject>;
}

export function CreateGradeChangeExamsAdmProtocolStudentCommandFromJSON(json: any): CreateGradeChangeExamsAdmProtocolStudentCommand {
    if (json == null) {
        return json;
    }

    return {
        'classId': json['classId'],
        'personId': json['personId'],
        'subjects': (json['subjects'] as Array<any>)?.map(CreateGradeChangeExamsAdmProtocolStudentCommandSubjectFromJSON),
    };
}

export function CreateGradeChangeExamsAdmProtocolStudentCommandToJSON(value?: CreateGradeChangeExamsAdmProtocolStudentCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        'classId': value.classId,
        'personId': value.personId,
        'subjects': (value.subjects as Array<any>)?.map(CreateGradeChangeExamsAdmProtocolStudentCommandSubjectToJSON),
    };
}

