/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface CreateScheduleAndAbsencesByMonthReportCommand { 
    year: number;
    month: number;
    classBookId: number;
}

export function CreateScheduleAndAbsencesByMonthReportCommandFromJSON(json: any): CreateScheduleAndAbsencesByMonthReportCommand {
    if (json == null) {
        return json;
    }

    return {
        'year': json['year'],
        'month': json['month'],
        'classBookId': json['classBookId'],
    };
}

export function CreateScheduleAndAbsencesByMonthReportCommandToJSON(value?: CreateScheduleAndAbsencesByMonthReportCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        'year': value.year,
        'month': value.month,
        'classBookId': value.classBookId,
    };
}

