/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { CreateExamResultProtocolStudentCommandStudent, CreateExamResultProtocolStudentCommandStudentFromJSON, CreateExamResultProtocolStudentCommandStudentToJSON } from './createExamResultProtocolStudentCommandStudent';


export interface CreateExamResultProtocolStudentCommand { 
    students: Array<CreateExamResultProtocolStudentCommandStudent>;
}

export function CreateExamResultProtocolStudentCommandFromJSON(json: any): CreateExamResultProtocolStudentCommand {
    if (json == null) {
        return json;
    }

    return {
        'students': (json['students'] as Array<any>)?.map(CreateExamResultProtocolStudentCommandStudentFromJSON),
    };
}

export function CreateExamResultProtocolStudentCommandToJSON(value?: CreateExamResultProtocolStudentCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        'students': (value.students as Array<any>)?.map(CreateExamResultProtocolStudentCommandStudentToJSON),
    };
}

