/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface CreatePublicationCommandFile { 
    blobId: number;
    fileName: string;
}

export function CreatePublicationCommandFileFromJSON(json: any): CreatePublicationCommandFile {
    if (json == null) {
        return json;
    }

    return {
        'blobId': json['blobId'],
        'fileName': json['fileName'],
    };
}

export function CreatePublicationCommandFileToJSON(value?: CreatePublicationCommandFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        'blobId': value.blobId,
        'fileName': value.fileName,
    };
}

