/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { SchoolTerm, SchoolTermFromJSON, SchoolTermToJSON } from './schoolTerm';


export interface CreateScheduleAndAbsencesByTermReportCommand { 
    term: SchoolTerm;
    classBookId: number;
}

export function CreateScheduleAndAbsencesByTermReportCommandFromJSON(json: any): CreateScheduleAndAbsencesByTermReportCommand {
    if (json == null) {
        return json;
    }

    return {
        'term': SchoolTermFromJSON(json['term']),
        'classBookId': json['classBookId'],
    };
}

export function CreateScheduleAndAbsencesByTermReportCommandToJSON(value?: CreateScheduleAndAbsencesByTermReportCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        'term': SchoolTermToJSON(value.term),
        'classBookId': value.classBookId,
    };
}

