/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { GradeType, GradeTypeFromJSON, GradeTypeToJSON } from './gradeType';


export interface EnumNomVOOfGradeType { 
    id: GradeType;
    name: GradeType;
    orderNum: number;
}

export function EnumNomVOOfGradeTypeFromJSON(json: any): EnumNomVOOfGradeType {
    if (json == null) {
        return json;
    }

    return {
        'id': GradeTypeFromJSON(json['id']),
        'name': GradeTypeFromJSON(json['name']),
        'orderNum': json['orderNum'],
    };
}

export function EnumNomVOOfGradeTypeToJSON(value?: EnumNomVOOfGradeType | null): any {
    if (value == null) {
        return value;
    }
    return {
        'id': GradeTypeToJSON(value.id),
        'name': GradeTypeToJSON(value.name),
        'orderNum': value.orderNum,
    };
}

