/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { QualificationAcquisitionProtocolType, QualificationAcquisitionProtocolTypeFromJSON, QualificationAcquisitionProtocolTypeToJSON } from './qualificationAcquisitionProtocolType';


export interface EnumNomVOOfQualificationAcquisitionProtocolType { 
    id: QualificationAcquisitionProtocolType;
    name: QualificationAcquisitionProtocolType;
    orderNum: number;
}

export function EnumNomVOOfQualificationAcquisitionProtocolTypeFromJSON(json: any): EnumNomVOOfQualificationAcquisitionProtocolType {
    if (json == null) {
        return json;
    }

    return {
        'id': QualificationAcquisitionProtocolTypeFromJSON(json['id']),
        'name': QualificationAcquisitionProtocolTypeFromJSON(json['name']),
        'orderNum': json['orderNum'],
    };
}

export function EnumNomVOOfQualificationAcquisitionProtocolTypeToJSON(value?: EnumNomVOOfQualificationAcquisitionProtocolType | null): any {
    if (value == null) {
        return value;
    }
    return {
        'id': QualificationAcquisitionProtocolTypeToJSON(value.id),
        'name': QualificationAcquisitionProtocolTypeToJSON(value.name),
        'orderNum': value.orderNum,
    };
}

