/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { SchoolTerm, SchoolTermFromJSON, SchoolTermToJSON } from './schoolTerm';


export interface EnumNomVOOfSchoolTerm { 
    id: SchoolTerm;
    name: SchoolTerm;
    orderNum: number;
}

export function EnumNomVOOfSchoolTermFromJSON(json: any): EnumNomVOOfSchoolTerm {
    if (json == null) {
        return json;
    }

    return {
        'id': SchoolTermFromJSON(json['id']),
        'name': SchoolTermFromJSON(json['name']),
        'orderNum': json['orderNum'],
    };
}

export function EnumNomVOOfSchoolTermToJSON(value?: EnumNomVOOfSchoolTerm | null): any {
    if (value == null) {
        return value;
    }
    return {
        'id': SchoolTermToJSON(value.id),
        'name': SchoolTermToJSON(value.name),
        'orderNum': value.orderNum,
    };
}

