/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export type ExamResultProtocolType = 'Exam' | 'Qualification' | 'SkillsCheck' | 'HighSchoolCertificate' | 'QualificationAcquisition' | 'QualificationAcquisitionExamGrades' | 'QualificationAcquisitionStateExamGrades' | 'GraduationThesisDefense';

export const ExamResultProtocolType = {
    Exam: 'Exam' as ExamResultProtocolType,
    Qualification: 'Qualification' as ExamResultProtocolType,
    SkillsCheck: 'SkillsCheck' as ExamResultProtocolType,
    HighSchoolCertificate: 'HighSchoolCertificate' as ExamResultProtocolType,
    QualificationAcquisition: 'QualificationAcquisition' as ExamResultProtocolType,
    QualificationAcquisitionExamGrades: 'QualificationAcquisitionExamGrades' as ExamResultProtocolType,
    QualificationAcquisitionStateExamGrades: 'QualificationAcquisitionStateExamGrades' as ExamResultProtocolType,
    GraduationThesisDefense: 'GraduationThesisDefense' as ExamResultProtocolType
};

export function ExamResultProtocolTypeFromJSON(json: any): ExamResultProtocolType {
    return json as ExamResultProtocolType;
}

export function ExamResultProtocolTypeToJSON(value?: ExamResultProtocolType | null): any {
    return value as any;
}

