/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { ExcuseAbsencesCommandAbsence, ExcuseAbsencesCommandAbsenceFromJSON, ExcuseAbsencesCommandAbsenceToJSON } from './excuseAbsencesCommandAbsence';


export interface ExcuseAbsencesCommand { 
    absences: Array<ExcuseAbsencesCommandAbsence>;
    excusedReasonId?: number | null;
    excusedReasonComment?: string | null;
}

export function ExcuseAbsencesCommandFromJSON(json: any): ExcuseAbsencesCommand {
    if (json == null) {
        return json;
    }

    return {
        'absences': (json['absences'] as Array<any>)?.map(ExcuseAbsencesCommandAbsenceFromJSON),
        'excusedReasonId': json['excusedReasonId'],
        'excusedReasonComment': json['excusedReasonComment'],
    };
}

export function ExcuseAbsencesCommandToJSON(value?: ExcuseAbsencesCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        'absences': (value.absences as Array<any>)?.map(ExcuseAbsencesCommandAbsenceToJSON),
        'excusedReasonId': value.excusedReasonId,
        'excusedReasonComment': value.excusedReasonComment,
    };
}

