/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export type GradeResultType = 'CompletesGrade' | 'MustRetakeExams' | 'RepeatsGrade';

export const GradeResultType = {
    CompletesGrade: 'CompletesGrade' as GradeResultType,
    MustRetakeExams: 'MustRetakeExams' as GradeResultType,
    RepeatsGrade: 'RepeatsGrade' as GradeResultType
};

export function GradeResultTypeFromJSON(json: any): GradeResultType {
    return json as GradeResultType;
}

export function GradeResultTypeToJSON(value?: GradeResultType | null): any {
    return value as any;
}

