/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { HisMedicalNoticesGetVOReceipt, HisMedicalNoticesGetVOReceiptFromJSON, HisMedicalNoticesGetVOReceiptToJSON } from './hisMedicalNoticesGetVOReceipt';


export interface HisMedicalNoticesGetVO { 
    schoolYears: string;
    nrnMedicalNotice: string;
    nrnExamination: string;
    identifierType: number;
    identifier: string;
    givenName: string;
    familyName: string;
    pmi: string;
    matchedStudentNames?: string | null;
    matchedStudentIdentifier?: string | null;
    authoredOn: Date;
    fromDate: Date;
    toDate: Date;
    receipts: Array<HisMedicalNoticesGetVOReceipt>;
}

export function HisMedicalNoticesGetVOFromJSON(json: any): HisMedicalNoticesGetVO {
    if (json == null) {
        return json;
    }

    return {
        'schoolYears': json['schoolYears'],
        'nrnMedicalNotice': json['nrnMedicalNotice'],
        'nrnExamination': json['nrnExamination'],
        'identifierType': json['identifierType'],
        'identifier': json['identifier'],
        'givenName': json['givenName'],
        'familyName': json['familyName'],
        'pmi': json['pmi'],
        'matchedStudentNames': json['matchedStudentNames'],
        'matchedStudentIdentifier': json['matchedStudentIdentifier'],
        'authoredOn': isoStringToLocalDateTime(json['authoredOn']),
        'fromDate': isoStringToLocalDateTime(json['fromDate']),
        'toDate': isoStringToLocalDateTime(json['toDate']),
        'receipts': (json['receipts'] as Array<any>)?.map(HisMedicalNoticesGetVOReceiptFromJSON),
    };
}

export function HisMedicalNoticesGetVOToJSON(value?: HisMedicalNoticesGetVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'schoolYears': value.schoolYears,
        'nrnMedicalNotice': value.nrnMedicalNotice,
        'nrnExamination': value.nrnExamination,
        'identifierType': value.identifierType,
        'identifier': value.identifier,
        'givenName': value.givenName,
        'familyName': value.familyName,
        'pmi': value.pmi,
        'matchedStudentNames': value.matchedStudentNames,
        'matchedStudentIdentifier': value.matchedStudentIdentifier,
        'authoredOn': dateTimeToLocalIsoString(value.authoredOn),
        'fromDate': dateTimeToLocalIsoString(value.fromDate),
        'toDate': dateTimeToLocalIsoString(value.toDate),
        'receipts': (value.receipts as Array<any>)?.map(HisMedicalNoticesGetVOReceiptToJSON),
    };
}

