/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface LectureSchedulesReportsGetAllVO { 
    lectureSchedulesReportId: number;
    period: string;
    yearAndMonth?: string | null;
    teacherName?: string | null;
    createDate: Date;
}

export function LectureSchedulesReportsGetAllVOFromJSON(json: any): LectureSchedulesReportsGetAllVO {
    if (json == null) {
        return json;
    }

    return {
        'lectureSchedulesReportId': json['lectureSchedulesReportId'],
        'period': json['period'],
        'yearAndMonth': json['yearAndMonth'],
        'teacherName': json['teacherName'],
        'createDate': isoStringToLocalDateTime(json['createDate']),
    };
}

export function LectureSchedulesReportsGetAllVOToJSON(value?: LectureSchedulesReportsGetAllVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'lectureSchedulesReportId': value.lectureSchedulesReportId,
        'period': value.period,
        'yearAndMonth': value.yearAndMonth,
        'teacherName': value.teacherName,
        'createDate': dateTimeToLocalIsoString(value.createDate),
    };
}

