/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { LectureSchedulesReportPeriod, LectureSchedulesReportPeriodFromJSON, LectureSchedulesReportPeriodToJSON } from './lectureSchedulesReportPeriod';


export interface LectureSchedulesReportsGetVO { 
    schoolYear: number;
    lectureSchedulesReportId: number;
    period: LectureSchedulesReportPeriod;
    year?: number | null;
    month?: number | null;
    teacherPersonName?: string | null;
    createDate: Date;
}

export function LectureSchedulesReportsGetVOFromJSON(json: any): LectureSchedulesReportsGetVO {
    if (json == null) {
        return json;
    }

    return {
        'schoolYear': json['schoolYear'],
        'lectureSchedulesReportId': json['lectureSchedulesReportId'],
        'period': LectureSchedulesReportPeriodFromJSON(json['period']),
        'year': json['year'],
        'month': json['month'],
        'teacherPersonName': json['teacherPersonName'],
        'createDate': isoStringToLocalDateTime(json['createDate']),
    };
}

export function LectureSchedulesReportsGetVOToJSON(value?: LectureSchedulesReportsGetVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'schoolYear': value.schoolYear,
        'lectureSchedulesReportId': value.lectureSchedulesReportId,
        'period': LectureSchedulesReportPeriodToJSON(value.period),
        'year': value.year,
        'month': value.month,
        'teacherPersonName': value.teacherPersonName,
        'createDate': dateTimeToLocalIsoString(value.createDate),
    };
}

