/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface LectureSchedulesReportsGetItemsVOInfoRow { 
    teacherPersonId: number;
    teacherPersonName: string;
    date: Date;
    classBookName: string;
    curriculumName: string;
    lectureScheduleId?: number | null;
    orderNumber: string;
    orderDate: Date;
    hoursTaken: number;
}

export function LectureSchedulesReportsGetItemsVOInfoRowFromJSON(json: any): LectureSchedulesReportsGetItemsVOInfoRow {
    if (json == null) {
        return json;
    }

    return {
        'teacherPersonId': json['teacherPersonId'],
        'teacherPersonName': json['teacherPersonName'],
        'date': isoStringToLocalDateTime(json['date']),
        'classBookName': json['classBookName'],
        'curriculumName': json['curriculumName'],
        'lectureScheduleId': json['lectureScheduleId'],
        'orderNumber': json['orderNumber'],
        'orderDate': isoStringToLocalDateTime(json['orderDate']),
        'hoursTaken': json['hoursTaken'],
    };
}

export function LectureSchedulesReportsGetItemsVOInfoRowToJSON(value?: LectureSchedulesReportsGetItemsVOInfoRow | null): any {
    if (value == null) {
        return value;
    }
    return {
        'teacherPersonId': value.teacherPersonId,
        'teacherPersonName': value.teacherPersonName,
        'date': dateTimeToLocalIsoString(value.date),
        'classBookName': value.classBookName,
        'curriculumName': value.curriculumName,
        'lectureScheduleId': value.lectureScheduleId,
        'orderNumber': value.orderNumber,
        'orderDate': dateTimeToLocalIsoString(value.orderDate),
        'hoursTaken': value.hoursTaken,
    };
}

