/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface LectureSchedulesReportsGetItemsVOTotalRow { 
    totalHoursTaken: number;
}

export function LectureSchedulesReportsGetItemsVOTotalRowFromJSON(json: any): LectureSchedulesReportsGetItemsVOTotalRow {
    if (json == null) {
        return json;
    }

    return {
        'totalHoursTaken': json['totalHoursTaken'],
    };
}

export function LectureSchedulesReportsGetItemsVOTotalRowToJSON(value?: LectureSchedulesReportsGetItemsVOTotalRow | null): any {
    if (value == null) {
        return value;
    }
    return {
        'totalHoursTaken': value.totalHoursTaken,
    };
}

