/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface PublicationsGetAllVO { 
    publicationId: number;
    type: string;
    status: string;
    date: Date;
    title: string;
    content: string;
}

export function PublicationsGetAllVOFromJSON(json: any): PublicationsGetAllVO {
    if (json == null) {
        return json;
    }

    return {
        'publicationId': json['publicationId'],
        'type': json['type'],
        'status': json['status'],
        'date': isoStringToLocalDateTime(json['date']),
        'title': json['title'],
        'content': json['content'],
    };
}

export function PublicationsGetAllVOToJSON(value?: PublicationsGetAllVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'publicationId': value.publicationId,
        'type': value.type,
        'status': value.status,
        'date': dateTimeToLocalIsoString(value.date),
        'title': value.title,
        'content': value.content,
    };
}

