/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export type QualificationAcquisitionProtocolType = 'QualificationAcquisition' | 'QualificationAcquisitionExamGrades' | 'QualificationAcquisitionStateExamGrades';

export const QualificationAcquisitionProtocolType = {
    QualificationAcquisition: 'QualificationAcquisition' as QualificationAcquisitionProtocolType,
    QualificationAcquisitionExamGrades: 'QualificationAcquisitionExamGrades' as QualificationAcquisitionProtocolType,
    QualificationAcquisitionStateExamGrades: 'QualificationAcquisitionStateExamGrades' as QualificationAcquisitionProtocolType
};

export function QualificationAcquisitionProtocolTypeFromJSON(json: any): QualificationAcquisitionProtocolType {
    return json as QualificationAcquisitionProtocolType;
}

export function QualificationAcquisitionProtocolTypeToJSON(value?: QualificationAcquisitionProtocolType | null): any {
    return value as any;
}

