/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export type ReportPeriod = 'TermOne' | 'TermTwo' | 'WholeYear';

export const ReportPeriod = {
    TermOne: 'TermOne' as ReportPeriod,
    TermTwo: 'TermTwo' as ReportPeriod,
    WholeYear: 'WholeYear' as ReportPeriod
};

export function ReportPeriodFromJSON(json: any): ReportPeriod {
    return json as ReportPeriod;
}

export function ReportPeriodToJSON(value?: ReportPeriod | null): any {
    return value as any;
}

