/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { ScheduleAndAbsencesByTermReportsGetWeeksVODay, ScheduleAndAbsencesByTermReportsGetWeeksVODayFromJSON, ScheduleAndAbsencesByTermReportsGetWeeksVODayToJSON } from './scheduleAndAbsencesByTermReportsGetWeeksVODay';


export interface ScheduleAndAbsencesByTermReportsGetWeeksVO { 
    studentName?: string | null;
    weekName: string;
    additionalActivities?: string | null;
    days: Array<ScheduleAndAbsencesByTermReportsGetWeeksVODay>;
}

export function ScheduleAndAbsencesByTermReportsGetWeeksVOFromJSON(json: any): ScheduleAndAbsencesByTermReportsGetWeeksVO {
    if (json == null) {
        return json;
    }

    return {
        'studentName': json['studentName'],
        'weekName': json['weekName'],
        'additionalActivities': json['additionalActivities'],
        'days': (json['days'] as Array<any>)?.map(ScheduleAndAbsencesByTermReportsGetWeeksVODayFromJSON),
    };
}

export function ScheduleAndAbsencesByTermReportsGetWeeksVOToJSON(value?: ScheduleAndAbsencesByTermReportsGetWeeksVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'studentName': value.studentName,
        'weekName': value.weekName,
        'additionalActivities': value.additionalActivities,
        'days': (value.days as Array<any>)?.map(ScheduleAndAbsencesByTermReportsGetWeeksVODayToJSON),
    };
}

