/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface ScheduleLessonNomVO { 
    scheduleLessonId: number;
    teacherAbsenceId?: number | null;
    individualCurriculumPersonId?: number | null;
    name: string;
    isVerified: boolean;
}

export function ScheduleLessonNomVOFromJSON(json: any): ScheduleLessonNomVO {
    if (json == null) {
        return json;
    }

    return {
        'scheduleLessonId': json['scheduleLessonId'],
        'teacherAbsenceId': json['teacherAbsenceId'],
        'individualCurriculumPersonId': json['individualCurriculumPersonId'],
        'name': json['name'],
        'isVerified': json['isVerified'],
    };
}

export function ScheduleLessonNomVOToJSON(value?: ScheduleLessonNomVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'scheduleLessonId': value.scheduleLessonId,
        'teacherAbsenceId': value.teacherAbsenceId,
        'individualCurriculumPersonId': value.individualCurriculumPersonId,
        'name': value.name,
        'isVerified': value.isVerified,
    };
}

