/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface SchedulesGetClassBookScheduleForWeekVOHourTeacher { 
    teacherPersonId: number;
    teacherFirstName: string;
    teacherLastName: string;
    markedAsNoReplacement: boolean;
}

export function SchedulesGetClassBookScheduleForWeekVOHourTeacherFromJSON(json: any): SchedulesGetClassBookScheduleForWeekVOHourTeacher {
    if (json == null) {
        return json;
    }

    return {
        'teacherPersonId': json['teacherPersonId'],
        'teacherFirstName': json['teacherFirstName'],
        'teacherLastName': json['teacherLastName'],
        'markedAsNoReplacement': json['markedAsNoReplacement'],
    };
}

export function SchedulesGetClassBookScheduleForWeekVOHourTeacherToJSON(value?: SchedulesGetClassBookScheduleForWeekVOHourTeacher | null): any {
    if (value == null) {
        return value;
    }
    return {
        'teacherPersonId': value.teacherPersonId,
        'teacherFirstName': value.teacherFirstName,
        'teacherLastName': value.teacherLastName,
        'markedAsNoReplacement': value.markedAsNoReplacement,
    };
}

