/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { SeparateClassBooksCommandClassBook, SeparateClassBooksCommandClassBookFromJSON, SeparateClassBooksCommandClassBookToJSON } from './separateClassBooksCommandClassBook';


export interface SeparateClassBooksCommand { 
    parentClassId: number;
    childClassBooks: Array<SeparateClassBooksCommandClassBook>;
}

export function SeparateClassBooksCommandFromJSON(json: any): SeparateClassBooksCommand {
    if (json == null) {
        return json;
    }

    return {
        'parentClassId': json['parentClassId'],
        'childClassBooks': (json['childClassBooks'] as Array<any>)?.map(SeparateClassBooksCommandClassBookFromJSON),
    };
}

export function SeparateClassBooksCommandToJSON(value?: SeparateClassBooksCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        'parentClassId': value.parentClassId,
        'childClassBooks': (value.childClassBooks as Array<any>)?.map(SeparateClassBooksCommandClassBookToJSON),
    };
}

