/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface SpbsBookRecordsGetVOMovement { 
    orderNum: number;
    courtDecisionNumber?: string | null;
    courtDecisionDate?: Date | null;
    incomingInst?: string | null;
    incommingLetterNumber?: string | null;
    incommingLetterDate?: Date | null;
    incommingDate?: Date | null;
    incommingDocNumber?: string | null;
    transferInst?: string | null;
    transferReason?: string | null;
    transferProtocolNumber?: string | null;
    transferProtocolDate?: Date | null;
    transferLetterNumber?: string | null;
    transferLetterDate?: Date | null;
    transferCertificateNumber?: string | null;
    transferCertificateDate?: Date | null;
    transferMessageNumber?: string | null;
    transferMessageDate?: Date | null;
}

export function SpbsBookRecordsGetVOMovementFromJSON(json: any): SpbsBookRecordsGetVOMovement {
    if (json == null) {
        return json;
    }

    return {
        'orderNum': json['orderNum'],
        'courtDecisionNumber': json['courtDecisionNumber'],
        'courtDecisionDate': isoStringToLocalDateTime(json['courtDecisionDate']),
        'incomingInst': json['incomingInst'],
        'incommingLetterNumber': json['incommingLetterNumber'],
        'incommingLetterDate': isoStringToLocalDateTime(json['incommingLetterDate']),
        'incommingDate': isoStringToLocalDateTime(json['incommingDate']),
        'incommingDocNumber': json['incommingDocNumber'],
        'transferInst': json['transferInst'],
        'transferReason': json['transferReason'],
        'transferProtocolNumber': json['transferProtocolNumber'],
        'transferProtocolDate': isoStringToLocalDateTime(json['transferProtocolDate']),
        'transferLetterNumber': json['transferLetterNumber'],
        'transferLetterDate': isoStringToLocalDateTime(json['transferLetterDate']),
        'transferCertificateNumber': json['transferCertificateNumber'],
        'transferCertificateDate': isoStringToLocalDateTime(json['transferCertificateDate']),
        'transferMessageNumber': json['transferMessageNumber'],
        'transferMessageDate': isoStringToLocalDateTime(json['transferMessageDate']),
    };
}

export function SpbsBookRecordsGetVOMovementToJSON(value?: SpbsBookRecordsGetVOMovement | null): any {
    if (value == null) {
        return value;
    }
    return {
        'orderNum': value.orderNum,
        'courtDecisionNumber': value.courtDecisionNumber,
        'courtDecisionDate': dateTimeToLocalIsoString(value.courtDecisionDate),
        'incomingInst': value.incomingInst,
        'incommingLetterNumber': value.incommingLetterNumber,
        'incommingLetterDate': dateTimeToLocalIsoString(value.incommingLetterDate),
        'incommingDate': dateTimeToLocalIsoString(value.incommingDate),
        'incommingDocNumber': value.incommingDocNumber,
        'transferInst': value.transferInst,
        'transferReason': value.transferReason,
        'transferProtocolNumber': value.transferProtocolNumber,
        'transferProtocolDate': dateTimeToLocalIsoString(value.transferProtocolDate),
        'transferLetterNumber': value.transferLetterNumber,
        'transferLetterDate': dateTimeToLocalIsoString(value.transferLetterDate),
        'transferCertificateNumber': value.transferCertificateNumber,
        'transferCertificateDate': dateTimeToLocalIsoString(value.transferCertificateDate),
        'transferMessageNumber': value.transferMessageNumber,
        'transferMessageDate': dateTimeToLocalIsoString(value.transferMessageDate),
    };
}

