/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface SpbsBookRecordsGetEscapeVO { 
    orderNum: number;
    escapeDate: Date;
    escapeTime: string;
    policeNotificationDate: Date;
    policeNotificationTime: string;
    policeLetterNumber: string;
    policeLetterDate: Date;
    returnDate?: Date | null;
    escapeDateTime: Date;
    policeNotificationDateTime: Date;
    escapeDays?: number | null;
}

export function SpbsBookRecordsGetEscapeVOFromJSON(json: any): SpbsBookRecordsGetEscapeVO {
    if (json == null) {
        return json;
    }

    return {
        'orderNum': json['orderNum'],
        'escapeDate': isoStringToLocalDateTime(json['escapeDate']),
        'escapeTime': json['escapeTime'],
        'policeNotificationDate': isoStringToLocalDateTime(json['policeNotificationDate']),
        'policeNotificationTime': json['policeNotificationTime'],
        'policeLetterNumber': json['policeLetterNumber'],
        'policeLetterDate': isoStringToLocalDateTime(json['policeLetterDate']),
        'returnDate': isoStringToLocalDateTime(json['returnDate']),
        'escapeDateTime': isoStringToLocalDateTime(json['escapeDateTime']),
        'policeNotificationDateTime': isoStringToLocalDateTime(json['policeNotificationDateTime']),
        'escapeDays': json['escapeDays'],
    };
}

export function SpbsBookRecordsGetEscapeVOToJSON(value?: SpbsBookRecordsGetEscapeVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'orderNum': value.orderNum,
        'escapeDate': dateTimeToLocalIsoString(value.escapeDate),
        'escapeTime': value.escapeTime,
        'policeNotificationDate': dateTimeToLocalIsoString(value.policeNotificationDate),
        'policeNotificationTime': value.policeNotificationTime,
        'policeLetterNumber': value.policeLetterNumber,
        'policeLetterDate': dateTimeToLocalIsoString(value.policeLetterDate),
        'returnDate': dateTimeToLocalIsoString(value.returnDate),
        'escapeDateTime': dateTimeToLocalIsoString(value.escapeDateTime),
        'policeNotificationDateTime': dateTimeToLocalIsoString(value.policeNotificationDateTime),
        'escapeDays': value.escapeDays,
    };
}

