/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface SpbsBookRecordsGetAbsenceVO { 
    orderNum: number;
    absenceDate: Date;
    absenceReason: string;
}

export function SpbsBookRecordsGetAbsenceVOFromJSON(json: any): SpbsBookRecordsGetAbsenceVO {
    if (json == null) {
        return json;
    }

    return {
        'orderNum': json['orderNum'],
        'absenceDate': isoStringToLocalDateTime(json['absenceDate']),
        'absenceReason': json['absenceReason'],
    };
}

export function SpbsBookRecordsGetAbsenceVOToJSON(value?: SpbsBookRecordsGetAbsenceVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'orderNum': value.orderNum,
        'absenceDate': dateTimeToLocalIsoString(value.absenceDate),
        'absenceReason': value.absenceReason,
    };
}

