/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface StudentsAtRiskOfDroppingOutReportsGetVO { 
    studentsAtRiskOfDroppingOutReportId: number;
    reportDate: Date;
    createDate: Date;
}

export function StudentsAtRiskOfDroppingOutReportsGetVOFromJSON(json: any): StudentsAtRiskOfDroppingOutReportsGetVO {
    if (json == null) {
        return json;
    }

    return {
        'studentsAtRiskOfDroppingOutReportId': json['studentsAtRiskOfDroppingOutReportId'],
        'reportDate': isoStringToLocalDateTime(json['reportDate']),
        'createDate': isoStringToLocalDateTime(json['createDate']),
    };
}

export function StudentsAtRiskOfDroppingOutReportsGetVOToJSON(value?: StudentsAtRiskOfDroppingOutReportsGetVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'studentsAtRiskOfDroppingOutReportId': value.studentsAtRiskOfDroppingOutReportId,
        'reportDate': dateTimeToLocalIsoString(value.reportDate),
        'createDate': dateTimeToLocalIsoString(value.createDate),
    };
}

