/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface StudentInfoClassBooksGetPgResultsVO { 
    pgResultId: number;
    curriculumName?: string | null;
    startSchoolYearResult?: string | null;
    endSchoolYearResult?: string | null;
}

export function StudentInfoClassBooksGetPgResultsVOFromJSON(json: any): StudentInfoClassBooksGetPgResultsVO {
    if (json == null) {
        return json;
    }

    return {
        'pgResultId': json['pgResultId'],
        'curriculumName': json['curriculumName'],
        'startSchoolYearResult': json['startSchoolYearResult'],
        'endSchoolYearResult': json['endSchoolYearResult'],
    };
}

export function StudentInfoClassBooksGetPgResultsVOToJSON(value?: StudentInfoClassBooksGetPgResultsVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'pgResultId': value.pgResultId,
        'curriculumName': value.curriculumName,
        'startSchoolYearResult': value.startSchoolYearResult,
        'endSchoolYearResult': value.endSchoolYearResult,
    };
}

