/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface StudentPublicationsGetStudentPublicationVOFile { 
    fileName: string;
    location: string;
    extension: string;
}

export function StudentPublicationsGetStudentPublicationVOFileFromJSON(json: any): StudentPublicationsGetStudentPublicationVOFile {
    if (json == null) {
        return json;
    }

    return {
        'fileName': json['fileName'],
        'location': json['location'],
        'extension': json['extension'],
    };
}

export function StudentPublicationsGetStudentPublicationVOFileToJSON(value?: StudentPublicationsGetStudentPublicationVOFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        'fileName': value.fileName,
        'location': value.location,
        'extension': value.extension,
    };
}

