/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface StudentInfoClassBooksGetAbsencesDplrVO { 
    curriculumId: number;
    curriculumName: string;
    curriculumIsValid: boolean;
    count: number;
}

export function StudentInfoClassBooksGetAbsencesDplrVOFromJSON(json: any): StudentInfoClassBooksGetAbsencesDplrVO {
    if (json == null) {
        return json;
    }

    return {
        'curriculumId': json['curriculumId'],
        'curriculumName': json['curriculumName'],
        'curriculumIsValid': json['curriculumIsValid'],
        'count': json['count'],
    };
}

export function StudentInfoClassBooksGetAbsencesDplrVOToJSON(value?: StudentInfoClassBooksGetAbsencesDplrVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'curriculumId': value.curriculumId,
        'curriculumName': value.curriculumName,
        'curriculumIsValid': value.curriculumIsValid,
        'count': value.count,
    };
}

