/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface SupportsGetAllVO { 
    supportId: number;
    isForAllStudents: boolean;
    difficulties: string;
    students: string;
    activities: string;
    createDate: Date;
    endDate: Date;
}

export function SupportsGetAllVOFromJSON(json: any): SupportsGetAllVO {
    if (json == null) {
        return json;
    }

    return {
        'supportId': json['supportId'],
        'isForAllStudents': json['isForAllStudents'],
        'difficulties': json['difficulties'],
        'students': json['students'],
        'activities': json['activities'],
        'createDate': isoStringToLocalDateTime(json['createDate']),
        'endDate': isoStringToLocalDateTime(json['endDate']),
    };
}

export function SupportsGetAllVOToJSON(value?: SupportsGetAllVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'supportId': value.supportId,
        'isForAllStudents': value.isForAllStudents,
        'difficulties': value.difficulties,
        'students': value.students,
        'activities': value.activities,
        'createDate': dateTimeToLocalIsoString(value.createDate),
        'endDate': dateTimeToLocalIsoString(value.endDate),
    };
}

