/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { StudentInfoClassBooksGetExamsVO, StudentInfoClassBooksGetExamsVOFromJSON, StudentInfoClassBooksGetExamsVOToJSON } from './studentInfoClassBooksGetExamsVO';


export interface TableResultVOOfStudentInfoClassBooksGetExamsVO { 
    result: Array<StudentInfoClassBooksGetExamsVO>;
    length: number;
}

export function TableResultVOOfStudentInfoClassBooksGetExamsVOFromJSON(json: any): TableResultVOOfStudentInfoClassBooksGetExamsVO {
    if (json == null) {
        return json;
    }

    return {
        'result': (json['result'] as Array<any>)?.map(StudentInfoClassBooksGetExamsVOFromJSON),
        'length': json['length'],
    };
}

export function TableResultVOOfStudentInfoClassBooksGetExamsVOToJSON(value?: TableResultVOOfStudentInfoClassBooksGetExamsVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'result': (value.result as Array<any>)?.map(StudentInfoClassBooksGetExamsVOToJSON),
        'length': value.length,
    };
}

