/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { SessionStudentsReportsGetItemsVO, SessionStudentsReportsGetItemsVOFromJSON, SessionStudentsReportsGetItemsVOToJSON } from './sessionStudentsReportsGetItemsVO';


export interface TableResultVOOfSessionStudentsReportsGetItemsVO { 
    result: Array<SessionStudentsReportsGetItemsVO>;
    length: number;
}

export function TableResultVOOfSessionStudentsReportsGetItemsVOFromJSON(json: any): TableResultVOOfSessionStudentsReportsGetItemsVO {
    if (json == null) {
        return json;
    }

    return {
        'result': (json['result'] as Array<any>)?.map(SessionStudentsReportsGetItemsVOFromJSON),
        'length': json['length'],
    };
}

export function TableResultVOOfSessionStudentsReportsGetItemsVOToJSON(value?: TableResultVOOfSessionStudentsReportsGetItemsVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'result': (value.result as Array<any>)?.map(SessionStudentsReportsGetItemsVOToJSON),
        'length': value.length,
    };
}

