/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { QualificationExamResultProtocolsGetStudentAllVO, QualificationExamResultProtocolsGetStudentAllVOFromJSON, QualificationExamResultProtocolsGetStudentAllVOToJSON } from './qualificationExamResultProtocolsGetStudentAllVO';


export interface TableResultVOOfQualificationExamResultProtocolsGetStudentAllVO { 
    result: Array<QualificationExamResultProtocolsGetStudentAllVO>;
    length: number;
}

export function TableResultVOOfQualificationExamResultProtocolsGetStudentAllVOFromJSON(json: any): TableResultVOOfQualificationExamResultProtocolsGetStudentAllVO {
    if (json == null) {
        return json;
    }

    return {
        'result': (json['result'] as Array<any>)?.map(QualificationExamResultProtocolsGetStudentAllVOFromJSON),
        'length': json['length'],
    };
}

export function TableResultVOOfQualificationExamResultProtocolsGetStudentAllVOToJSON(value?: TableResultVOOfQualificationExamResultProtocolsGetStudentAllVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'result': (value.result as Array<any>)?.map(QualificationExamResultProtocolsGetStudentAllVOToJSON),
        'length': value.length,
    };
}

