/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { ClassBooksAdminGetAllVO, ClassBooksAdminGetAllVOFromJSON, ClassBooksAdminGetAllVOToJSON } from './classBooksAdminGetAllVO';


export interface TableResultVOOfClassBooksAdminGetAllVO { 
    result: Array<ClassBooksAdminGetAllVO>;
    length: number;
}

export function TableResultVOOfClassBooksAdminGetAllVOFromJSON(json: any): TableResultVOOfClassBooksAdminGetAllVO {
    if (json == null) {
        return json;
    }

    return {
        'result': (json['result'] as Array<any>)?.map(ClassBooksAdminGetAllVOFromJSON),
        'length': json['length'],
    };
}

export function TableResultVOOfClassBooksAdminGetAllVOToJSON(value?: TableResultVOOfClassBooksAdminGetAllVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        'result': (value.result as Array<any>)?.map(ClassBooksAdminGetAllVOToJSON),
        'length': value.length,
    };
}

