/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface TeacherAbsencesGetVOHour { 
    scheduleLessonId: number;
    replTeacherPersonId?: number | null;
    replTeacherFirstName?: string | null;
    replTeacherLastName?: string | null;
    replTeacherIsNonSpecialist?: boolean | null;
    extReplTeacherName?: string | null;
    isInUse?: boolean | null;
}

export function TeacherAbsencesGetVOHourFromJSON(json: any): TeacherAbsencesGetVOHour {
    if (json == null) {
        return json;
    }

    return {
        'scheduleLessonId': json['scheduleLessonId'],
        'replTeacherPersonId': json['replTeacherPersonId'],
        'replTeacherFirstName': json['replTeacherFirstName'],
        'replTeacherLastName': json['replTeacherLastName'],
        'replTeacherIsNonSpecialist': json['replTeacherIsNonSpecialist'],
        'extReplTeacherName': json['extReplTeacherName'],
        'isInUse': json['isInUse'],
    };
}

export function TeacherAbsencesGetVOHourToJSON(value?: TeacherAbsencesGetVOHour | null): any {
    if (value == null) {
        return value;
    }
    return {
        'scheduleLessonId': value.scheduleLessonId,
        'replTeacherPersonId': value.replTeacherPersonId,
        'replTeacherFirstName': value.replTeacherFirstName,
        'replTeacherLastName': value.replTeacherLastName,
        'replTeacherIsNonSpecialist': value.replTeacherIsNonSpecialist,
        'extReplTeacherName': value.extReplTeacherName,
        'isInUse': value.isInUse,
    };
}

