/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { TeacherAbsencesGetScheduleVOSlotHour, TeacherAbsencesGetScheduleVOSlotHourFromJSON, TeacherAbsencesGetScheduleVOSlotHourToJSON } from './teacherAbsencesGetScheduleVOSlotHour';


export interface TeacherAbsencesGetScheduleVOSlot { 
    day: number;
    slotNumber: number;
    hours: Array<TeacherAbsencesGetScheduleVOSlotHour>;
}

export function TeacherAbsencesGetScheduleVOSlotFromJSON(json: any): TeacherAbsencesGetScheduleVOSlot {
    if (json == null) {
        return json;
    }

    return {
        'day': json['day'],
        'slotNumber': json['slotNumber'],
        'hours': (json['hours'] as Array<any>)?.map(TeacherAbsencesGetScheduleVOSlotHourFromJSON),
    };
}

export function TeacherAbsencesGetScheduleVOSlotToJSON(value?: TeacherAbsencesGetScheduleVOSlot | null): any {
    if (value == null) {
        return value;
    }
    return {
        'day': value.day,
        'slotNumber': value.slotNumber,
        'hours': (value.hours as Array<any>)?.map(TeacherAbsencesGetScheduleVOSlotHourToJSON),
    };
}

