/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { UpdateGradeResultSessionsCommandSession, UpdateGradeResultSessionsCommandSessionFromJSON, UpdateGradeResultSessionsCommandSessionToJSON } from './updateGradeResultSessionsCommandSession';


export interface UpdateGradeResultSessionsCommand { 
    sessions?: Array<UpdateGradeResultSessionsCommandSession> | null;
}

export function UpdateGradeResultSessionsCommandFromJSON(json: any): UpdateGradeResultSessionsCommand {
    if (json == null) {
        return json;
    }

    return {
        'sessions': (json['sessions'] as Array<any>)?.map(UpdateGradeResultSessionsCommandSessionFromJSON),
    };
}

export function UpdateGradeResultSessionsCommandToJSON(value?: UpdateGradeResultSessionsCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        'sessions': (value.sessions as Array<any>)?.map(UpdateGradeResultSessionsCommandSessionToJSON),
    };
}

