/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';
import { UpdateIsVerifiedScheduleLessonCommandScheduleLesson, UpdateIsVerifiedScheduleLessonCommandScheduleLessonFromJSON, UpdateIsVerifiedScheduleLessonCommandScheduleLessonToJSON } from './updateIsVerifiedScheduleLessonCommandScheduleLesson';


export interface UpdateIsVerifiedScheduleLessonCommand { 
    scheduleLessons: Array<UpdateIsVerifiedScheduleLessonCommandScheduleLesson>;
}

export function UpdateIsVerifiedScheduleLessonCommandFromJSON(json: any): UpdateIsVerifiedScheduleLessonCommand {
    if (json == null) {
        return json;
    }

    return {
        'scheduleLessons': (json['scheduleLessons'] as Array<any>)?.map(UpdateIsVerifiedScheduleLessonCommandScheduleLessonFromJSON),
    };
}

export function UpdateIsVerifiedScheduleLessonCommandToJSON(value?: UpdateIsVerifiedScheduleLessonCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        'scheduleLessons': (value.scheduleLessons as Array<any>)?.map(UpdateIsVerifiedScheduleLessonCommandScheduleLessonToJSON),
    };
}

