/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface UpdateNvoExamDutyProtocolCommand { 
    protocolNumber?: string | null;
    protocolDate?: Date | null;
    basicClassId?: number | null;
    subjectId?: number | null;
    subjectTypeId?: number | null;
    date?: Date | null;
    roomNumber?: string | null;
    directorPersonId?: number | null;
    supervisorPersonIds?: Array<number> | null;
}

export function UpdateNvoExamDutyProtocolCommandFromJSON(json: any): UpdateNvoExamDutyProtocolCommand {
    if (json == null) {
        return json;
    }

    return {
        'protocolNumber': json['protocolNumber'],
        'protocolDate': isoStringToLocalDateTime(json['protocolDate']),
        'basicClassId': json['basicClassId'],
        'subjectId': json['subjectId'],
        'subjectTypeId': json['subjectTypeId'],
        'date': isoStringToLocalDateTime(json['date']),
        'roomNumber': json['roomNumber'],
        'directorPersonId': json['directorPersonId'],
        'supervisorPersonIds': (json['supervisorPersonIds']),
    };
}

export function UpdateNvoExamDutyProtocolCommandToJSON(value?: UpdateNvoExamDutyProtocolCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        'protocolNumber': value.protocolNumber,
        'protocolDate': dateTimeToLocalIsoString(value.protocolDate),
        'basicClassId': value.basicClassId,
        'subjectId': value.subjectId,
        'subjectTypeId': value.subjectTypeId,
        'date': dateTimeToLocalIsoString(value.date),
        'roomNumber': value.roomNumber,
        'directorPersonId': value.directorPersonId,
        'supervisorPersonIds': (value.supervisorPersonIds),
    };
}

