/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues, dateToLocalIsoString, dateTimeToLocalIsoString, isoStringToLocalDate, isoStringToLocalDateTime } from '../encoder';


export interface ValidationErrorResponse { 
    errors: Array<string>;
    errorMessages: Array<string>;
    sysErrorMessage: string;
}

export function ValidationErrorResponseFromJSON(json: any): ValidationErrorResponse {
    if (json == null) {
        return json;
    }

    return {
        'errors': (json['errors']),
        'errorMessages': (json['errorMessages']),
        'sysErrorMessage': json['sysErrorMessage'],
    };
}

export function ValidationErrorResponseToJSON(value?: ValidationErrorResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        'errors': (value.errors),
        'errorMessages': (value.errorMessages),
        'sysErrorMessage': value.sysErrorMessage,
    };
}

