export const CONSTANTS = {
    CACHE_STORAGE_TELELINK_TOKEN: 'token_telelink',
    CACHE_STORAGE_GRAPH_TOKEN: 'token_graph',
    CACHE_STORAGE_GRAPH_TOKEN_PARENT: 'token_graph_parent',
    CACHE_STORAGE_SYSTEM_USER_USERNAME: 'system-user-username',

    JOB_CRON_ARCHIVE_AZURE_USERS: '0 0 0-1 * * *',
    JOB_CRON_ARCHIVE_AZURE_ORGANIZATIONS: '0 0 0-1 * * *',
    JOB_CRON_ARCHIVE_AZURE_ENROLLMENTS: '0 0 0-1 * * *',
    JOB_CRON_ARCHIVE_AZURE_CLASSES: '0 0 0-1 * * *',

    JOB_CRON_REVERT_AZURE_USERS: '*/10 * 1-23 * * *',
    JOB_CRON_REVERT_AZURE_ORGANIZATIONS: '*/10 * 1-23 * * *',
    JOB_CRON_REVERT_AZURE_ENROLLMENTS: '*/10 * 1-23 * * *',
    JOB_CRON_REVERT_AZURE_CLASSES: '*/10 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_ENROLLMENTS_STUDENT_TO_CLASS_CREATE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_ENROLLMENTS_STUDENT_TO_CLASS_DELETE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_ENROLLMENTS_TEACHER_TO_CLASS_CREATE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_ENROLLMENTS_TEACHER_TO_CLASS_DELETE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_ENROLLMENTS_STUDENT_TO_SCHOOL_CREATE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_ENROLLMENTS_STUDENT_TO_SCHOOL_DELETE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_ENROLLMENTS_TEACHER_TO_SCHOOL_CREATE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_ENROLLMENTS_TEACHER_TO_SCHOOL_DELETE: '*/59 * 1-23 * * *',

    JOB_CRON_SEND_AZURE_USERS_CREATE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_USERS_UPDATE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_USERS_DELETE: '*/59 * 1-23 * * *',

    JOB_CRON_SEND_AZURE_ORGANIZATIONS_CREATE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_ORGANIZATIONS_UPDATE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_ORGANIZATIONS_DELETE: '*/59 * 1-23 * * *',

    JOB_CRON_GET_AZURE_ENROLLMENTS_STUDENT_TO_CLASS: '*/5 * 1-23 * * *',
    JOB_CRON_GET_AZURE_ENROLLMENTS_TEACHER_TO_CLASS: '*/30 * 1-23 * * *',
    JOB_CRON_GET_AZURE_ENROLLMENTS_TO_SCHOOL: '*/1 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_CLASSES_CREATE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_CLASSES_UPDATE: '*/59 * 1-23 * * *',
    JOB_CRON_SEND_AZURE_CLASSES_DELETE: '*/59 * 1-23 * * *',

    JOB_CRON_CHECK_AZURE_USERS: '*/10 * 1-23 * * *',
    JOB_CRON_CHECK_AZURE_ORGANIZATIONS: '0 */1 * 1-23 * *',
    JOB_CRON_CHECK_AZURE_ENROLLMENTS_TO_CLASS: '*/30 * 1-23 * * *',
    JOB_CRON_CHECK_AZURE_ENROLLMENTS_TO_SCHOOL: '*/10 * 1-23 * * *',
    JOB_CRON_CHECK_AZURE_CLASSES: '*/10 * 1-23 * * *',

    JOB_CRON_CREATE_USERS: '*/10 * 1-23 * * *',
    JOB_CRON_UPDATE_INSTITUTIONS: '0 */1 * 1-23 * *',
    JOB_CRON_UPDATE_CLASSES: '*/10 * 1-23 * * *',

    JOB_CRON_DAILY_RUN_CLI_SCRIPT_SYNC_AZURE_USERS: '0 15 0-1 * * *',

    JOB_CRON_DAILY_RUN_CLI_SCRIPT_SYNC_AZURE_SCHOOLS: '0 30 0-1 * * *',

    JOB_CRON_DAILY_RUN_CLI_SCRIPT_SYNC_AZURE_CLASSES: '0 30 0-1 * * *',

    JOB_CRON_DAILY_RUN_CLI_SCRIPT_SYNC_AZURE_SCHOOL_ENROLLMENTS: '0 30 0-1 * * *',

    JOB_CRON_DAILY_RUN_CLI_SCRIPT_SYNC_AZURE_CLASS_ENROLLMENTS: '0 30 0-1 * * *',

    JOB_CRON_ARCHIVE_USERS_PREVIOUS_YEARS: '0 */15 0 * * *',

    JOB_CRON_ARCHIVE_ORGANIZATIONS_PREVIOUS_YEARS: '0 */15 0 * * *',

    JOB_CRON_ARCHIVE_ENROLLMENTS_PREVIOUS_YEARS: '0 */15 0 * * *',

    JOB_CRON_ARCHIVE_CLASSES_PREVIOUS_YEARS: '0 */15 0 * * *',

    JOB_CRON_RESTART_FAILED_JOBS_WORKFLOWS: '*/30 * 1-23 * * *',

    JOB_CRON_ARCHIVE_FAILED_JOBS_WORKFLOWS: '0 * 0-1 * * *',

    JOB_CRON_ARCHIVE_NOT_STARTED_JOBS_WORKFLOWS: '0 * 0-1 * * *',

    JOB_CRON_DELETE_ENTITIES_IN_GENERATION: '0 0 1 * * *',

    JOB_CRON_ERROR_EMAIL_NOTIFICATION: '0 0 1 * * 5',

    JOB_CRON_DELETE_UNATTENDING_STUDENT_USERS: '10 3 1 10 * *',

    JOB_CRON_DELETE_GRADUATED_STUDENTS: '0 */30 0-6 * * 6-7',

    JOB_CRON_DELETE_UNEMPLOYED_TEACHERS: '10 3 1 10 * *',

    JOB_CRON_CUSTOM_EMAIL_NOTIFICATION: '0 0 8 * * 1-5',

    JOB_INTERVAL_BEARER_TOKEN: 1000 * 3500,
    JOB_INTERVAL_JOB_UPDATE: 1000 * 30,
    JOB_INTERVAL_JOB_UPDATE_TOP_VALUES: 1000 * 30,

    JOB_TYPE_GET_AZURE_USERS: 'azure-users',
    JOB_TYPE_GET_AZURE_ORGANIZATIONS: 'azure-organizations',
    JOB_TYPE_GET_AZURE_ENROLLMENTS: 'azure-enrollments',
    JOB_TYPE_GET_AZURE_CLASSES: 'azure-classes',

    JOB_INTERVAL_NAME_BEARER_TOKEN: 'token-refresh',

    JOB_INTERVAL_NAME_UPDATE_JOB: 'update-job',
    JOB_INTERVAL_NAME_UPDATE_JOB_TOP_VALUES: 'update-job-top-values',

    JOB_NAME_SEND_AZURE_ENROLLMENTS_STUDENT_TO_CLASS_CREATE: 'send-azure-enrollments-student-to-class-create',
    JOB_NAME_SEND_AZURE_ENROLLMENTS_STUDENT_TO_CLASS_DELETE: 'send-azure-enrollments-student-to-class-delete',
    JOB_NAME_SEND_AZURE_ENROLLMENTS_STUDENT_TO_SCHOOL_CREATE: 'send-azure-enrollments-student-to-school-create',
    JOB_NAME_SEND_AZURE_ENROLLMENTS_STUDENT_TO_SCHOOL_DELETE: 'send-azure-enrollments-student-to-school-delete',

    JOB_NAME_SEND_AZURE_ENROLLMENTS_TEACHER_TO_SCHOOL_CREATE: 'send-azure-enrollments-teacher-to-school-create',
    JOB_NAME_SEND_AZURE_ENROLLMENTS_TEACHER_TO_SCHOOL_DELETE: 'send-azure-enrollments-teacher-to-school-delete',
    JOB_NAME_SEND_AZURE_ENROLLMENTS_TEACHER_TO_CLASS_CREATE: 'send-azure-enrollments-teacher-to-class-create',
    JOB_NAME_SEND_AZURE_ENROLLMENTS_TEACHER_TO_CLASS_DELETE: 'send-azure-enrollments-teacher-to-class-delete',

    JOB_NAME_SEND_AZURE_USERS_CREATE: 'send-azure-users-create',
    JOB_NAME_SEND_AZURE_USERS_UPDATE: 'send-azure-users-update',
    JOB_NAME_SEND_AZURE_USERS_DELETE: 'send-azure-users-delete',

    JOB_NAME_SEND_AZURE_ORGANIZATIONS_CREATE: 'send-azure-organizations-create',
    JOB_NAME_SEND_AZURE_ORGANIZATIONS_UPDATE: 'send-azure-organizations-update',
    JOB_NAME_SEND_AZURE_ORGANIZATIONS_DELETE: 'send-azure-organizations-delete',

    JOB_NAME_GET_AZURE_ENROLLMENTS_STUDENT_TO_CLASS: 'azure-enrollments-student-to-class-create',
    JOB_NAME_GET_AZURE_ENROLLMENTS_TEACHER_TO_CLASS: 'azure-enrollments-teacher-to-class-create',
    JOB_NAME_GET_AZURE_ENROLLMENTS_TO_SCHOOL: 'azure-enrollments-to-school-create',
    JOB_NAME_SEND_AZURE_CLASSES_CREATE: 'send-azure-classes-create',
    JOB_NAME_SEND_AZURE_CLASSES_UPDATE: 'send-azure-classes-update',
    JOB_NAME_SEND_AZURE_CLASSES_DELETE: 'send-azure-classes-delete',
    JOB_NAME_ERROR_EMAIL_NOTIFICATION: 'error-email-notification',
    JOB_NAME_DELETE_UNATTENDING_STUDENT_USERS: 'azure-users-delete-unattending',
    JOB_NAME_DELETE_GRADUATED_STUDENTS: 'azure-users-delete-graduated-students',

    JOB_NAME_DELETE_UNEMPLOYED_TEACHERS: 'azure-teachers-unemployed-delete',

    JOB_NAME_CHECK_AZURE_USERS: 'azure-users-check',
    JOB_NAME_CHECK_AZURE_ORGANIZATIONS: 'azure-organizations-check',
    JOB_NAME_CHECK_AZURE_ENROLLMENTS_TO_SCHOOL: 'azure-enrollments-to-school-check',
    JOB_NAME_CHECK_AZURE_ENROLLMENTS_TO_CLASS: 'azure-enrollments-to-class-check',
    JOB_NAME_CHECK_AZURE_CLASSES: 'azure-classes-check',

    JOB_NAME_ARCHIVE_AZURE_USERS: 'azure-users-archive',
    JOB_NAME_ARCHIVE_AZURE_ORGANIZATIONS: 'azure-organizations-archive',
    JOB_NAME_ARCHIVE_AZURE_ENROLLMENTS: 'azure-enrollments-archive',
    JOB_NAME_ARCHIVE_AZURE_CLASSES: 'azure-classes-archive',

    JOB_NAME_REVERT_AZURE_USERS: 'azure-users-revert',
    JOB_NAME_REVERT_AZURE_ORGANIZATIONS: 'azure-organizations-revert',
    JOB_NAME_REVERT_AZURE_ENROLLMENTS: 'azure-enrollments-revert',
    JOB_NAME_REVERT_AZURE_CLASSES: 'azure-classes-revert',

    JOB_NAME_CREATE_USERS: 'sync-users',
    JOB_NAME_UPDATE_INSTITUTIONS: 'sync-institutions',
    JOB_NAME_UPDATE_CLASSES: 'sync-classes',

    JOB_NAME_DAILY_RUN_CLI_SCRIPT_SYNC_AZURE_USERS: 'daily-run-script-sync-users',
    JOB_NAME_DAILY_RUN_CLI_SCRIPT_SYNC_AZURE_SCHOOLS: 'daily-run-script-sync-schools',
    JOB_NAME_DAILY_RUN_CLI_SCRIPT_SYNC_AZURE_CLASSES: 'daily-run-script-sync-classes',
    JOB_NAME_DAILY_RUN_CLI_SCRIPT_SYNC_AZURE_SCHOOL_ENROLLMENTS: 'daily-run-script-sync-school-enrollments',
    JOB_NAME_DAILY_RUN_CLI_SCRIPT_SYNC_AZURE_CLASS_ENROLLMENTS: 'daily-run-script-sync-class-enrollments',

    JOB_NAME_ARCHIVE_USERS_PREVIOUS_YEARS: 'archive-users-previous-years',
    JOB_NAME_ARCHIVE_ORGANIZATIONS_PREVIOUS_YEARS: 'archive-organizations-previous-years',
    JOB_NAME_ARCHIVE_ENROLLMENTS_PREVIOUS_YEARS: 'archive-enrollments-previous-years',
    JOB_NAME_ARCHIVE_CLASSES_PREVIOUS_YEARS: 'archive-classes-previous-years',

    JOB_NAME_RESTART_FAILED_JOBS_WORKFLOWS: 'restart-failed-workflows',

    JOB_NAME_ARCHIVE_FAILED_JOBS_WORKFLOWS: 'archive-failed-workflows',

    JOB_NAME_ARCHIVE_NOT_STARTED_ENROLLMENTS: 'archive-not-started-workflows',

    JOB_NAME_DELETE_ENTITIES_IN_GENERATION: 'delete-entities-in-generation',

    JOB_NAME_CUSTOM_EMAIL_NOTIFICATION: 'custom-email-notification',

    LOGGER_NAME_JOBS: 'JOBS',
    LOGGER_NAME_USER_LOGGINGS: 'USERS',

    RESPONSE_PARAM_NAME_CHECK_CODE: 'CheckCode',
    RESPONSE_PARAM_NAME_RE_ASSIGN_CODE: 'Codes',
    RESPONSE_PARAM_NAME_PARENTIDS: 'ParentIDs',
    RESPONSE_PARAM_NAME_PARENT_CHILD_ACCESS: 'ParentChildAccess',
    RESPONSE_PARAM_NAME_ORGANIZATION_CREATED: 'AzureOrganizationID',
    RESPONSE_PARAM_NAME_CLASS_CREATED: 'AzureClassID',
    RESPONSE_PARAM_NAME_USER_CREATED: 'AzureUserID',
    RESPONSE_PARAM_NAME_ENROLLMENT_CREATED: 'AzureEnrollmentID',
    RESPONSE_PARAM_NAME_EVENT_STATUS: 'EventStatus',
    RESPONSE_PARAM_NAME_AUDIT_ROLE_ASSIGNMENT: 'AuditRoleAssignment',
    RESPONSE_PARAM_NAME_BULK_CLASS_CREATED: 'AzureClasses',
    RESPONSE_PARAM_NAME_PERSON_ID: 'PersonID',

    RESPONSE_PARAM_ERROR_MESSAGE_DEFAULT: 'Please contact system administrator.',
    RESPONSE_PARAM_ERROR_MESSAGE_DATA_NOT_FOUND: 'No rows in the database match the provided parameters.',
    RESPONSE_PARAM_ERROR_MESSAGE_ALREADY_IN_CREATION: 'Workflow with provided params is already in creation.',
    RESPONSE_PARAM_ERROR_MESSAGE_USER_NOT_FOUND: 'User not found.',
    RESPONSE_PARAM_ERROR_MESSAGE_CURRICULUM_NOT_FOUND: 'Curriculum not found.',
    RESPONSE_PARAM_ERROR_MESSAGE_ORGANIZATION_NOT_FOUND: 'Organization not found.',
    RESPONSE_PARAM_ERROR_MESSAGE_AZURE_DATA_NOT_FOUND: 'User not found in azure for the provided parameters.',
    RESPONSE_PARAM_ERROR_MESSAGE_PERSON_IS_ATTENDING: 'Person is neither unattending nor graduated',
    RESPONSE_PARAM_ERROR_MESSAGE_JOB_ENTITY_NOT_CREATED: 'Record failed to be written in database.',
    RESPONSE_PARAM_ERROR_MESSAGE_USER_ALREADY_EXISTS: 'User already exists in the database.',
    RESPONSE_PARAM_ERROR_MESSAGE_PARENT_ALREADY_EXISTS: 'Parent already exists in core.SysUser table.',
    RESPONSE_PARAM_ERROR_MESSAGE_SCHOOL_BOOK_ACCESS_NOT_FOUND: 'School book access not found.',

    JOBS_VARIABLES_TOP: 'JOBS_TOP',
    JOBS_VARIABLES_DEFAULT_TOP: '800',
    JOBS_ENROLLMENTS_STUDENT_TO_CLASS_CREATE_DEFAULT_TOP_NAME: 'JOBS_ENROLLMENTS_STUDENT_TO_CLASS_CREATE_TOP_VALUE',
    JOBS_ENROLLMENTS_STUDENT_TO_CLASS_DELETE_DEFAULT_TOP_NAME: 'JOB_ENROLLMENTS_STUDENT_TO_CLASS_DELETE_TOP_VALUE',
    JOBS_ENROLLMENTS_STUDENT_TO_SCHOOL_CREATE_DEFAULT_TOP_NAME: 'JOB_ENROLLMENTS_STUDENT_TO_SCHOOL_CREATE_TOP_VALUE',
    JOBS_ENROLLMENTS_STUDENT_TO_SCHOOL_DELETE_DEFAULT_TOP_NAME: 'JOB_ENROLLMENTS_STUDENT_TO_SCHOOL_DELETE_TOP_VALUE',

    JOBS_ENROLLMENTS_TEACHER_TO_SCHOOL_CREATE_DEFAULT_TOP_NAME: 'JOB_ENROLLMENTS_TEACHER_TO_SCHOOL_CREATE_TOP_VALUE',
    JOBS_ENROLLMENTS_TEACHER_TO_SCHOOL_DELETE_DEFAULT_TOP_NAME: 'JOB_ENROLLMENTS_TEACHER_TO_SCHOOL_DELETE_TOP_VALUE',
    JOBS_ENROLLMENTS_TEACHER_TO_CLASS_CREATE_DEFAULT_TOP_NAME: 'JOB_ENROLLMENTS_TEACHER_TO_CLASS_CREATE_TOP_VALUE',
    JOBS_ENROLLMENTS_TEACHER_TO_CLASS_DELETE_DEFAULT_TOP_NAME: 'JOB_ENROLLMENTS_TEACHER_TO_CLASS_DELETE_TOP_VALUE',

    JOBS_ENROLLMENTS_STUDENT_TO_CLASS_CREATE_DEFAULT_TOP_VALUE: '1690',
    JOBS_ENROLLMENTS_STUDENT_TO_CLASS_DELETE_DEFAULT_TOP_VALUE: '50',
    JOBS_ENROLLMENTS_TEACHER_TO_CLASS_CREATE_DEFAULT_TOP_VALUE: '57',
    JOBS_ENROLLMENTS_TEACHER_TO_CLASS_DELETE_DEFAULT_TOP_VALUE: '50',

    JOBS_ENROLLMENTS_STUDENT_TO_SCHOOL_CREATE_DEFAULT_TOP_VALUE: '50',
    JOBS_ENROLLMENTS_STUDENT_TO_SCHOOL_DELETE_DEFAULT_TOP_VALUE: '50',
    JOBS_ENROLLMENTS_TEACHER_TO_SCHOOL_CREATE_DEFAULT_TOP_VALUE: '50',
    JOBS_ENROLLMENTS_TEACHER_TO_SCHOOL_DELETE_DEFAULT_TOP_VALUE: '50',

    JOBS_USERS_CREATE_DEFAULT_TOP_NAME: 'JOBS_USERS_CREATE_TOP_VALUE',
    JOBS_USERS_UPDATE_DEFAULT_TOP_NAME: 'JOBS_USERS_UPDATE_TOP_VALUE',
    JOBS_USERS_DELETE_DEFAULT_TOP_NAME: 'JOBS_USERS_DELETE_TOP_VALUE',
    JOBS_USERS_CREATE_DEFAULT_TOP_VALUE: '331',
    JOBS_USERS_UPDATE_DEFAULT_TOP_VALUE: '3330',
    JOBS_USERS_DELETE_DEFAULT_TOP_VALUE: '988',
    JOBS_ORGANIZATIONS_CREATE_DEFAULT_TOP_NAME: 'JOBS_ORGANIZATIONS_CREATE_TOP_VALUE',
    JOBS_ORGANIZATIONS_UPDATE_DEFAULT_TOP_NAME: 'JOBS_ORGANIZATIONS_UPDATE_TOP_VALUE',
    JOBS_ORGANIZATIONS_DELETE_DEFAULT_TOP_NAME: 'JOBS_ORGANIZATIONS_DELETE_TOP_VALUE',
    JOBS_ORGANIZATIONS_CREATE_DEFAULT_TOP_VALUE: '115',
    JOBS_ORGANIZATIONS_UPDATE_DEFAULT_TOP_VALUE: '231',
    JOBS_ORGANIZATIONS_DELETE_DEFAULT_TOP_VALUE: '463',
    JOBS_RETRY_ATTEMPTS_LIMIT: '5',
    JOBS_IN_PROGRESS_RESULT_COUNT_LIMIT: '50',

    JOBS_CLASSES_CREATE_DEFAULT_TOP_NAME: 'JOBS_CLASSES_CREATE_TOP_VALUE',
    JOBS_CLASSES_UPDATE_DEFAULT_TOP_NAME: 'JOBS_CLASSES_UPDATE_TOP_VALUE',
    JOBS_CLASSES_DELETE_DEFAULT_TOP_NAME: 'JOBS_CLASSES_DELETE_TOP_VALUE',
    JOBS_CLASSES_CREATE_DEFAULT_TOP_VALUE: '115',
    JOBS_CLASSES_UPDATE_DEFAULT_TOP_VALUE: '231',
    JOBS_CLASSES_DELETE_DEFAULT_TOP_VALUE: '463',

    DB_QUERY_PARAM_ROWS_PER_PAGE_GET_PERSONAL_IDS: 100,
    DB_QUERY_PARAM_ROWS_PER_PAGE_GET_SCHOOL_IDS: 100,
    DB_QUERY_PARAM_ROWS_PER_PAGE_STUDENTS: 100,
    DB_ERROR_MESSAGE_EXCEPTION_LENGTH_MAX: 1000,
    DB_ERROR_MESSAGE_FAILED_SYNCRONIZATION_LENGTH_MAX: 1000,
    DB_ERROR_MESSAGE_EXCEPTION: 'Exception has occurred.',
    DB_ERROR_MESSAGE_NOT_FOUND: 'GUID is not found in Azure.',
    DB_ERROR_MESSAGE_FAILED_SYNCRONIZATION: 'Error during synchronization',

    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_CLASS_CREATE:
        'Creates a CLASS_CREATE workflow in Azure AD aswell as ENROLLMENT_CLASS_CREATE for each person in the personIDs array.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_CLASS_CREATE_BULK:
        'Creates a CLASS_CREATE workflows in Azure AD aswell as ENROLLMENT_CLASS_CREATE for each person in the personIDs array for every element in the provided array. This method is the same as the single class create endpoint but for and array of classes.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_CLASS_DELETE:
        'Creates a CLASS_DELETE workflow in Azure AD for the given curriculumID.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_CLASS_UPDATE:
        'Creates a CLASS_UPDATE workflow in Azure AD aswell as ENROLLMENT_CLASS_DELETE for given personIDsToDelete and ENROLLMENT_CLASS_CREATE for given personIDsToCreate.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_CLASS_RESTART_WORKFLOW: 'Restarts the CLASS workflow with the given id.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_CLASS_CHECK_STATUS: 'Checks the status of the CLASS workflow with the given id.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_ENROLLMENT_RESTART_WORKFLOW:
        'Restarts the ENROLLMENT workflow with the given id.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_ENROLLMENT_CHECK_STATUS:
        'Checks the status of the ENROLLMENT workflow with the given id.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_ORGANIZATION_GET_ALL:
        'Returns an array containing paginated data of all SCHOOL workflows.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_ORGANIZATION_CREATE: 'Creates a SCHOOL_CREATE workflow in Azure AD.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_ORGANIZATION_DELETE:
        'Creates a SCHOOL_DELETE workflow in Azure AD for the given institutionID.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_ORGANIZATION_UPDATE: 'Creates a SCHOOL_UPDATE workflow in Azure AD.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_ORGANIZATION_RESTORE:
        'Creates a SCHOOL_CREATE For and already deleted school. Enrolls teachers students and accountants aswell.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_ORGANIZATION_RESTART_WORKFLOW: 'Restarts the SCHOOL workflow with the given id.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_ORGANIZATION_CHECK_STATUS:
        'Checks the status of the SCHOOL workflow with the given id.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_STUDENT_CREATE: 'Creates a USER_CREATE workflow in Azure AD.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_STUDENT_DELETE:
        'Creates a USER_DELETE workflow in Azure AD for the given personID.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_STUDENT_UPDATE:
        'Creates a USER_UPDATE workflow in Azure AD and sets core.SysUser isAzureSynced column to  0.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_STUDENT_ENROLLMENT_SCHOOL_DELETE:
        'Creates an ENROLLMENT_SCHOOL_DELETE workflow in Azure AD for the given personID and institutionID.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_STUDENT_ENROLLMENT_SCHOOL_CREATE:
        'Creates an ENROLLMENT_SCHOOL_CREATE workflow in Azure AD for the given personID and institutionID.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_STUDENT_ENROLLMENT_CLASS_DELETE:
        'Creates an ENROLLMENT_CLASS_DELETE workflow in Azure AD for the given personID and curriculumID.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_STUDENT_ENROLLMENT_CLASS_CREATE:
        'Creates an ENROLLMENT_CLASS_CREATE workflow in Azure AD for the given personID and curriculumID.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_TEACHER_CREATE:
        'Creates a USER_CREATE workflow in Azure AD as well as an ENROLLMENT_SCHOOL_CREATE.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_TEACHER_DELETE:
        'Creates a USER_DELETE workflow in Azure AD for the given personID.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_TEACHER_UPDATE:
        'Creates a USER_UPDATE workflow in Azure AD and sets core.SysUser isAzureSynced column to  0.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_TEACHER_ENROLLMENT_SCHOOL_DELETE:
        'Creates an ENROLLMENT_SCHOOL_DELETE workflow in Azure AD for the given personID and institutionID.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_TEACHER_ENROLLMENT_SCHOOL_CREATE:
        'Creates an ENROLLMENT_SCHOOL_CREATE workflow in Azure AD for the given personID and institutionID.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_TEACHER_ENROLLMENT_CLASS_DELETE:
        'Creates an ENROLLMENT_CLASS_DELETE workflow in Azure AD for the given personID and curriculumID.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_TEACHER_ENROLLMENT_CLASS_CREATE:
        'Creates an ENROLLMENT_CLASS_CREATE workflow in Azure AD for the given personID and curriculumID.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_USER_CHECK_STATUS: 'Checks the status of the USER workflow with the given id.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_USER_RESTART_WORKFLOW: 'Restarts the USER workflow with the given id.',
    SWAGGER_PARAM_ENDPOINT_DESCRIPTION_USER_AZURE_SYNC: 'Syncs azureID and publicEduNumber for given record.',
    NANOID_CUSTOM_ALPHABET: '23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz',

    DOMAIN_NAME_DEVELOPMENT: '@m365edu841480.onmicrosoft.com',
    DOMAIN_NAME_PRODUCTION: '@edu.mon.bg',
    SYS_USER_USERNAME: `usermng-system-user`,
    PARENT_PASSWORD_DEFAULT: `Default`,

    DB_QUERY_SEARCH_USERS_TOP_VALUE: 10,

    LOG_OBJECT_NAME_PARENT_CHILD_SCHOOL_BOOK_ACCESS: 'ParentChildSchoolBookAccess',
};
