export enum ActionTypeEnum {
    CREATE_SCHOOL = <any>'CreateSchool',
    CREATE_PRINCIPAL = <any>'CreatePrincipal',
    CREATE_CLASS = <any>'CreateClass',
    CREATE_USER = <any>'CreateUser',
    UPDATE_SCHOOL = <any>'UpdateSchool',
    UPDATE_CLASS = <any>'UpdateClass',
    UPDATE_USER = <any>'UpdateUser',
    DELETE_SCHOOL = <any>'DeleteSchool',
    DELETE_CLASS = <any>'DeleteClass',
    DELETE_USER = <any>'DeleteUser',
    ADD_USER_TO_CLASS = <any>'AddUserToClass',
    ADD_USER_TO_SCHOOL = <any>'AddUserToSchool',
    ADD_PRINCIPAL_TO_SCHOOL = <any>'AddPrincipalToSchool',
    REMOVE_USER_FROM_CLASS = <any>'RemoveUserFromClass',
    REMOVE_USER_FROM_SCHOOL = <any>'RemoveUserFromSchool',
    RESET_PASSWORD = <any>'ResetPassword',
    UNDEFINED = <any>'Undefined',
}
