#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["MonProjects.Api/MonProjects.Api.csproj", "MonProjects.Api/"]
RUN dotnet restore "MonProjects.Api/MonProjects.Api.csproj"
COPY . .
COPY MonProjects.Api/appsettings.test.json MonProjects.Api/appsettings.json
WORKDIR "/src/MonProjects.Api"
RUN dotnet build "MonProjects.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MonProjects.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MonProjects.Api.dll"]